### ISSUE TITLE
Third party directives added to ui-select-choices is created 2 times

### ISSUE THREAD

**Issue by hyzhak** [angular-ui/ui-select#1000]
Seems `ui-select-choices` does extra work. Here is example. third party directive in any place is created once but in `ui-select-choices` it happens twice.
http://plnkr.co/edit/4nmGd7DxkDO6JuvONJ4D?p=preview

**Comment by bluemaex** [comment]
Also stumpled upon this bug today. Did you find a way to get around?

**Comment by hyzhak** [comment]
no

**Comment by user378230** [comment]
Related #170 ?

**Comment by wesleycho** [comment]
#170 is too old, just closed it.
