### ISSUE TITLE
Tagging is not working correctly when ui-select's ng-model is bound to a list

### ISSUE THREAD

**Issue by move-fast** [angular-ui/ui-select#1002]
When using tagging, `ui-select` seems to have problems when `ng-model' is bound to a list variable. E.g., `ng-model="demo.colors"` is working correctly, but `ng-model="colors"` does not update `$scope.colors` when tags are selected

This is working correctly:
```
  <ui-select multiple tagging tagging-label="(custom 'new' label)" ng-model="demo.colors" theme="bootstrap" style="width: 300px;" title="Choose a color">
    <ui-select-match placeholder="Select colors...">{{$item}}</ui-select-match>
    <ui-select-choices repeat="color in availableColors | filter:$select.search">
      {{color}}
    </ui-select-choices>
  </ui-select>
  <p>Selected: {{demo.colors}}</p>
```

In this case scope variable `colours` is not assigned to selected tags:
```
  <h3>Not Working Example</h3>
  <ui-select multiple tagging tagging-label="(custom 'new' label)" ng-model="colors" theme="bootstrap" style="width: 300px;" title="Choose a color">
    <ui-select-match placeholder="Select colors...">{{$item}}</ui-select-match>
    <ui-select-choices repeat="color in availableColors | filter:$select.search">
      {{color}}
    </ui-select-choices>
  </ui-select>
  <p>Selected: {{colors}}</p>
```
Here is [Plunker link](http://plnkr.co/edit/x8ij5wFTbEEZ9Q40Ehqw) with working and not working examples.

**Comment by samlroberts** [comment]
If you're still dealing with this problem I think the problem is scoping with the ng-model, described a bit here: http://stackoverflow.com/questions/17606936/angularjs-dot-in-ng-model.

**Comment by user378230** [comment]
As per linked stackoverflow question, ng-model requires dot notation. See also FAQ https://github.com/angular-ui/ui-select/wiki/FAQs
