### ISSUE TITLE
Backspace key with append-to-body sends history back

### ISSUE THREAD

**Issue by ro0sterjam** [angular-ui/ui-select#1003]
I've noticed that when append-to-body is set to true and I attempt to erase an item, I'm sent back in history. Is there an extra setting required to get the backspace to remove items again?

**Comment by rysilva** [comment]
I noticed this as well.  It's probably because the entire select, not just the dropdown, is appended to body.  So when the dropdown disappears, the entire thing moves and it loses focus.

**Comment by vertex** [comment]
:+1: created a PR for this...

**Comment by onemenny** [comment]
the PR is working

**Comment by vaer-k** [comment]
I'm encountering this issue when append-to-body is set to false.

**Comment by vaer-k** [comment]
I don't know what the best fix will be for the source, but I am able to solve my problem by taking advantage of the on-select attribute and defining a function to shift focus back to input whenever a selection is made.
