### ISSUE TITLE
Using ng-csp causes ui-select to break

### ISSUE THREAD

**Issue by letscreate** [angular-ui/ui-select#1009]
When using ng-csp i.e. <html ng-app ng-csp>, this causes the angular ui select to 'break'. Although saying that, it does work however looks like the styling is not 'accepted' / working as normal.

As below 2 input boxes are shown instead of 1 and the styling is off.

![screen shot 2015-06-12 at 08 21 53](https://cloud.githubusercontent.com/assets/7583481/8125271/496f6900-10dc-11e5-9d1c-12c074ea7fe2.png)

**Comment by user378230** [comment]
Closing this issue as it is over a year old and doesn't have a repro sample. 

If you believe its still relevant please update with a plunkr (or similar) against the latest version of ui-select (currently v0.15.0)

**Comment by soorajvnair** [comment]
The issue still persists. Check this plunker. http://plnkr.co/edit/IMRcgO?p=preview

**Comment by user378230** [comment]
The plunkr is using ui-select v0.11 can you update to latest so it can be confirmed? I'll reopen then.

https://cdnjs.com/libraries/angular-ui-select

**Comment by jmastron** [comment]
Still broken with 0.20: http://plnkr.co/edit/Vhqw8RqRFATo9X5ih667?p=preview .  Pretty sure it's the inline style injection.
