### ISSUE TITLE
Dropdown direction issue on webkit

### ISSUE THREAD

**Issue by pulse14** [angular-ui/ui-select#1016]
The problem is on this line (in uiselect directive), on Chrome (43) ```$document[0].documentElement.scrollTop``` return 0

```javascript
 else if (offset.top + offset.height + offsetDropdown.height > $document[0].documentElement.scrollTop + $document[0].documentElement.clientHeight)
```
It works if i replace by 
```javascript
 else if (offset.top + offset.height + offsetDropdown.height > $document[0].body.scrollTop + $document[0].documentElement.clientHeight)
```
But it doesn't work anymore on Firefox now...

Anyone have this problem ?

EDIT :
```window.pageYOffset``` work on both

Thank you

**Comment by hengun348** [comment]
I can confirm this issue as well

**Comment by acetrand** [comment]
Im seeing this also in Chrome. Please fix asap.

**Comment by pulse14** [comment]
I will make a pull req. 
It works fine after my fix.

**Comment by acetrand** [comment]
@pulse14 Please do. I didnt follow where you put the `window.pageYOffset` so I'm holding my breath for your PR :wink:

**Comment by sricc** [comment]
Seeing this as well.

**Comment by jonasflesch** [comment]
I confirm that this fixed the problem for me.

**Comment by tjsail33** [comment]
+1. This is a pretty serious bug and the PR needs to be accepted.

**Comment by tinybigideas** [comment]
+1 for the PR to be accepted. Great fix @pulse14. I've accepted this into my build and it has corrected the issue. Hopefully this is accepted into the master sooner rather than later!

**Comment by Iku-turso** [comment]
+1.

**Comment by evillemez** [comment]
+1 I can also confirm the fix by @pulse14 works.  Thank you!

**Comment by dimirc** [comment]
Should be solved with https://github.com/angular-ui/ui-select/pull/1212
