### ISSUE TITLE
on-select event doesnt work

### ISSUE THREAD

**Issue by alexborisov** [angular-ui/ui-select#1024]
Perhaps it's me, but I'm pretty sure this is straight forward:

add an `on-select` attribute to the parent `ui-select` directive and point it to a function. Nothing happens.

```
<ui-select ng-model="from" ng-required="true" id="dept" on-select="console.log($item, $model)"></ui-select>
```

**Comment by RyanDale** [comment]
Unless you have something like ```$scope.console = console;``` in your controller the ui-select directive won't know what "console" is. What you probably want to do instead is define a function in your controller and pass that function to the directive. Example below, I tested this in the latest version of ui-select and it appears to be working correctly.

```
  $scope.fromSelected = function(item, model) {
    console.log(item, model);
  };
```

```
<ui-select ng-model="from" on-select="fromSelected($item, $model)">
...
</ui-select>
```

**Comment by alexborisov** [comment]
Hmm... I'm still having issues. Here is my code:

html
```html
<ui-select ng-model="from" on-select="vm.formSelected($item, $model)"></ui-select>
```

js
```js
function Controller() {
  var vm = this;

  vm.formSelected = function($item, $model) {
    console.log('formSelected', $item, $model)
  }
}
```

It doesn't seem to work. I mean besides using `controllerAs` vs `$scope` our examples are identical. My angular version is 1.3.16 and my ui-select version is 0.11.2.

As far as I can tell I'm not doing anything exotic...

**Comment by RyanDale** [comment]
I just tested it using the ```controllerAs``` syntax without problems. Would you mind setting up a Plunker? I think that may be beneficial in this situation.

**Comment by fjcero** [comment]
I have the same issue, and I'm not sure how to check if any event was triggered.

**Comment by user378230** [comment]
Closing this issue as it is over 6 months and doesn't have a repro sample. 

If you believe its still relevant please update with a plunkr (or similar) against the latest version of ui-select (currently v0.16.0)

**Comment by hamza1100** [comment]
> Hmm... I'm still having issues. Here is my code:
> 
> **html**
> 
> ```
> <ui-select ng-model="from" on-select="vm.formSelected($item, $model)"></ui-select>
> ```
> 
> **js**
> 
> ```js
> function Controller() {
>   var vm = this;
> 
>   vm.formSelected = function($item, $model) {
>     console.log('formSelected', $item, $model)
>   }
> }
> ```
> 
> It doesn't seem to work. I mean besides using `controllerAs` vs `$scope` our examples are identical. My angular version is 1.3.16 and my ui-select version is 0.11.2.
> 
> As far as I can tell I'm not doing anything exotic...

i am having similar problem. Did you find the solution while working on this ui-select version? I am running on 0.13.2 with same problem. i tried it on latest version that is 0.19.x it works fine. But i can't update because of library dependencies.
