### ISSUE TITLE
Improve build process

### ISSUE THREAD

**Issue by dimirc** [angular-ui/ui-select#103]
- [ ] Improve how jshint fails while "watch"
- [ ] Add changelog task
- [ ] Bump new version to bower.json and package.json

**Comment by Jefiozie** [comment]
@user378230 , Is this still a valid Issue?

**Comment by Jefiozie** [comment]
Closing it down as it is a old issue. Please create new issue if this is still a bug/ problem.
Next i'm trying to get a good overview of recent bugs.

Thanks for understanding.
