### ISSUE TITLE
Select2 dropdown does not automatically focus input element anymore in v0.12

### ISSUE THREAD

**Issue by crazysaem** [angular-ui/ui-select#1032]
Hi all,

If you take a look at the following plnkr, which is exactly the same Demo has shown on the Readme, except for the select.css and select.js updated to v0.12, you can see that after clicking the "Select2 theme" dropdown button, the input field which is displayed, is not focused anymore:
http://plnkr.co/edit/fJPVe62mYUwIwTbsIonC?p=preview

The plnkr with v0.11.2 from the Readme file still works correctly:
http://plnkr.co/edit/a3KlK8dKH3wwiiksDSn2?p=preview

As a Workaround I increased the timeout before setting the focus to 10ms, in line 332 of the select.js file. With the Workaround the focus is set properly again for me locally:
http://plnkr.co/edit/TOp93LHaqDCx2fuPOO8V?p=preview

**Comment by MiguelMike** [comment]
+1.

Same here.

**Comment by Biron** [comment]
+1

**Comment by nherzing** [comment]
This appears to be related to https://github.com/angular-ui/ui-select/commit/02bebc0d48b0faf81a62bac3f0eb1f855db1f7dc. It sets the visibility of the dropdown to `hidden` during setup which prevents the `focus` event from working. If you remove [this line](https://github.com/angular-ui/ui-select/blob/2d1422d109dc1cd64213271e59506b14f74d356f/src/uiSelectDirective.js#L265) it focuses correctly but would obviously introduce other issues. 

I don't have a decent solution to offer but hopefully this helps if someone else wants to dive in to it.

**Comment by markwylde** [comment]
+1

**Comment by mburgosh** [comment]
The commit  fc722b6 needs to be included to solve this issue.

**Comment by rahulmittal1990** [comment]
+1
