### ISSUE TITLE
Remove Tag On Click

### ISSUE THREAD

**Issue by rkhayat** [angular-ui/ui-select#1033]
Hello,

I noticed that clicking any of the tags makes them blue, which has no purpose for what I would like to do. I would like them removed if clicked

Can someone please chime in? I appreciate the help.

http://stackoverflow.com/questions/30941141/angular-ui-select-remove-item-on-click

**Comment by user378230** [comment]
It looks like you were on the right track with 
```html
<span class="ui-select-match">
  <span ng-repeat="$item in $select.selected">
    <span 
      class="ui-select-match-item btn btn-default btn-xs"
      tabindex="-1"
      type="button"
      ng-disabled="$select.disabled"

      ng-click="$selectMultiple.removeChoice($index)"
      ng-class="{'btn-primary':$selectMultiple.activeMatchIndex === $index, 'select-locked':$select.isLocked(this, $index)}"
      ui-select-sort="$select.selected">
        <span class="close ui-select-match-close" ng-hide="$select.disabled" ng-click="$selectMultiple.removeChoice($index)">&nbsp;&times;</span>
    <span uis-transclude-append></span>
  </span>
 </span>
</span>
```
Which should work. 

Given the lack of activity I'll assume you no longer need assistance so I'm going to close this issue. 

---
If you believe its still relevant please update with a plunkr (or similar) with your changes so far - against the latest version of ui-select (currently v0.15.0)
