### ISSUE TITLE
search-enabled="false" does not work with multiple select

### ISSUE THREAD

**Issue by wdrai** [angular-ui/ui-select#1034]
http://plnkr.co/edit/rzJk5DYQ2ApHfveTeGCl?p=preview

The search input is still enabled (and search works) with the search-enabled="false" option

**Comment by thefewminutes** [comment]
+1

**Comment by wdrai** [comment]
Changing this in select.js works for me :
$templateCache.put("bootstrap/select-multiple.tpl.html", ... <input type=\"text\" **ng-readonly=\"!$select.searchEnabled\"** autocomplete=\"off\"...);

**Comment by user378230** [comment]
This appears to be resolved in latest version (v0.16.0)

**Comment by rafaeleyng** [comment]
It doesn't work for me in v0.17.0, and it doesn't seem to work in the Plunker also.

**Comment by user378230** [comment]
@rafaeleyng Which version? v0.17.1 is the latest. The plunkr I linked too works for me. 

Can you reproduce against one of the latest [Examples](http://angular-ui.github.io/ui-select/#examples)? (Please post plunkr too..)

**Comment by rafaeleyng** [comment]
![image](https://cloud.githubusercontent.com/assets/4842605/15540020/e33bf54e-225b-11e6-8705-662fb5f52de1.png)

@user378230 The image above shows the Plunkr with version 0.17.0, `search-enabled="false"` for the select multiple and the search still works.

Am I doing something wrong?
