### ISSUE TITLE
Issues with multiple ajax select with Select2 theme

### ISSUE THREAD

**Issue by oowowaee** [angular-ui/ui-select#1042]
Wondering if there is a fix for the following issue - the select doesn't look very good in the aforementioned case, and it's very confusing and difficult to click and type into the field.

![screen shot 2015-06-25 at 1 46 42 pm](https://cloud.githubusercontent.com/assets/1934918/8361350/ae93aa44-1b40-11e5-9267-70e25ee17811.png)

**Comment by user378230** [comment]
Closing due to lack of info and repro.

If you believe this issue is still relevant please update with a plunkr (or similar) against the latest version of ui-select (currently v0.16.0)
