### ISSUE TITLE
UI-Select does not show message "Result not found" when server responds with "404 Not Found"

### ISSUE THREAD

**Issue by razam217** [angular-ui/ui-select#1048]
Hi Guyz, I'm working with UI-Select, and I'm using Ajax based UI-Select. I want to know that how can I get a message of "Result not found" when the response from the web server is "404". While using Jquery Select2, this message was available. I've tried almost all the examples but did not find any solution. 
Any help will be appreciated.

**Comment by awerlang** [comment]
ui-select doesn't do any ajax, so you should put this message yourself inside the template provided on ui-select-match placeholder or ui-select-choices. Handle a failure on your ajax request for instance.
