### ISSUE TITLE
Feature Request: Multi-level group by

### ISSUE THREAD

**Issue by xforceco** [angular-ui/ui-select#1054]
After reading through the docs, it is quite certain that ui-select does not support multi-level grouping, which has been supported by select2.

I change this issue as a feature request as a result.

**Comment by bashanam** [comment]
+1

**Comment by ikhos** [comment]
+1

**Comment by danduh** [comment]
+1

**Comment by akabhirav** [comment]
+1

**Comment by user378230** [comment]
For multiple level grouping, what you actually really want is a tree control with search/find functionality. 

I'm going to close this as I don't think it's a direction the control should go in. It will most likely be very complicated to implement as well. 

PRs will always be welcome, so if anyone really feels up for it they can certainly make an attempt.
