### ISSUE TITLE
ui-select-choices refresh property doesnt accept nothing but a scope variable

### ISSUE THREAD

**Issue by uguryilmaz** [angular-ui/ui-select#1056]
hi, is it possible to make a service call for refresh attribute. i will show you what i want with two code sample.

this is a working axample:

in html template file: 

    <ui-select multiple tagging="tagTransform" ng-model="myCompetences.competences" theme="bootstrap" ng-disabled="disabled" style="width: 800px;" title="Choose a person">
    <ui-select-match placeholder="Select a address...">{{$item.formatted_address}}</ui-select-match>
    <ui-select-choices repeat="address in addresses track by $index"  refresh="refreshAddresses($select.search)" refresh-delay="0">
    <div ng-if="address.isTag" ng-bind-html="'<small>(new)</small>'"></div>
      <small>
        {{address.formatted_address}} 
      </small>
    </ui-select-choices>
  </ui-select>

in js file:

    $scope.refreshAddresses = function(address) {
    var params = {address: address, sensor: false};
    return $http.get(
      'http://maps.googleapis.com/maps/api/geocode/json',
      {params: params}
    ).then(function(response) {
      $scope.addresses = response.data.results;
    });
  };

but this is not working. only changes in refresh function. 

    <ui-select multiple tagging="tagTransform" ng-model="myCompetences.competences" theme="bootstrap" ng-disabled="disabled" style="width: 800px;" title="Choose a person">
    <ui-select-match placeholder="Select a address...">{{$item.formatted_address}}</ui-select-match>
    <ui-select-choices repeat="address in addresses track by $index"  refresh="DemoService.refreshAddresses($select.search,$http,$scope)" refresh-delay="0">
    <div ng-if="address.isTag" ng-bind-html="'<small>(new)</small>'"></div>
      <small>
        {{address.formatted_address}} 
      </small>
    </ui-select-choices>
  </ui-select>

    .factory('DemoService',function (){
      var service = {
    refreshAddresses : function(address,$http,$scope) {
    var params = {address: address, sensor: false};
    return $http.get(
      'http://maps.googleapis.com/maps/api/geocode/json',
      {params: params}
    ).then(function(response) {
      debugger;
      $scope.addresses = response.data.results;
    });
      }
      }
      return service;
    });

this is the plunker.

http://plnkr.co/edit/kgHG8sA64LR8UoEF50lG?p=preview

is this a bug or expected behaviour?

**Comment by wesleycho** [comment]
This is a usage issue - see [here](http://plnkr.co/edit/PXpDeS0srLWjgkMw6wxE?p=preview).

Closing due to user error.
