### ISSUE TITLE
Up and down arrow keys not working on select2 theme (version 0.12.0)

### ISSUE THREAD

**Issue by tolemac** [angular-ui/ui-select#1059]
Can see this plunkr: 
http://plnkr.co/edit/q8fNxmGb1hqi3SuGdmeU?p=preview

Arrow keys work fine in Bootstrap and selectize but not in select2.

**Comment by RyanDale** [comment]
The bug is happening because the dropdown is not focused. If you first click the search box to focus it, then the up/down arrow keys will work. I tested locally, and this issue (also referenced in #1053) should be fixed by #1040.

**Comment by tolemac** [comment]
Then if you are in a form with several fileds and you are using the keyboard to enter data and using TAB to jump between fields ... when you arrive to ui-select ... have you take the mouse, point and click in search text box? It seems uncomfortable ...

**Comment by RyanDale** [comment]
I wasn't suggesting that you should have to focus the select before using the arrow keys, just that the issue stemmed from the input not being correctly focused. Once the pull request I mentioned is merged, the dropdown will be correctly focused and the up/down keys should work as expected.

**Comment by tolemac** [comment]
Ops! sorry, I misunderstood ... :(
Thanks

**Comment by cbryer** [comment]
this happens when using search-enabled="false" attribute on the ui-select directive as well.  in that case there is no search box to focus and up/down never works.

**Comment by dimirc** [comment]
Should be fixed with https://github.com/angular-ui/ui-select/pull/1040

**Comment by cbryer** [comment]
unfortunately this is not fixed with #1040 because there is an ng-show="$select.searchEnabled" on the search input.  when searchEnabled == false the input has a style of display:none and can not get focus and the keyboard keys stop working.
