### ISSUE TITLE
Proposal: Smaller syntax for simple cases

### ISSUE THREAD

**Issue by dimirc** [angular-ui/ui-select#106]
There are cases where we might not need to specify templates or anything complex. So what about if we go with a simpler syntax where we could just apply defaults. 

Something like this:

``` html
<ui-select ng-model="data.selected" 
           choices="person in people" 
           match="person.name"></ui-select>
```

**Comment by Jefiozie** [comment]
Closing it down as it is a old issue. Please create new issue if this is still a bug/ problem.
Alsoi'm trying to get a good overview of recent bugs and maintaining the repo.

Thanks for understanding.
