### ISSUE TITLE
How can I prevent the selected item change in on-change function?

### ISSUE THREAD

**Issue by iltera** [angular-ui/ui-select#1063]
I have a situation which needs to prevent the change of selected item on on-change event. I read some threads which were created earlier this year but couldn't find an explanation in the docs.

I simply need to show a promt box for some conditions on page, if these conditions are not met, ui-select component should show a prompt to ask user if they really want to change another item in the ui-select items.

How can I achieve this?
Simply returning false, doesn't work in on-change function.

**Comment by iltera** [comment]
I managed to solve the issue by manually selecting the item back.

**Comment by wesleycho** [comment]
Going to close as a usage issue - this doesn't really have a great solution at the library level for requirements like this.
