### ISSUE TITLE
How can I close the dropdown with the ESC key?

### ISSUE THREAD

**Issue by eeejayg** [angular-ui/ui-select#1064]
I am using the select2 theme.  The dropdown toggles the way I want, but I also want the dropdown to close when the user presses ESC.

**Comment by RyanDale** [comment]
This looks like another bug that's occurring because the dropdown isn't focused. Take a look at #1040, it will fix this issue.

**Comment by eeejayg** [comment]
Ryan:

How do I implement the fix?  Or is there a newer version that fixes this?

Thanks so much.

Eric

**Comment by dimirc** [comment]
Should be fixed with https://github.com/angular-ui/ui-select/pull/1040
