### ISSUE TITLE
Mobile Fallback

### ISSUE THREAD

**Issue by eeejayg** [angular-ui/ui-select#1069]
I am using the select2 theme.  Is there a mobile fallback for this control so that it reverts to standard a standard option dropdown when you are on mobile?  If so, how do you activate it?

**Comment by wry791** [comment]
+1

**Comment by trickpattyFH20** [comment]
+1

**Comment by tomauty** [comment]
No results for a `<select>` tag in the repo, so I doubt there's a fallback. I haven't actually seen fallback like that in any select-wrapping libraries. Maybe in the meantime you could create a wrapper that swaps elements based on viewport dimensions or user agents?

**Comment by trickpattyFH20** [comment]
The answer on this question has a very nice solution for device detection ( http://stackoverflow.com/questions/11381673/detecting-a-mobile-browser ) I used that answer + ng-if to swap for a default <select> on mobile

**Comment by user378230** [comment]
I think this would add unnecessary bloat to the library and I'm not sure if its even supported by something like select2. 

Given that you can work around using ng-if I'm going to close for now. If demand increases we can look at reopening.
