### ISSUE TITLE
Cannot install ui-select using bower

### ISSUE THREAD

**Issue by laurynas-karvelis** [angular-ui/ui-select#1078]
Hey :),

while trying to install ui-select via bower it actually downloads completely different project. Would you be able to supply a possibility to install this project as dependency via bower?

**Comment by mohitsuman** [comment]
Hey, Please try:
1. "bower install angular-ui-select".
2. The scripts can be references using reference the scripts

bower_components/angular-ui-select/dist/select.js
bower_components/angular-ui-select/dist/select.css

**Comment by laurynas-karvelis** [comment]
Thank you @mohitsuman, I then found on docs that the bower package name is different that the one provided in bower.json;

I'll try to submit a pull request for this, as it can be easily misleading others too.
