### ISSUE TITLE
Make ui-select templates HTML5 compatible

### ISSUE THREAD

**Issue by Vayvala** [angular-ui/ui-select#1084]
Regular Angular attributes are not HTML5 compatible:
https://stackoverflow.com/questions/15767279/angularjs-app-not-passing-official-w3c-html5-validation

To make them compatible you should use `data-` prefix: `ng-app` would become `data-ng-app`, `ng-repeat` - `data-ng-repeat`, etc.

You can use `gulp-angular-htmlify` to create valid HTML5 output for deployment:
https://github.com/pgilad/gulp-angular-htmlify

**Comment by user378230** [comment]
Given that this isn't done on the main  [angular-ui/bootstrap](https://github.com/angular-ui/bootstrap-bower/blob/7d5d0789cb5a43b8a9da9afc6bba62f788ef119b/ui-bootstrap-tpls.js#L7186) or [angular-strap](https://github.com/mgcrea/angular-strap/blob/7c9f1b5038631c0f92432d5d9e11a192b95c77e6/dist/angular-strap.tpl.js#L11) I'm going to close this as a won't fix. 

If its good enough for those libs its good enough for ours at this point :smile:. You can always build this into your own build process if necessary as the package is available through npm.
