### ISSUE TITLE
Refresh call fills dropdown with already selected values

### ISSUE THREAD

**Issue by Zacharias3690** [angular-ui/ui-select#1092]
in ui-select-multiple, the initial list is filtered correctly, but after a call to the server, the objects don't match up anymore and the refresh call won't filter values out.

In uiSelectController ctrl.refreshItems
```javascript
var filteredItems = data.filter(function(i) {return selectedItems.indexOf(i) < 0;});
```

This will work when the selectedItem and the items in data match exactly, however when pulled from the server, the item in selectedItems isn't the exact same item as in data.

a fix for this is to change the filter function to do angular.equals like so

```javascript

var filteredItems = data.filter(function(i) {
   for(var j in selectedItems) {
     if(angular.equals(selectedItems[j],i)) {
       return false;
     }
   }
   return true;
});
```

**Comment by kmccullough** [comment]
I'm using something like this:

```html
<div ui-select-choices
    repeat="
        language.language as language in
        languages.sorted | filter:$select.search
    ">
        {{language.description}}
</div>
```
While your solution apparently fixes your use case, mine is still going to be broken, because this function does not account for the property used here (language.language); it will compare the full record to the language key, which will obviously not match.

**Comment by stevematyas** [comment]
1. Is there a way to obtain/reference the binding property from the alias that is used  (myobject.property from `repeat="myobject.property as myobject in mylistofobjects"`)? 

2. What's the correct way to expose an expression for the filter function? 
`var filteredItems = data.filter(function(i) {return filteredItemsFunction(selectedItems, i); }     );`

3. Others?

**Comment by wesleycho** [comment]
One should probably look into implementing a filter on the user's side for this.

Going to close as something already doable.
