### ISSUE TITLE
e.match is not a function

### ISSUE THREAD

**Issue by joelcdoyle** [angular-ui/ui-select#1094]
Using tagging, when I enter text into the text input, I get this dev console error once for every character I enter in the input:

```js
Uncaught TypeError: e.match is not a function
```

The select is working properly, but what is this annoying error?

```html
<ui-select multiple tagging="tagTransform"
                  ng-disabled="disabled"
                  search-enabled="true"
                  tagging-label="(custom 'new' label)" 
                  theme="bootstrap"
                  sortable="true" 
                  title="Choose a category"
                  id="add-categories" 
                  ng-model="transaction.selected">
  <ui-select-match placeholder="Enter category title and press enter..." >
    {{$item.description}}
  </ui-select-match>
  <ui-select-choices repeat="category in categories | filter:$select.search">
    <span ng-bind-html="category.description | highlight: $select.search"></span>
  </ui-select-choices>
</ui-select>
```

```js
$scope.categories = [
 {
    code: 50,
    description: "Gas"
 },
 ...
 {
   code: 100,
   description: "Utilities"
 }
]
```

**Comment by dcjohnston** [comment]
+1

**Comment by quotient** [comment]
Is there a solution on this issue?

**Comment by erikakinga** [comment]
+1

**Comment by user378230** [comment]
It would help greatly if someone can provide a demo plunkr or similar reproducing the error.

**Comment by AnatoliyLitinskiy** [comment]
https://embed.plnkr.co/OLkILVt02vBFhonBPExD/
Please try to search something
it looks, that `item.id` is not a string, so doesn't have `match` method

**Comment by user378230** [comment]
@AnatoliyLitinskiy you must specify a tagging function on the `tagging` attribute as per [Wiki](https://github.com/angular-ui/ui-select/wiki/ui-select) guidance:

>| option | description | value | default |
>|---|---|---|---|
>| `tagging` | Enable tagging mode (add new items on the fly). Accepts a string which is a scope function. If your model is an array of objects, this string is **required**. The function will be passed the new item as a string and should return an object which is the transformed value to be pushed to the items array. | string ($scope function)| undefined |

**Comment by wesleycho** [comment]
Going to close as this seems like a usage issue - feel free to open a new issue if this is not the case with appropriate reproduction.

**Comment by AnatoliyLitinskiy** [comment]
Thank you, @user378230

**Comment by samuelzyx** [comment]
I had same problem. But i fixed when the attribute taggin-lable set to false

```
<ui-select multiple tagging tagging-label="false"
      on-select="vm.addTag(task.id,$item)" on-remove="vm.removeTag(task.id,$item)"
      ng-model="task.etiquetas" theme="bootstrap" style="width: 100%;text-align: left;"
      title="{{vm.appData.introduceEtiqueta_label}}">
        <ui-select-match placeholder="{{vm.appData.add_label}}">{{$item.nombre}}</ui-select-match>
        <ui-select-choices repeat="tag in vm.availableTags | filter:$select.search"
        refresh="vm.refreshTagSearh($select.search);"
        refresh-delay="700">
        {{tag.nombre}}
      </ui-select-choices>
```

**Comment by swatijoshi** [comment]
tagging-label="false" fixed my issue.

**Comment by arjuneyy** [comment]
I also run into this issue, and I just wanna share to you guys how I fixed it.

For `<ui-select-choices>`, the value to provide should be **array of strings** and NOT array of objects. The javascript's **.match()** method is intended for String.

I also provided **tagging** and **tagging-label =" (New)"** to fix other issues related to **close-on-select="false"**
