### ISSUE TITLE
Bind ng-change event to input text box

### ISSUE THREAD

**Issue by riyunoa** [angular-ui/ui-select#1103]
Is it possible to bind the ng-change event to the input text box? I'm trying to change the width of the dropdown and textbox based on the number of characters the user has already typed.

Thanks in advance!

**Comment by jlandry** [comment]
<ui-select  multiple ng-model="savedItems" ng-disabled="disabled">
       <ui-select-match placeholder="test">{{$item}}</ui-select-match>
        <ui-select-choices repeat="thing in things" refresh="refreshFunction($select.search, $select)" refresh-delay="400">
         {{thing}}
</ui-select>

Then you can use the refreshFunction to grab the information and make a call in your main controller.

**Comment by wesleycho** [comment]
Closing as usage issue.
