### ISSUE TITLE
It seems that ui-select doesnt show all the choices inside node-webkit

### ISSUE THREAD

**Issue by benag** [angular-ui/ui-select#1104]
$scope.locations = ['asd','asdsd','asdd'];
     <ui-select ng-model="selected" theme="bootstrap" style="width: 300px;">
            <ui-select-match placeholder="Select Location">{{$select.selected}}</ui-select-match>
            <ui-select-choices repeat="location in locations | filter: $select.search">
               <div ng-bind-html="location"></div>
            </ui-select-choices>
        </ui-select>

**Comment by pkuklin** [comment]
try to add  ng-show="$select.open" to <ui-select-choices>

**Comment by wesleycho** [comment]
Can you post a reproduction with Plunker that can help and add more detail?

**Comment by benag** [comment]
sorry i am not on this project any more..
