### ISSUE TITLE
search fix

### ISSUE THREAD

**Issue by artemijan** [angular-ui/ui-select#1113]
Hello, i'm using your directive and seems like i have a problem with search logic.
When i'm typing into search input, '$select.seach' (it's a ng-model) updates only on blur or right click on dropdown or click somewhere else ('blur' again). I found a solution to fix it just add to ng-model-options="{updateOnDefault:true}" in your code (select.js). But i need to know, why it's happening?

**Comment by user378230** [comment]
I think ngModelOptions docs should contain what you need. https://docs.angularjs.org/api/ng/directive/ngModelOptions
