### ISSUE TITLE
tagging function should handle promises

### ISSUE THREAD

**Issue by ccollie** [angular-ui/ui-select#1118]
In my app, tags have identity, so on search we do an async call to the backend. Conversely adding a tag means inserting it into the db. It is therefore a necessity to be able to add tags asynchronously.

**Comment by user378230** [comment]
When using `taggingLabel !== false` the `taggingFunction` is actually run to create the item that is added to the start of the item list, so the user can select it if they wish. Therefore this wouldn't be a workable solution for your use case. 

This can be managed externally, using an `onSelect` callback to check if the new item is part of your existing list and saving to the db if not. 

It would be unnecessarily complicated to introduce I think, so I'm closing.

**Comment by scholtzm** [comment]
@user378230 What if the DB insert fails? In that case I don't want to add (and display) the value in ui-select component.

Sorry for bumping an old issue, I don't think the question above deserves a new one to be opened.
