### ISSUE TITLE
Issues restoring default browser styling when focused

### ISSUE THREAD

**Issue by kathkroll** [angular-ui/ui-select#1122]
Hi,

We are using the select2 theme for our dropdowns. When tabbing through the page elements, we would like the default browser styling to appear on the link element when reaching the ui-select element (blue outline for Chrome, dotted outline for Firefox, etc.). We are loading bootstrap v 3.2 css on the page, but that doesn't seem to be affecting the ability of other input elements on the page to use the default styling. I have tried removing all the outline: 0 and outline: none from the CSS files, but nothing seems to be working. 

Any insight?

**Comment by wesleycho** [comment]
Closing as a support issue.
