### ISSUE TITLE
AngularJS 1.4.3 TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by therealtomas** [angular-ui/ui-select#1128]
Hi, 

When selecting in single or multiselect i get TypeError: Cannot read property 'style' of undefined at Object.fn (select.js:1024).

I am running AngularJS 1.4.3, im guessing dropdown = angular.element(element).querySelectorAll('.ui-select-dropdown'); cant find correct element. Any ideas?

 <ui-select multiple ng-model="connectingDimensionValue.Value" theme="select2" name="connectingDimensionValue">
                <ui-select-match placeholder="Choose X">{{$item.Name}}</ui-select-match>
                <ui-select-choices repeat="connectingDimensionValue.Value as connectingDimensionValue in connectingDimensionValues | filter: $select.search">
                  <div ng-bind-html="connectingDimensionValue.Name"></div>
                </ui-select-choices>
              </ui-select>

**Comment by palpalani** [comment]
We are also getting similar issue, when using with AngularJS 1.4.3:

`TypeError: Cannot read property 'style' of undefined
    at Object.fn (select.js:1047)
    at Scope.$digest (angular.js:15683)
    at Scope.$apply (angular.js:15951)
    at HTMLDivElement.<anonymous> (angular.js:23303)
    at HTMLDivElement.eventHandler (angular.js:3271)`

**Comment by cjroth** [comment]
+1

**Comment by cjroth** [comment]
Just submitted a PR to fix it.

**Comment by carlos-** [comment]
+1 angular 1.4.4

**Comment by carlos-** [comment]
@cjroth verified your fix and it works on Angular 1.4.4

**Comment by cjroth** [comment]
Thanks @carlos.

**Comment by carlos-** [comment]
Do you know when is this issue being merged?

**Comment by IgorAufricht** [comment]
+1

**Comment by seilebri** [comment]
+1

**Comment by aghreed** [comment]
+1

**Comment by GregePorter** [comment]
+1
I am seeing this issue in IE with Angular 1.4.4

**Comment by wesleycho** [comment]
Post a reproduction if it is still an issue - the main fix already made it in `master` that I've seen.
