### ISSUE TITLE
Allow clear deletes the model completely 

### ISSUE THREAD

**Issue by GBora** [angular-ui/ui-select#1129]
When using  allow-clear="true" upon clearing the whole model gets deleted completely see plunker http://plnkr.co/edit/G3f7ox2suhUNM8e86jOb?p=preview

Is there any way to connect to the on-clear event and simply set the model to null ?

**Comment by awerlang** [comment]
Have you tried an on-select event handler, checking for undefined?

And out of curiosity, how does your app break if model value equals to undefined?

Source: https://github.com/angular-ui/ui-select/blob/master/dist/select.js#L562
