### ISSUE TITLE
Display html chars such as <foo> in the select

### ISSUE THREAD

**Issue by Amir-E** [angular-ui/ui-select#1136]
When adding special chars in the select I am getting an error:
"The sanitizer was unable to parse the following block of html"

I tried to use encode html and got: &lt ;foo&gt ;
This one worked when I am opening the dropdown and show &lt;foo&gt;
but when selecting the item I see &lt ;foo&gt ;

Any Solution other then using something like that:
<span ng-bind-html="encodeHtml(person.Name) | highlight: $select.search"></span>

http://plnkr.co/edit/SEzrd9vSEmneX4o87UCg?p=preview
Check the first country in the list to reproduce the issue

**Comment by sanderaido** [comment]
Can you pre-encode the list and use &lt; and &gt; instead of < and > ? Then it would work without html binding.

**Comment by Amir-E** [comment]
But then, when I am selecting the item it looks like &lt ;foo&gt ; and not &lt;foor&gt;

**Comment by user378230** [comment]
But then, when I am selecting the item it looks like &lt ;foo&gt ; and not <foo>

This can subsequently be resolved by doing
```html
<ui-select-match placeholder="Select or search a country in the list..."><span ng-bind-html="$select.selected.name"></span></ui-select-match>
```
Note the `ng-bind-html`

Closing as resolved.
