### ISSUE TITLE
Is there an option to not remove an option from a multiselect drop menu when it is selected?

### ISSUE THREAD

**Issue by jermsull** [angular-ui/ui-select#1137]
The default behavior on mult-select controls is to have a selected option in the drop menu to not show in the drop list after selection.  Is there an option or another method for allowing the selected item to stay in the drop list after selection?

**Comment by awerlang** [comment]
Looking at the code we can see that a `removeSelected` flag is set to `true` on `uiSelect` controller.

A possible solution would be a directive that requires the `uiSelect` and sets `uiSelect.removeSelected` to `false` during post-link. It just have to be executed later than `uiSelectMultiple` controller. Just put your directive at the same tag as `uiSelect`.

Source: https://github.com/angular-ui/ui-select/blob/master/dist/select.js#L1165

**Comment by jermsull** [comment]
Thanks, awerlang!

**Comment by user378230** [comment]
This is now possible using the `remove-selected="false"` public api attribute. closing.
