### ISSUE TITLE
Empty Result Notification

### ISSUE THREAD

**Issue by TJSoftware** [angular-ui/ui-select#1144]
I have a need for a notification when the search results are empty.  I glanced at the code and other places and I was not able to find that UISelect does this.  Please let me know if it does and how to do this if so.  

Based on what I found in the code, `ctrl.searchInput.on('keydown', function (e) {` can tell when `ctrl.items.length === 0`.  The issue is I do not know how I can pass from the UISelect scope to my scope that no items are in the search.  

Is this something that you can help with?

**Comment by nvernooy** [comment]
+1

**Comment by jitendersandhu** [comment]
+1

**Comment by maorshabo** [comment]
+1

**Comment by user378230** [comment]
You can achieve this by creating a custom directive that `require`s ui-select and then accessing `$select` you should then be able to watch `$select.items`.

**Comment by TJSoftware** [comment]
@user378230 That may be possible, I am not working on that project anymore.  It would be nice if you provided a bit more than just a general overview of how to do this before assuming that you can close something.  I.E. Confirming that the OP or anyone else in the thread is able to do what you are doing.  My original request was not just how to do it, but to have the functionality added to AngularJS.

**Comment by user378230** [comment]
Hi @TJSoftware 

I completely understand where you're coming from and I would feel the same under most typical active repo circumstances. However in this instance the repo has been dead for about 6 months and there is a huge backlog of issues. I'm currently working to try and reduce the noise in the issue log of things such as support requests, repeated questions and very specific feature requests.

Also just to be clear, we aren't affiliated with AngularJS. AngularJS is run by a team of 5+ full time (paid?) contributers, this repo is currently being run by about 3 of us who look after it during our lunch breaks and occasionally our free evenings (at least I do! :smile:). 

I also closed it as I don't think this is a highly demanded feature, as you can see only three others have requested it in 6 months. For the additional complexity and code this might add I do not believe it worth the effort. 

With issues of this age most users, like yourself, are no longer working on the project that cause them to raise it, this is why I kept my reply short and concise. I've closed ~100 issues in the last few days this is the first time anyone has replied. If anyone requires more assistance I or others would be happy to provide it within reason. 

I hope this help you understand my reasoning for closing, I generally do include a short reason when closing but on this occasion thought it wasn't necessary. I'll keep that in mind in future.

Thanks

**Comment by TJSoftware** [comment]
@user378230 I appreciate you taking the time to give an explanation.  I can understand not keeping up with an out of date repo.  Especially with Angular2 out there.  Seeing your account name I originally assumed that someone just saw the issue and made a comment about a possible solution.  I had also assumed that anyone could close an issue and only contributors could reopen it.
