### ISSUE TITLE
Pleaceholder is not visible when search-enabled is false

### ISSUE THREAD

**Issue by AndrewEastwood** [angular-ui/ui-select#1145]
How to show placeholder for regular mode of select?

**Comment by bliitzkrieg** [comment]
@AndrewEastwood did u find a fix?

**Comment by AndrewEastwood** [comment]
I'll try and let you know later

**Comment by chielsen** [comment]
I have the same problem

**Comment by AndrewEastwood** [comment]
Guys, I've just dropped this buggy lib out from my project and switched to select2

**Comment by hkorutla** [comment]
Did you find any fix?

**Comment by hkorutla** [comment]
I have the same problem with "selectize" theme.

**Comment by wesleycho** [comment]
This needs a reproduction via Plunker.

**Comment by buffaloproject1** [comment]
Looks like this specific to IE and Firefox in Windows
