### ISSUE TITLE
Outdated NPM version

### ISSUE THREAD

**Issue by Oza94** [angular-ui/ui-select#1148]
The published version on NPM is only `0.11.2`, can you please publish `0.12`?

My concern is the `"postinstall": "bower install"` under `0.12` which would force me to install globally bower on my production machines only for `ui-select`.

**Comment by Schlogen** [comment]
+1

**Comment by chadfawcett** [comment]
+1

**Comment by yangliuyu** [comment]
+1

**Comment by yangliuyu** [comment]
0.12.1 please

**Comment by nfleury** [comment]
+1 
pleeaaase

**Comment by arathael** [comment]
+2 (I have a dude right next to me)

**Comment by tb** [comment]
+ 1

**Comment by mkoryak** [comment]
`npm publish` from project root

**Comment by mkoryak** [comment]
i forked it and published under a different name:

https://www.npmjs.com/package/ui-select-that-was-forked-solely-to-update-npm-version

**Comment by eranimo** [comment]
:clap:

**Comment by jmendiara** [comment]
+1

**Comment by chrisfosterelli** [comment]
+1

**Comment by mkoryak** [comment]
this is the problem with 500+ open issues. something trivial that will make a lot of peoples lives easier gets ignored for no reason

**Comment by lazychino** [comment]
:+1: we need this!!

**Comment by mkoryak** [comment]
`npm install ui-select-that-was-forked-solely-to-update-npm-version` gets you the latest one, though ill probably delete it when ui-select publishes a new version.. so in a few months

**Comment by chrisfosterelli** [comment]
@mkoryak Please consider not deleting the package. Anyone who relies on it may discover suddenly during a deployment that the package is gone with no context. [npm recommends against unpublishing packages people depend on](https://docs.npmjs.com/cli/unpublish).

**Comment by mkoryak** [comment]
fair enough, ill do that. Glad people found it useful, even with the funny package name :)

**Comment by bathos** [comment]
npm version is out of date again, 0.12.100 instead of 0.13.2, which contains big fixes. @mkoryak since this is a recurring issue could we get npm install ui-select-that-was-forked-solely-to-update-npm-version upgraded to 0.13.2?

**Comment by mkoryak** [comment]
maybe you are looking at the wrong thing, but the npm version is now correct: https://www.npmjs.com/package/ui-select

(it still doesnt have a correct main in package.json though)

**Comment by wesleycho** [comment]
Closing as the current maintainers are publishing to npm.
