### ISSUE TITLE
Input field is obscured by results list in v0.12.0 and newer

### ISSUE THREAD

**Issue by timscaffidi** [angular-ui/ui-select#1158]
When using ui-select v0.12.0 or newer, the input field gets covered up by the results list, it should appear below the field so that the input is always visible. I tested v0.12.0 and 0.12.1, and both behaved the same. v0.11.2 works as expected.

**Comment by JL-Aus** [comment]
I confirm the same issue in v.0.12.1

**Comment by wesleycho** [comment]
Could you post a reproduction in Plunker?
