### ISSUE TITLE
Tab out of select field

### ISSUE THREAD

**Issue by SimeonC** [angular-ui/ui-select#116]
This is a bug with #92.

**Steps**
1. Click to open field - so it shows the input field for searching.
2. Press TAB
3. ui-select is still active field.

**Problem**
Step 3 should be that the next tabbable input should be focussed.

**Fix**
I think the fix for this is to do with the `tabindex` attribute. Currently we have 2 inputs, the `tabindex="-1"` input used for searching (search input) and the other one we use for detecting tab order (tab input) has class `.ui-select-offscreen`.
The solution I think is as follows:
1. Click to open field - Triggers a focus for the 'search input' field.
2. The 'search input' field has it's tabindex attribute set to that of the 'tab input'
3. The 'tab input' field should have it's tabindex attribute set to -1.
   4 On 'search input' blur (item selected/tab out etc) return the tabindex to what they originally were.

**Comment by marcievanauken** [comment]
Hi - this is still broken. Any updates?

**Comment by kristerd** [comment]
It seems like this still is broken on 18.0?

**Comment by johanroug** [comment]
Any news here. Still an issue

**Comment by julienrott** [comment]
Based on [https://github.com/angular-ui/ui-select/issues/1544](url)
I use this to focus out when tab key is pressed in multiple ui-select :

```
    angular.module('myModule')
        .directive('uiSelectCloseOnTab', uiSelectCloseOnTab);

    function uiSelectCloseOnTab() {
        return {
            require: 'uiSelect',
            link: function(scope, element, attrs, $select) {
				var that = this;
                var searchInput = element.querySelectorAll('input.ui-select-search');
                if(searchInput.length !== 1) throw Error("bla");

                searchInput.on('keydown', {select: $select}, function(event) {
                    if(event.keyCode == 9) {
                        event.data.select.close();
                        event.data.select.setFocus();
                    }
                });
			}
        };
    }
```
