### ISSUE TITLE
Don't show choices with a large data set

### ISSUE THREAD

**Issue by jcfiorenzano** [angular-ui/ui-select#1160]
I have some problems using ui-select with 172 items it's not a too large data set but when I used it the choices's panel don't appear, I can search into the component but the list of choices don't appear when   the dataset is small 20 items perhaps,  it work very well.

**Comment by user378230** [comment]
I think you are looking for the minimum input length option included as part of #1291 

Closing for now, please update this issue with more information if you need it reopened.
