### ISSUE TITLE
Placeholder not showing in ie9

### ISSUE THREAD

**Issue by gaultier** [angular-ui/ui-select#1161]
Hello,
When I use the option `placeholder="my text"` inside the `ui-select-match` directive, it works in recent versions of Firefox and Chrome but not in IE9: no text shows up.

We have a workaround for IE9 placeholders in the form of a special directive but it does not work inside the `ui-select-match` directive for some reason.

Do you have any idea on how to fix this issue?
Thanks for your time.

**Comment by llinard** [comment]
FYI, Internet Explorer 9 does not support the HTML placeholder attribute.  The template uses the standard placeholder attribute on the input in select.tpl.html to show placeholder text.

I'd imagine that you will probably have to customize the select.tpl.html template for the theme you are using to instead hide the input and show a span or something to work around the browser limitation, or you might be able to attach your custom directive directly to the input.

Be aware that disabling search currently hides the input thus also removing the placeholder.

**Comment by wesleycho** [comment]
Closing as a support issue.
