### ISSUE TITLE
Equivalent to select2 formatSelectionCssClass

### ISSUE THREAD

**Issue by triforce** [angular-ui/ui-select#1164]
In angular-ui-select2 you could change the styling of the selected items (tagging mode) using select2Options as follows:

$scope.select2Options = {
    formatSelectionCssClass: function (item, container) {
        $(container).parent().css({ "background-color": "#000000", "color": "FFFFFF" });
    });
}

I am using this to add custom colors to each tag a user selects. Each tag is a custom object that contains a 'color' property.

Is there an equivalent in angular-ui-select? If not is there a plan to add this feature in?

Many thanks.

**Comment by faisalferoz** [comment]
+1

**Comment by triforce** [comment]
+1

**Comment by jacobmumm** [comment]
+1

**Comment by marincode11** [comment]
+1

**Comment by user378230** [comment]
You can customise match-multiple.tpl.html and/or the contents or <ui-select-match> using usual angular directive to achieve this. 

Closing as there the existing solution is adequate.
