### ISSUE TITLE
Missing implementation in dist script

### ISSUE THREAD

**Issue by rafakato** [angular-ui/ui-select#1166]
I was checking the dist script for a feature introduced with #1110, it is merged as seen into (https://github.com/angular-ui/ui-select/blob/bc3de20678e243433d3f02ec96060d538a63183b/src/uiSelectDirective.js#L47) but does not exists in the `select.js` file in `dist` folder (https://github.com/angular-ui/ui-select/blob/master/dist/select.js#L805).

**Comment by user378230** [comment]
The dist scripts should have been regenerated since thus including the PR changes, so closing.
