### ISSUE TITLE
Wrong top position of choices when edit value

### ISSUE THREAD

**Issue by vatcher** [angular-ui/ui-select#1167]
Hi,

I´m using your ui-slect and it is a great component.
I´m using it a I belive to find a bug. 
When ui-slect shows the choices on top of the input field an I enter some value, the box with choises reduces its hight, but not its position. So the choices are somwhere over the top of my component.
Here is my code:
 
![ui-select-full](https://cloud.githubusercontent.com/assets/12648906/9519581/27744f58-4cc0-11e5-8417-edd350dd6cc9.PNG)
![ui-select-edit](https://cloud.githubusercontent.com/assets/12648906/9519582/277a71b2-4cc0-11e5-9d06-d8036af9f2e4.PNG)
```
<div class="form-group required">
    <label for="countryCB" class="control-label">{{'PRODUCT_COUNTRY_SELECT' | translate}}</label>
    <ui-select id="countryCB" ng-model="vm.selectedCountry" ng-disabled="disabled" title="{{'PRODUCT_COUNTRY_SELECT' | translate}}">
        <ui-select-match placeholder="{{'PRODUCT_COUNTRY_SELECT' | translate}}">
            <span ng-bind-html="$select.selected.country"></span>
            <small ng-bind-html="$select.selected.countryIso"></small>
        </ui-select-match>
        <ui-select-choices repeat="country in vm.countries | filter:{country:$select.search}">
            <span ng-bind-html="country.country | highlight: $select.search"></span>
            <small ng-bind-html="country.countryIso | highlight: $select.search"></small>
        </ui-select-choices>
    </ui-select>
</div>
```
Is it a bug, or am I wrong?

**Comment by vatcher** [comment]
Seems to be the same issue as #1007

**Comment by wesleycho** [comment]
Closing as a duplicate
