### ISSUE TITLE
buggy ui when search-enabled="false" and open top

### ISSUE THREAD

**Issue by benri** [angular-ui/ui-select#1171]
http://plnkr.co/edit/zjtzBp4aV3PqVcIGcy9U?p=preview

bootstrap theme, the whole thing disappears, not sure if this is intended
select 2 theme, there is a gap between dropdown and the bar
selectize theme, the top is cut off without a search bar

**Comment by wesleycho** [comment]
It seems only the Bootstrap theme is broken currently, as seen [here](http://plnkr.co/edit/aVuIaBltlgutJZ1cDCvq?p=preview).

Going to close in favor of #1520.
