### ISSUE TITLE
Crash when .ui-select-dropdown is missing

### ISSUE THREAD

**Issue by vivainio** [angular-ui/ui-select#1172]
Repro: have choices.tpl.html that doesn't have ui-select-dropdown class in ui-select-choices

The offending code in uiSelectDirective.js only check the result for null-ness, not empty list (and tries to access the first element of the list)

```javascript
        // Support changing the direction of the dropdown if there isn't enough space to render it.
        scope.$watch('$select.open', function(isOpen) {
          if (isOpen) {
            dropdown = angular.element(element).querySelectorAll('.ui-select-dropdown');
            if (dropdown === null) {
              return;
            }

            // Hide the dropdown so there is no flicker until $timeout is done executing.
            dropdown[0].style.opacity = 0;

```

**Comment by user378230** [comment]
Closing this as not really a bug. 

`ui-select-dropdown` is required for library to function so simply don't delete it.
