### ISSUE TITLE
 keep the drop down list always open

### ISSUE THREAD

**Issue by manichandra** [angular-ui/ui-select#1177]
I tried to keep the drop down list always open but i coudn't find the option . 
It would be very nice to have a feature to produce dual list box using ui-select .

**Comment by lesavsoftware** [comment]
Had similar problem. Wanted to keep the selection box always open. One way to do it is to create wrapper directive and to override the close method for the internal ui-select component on linking.
At least, it worked for me.

            link: function(scope, element, attrs){
                var selectElement = element.find(".ui-select-container");
                var uiSelect = selectElement.controller('uiSelect');
                uiSelect.close = function(){};
            }

**Comment by manichandra** [comment]
@lesavsoftware 
can you please share a plunker if you have any or can you explain me in little more detail ?

**Comment by lesavsoftware** [comment]
Hi.

you can see it in action here:
http://embed.plnkr.co/WWjlKaua4rAgvdbJu43G/preview

What I did for my app, I also added some css overrides to remove the blue background for selected color.

**Comment by manichandra** [comment]
Thanks @lesavsoftware . 
I will use it to create a dual list box . basically i want to keep the list open and show it on the left side and  selected items in a different box on the right side of the page .

**Comment by user378230** [comment]
Closing as answered.
