### ISSUE TITLE
No event fired or callback when clearing the input?

### ISSUE THREAD

**Issue by burzum** [angular-ui/ui-select#1178]
On https://github.com/angular-ui/ui-select/wiki/ui-select-match it says I can use a boolean to allow clearing the input, this works fine but there seems to be no away to register that?

My issue is that I'm using two dependent selects, when I clear my country select I would like to reset the state select as well. But I can't do that because I can't detect that country_id got reset.

Is this not possible with the current version of ui-select or am I missing something?

**Comment by nmeln** [comment]
@burzum Have you found any solution/workaround to this problem?

**Comment by gitnik** [comment]
Currently not supported but would be fairly easy to integrate

**Comment by wesleycho** [comment]
Going to close this as a duplicate of some issues.
