### ISSUE TITLE
set value or a default value

### ISSUE THREAD

**Issue by viniciusgava** [angular-ui/ui-select#1180]
Hello I am trying to set a value to ui-select but does not work.

I saw this issue (https://github.com/angular-ui/ui-select/issues/334) but the solution proposal there does not work for me.

Example:
````html
<ui-select multiple ng-model="attribute.selectedValue" name="{{'attribute_' + attribute.id_catalog_attribute}}" theme="select2" ng-required="fieldIsRequired(attribute)">
   <ui-select-match placeholder="Select ">
      {{ $item.name }}
   </ui-select-match>
   <ui-select-choices repeat="option in attribute.options | propsFilter: { name: $select.search } ">
      <div ng-bind-html="option.name | highlight: $select.search"></div>
   </ui-select-choices>
</ui-select>
````

Just for test, I add this line to see if the ui-select set the value
````javascript
$scope.attributes[0].attributes[144].selectedValue = $scope.attributes[0].attributes[144].options[3];
````
But did not worked.

**Comment by viniciusgava** [comment]
For normal select I resolved, I found a mistake that is removing the default value, for multiselect/multichoice I change for  a normal select.

**Comment by karthikeyar9** [comment]
Hi its not getting updated with ng-model in my application I need select to have 2 way data binding. can anyone help me how to achieve this. Thanks in advance

**Comment by viniciusgava** [comment]
Hello @karthikeyar9, are you trying to select two values by the model in multi-select? If yes, I had this problem and after some time trying to resolve it, I decided to remove ui-select and use a normal multi-select(html) and after that, the multi-select started work.

**Comment by karthikeyar9** [comment]
@viniciusgava I was trying to use one value only, when i change from UI ng-model was not getting updated so i used change event like below and sending selected value. Hope it helps someone
ng-change="changeFunc($select.selected)"

**Comment by CoconutDeveloper** [comment]
@karthikeyar9 
> @viniciusgava I was trying to use one value only, when i change from UI ng-model was not getting updated so i used change event like below and sending selected value. Hope it helps someone
> ng-change="changeFunc($select.selected)"

helped me :D thanks 👍
