### ISSUE TITLE
Tagging has a bug in with Angular 1.4.4

### ISSUE THREAD

**Issue by burakkilic** [angular-ui/ui-select#1187]
Hi;

I am using tagging with AngularJS 1.4.4.

I want to add tags with ',' but it is not possible. Only "ENTER" works.

With 1.3.0 like in the example, it works fine.

Please fix it.

Thank you.

**Comment by vitalii** [comment]
Hi!
The same for 1.4.5 angular, but even ENTER doesn't work and any other symbol.

**Comment by user378230** [comment]
Closing this issue as it is 6 months and doesn't have a repro sample. 

**Please note**  tagging functionality is currently broken for single select. (There are existing issues open already)

If you believe its still relevant please create a new issue with a plunkr (or similar) against the latest version of ui-select (currently v0.16.0) along with more detailed information. 

Thanks
