### ISSUE TITLE
What is the min-width of ui-select-choices box? 

### ISSUE THREAD

**Issue by EnvySky** [angular-ui/ui-select#1198]
I see we have this css:
.ui-select-bootstrap>.ui-select-choices {
    width: 100%;
    height: auto;
    max-height: 200px;
    overflow-x: hidden;
    margin-top: -1px;
}

So what does "width: 100%;" mean? Because if I set the width of ui-select equal to 150px, the ui-select-choices always equal to 158px, so is width: 100%  equal to 158px?

Can I set the width of ui-select-choices equal to 150px or less than?

**Comment by wesleycho** [comment]
Closing as a support issue.
