### ISSUE TITLE
IE8 event delegation in ng-repeat

### ISSUE THREAD

**Issue by drozv** [angular-ui/ui-select#120]
In the following code: 

```javascript
choices.attr('ng-repeat', RepeatParser.getNgRepeatExpression(repeat.lhs, '$select.items', repeat.trackByExp, groupByExp))
              .attr('ng-mouseenter', '$select.setActiveItem('+repeat.lhs+')')
              .attr('ng-click', '$select.select(' + repeat.lhs + ')');
```

The ng-mouseenter and ng-click events are attached to the initial element that is later converted into a list of elements. The problem is that in IE8 the jquery session attribute is copied from the initial element to each repeated element, and therefore it is the same for each one. As a result, when one of the events is fired for a single element, it is also fired for all of the other elements. This causes IE8 to freeze up and crap out for medium-sized lists (60+ elements).

To fix this, either delegated events or a rewrite of this code needs to be done. I don't really understand why the repeat attribute is used and why the above attributes are attached using jquery...

**Comment by user378230** [comment]
Closing as resolved by #754 (via #158)
