### ISSUE TITLE
Problem with multiple ui-select and ui-disable-choice

### ISSUE THREAD

**Issue by ludydoo** [angular-ui/ui-select#1200]
When using the ```ui-disable-choice``` attribute, the plugin will add the ```_uiSelectChoiceDisabled``` property directly to the option model to store if the option is disabled or not. So, when two ```ui-select``` share the same list of object, options will be disabled in both ```ui-select```. This is not desirable because a different ```ui-disable-choice``` attribute might be defined for different ```ui-select``` that share the same data.

A hack would be to clone the options object. But is it possible to have a better fix than that?

Is it possible that this attribute be ```_uiSelectChoiceDisabled-{{UNIQUE ID OF UI-SELECT}}```, that would permit to disable the option only in the given ```ui-select```?

Check this http://plnkr.co/edit/WD8eEo?p=info

For a given **Transaction**, there is an **Account** and a **Category** defined.
Both **Account** and **Category** options are issued from the same list. An **Account is** a **Category** and vice-versa.

The **Category** ```ui-select-choice``` tag has the ```ui-disable-choice``` attribute set to a function that disables the **Category** if this **Category** has the same ```id``` property as the **Account** ```id``` property.

1. Select "Category 1" as the account
2. Select "Category 2" as the category
3. Select "Category 2" as the account
4. Try to select "Category 1" as the account (doesn't work)

**Comment by arseneoaa** [comment]
+1
This is related to bug #656
