### ISSUE TITLE
[REQUEST] Pass removed item index from removeChoice() to on-remove event

### ISSUE THREAD

**Issue by soee** [angular-ui/ui-select#1202]
ui-select offers [on-remove](https://github.com/angular-ui/ui-select/wiki/ui-select#events) that is called when item gets removed. This event recieves 2 parameters: $item, $model but there are situations when we need index of removed element. 

So my suggestion is to add maybe third parameter that will pass removed element index to on-remove event.

**Comment by user378230** [comment]
Can be achieved using `indexOf` on the appropriate array. Closing, a PR would be welcome if anyone needs this, should be a minor change.
