### ISSUE TITLE
The docs don't mention that you actually need an external theme or it won't work at all

### ISSUE THREAD

**Issue by gkinsman** [angular-ui/ui-select#1205]
If you don't include one of select2, bootstrap or selectize's css files, the ui-select will be completely broken and not work at all.

Is this project designed to be a standalone angular control, or have a dependency on select2? It seems to be halfway there given that you still need external css. 

Either include the select2 css theme or mention that it depends on select2, please.

**Comment by user378230** [comment]
Wiki must have been updated since this issue was created so closing.

>Bootstrap/Select2/Selectize CSS as appropriate

https://github.com/angular-ui/ui-select/wiki
