### ISSUE TITLE
Problem with ui-select-required

### ISSUE THREAD

**Issue by dshep4** [angular-ui/ui-select#1206]
Upon selecting an item from a multi select box and then deselecting it I am left with the following classes in the element

```html
<div class="ui-select-container ui-select-multiple ui-select-bootstrap dropdown form-control ng-valid ng-dirty ng-touched" 
    ng-class="{open: $select.open}" 
    name="slideTransitions" 
    ng-model="slide.transitions" 
    theme="bootstrap" 
    ui-select-required="">
```

As you can see the element still believes it valid when ui-select-required should step in and make it invalid because nothing is selected

**Comment by user378230** [comment]
This should be resolved by #1492 when release. 

If not please update the issue with a demo plunkr (or similar) against the latest version of ui-select (currently v0.16.0)  and it we can reopen the issue.

**Comment by tmanoel** [comment]
It's not working yet. Using v0.19.0...

**Comment by user378230** [comment]
@tmanoel please provide plunkr

**Comment by tmanoel** [comment]
Take a look, it doesnt work on single neither multiple..
http://plnkr.co/edit/5Zt0OfEFh18tlcKP1Yen?p=preview

**Comment by user378230** [comment]
Only latest version is supported. `v0.11.2` is very old, please ensure plunkr is update to date.

**Comment by tmanoel** [comment]
Sorry, updated... Look:
http://plnkr.co/edit/21NTjbyMIHY67gf6BN2S?p=preview

Note: in the version 0.19 we have this note:
 * http://github.com/angular-ui/ui-select
 * Version: 0.18.1 - 2016-07-10T00:18:11.107Z
 * License: MIT
