### ISSUE TITLE
CSP errors caused by inline script

### ISSUE THREAD

**Issue by rchdly** [angular-ui/ui-select#1218]
I'm seeing CSP errors due to `.ui-select-row-choices-inner` elements having an `href="javascript:void(0);"` - inline scripts are not allowed by CSP.

I suggest using `href="#"` here and adding `$event.preventDefault()` to the `select` function.

**Comment by pra85** [comment]
This issue has been addressed by the pull request #1182

**Comment by wesleycho** [comment]
Closing as already fixed.

**Comment by graingert** [comment]
@wesleycho should be re-opened because there's yet more inline JS. #1958
