### ISSUE TITLE
extra input box shows up after updating to new version 0.13.1 . tried going back to the older version but it dint fix the problem. 

### ISSUE THREAD

**Issue by manichandra** [angular-ui/ui-select#1219]
I am getting extra input field below all the UI-select fields. 
it started after updating to the new version (0.13.1) . So i tried going back to the older version but it dint fix the problem .
![capture](https://cloud.githubusercontent.com/assets/2058515/10200570/34cc9578-6775-11e5-9af5-a7ae05cca300.PNG)
![capture1](https://cloud.githubusercontent.com/assets/2058515/10200569/34c9fc64-6775-11e5-8cba-db343b755f50.PNG)

**Comment by dimirc** [comment]
Can you setup a plunker or give me more info on how to reproduce it?

**Comment by manichandra** [comment]
Unfortunately i am unable to reproduce the same in plunker . I have copied the same javascript code and css i am using,  but no luck . 
I will try again with different versions of js and css file and let you know . 

Meanwhile can you please help me with a feature i have been trying to achieve . In the application we are creating i am using a single select(not multi select). add new entry by tagging for single select is not working in the master build.  With the help other helpful  guys like you i was able to make it work . Now  I want to select new entry on "blur" event  after typing . I tried different options but i am losing other features like "search". please have a look at the below plunker .

http://plnkr.co/edit/8YiSdUULm336giX3gglZ?p=preview

**Comment by felix2feng** [comment]
did you ever figure out the cause of this issue?

**Comment by SaveTheJungle** [comment]
For any one who have the same problem, the problem in missing ui-select css styles.
See stackoverflow issue [how to remove unwanted box in ui-select?](https://stackoverflow.com/questions/29386988/how-to-remove-unwanted-box-in-ui-select)
