### ISSUE TITLE
Selected choices to be available in list(ui-select-choices ) after selection.

### ISSUE THREAD

**Issue by settysreekanth** [angular-ui/ui-select#1221]
Hi, I am trying to implement multi-select using this library. 

My requirement is to provide multiple choices using a checkbox instead of showing selected items at ui-select-match(as a tag).

To achieve above requirement, I want selected item to be still available in choice list instead of clearing it from the choice list. 

It would be good if this kind of feature is available in ui-select-choices directive.

please share the approach -if anyone has already implemented above requirement .

FYI - Image for my requirement is attached.

![multiselect](https://cloud.githubusercontent.com/assets/9054436/10209544/d6a84aee-6799-11e5-82cf-93e427122401.PNG)

**Comment by dimirc** [comment]
Probably you might only need to implement your own theme to make it possible

**Comment by settysreekanth** [comment]
@dimirc Thanks for your reply....
