### ISSUE TITLE
Overriding Bootstrap theme text color

### ISSUE THREAD

**Issue by dcb96** [angular-ui/ui-select#1222]
in select.css line 224 the code"color: # 333"(minus the space) (after ".ui-select-bootstrap .ui-select-choices-row>a )  is overriding the bootstrap theme.  It becomes a problem when the select background is close to that color.  I'm using  <a href="https://bootswatch.com/cyborg/bootstrap.min.css">  Cyborg</a> in the screenshots 

![image](https://cloud.githubusercontent.com/assets/14916228/10209673/3cda3fba-679b-11e5-8572-333fd6130be6.png)

![image](https://cloud.githubusercontent.com/assets/14916228/10209595/6ab50ee8-679a-11e5-8c55-fbd20c9712ae.png)

removing it allows the theme's color
![image](https://cloud.githubusercontent.com/assets/14916228/10209606/98601540-679a-11e5-9436-7c2e5707598b.png)

**Comment by dimirc** [comment]
What will be your suggestion?

**Comment by dcb96** [comment]
Just removed it. It works fine even with stock bootstrap.css.

Stock:
![image](https://cloud.githubusercontent.com/assets/14916228/10212501/826f5e8a-67bd-11e5-8ebc-2fbd0e2bc556.png)

Sandstone:
![image](https://cloud.githubusercontent.com/assets/14916228/10212528/d2b7de58-67bd-11e5-8331-893b3c1d17e2.png)

Slate:
![image](https://cloud.githubusercontent.com/assets/14916228/10212566/63e7cd7a-67be-11e5-8d9c-cf94cd48bbd0.png)


I haven't seen any cases (so long as the theme is based on bootstrap of course) that there is a need to force a specific color.

**Comment by dimirc** [comment]
Can you do a PR for this?

**Comment by user378230** [comment]
Looks like this only ever affected one person, PR welcome if anyone wants to submit though I'm not sure the blue colour is great on the select list text.

Maybe users should just consider to override in their own styling.
