### ISSUE TITLE
Duplicate search

### ISSUE THREAD

**Issue by furyscript** [angular-ui/ui-select#1223]
I've a problem with multiple select
```javascript
$scope.user = {}; 
$scope.user.selected = []; // array ID users
$scope.users = []; // array users founded
$scope.refreshUsers = function(user) {
        return httpService.get('/users?take=200&skip=0&page=1&pageSize=200&filter[filters][0][full_text][value]=' + user, function(data, status) {
            $scope.users = data.data;
            console.log($scope.users);
        });

};
```
```html
<ui-select multiple='true' ng-model="user.selected" theme="bootstrap" reset-search-input="false">
    <ui-select-match placeholder="Seleziona un utente...">{{$item.first_name}}</ui-select-match>
    <ui-select-choices repeat="user.id as user in users track by $index | propsFilter: {first_name: $select.search, last_name: $select.search}" refresh="refreshUsers($select.search)" refresh-delay="0">
        <div ng-bind-html="(user.first_name | highlight: $select.search) + ' ' + (user.last_name | highlight: $select.search)"></div>
        <small>E-Mail: {{ user.email }} </small>
    </ui-select-choices>
</ui-select>
```
```
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys .... [...]
```

The problem is that when I select a user, and I research it, I've found again him and I can re-insert it, but I don't want it...
I add `track by $index` or `track by user.id` but don't work...

I search a lot but all solutions not work...

I would be able to prevent same record in the search dropdown, so I think don't use track by... 
This plunkr could be help: http://plnkr.co/edit/DKcuPuzwfmAsOhlkhylP?p=preview
Type Adam and adam again, it show error..

**Comment by bni** [comment]
I also have this problem with multi select. Items already selected show up in the search dropdown.

After some testing with versions back and forth i found out this:

v0.11.1 and earlier this works as expected. 0.11.2 and later has the error.

**Comment by furyscript** [comment]
I'm testing with 0.11.1 and also not work.. @bni

**Comment by furyscript** [comment]
Some news?

**Comment by furyscript** [comment]
I need this!!!

**Comment by wesleycho** [comment]
Closing as a duplicate issue.
