### ISSUE TITLE
ui-select validation - 'required' not working with single select.

### ISSUE THREAD

**Issue by crypticsymbols** [angular-ui/ui-select#1226]
Template:

`<div class='form-group'>`
`<ui-select ng-model="user.bill_address.state" reset-search-input="false" required>`
`<ui-select-match placeholder="{{ 'STATE' | translate }}">{{$select.selected.name}}</ui-select-match>`
`<ui-select-choices repeat="state in user.bill_address.country.states track by $index" refresh-delay="0">`
            `{{state.name}}`
 `</ui-select-choices>`
`</ui-select>`
`</div>`

Form is not stopped by validation and attempts to submit when this field is empty.

Markup output:

![screen shot 2015-10-01 at 4 51 24 pm](https://cloud.githubusercontent.com/assets/1591971/10233525/e912dd16-685c-11e5-8f08-58eb994b064d.png)

Am I missing something?

**Comment by AlexEmashev** [comment]
Same issue.

**Comment by JobaDiniz** [comment]
`required` or `ng-required´ is not working at all.
I set `required` but the field has always `ng-valid` class applied to it, when actually it should have `ng-invalid` when invalid

**Comment by wesleycho** [comment]
Closing as a duplicate issue - the library does not support ng-required, that is a construct built into the angular input, select, and textarea directives.

PRs to implement it probably are welcome though.
