### ISSUE TITLE
Please use native for() loop instead of angular.forEach()

### ISSUE THREAD

**Issue by ChristianLJ** [angular-ui/ui-select#1234]
By using the native for() loop and not angular.forEach() (or the native forEach) it is possible to speed up the iterations by more than 60% in Chrome 45. This would indeed speed up the rendering of large datasets.

Test it: https://jsperf.com/angular-foreach-vs-native-for-loop/3

**Comment by williamoliveira** [comment]
:+1:

**Comment by lukaw3d** [comment]
Have you identified that the loops are the main cause of lower speed?
(they could represent less than 1% of the overall speed drop)

**Comment by user378230** [comment]
As mentioned above this issue lacks any thought through insight or information. 

There are existing already issues about performance, given that angular foreach is suitable for use by angular, I think its suitable for this library so I'm going to close this. 

If someone is willing to profile the library and submit a PR it can be reviewed by the team.

**Comment by noherczeg** [comment]
I'm not sure if this qualifies or not. Not to mention if the methodology is correct or not, but you may observe a 50% performance increase by using for() on larger data sets:

http://plnkr.co/edit/NHke0iFeJmcaurJclsvc?p=preview

**Comment by noherczeg** [comment]
Real application example of registerState seemingly being slow due to angular.forEach().

![registerState](http://i.imgur.com/OCsSg2P.png)

**Comment by user378230** [comment]
The problem is that no attempt has been made to determine if the angular.forEach loops are the cause of any major performance issues in the `ui-select` library. This isn't demonstrated in your plunkr either as far as I can tell.

**Comment by noherczeg** [comment]
@user378230 I'm terribly sorry. It was really late at night and I unintentionally dropped in on this project while I was experiencing the same problem with ui-router. The issue was too similar to what problem I'm facing with so I didn't notice that it's not the repo I should've been commenting on :/
