### ISSUE TITLE
Feature req: please $emit uis:close/activate when the close/activate events fire so parent controller can react

### ISSUE THREAD

**Issue by photostu** [angular-ui/ui-select#1235]
Have a use case where I need to know when selection is finished with a multiple select. Adding an $emit right after the broadcast solves this inside of ctrl.close function.

Let me know if you would like a PR and I can add this in, thanks!

**Comment by photostu** [comment]
Edit for activate call as well

**Comment by user378230** [comment]
Closing as resolved by #1723
