### ISSUE TITLE
when clearing the selected value or removing the model, activeIndex still exists.

### ISSUE THREAD

**Issue by alonn24** [angular-ui/ui-select#1241]
review here:
http://plnkr.co/edit/zmN4f1ALeMwtpZ4jTECz?p=preview

when opening the dropdown for the first time, $select.activeIndex gets a value,
and when removing the model or clearing the value (allow-clear="true"), the following code does not execute:
https://github.com/angular-ui/ui-select/blob/master/src/uiSelectController.js#L59
because ctrl.selected is falsy - there is a highlighted element in the middle of the list instead of the first item in the list.
![screen shot 2015-10-11 at 11 32 21 am](https://cloud.githubusercontent.com/assets/6017091/10416007/d03d5468-700b-11e5-8503-36d1de774d9e.png)

**Comment by kunal999** [comment]
I am having the same issue. This is causing an issue while testing using Selenium as the testing script assumes the first element would be selected when opened. I am using 0.13.2

**Comment by Jefiozie** [comment]
If i'm correct you have 2 problems. One is the activeindex (as issue is created for) is not cleared when pressing the clear button.
And the second problem is that you would expect that a error would be trowed as described on [line59](https://github.com/angular-ui/ui-select/blob/master/src/uiSelectController.js#L59)? (uiSelectMinErr)

**Comment by Jefiozie** [comment]
@alonn24 Did you already had a fix for this?

**Comment by alonn24** [comment]
@Jefiozie I do not have a fix for that, it is a minor one anyway.
