### ISSUE TITLE
tab out doesn't hide filter text

### ISSUE THREAD

**Issue by lvostinar** [angular-ui/ui-select#1242]
See:  http://plnkr.co/edit/Yyvw3lRPJMQzqBwzuEjG?p=preview

If I type some text in filter then tab out (and there are no matching results) the filter remains visible. If I do same thing but I click outside it works well.

Any thoughts how this should be fixed?

**Comment by samih-dev** [comment]
+1 
In my case I'm using multiple selection mode with tagging, I see x button tagged alone, without text. 
Using mouse click to focus out, the input value get deleted (again if the filtered text isn't exist) and not tag added - this should be the same behavior when pressing TAB.

**Comment by user378230** [comment]
Duplicate of #367

**Comment by wesleycho** [comment]
Closing as a duplicate as per comment
