### ISSUE TITLE
ui-select does not work with tabs.

### ISSUE THREAD

**Issue by psarda** [angular-ui/ui-select#1244]
Example: http://plnkr.co/edit/tck8hnHADbEEeRQ5ldE4

**Comment by bradhenslee** [comment]
Your <tabset> is part of your bootstrap library right? I think you just need to change to theme='bootstrap'...
``` <ui-select multiple ng-model='colors' theme='bootstrap' style='width: 100%'>```

Does this fix it?
http://plnkr.co/edit/OscyNWwbc3OTHl5hbtBL

**Comment by psarda** [comment]
Thanks Brad for the reply. 

In first case, (with theme='select2'), the dropdown was not working and placeholder text was not shown.
In second case, (with theme='bootstrap'), the dropdown is working but only for small limited area and placeholder text is also not completely visible.

![screen shot 2015-10-14 at 8 27 41 am](https://cloud.githubusercontent.com/assets/2437166/10473869/d4be841e-724d-11e5-95f5-77d763251ab4.png)

**Comment by kshutkin** [comment]
I think it is the same problem as in #212

**Comment by psarda** [comment]
Thanks @kshutkin for reply. Yes, you are write. I will try the workaround mentioned there.

**Comment by psarda** [comment]
closing as duplicate of #212 .
