### ISSUE TITLE
Multiple Select for Angular UI Select not able to Select Multiple values

### ISSUE THREAD

**Issue by muleya** [angular-ui/ui-select#1246]
Hi,

I implemented the AngularJS native implementation of Select.js but not able to select multiple values by Ctrl+Left Mouse Button click. I need to select multiple values is there a change in the implementation or am I doing something wrong ?

**Comment by kshutkin** [comment]
Is it not the same as #212?

**Comment by muleya** [comment]
I will tryout the fix suggested in #214.

**Comment by user378230** [comment]
ui select does not support ctrl click. Please refer to wiki or examples for multiple select demos.
