### ISSUE TITLE
ui-select encapsulated in a directive

### ISSUE THREAD

**Issue by chetanra** [angular-ui/ui-select#1247]
I am trying to abstract few things specific to my project into a directive built on top of ui-select.  I am running into a basic issue where the ui-select directive doesn't respond to any scope changes from with in my directive.

Weird part is watching for the same variables in my directive shows that values indeed are changing.

Here is the most stripped down plunker: http://plnkr.co/edit/8J3aMK1YMIIsJC3oa56U

Appreciate any help.

**Comment by chetanra** [comment]
I saw a solution on SO where the dev changed ui-select itself to solve the problem.  Seems like bit of an extreme situation for a simple problem.  Or is it a simple problem?

**Comment by kshutkin** [comment]
It is not clear what is the desired result but you probably want to check #1120 because inside your directive you have the same situation.

**Comment by chetanra** [comment]
Sorry for missing adding on what's expected.

In the plunker when you disable controls, both ui-selects have to be disabled.  And when enabled both have to.

Observed behavior is the ui-select directly used responds to buttons while the one included through a directive doesn't though the directive could see the state change.

**Comment by kshutkin** [comment]
It is easy: change `disabled="isDisabled == 'true'"` to `ng-disabled="isDisabled == 'true'"` inside your tagEditor.html.

**Comment by chetanra** [comment]
Thank you!  Any idea why just disabled didn't work?

**Comment by kshutkin** [comment]
Why you expect it to work? Plain `disabled` is just an html attribute and it can't eval angular expression. You can also check this [question](http://stackoverflow.com/questions/6961526/correct-value-for-disabled-attribute) about html `disabled`.
