### ISSUE TITLE
selected match doesn't update when removing the item with 'X' and the adding back programaticaly  

### ISSUE THREAD

**Issue by arsinawaz** [angular-ui/ui-select#1249]
Hi all,

I am try to remove a selected item from selected match by clicking in 'X' and then when i try to re-add the same item or even any other item programmatically by updating the model it doesn't show in the selected match even though it is present in the the model.

NOTE: removing and adding programmatically by updating model works properly until i press 'X'.

here i have created the issue in this plunker:
http://plnkr.co/edit/C2ua6cAaH0AQFZ5EUz7R?p=preview
First press 'X' and then 'add item' button.

Any help is appreciated. Thanks in advance.

**Comment by kshutkin** [comment]
Hi,
Your plunker link is not working. Probably you forgot to click Save on Plunker.

**Comment by arsinawaz** [comment]
Sorry my bad i have updated the plunker.

**Comment by kshutkin** [comment]
The main reason why it is not working as you expect it to work is #1120. You can check this plunker http://plnkr.co/edit/3iCzsdBYsD0qPWdQLzsT?p=preview. It is almost the same as your planker but I put model and choices into the `data` object and it works better.

**Comment by arsinawaz** [comment]
Wow that's strange it doesn't work if model is not an object. I am ok as long as it works.
thanks a bunch :)
