### ISSUE TITLE
Is it possible to Iterating over objects with multiple selection? 

### ISSUE THREAD

**Issue by Avien** [angular-ui/ui-select#1255]
When trying this template:

``` javascript
<ui-select multiple
               theme="select2"
               class="{{multiSelect.className}}"
               ng-model="multiSelect.ngModel"
               ng-disabled="disabled"
               on-select="multiSelect.selectModel()"
               on-remove="multiSelect.handleRemove()"
               focus-on="{{multiSelect.focusOn}}">
        <ui-select-match placeholder="{{multiSelect.placeHolder}}">{{$item.label || $item.name}}</ui-select-match>
        <ui-select-choices repeat="item.key as (key, item) in multiSelect.items | filter:$select.search">
            {{item.label || item.name}}
        </ui-select-choices>
    </ui-select>
```

I get the following errors:
TypeError: $select.refreshItems is not a function
TypeError: Cannot convert undefined or null to object

The only documentation I am trying to follow are these examples, which are for single selection:
http://plnkr.co/edit/9DsLidTZR7RJDEq6PW0H?p=preview

My object looks like this:

``` javascript
"campaignsMap":{
        "2672":{
            "id":2672,
            "name":"Engage Push Accept"
        },
        "1419":{
            "id": 1419,
            "name": "adSelected"
        },
        "1771":{
            "id": 1771,
            "name": "Close App"
        },
        "1979":{
            "id": 1979,
            "name": "Ad Selected"
        }
}
```

Help please,
Thanks

**Comment by Avien** [comment]
Ok after investigating a bit I think you have a problem with angular 1.4, perhaps ngRepeat implementation changed
Because when modifying the angular version in the plunker for key value binding (http://plnkr.co/edit/9DsLidTZR7RJDEq6PW0H?p=preview)
It doesn't work

**Comment by user378230** [comment]
The filter in the plunkr is incorrect, maybe it was a change between angular v1.2 > v1.4

`| filter: { value : { name :$select.search } }` fixes the first one - I assume it fixes the others as well but I haven't tested.

**Comment by user378230** [comment]
Closing as I don't think this is a problem with the library itself. 

It might be that you need to use the propsFilter like in the demo: https://github.com/angular-ui/ui-select/blob/7aabdc44f217fdbffcc4bafc7aceb9d93b5db486/docs/assets/demo.js#L11
