### ISSUE TITLE
Group-by does not work for nested objects

### ISSUE THREAD

**Issue by eugenekgn** [angular-ui/ui-select#1264]
Why cannot  the following `group-by="'country.countryName'"` be done?

**Comment by lukaw3d** [comment]
This is actually a decision between supporting
```js
[{
  "name": "A",
  "last.name": "B"
}, {
  "name": "C",
  "last.name": "B"
}]
group-by="'last.name'"
```

versus

```js
[{
  "name": "A",
  "country": {
    "name": "B"
  }
}, {
  "name": "C",
  "country": {
    "name": "B"
  }
}]
group-by="'country.name'"
```


I think the first one is currently supported, but you can use a function for either.

**Comment by eugenekgn** [comment]
Well I am currently solving this with a function. At the moment, I am referring to your second mock which has an object with a nesting -- i just think that it can be a lot more elegant if I would not have to solve it without a function, but I can see how just writing custom function on my end would be a better solution.

Thank you
Eugene

**Comment by wesleycho** [comment]
Closing as a resolved support issue.
