### ISSUE TITLE
Cannot read property 'length' of undefined 

### ISSUE THREAD

**Issue by srvee** [angular-ui/ui-select#1265]
Why I am facing this issue?

Can anyone please help me?

 class="btn  btn-primary" onclick="toggleModal()" 

JS:
function toggleModal() {
    var SelectedItems = angular.element(document.getElementById('spin1')).scope().gridOptions1.selectedItems;
  
    if (SelectedItems.length != 0) {    
       
        if (SelectedItems.length == 1) {         
         
            $("#dialog").dialog({
                resizable: true,
                width: 620,
                height: 300,
                modal: true,
                title: 'Duplicate Request',
                buttons: {
                    "Save": function () {
                        //$( this ).dialog( "close" );
                        var requestprefix = $("#inputreq1").val();
                        var requestyear = $("#inputreq2").val();
                        var requestnumber = $("#inputreq3").val();
                        var Comments = $("textarea#Comments").val();
                        console.log(comments);
                        angular.element(
                            document.getElementById('spin1')
                            ).scope().duplicateRequest(requestprefix, requestyear, requestnumber, Comments,
                            SelectedItems[0]);
                        $("textarea#Comments").val('');
                        $("#inputreq1").val("");
                        $("#inputreq2").val("");
                        $("#inputreq3").val("");
                        alert("comments" + Comments);
                        $(this).dialog("close");
                    }
                }
            });
        }
        else {
            alert("Please select only one item for Duplicate Request..");
        }
    }
    else {
        alert("Please select any one item for Duplicate Request..");
    }
}

**Comment by user378230** [comment]
Closing due to lack of repro and being 6 months old. 

If you require assistance please provide plunkr or similar demonstrating the problem.
