### ISSUE TITLE
Multiple/Tagging - If a user hits the spacebar, adds characters, and hits enter, a blank tag can created.

### ISSUE THREAD

**Issue by jdonisvitch** [angular-ui/ui-select#1267]
This is obviously quite the edge case. A user can however, when entering a good deal of tags, find themselves in this situation, where a blank tag is created, then due to it being blank, the user isn't allowed to delete it. This could be solved by a variety of fixes, not sure what would make the most sense. Limit the speed, limit spaces, or to allow the developer to give a regexp/pattern. 

Attached is an example, I've confirmed the issue with the newest version as well. 
<img width="173" alt="screen shot 2015-10-22 at 2 13 14 pm" src="https://cloud.githubusercontent.com/assets/2524677/10674075/1cfae446-78c7-11e5-9140-31a1d8b99ca1.png">

**Comment by jdonisvitch** [comment]
Can anyone give me any guidance or update to when this may be resolved?

**Comment by wesleycho** [comment]
Can you post a Plunker reproducing this?

**Comment by lkuklis** [comment]
Plunker with the bug.
http://plnkr.co/edit/z8KDrqwFUGbO2jWRA5Ni?p=preview

**Comment by jdonisvitch** [comment]
Oh dang, great work on the plunker @lkuklis. That made things much easier to reproduce on my end at least. What would it take to get a PR to fix this bad boy edge case? I'd be interested to help if needed. Thanks again! 👍 🙏
