### ISSUE TITLE
items not remove from dropdown list when binding deferred values with deferred data source

### ISSUE THREAD

**Issue by fujye** [angular-ui/ui-select#1268]
Demo:
http://plnkr.co/edit/cPgHc2iH0m1JAcLxFpps?p=preview

As in the demo, the data source and selected value are all deferred, that result to the "input" width is not correctly calculated and displayed in a seperated row with the selected items, is that a bug?

Plus, when the "input" got focused, all items including the selected ones will show up in the dropdown list. If you select any one of the selected, an error will be throw up: Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: $item in $select.selected, Duplicate key: object:00C

But if you do a search in the "input", the selected items will be removed from the dropdown list correctly. Why can't it filter those items out automatically on the first pop up?

**Comment by axos88** [comment]
Just spent 3 hours on this, and came to report the same bug

**Comment by axos88** [comment]
Just spent 3 hours on this, came to report the same bug. 
Also note that if you click on one of the items that are there in the dropdown list (but also selected), the a "duplicates in repeater" error is raised, and the control crashes.

**Comment by jefersondaniel** [comment]
+1 I have same problem

**Comment by wesleycho** [comment]
I believe both of these are reported in other issues, so closing in favor of those.
