### ISSUE TITLE
TypeError: Cannot read property '_uiSelectChoiceLocked' of undefined

### ISSUE THREAD

**Issue by lukaw3d** [angular-ui/ui-select#1269]
If tagging is enabled, it is possible to select a null item. After that I am getting errors

How to reproduce:
* Open [demo-tagging.html](http://rawgit.com/angular-ui/ui-select/master/examples/demo-tagging.html)
* Click on input inside `Object Tags`
* Press <kbd>Up</kbd> (this selects activeIndex `-1`)
* Press <kbd>Enter</kbd>
* A `null` item is added and can not be removed
* Trying to remove it causes `TypeError: Cannot read property '_uiSelectChoiceLocked' of undefined`

**Comment by ravishivt** [comment]
+1

**Comment by glenn-coessens** [comment]
+1

**Comment by asabirov** [comment]
+1

**Comment by roko-p** [comment]
+1

**Comment by mihot** [comment]
+1

**Comment by maramara** [comment]
+1

**Comment by Tibex** [comment]
+1

**Comment by ilongin** [comment]
+1

**Comment by tonilastre** [comment]
+1

**Comment by MacGyver27** [comment]
+1

**Comment by luckylucky** [comment]
+1

**Comment by johnmarkli** [comment]
+1

**Comment by logannc** [comment]
+1 @johnmarkli I have experienced this numerous times. I had thought it was something more insidious than just typing too fast, but I could never replicate it! XD

**Comment by andertun** [comment]
+1
