### ISSUE TITLE
Latest build (0.13.2) not working with latest angular (1.4.7) and bootstrap (3.3.7)

### ISSUE THREAD

**Issue by Dimitar-Karazhov** [angular-ui/ui-select#1270]
I have issues after upgrade to Angular 1.4.7, Bootstrap 3.3.5 and Select 0.13.2.
Select not working...

Error: [$parse:syntax] Syntax Error: Token 'track' is an unexpected token at column 11 of the expression [addresses track by $index] starting at [track by $index].

TypeError: Cannot read property 'source' of undefined

http://plnkr.co/edit/SQZXrRzOTZLG4YgXWOXr?p=info

**Comment by dashawk** [comment]
Just remove the `track by $index` and it will solve your problem.

**Comment by Dimitar-Karazhov** [comment]
The problem is not only the "track by $index", if remove other errors are generated.

**Comment by codetrash** [comment]
@Dimitar-Karazhov  yaap I've got the same issue too....still dont know wht's wrong

**Comment by tomasalmeida** [comment]
I am facing the same issue too.

**Comment by faisalhasnain** [comment]
Putting in parens has solved, I don't know whats the mystery here:
`city in (cities) track by $index`
ui-select 0.13.2 with angular 1.4.8

**Comment by user378230** [comment]
Resolved by #1477
