### ISSUE TITLE
Unable to get ui-select to work 

### ISSUE THREAD

**Issue by ekazaltzis** [angular-ui/ui-select#1271]
Hi,

I'm trying to get ui-select to work in my angular project but i'm unable to get the dropdown box to show the  data. I'm pretty sure that the data is returned and actually available because the drop down is showing with some empty lines. Occasionally when i select an empty line a actually can see the value in the input field. I'm unable to find out what is going on and struggling already the whole day with this problem. I don't get any errors in the console output. Help appreciated:

this is the div containing the ui-select tag. I have no <form> anywere

<div class='form-group'  careprovider-search-ctrl>
	<label class='col-sm-3 control-label'>{{label}}</label>
	items:{{items|json}}
	infoby:{{model}}
	<div class='col-sm-10'>
		<input class="form-control" type="text" list="listid" ng-model='filter' ng-change="refreshItems(filter)">
		    <datalist id='listid'>
		       <option ng-repeat="item in items" label="{{item.name}}" value="{{item.name}}" ng-selected="{{model=item._id}}">
		    </datalist>
		</input>
	</div>
</div>

controller that is used

angular.module('summary').directive('careproviderSearchCtrl', ['RestCall',
	function(RestCall) {
		return {	
			restrict: 'A',
			controller:function($scope) {
	      		$scope.findByName=function(filter, cb) {
	      			$scope.items=[];
	      			console.log("careproviderSearchCtrl findByName:" + filter);
					var rest = new RestCall('Careprovider');
					var params = new _$$.CRUDFindParams();
					params.filter = "likeName";
					params.context = {name:filter};
					
					if( filter && filter.length > 1) {
						// execute query
						rest.find(params, function(err,data){
							if(cb) {
								cb(err,data);
							}
							else {
								$scope.items=data;
							}
						});
					}
	      		}
			}
		}
	}
]);

**Comment by ekazaltzis** [comment]
```
angular.module('summary').directive('careproviderSearchCtrl', ['RestCall',
	function(RestCall) {
		return {	
			restrict: 'A',
			controller:function($scope) {
	      		$scope.findByName=function(filter, cb) {
	      			$scope.items=[];
	      			console.log("careproviderSearchCtrl findByName:" + filter);
					var rest = new RestCall('Careprovider');
					var params = new _$$.CRUDFindParams();
					params.filter = "likeName";
					params.context = {name:filter};
					
					if( filter && filter.length > 1) {
						// execute query
						rest.find(params, function(err,data){
							if(cb) {
								cb(err,data);
							}
							else {
								$scope.items=data;
							}
						});
					}
	      		}
			}
		}
	}
]);

```

**Comment by ekazaltzis** [comment]
```
<div class='form-group'>
	<label class='col-sm-3 control-label'>{{label}}</label>
	items:{{items|json}}
	infoby:{{model}}
	<div class='col-sm-10'>
		<input class="form-control" type="text" list="listid" ng-model='filter' ng-change="refreshItems(filter)">
		    <datalist id='listid'>
		       <option ng-repeat="item in items" label="{{item.name}}" value="{{item.name}}" ng-selected="{{model=item._id}}">
		    </datalist>
		</input>
	</div>
</div>

```

**Comment by ekazaltzis** [comment]
´´´```
<div class='form-group caseprovider-search-ctrl'>
    <label class='col-sm-3 control-label'>{{label}}</label>
    items:{{items|json}}
    infoby:{{model}}
    <div class='col-sm-10'>
        <input class="form-control" type="text" list="listid" ng-model='filter' ng-change="refreshItems(filter)">
            <datalist id='listid'>
               <option ng-repeat="item in items" label="{{item.name}}" value="{{item.name}}" ng-selected="{{model=item._id}}">
            </datalist>
        </input>
    </div>
</div>
´´´```

**Comment by ekazaltzis** [comment]
```
<div class='form-group' caseprovider-search-ctrl>
	<label class='col-sm-3 control-label'>{{label}}</label>
	<div class='col-sm-10'>
		<ui-select ng-model="model"
             theme="bootstrap"
             ng-disabled="disabled"
             reset-search-input="false"
             style="width: 300px;">
    	<ui-select-match placeholder="{{placeholder}}">{{$select.selected.name}}</ui-select-match>
    	<ui-select-choices repeat="item in items"
             refresh="refreshItems($select.search)"
             refresh-delay="500">
      		<div ng-bind-html="item.name | highlight: $select.search"></div>
    	</ui-select-choices>
		</ui-select>	
	</div>
</div>
```

**Comment by dashawk** [comment]
I have the same problem on my side.

This line is causing the problem.
```html
<div ng-bind-html="item.name | highlight: $select.search"></div>
```
You can look at your developer tool where angular shows an error about an unsafe html in a safe context.

I solved it by just removing the div with the ng-bind-html and replaced it with just `{{ item.name }}`
I also removed the `highlight: $select.search` because it will display the html tags that formats the selected search result. It's because its not using the $sce to actually render it as a safe html.

The div just actually highlight the text and adds a span that bolds the inputed text. It's no use for me so I just go with the plain old ng binding `{{ }}`

**Comment by ekazaltzis** [comment]
Tried your solution but without success.

So i just replaced {{item.name}} with TEST. When i open the listbox i can now see 1 line with value TEST. However I was expecting 2 lines with value TEST as i have items is a array with 2 entries.

It gets even more confusing:
Every time i select an item from the list and reopen the listbox a new line with value TEST is added. The newline however is not selectable.

Any other ideas?

**Comment by user378230** [comment]
ng-model binding is incorrect. Please see top question in FAQ https://github.com/angular-ui/ui-select/wiki/FAQs
