### ISSUE TITLE
ui-select is not compatible with angular-loader.js

### ISSUE THREAD

**Issue by eperret** [angular-ui/ui-select#1272]
I use the [angular-seed](https://github.com/angular/angular-seed/blob/master/app/index-async.html) where I load some more dependencies with `$script` as follow:

    $script([
        'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js',
        'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-route.min.js',
        'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-resource.min.js',
        'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-animate.min.js',
        'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-sanitize.min.js',
        'https://cdnjs.cloudflare.com/ajax/libs/angular-ui-select/0.13.2/select.js',
        'js/app.js'
    ], function() {
    ...

I think `ui-select` tries to call `angular.element.prototype.querySelectorAll` before angular has been loaded. Does it sounds right?

Here is the console error from Chrome (46)

    Uncaught TypeError: Cannot read property 'prototype' of undefined
        (anonymous function) @ select.js:70
        (anonymous function) @ select.js:1913

**Comment by wesleycho** [comment]
Can you post a reproduction in Plunker?

**Comment by user378230** [comment]
Closing as a usage issue. The library works fine when `angular.js` is included via `<script>` any other loading methods aren't really up to us to support. PRs welcome as always.

**Comment by senterright** [comment]
Is there any more insight besides including angular.js in the script tag? Like I get that you don't support more than that, but is there anything i can do to get this to play nice with webpack? I get the exact same error after following a variety of different tutorials. I also know this is well over a year old, but i can't find anything to solve
![screen shot 2017-11-10 at 10 25 10 am](https://user-images.githubusercontent.com/1960929/32672858-8f726d44-c601-11e7-8e29-c1349c7f978c.png)
