### ISSUE TITLE
Is there a way to limit ui-select component search input to aA - zZ characters?

### ISSUE THREAD

**Issue by jessepinuelas** [angular-ui/ui-select#1273]
Currently I have a method checking if the $select.search value is a number utilizing refresh and refresh delay. Any way to add a pattern to the the ui-select?

**Comment by user378230** [comment]
Dupe/Related #1232

**Comment by wesleycho** [comment]
One should use a custom $parser with ngModel by creating a custom directive for this.

Closing as support.
