### ISSUE TITLE
Casper Testing UI-Select2 

### ISSUE THREAD

**Issue by cwoodworth** [angular-ui/ui-select#1274]
Has anyone had success with testing their implementation of UI select with Casper?  I am running into an issue where keydown events do not trigger choices to be identified.  We ran into a similar issue with our directive level tests as well with Jasmine where keydowns would not trigger calls to our api.

casper.click('.select2-input');
      casper.sendKeys('.select2-input', 'some input');
      casper.waitForResource('/backendURL/search', function(){
      });

Any help would be greatly appreciated.

**Comment by cwoodworth** [comment]
If anyone else runs into the same issue, this is what worked for us!

casper.click('.select2-input');
      casper.sendKeys('.select2-input', 'foo', {keepFocus: true});
      casper.wait(1000, function() {
        casper.click('.ui-select-choices-row:first-of-type');
        casper.click('button#submit');
        casper.waitUntilVisible('a-list', function(){
           test.assertSelectorHasText('#bar', 'foo');
        });
      });

**Comment by dtle82** [comment]
Can you give me the corresponding HTML frontend that worked with your casper code?
