### ISSUE TITLE
event for toggling ui-select-choices 

### ISSUE THREAD

**Issue by donghwicha** [angular-ui/ui-select#1280]
hello all. 

is there any way to get a event or trigger for showing ui-select-choices's?

what I want is to do is that every time a user clicks and dropdown shows, 
the list is updated with synchronized with server
(if new one is added on server side, then it is added to ui,
and if one is deleted on server side, then it is removed from user and user's choice ). 

I know there is similar one but, I just want it to be done at user's click and just before dropdown shows.

**Comment by wesleycho** [comment]
One could probably accomplish this using the refresh expression or something similar.

There is not enough information to determine whether it is a library issue, and it seems strongly like a support issue, so closing as per policy in CONTRIBUTING.md
