### ISSUE TITLE
Controller 'uiSelect', required by directive 'uiSelectSort', can't be found!

### ISSUE THREAD

**Issue by koolshams** [angular-ui/ui-select#1287]
Nice work guys. It saved lot of time. 

I got an annoying error in console when i used it with angular-strap. I used all latest codes. 

http://plnkr.co/edit/kWzwR3gxD19XQCoifapp?p=preview

Steps to reproduce the error.
Open above link. First click on 'Open window with none selected' link, click on cancel to close the modal. After that click on 'Open window with some selected users', you can see this error in console.

I have used code from examples. Please someone help me with this.

Thanks,
Shamseer

**Comment by koolshams** [comment]
Looks like there is a watchCollection on ng-model in ui-select which is not removed when select is destroyed. as i am using same scope for modal screens, so scope is not destroyed when modal window is closed. Looks like i need to use new scope for each modal. See this plunker which create new scope for each modal.

http://plnkr.co/edit/gkueBKeagIs6fYNlXHnc?p=preview

I am closing this issue, It may help some one else who faces same issue.

**Comment by 3v3r3tt** [comment]
Another solution I found was to manually remove the watchers from the scope when cleaning up:

`delete scope.$$watchers`

**Comment by pior** [comment]
We also encounter this when changing state in ui-router.

**Comment by AnatoliyLitinskiy** [comment]
### Same error with `ui-view`

Hi, but what to do if I'm not using `$modal` service?
here this error appears when child `state` is been opened

(just click on `go to sub` link and see console output)
https://embed.plnkr.co/yjCvvyIpGgwCUljy214X/

**Comment by Clar64** [comment]
I've also got the same issue, when using a multiple select using XEditable. Any suggestions on how to fix this?
