### ISSUE TITLE
Adding table inside ui-select-choices

### ISSUE THREAD

**Issue by syedsuhail** [angular-ui/ui-select#1294]
I have been trying to add a table inside the ui-select. But since repeat is used on the ui-select-choices directive it repeats the table each time. I am trying to repeat only the rows. Can anyone please help?

Take a look at this [plunker](http://plnkr.co/edit/FDt7WwcoEsCUDjiz6Cpi?p=preview)

**Comment by user378230** [comment]
You will most likely need to customise  [choices.tpl.html](https://github.com/angular-ui/ui-select/blob/master/src/bootstrap/choices.tpl.html) with `<table>` etc.
