### ISSUE TITLE
Dropdown flickering cause opacity set to 0 when filtering

### ISSUE THREAD

**Issue by onemenny** [angular-ui/ui-select#1298]
Please see: http://plnkr.co/edit/erN0pTgEVxBrfJF4p9U7?p=preview
Use the select2 theme and type 'a' and then 'd' you will see that on each letter you type the drop filckers.

It appears that this is cause by line 1091 
```javascript
// Hide the dropdown so there is no flicker until $timeout is done executing.
            dropdown[0].style.opacity = 0;

            // Delay positioning the dropdown until all choices have been added so its height is correct.
            $timeout(function(){
.
.
.
 // Display the dropdown once it has been positioned.
              dropdown[0].style.opacity = 1;
            });
```

opacity should not change.

**Comment by chnldw** [comment]
Same here with angular 1.4.7 and ui-select 0.13.2

**Comment by cfey** [comment]
this fixed it for me as well

**Comment by shyamal890** [comment]
Linking similar issue https://github.com/angular-ui/ui-select/issues/1314

**Comment by aaronroberson** [comment]
@shyamal890 Can you direct me to a PR that I can review and accept?

**Comment by onemenny** [comment]
@aaronroberson look at my pull requests https://github.com/angular-ui/ui-select/pull/1371 I already enhanced it with more bug fixes

**Comment by aaronroberson** [comment]
Any chance you can remove the updates to the dist files and optionally
squash the commits?

**Comment by onemenny** [comment]
Sure, I'll do it later on today.

**Comment by onemenny** [comment]
@aaronroberson ok, I hope I got it right. everything is squashed and dist is reset. 
There are many changes to this pull request and some new test. here are the highlights:

		a. Do not set opacity when typing (causes flickering)
		b. Appen-to-body=true cause loos of focus on tag add/delete, backspace…
		c. Using tags (dashboard tags): type the letter 'a' which should appear in one of the ddl items, then delete the letter (empty search), causes the <'a' new item> to remain in the ddl items
		d. when using closeOnSelect with tagging - hitting the enter key sets the new tag but keeps the search input value
		e. Find dupes: Tags duplication helper method was added (tags may be objects and need comparer function)
		f. Fix ensureHighlight to work only when ctrl.open

**Comment by yogeshgadge** [comment]
I am going with the following hack for now.
```

            // Hide the dropdown so there is no flicker until $timeout is done executing.
            if (dropdown[0].clientHeight == 0) {
              dropdown[0].style.opacity = 0;
            }
```

**Comment by aaronroberson** [comment]
Accept Your Gift! ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcsaB-2B1-2FyHdArrPm5zn4zScy1zY7XxP6Rtz7EOage7tISzW8bmZorL8eUVZpU3FO0xQOGjARAXsLiGT46I-2F03Ck7myP8BPUZBoXGR-2BV6uau9R5Jws1jddTzQtSRzHquRHUkYHP47iARJ7siqMYzE-2BWb2LXIvny-2FhRbzfccOFsxDMm5Ml9RIXg0rymw2xbtXZTh-2FZ6jPeHrZOD6Z7Ks54u5Z4VP4FC-2Foi5Yud7zX7TA2b-2F9r3lpnha-2BHio-2FUhIR12ErKLovUtMUrYJsX9xDPwfWkJafdDnLx5a8J4xlkM1b6KDMNWcAgd8aR8Ux7nswRPmhxQ-3D-3D_s5UH8bhnBaopYjthcNSRcZw7LRk5n3QTpqBbPD3NnVMZJJ25t9MFh6dZEv9V3SKydVM-2BApdE2Bi01oCG92RIQuceuIXKLhz-2B0yZyWsexx2YSL-2F-2B6nQWMr-2FgW8VMwHEpOg6-2FOVVaETnXdkkFiO-2BmXfbjeEzEFYVm-2B6-2F64j-2F-2B-2Bp5O-2FiXXIDA4dbEaZmJCWREJG5TYLdE-2FuXY4gB46L8E-2FBJ7O7uRhTvI3M7ZvztRMur2nNPkXaYNNaPQWomSEIoDSIPeKgBPJQYynbmuLNTk7yD20JgA2wfmZynzAydocehqwn9QbZZasNrXmuzt2qVSATRkSToCcasAZooLUhz3OQP7LY3apOUiHAlc60W6sTKBMMehd28ntIgdA1fv5X4qVP7qSkxeF60Ns-2BX3AARWYosQ-3D-3D )

Aaron sent you a $55 gift for Handy

With Handy, a spotless home is only a few clicks away. Just pick a service and choose a time—an experienced, background checked professional will take care of the rest. Click below to claim your $55 credit or use code AARON9231 at checkout.

Accept Your Gift! ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcsaB-2B1-2FyHdArrPm5zn4zScy1zY7XxP6Rtz7EOage7tISzW8bmZorL8eUVZpU3FO0xQOGjARAXsLiGT46I-2F03Ck7myP8BPUZBoXGR-2BV6uau9R5Jws1jddTzQtSRzHquRHUkYHP47iARJ7siqMYzE-2BWb2LXIvny-2FhRbzfccOFsxDMm5Ml9RIXg0rymw2xbtXZTh-2FZ6jPeHrZOD6Z7Ks54u5Z4VP4FC-2Foi5Yud7zX7TA2b-2F9r3lpnha-2BHio-2FUhIR12ErKLovUtMUrYJsX9xDPwfWkJafdDnLx5a8J4xlkM1b6KDMNWcAgd8aR8Ux7nswRPmhxQ-3D-3D_s5UH8bhnBaopYjthcNSRcZw7LRk5n3QTpqBbPD3NnVMZJJ25t9MFh6dZEv9V3SKydVM-2BApdE2Bi01oCG92RIQuceuIXKLhz-2B0yZyWsexx2YSL-2F-2B6nQWMr-2FgW8VMwHEpOg6-2FOVVaETnXdkkFiO-2BmXfbjeEzEFYVm-2B6-2F64j-2F-2B-2Bp5O-2FiXXIDA4dbEaZmJCWREJG5TYLdE-2FuXY4gB46L8E-2FBJ7O7uRhTvI3M7ZvztRMur2nNPkXaYNNaPQWomSEIoDSI78-2FujY3oAs0F2r1v9Z4s-2BaYpNaQW7aIWS2aWPqY3y9nB9yW2VOXAAD7c8W2O2IkmcGud241DuPzKJoI8mZsj9yuLOUQDc3l1WxVzglWm3Z-2B7xuILZ46z4gIxQfnLb1adG9gt1zvoVk5nGuBTBWS8RA-3D-3D )
Use your $55 gift on any of Handy's services
(use code AARON9231 at checkout):

View all of Handy's Services ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcsbv8X8Oszigzr5NNtGKza3MWDFialnox81TfwNCxNUNxhHKA-2BdMfFIp0irzQtrT5-2FC7EBZRmlTEE9RzPGGsa0-2BNerKUsc6-2FzrAdWKAQw-2BXzyldlAEwTjpfQF339Id5VSeQ2WO-2FQ9tSpKWE-2F-2BDilm3RY-3D_s5UH8bhnBaopYjthcNSRcZw7LRk5n3QTpqBbPD3NnVMZJJ25t9MFh6dZEv9V3SKydVM-2BApdE2Bi01oCG92RIQuceuIXKLhz-2B0yZyWsexx2YSL-2F-2B6nQWMr-2FgW8VMwHEpOg6-2FOVVaETnXdkkFiO-2BmXfbjeEzEFYVm-2B6-2F64j-2F-2B-2Bp5O-2FiXXIDA4dbEaZmJCWREJG5TYLdE-2FuXY4gB46L8E-2FBJ7O7uRhTvI3M7ZvztRMur2nNPkXaYNNaPQWomSEIoDSIjUL3ghSvDAnMtMi0IrM2HJPm2-2B5MoEmnzIOoOAtFlfAAUFlcNV8koUi3-2FWv-2BYCaYsjbH3rSoUW3Jok0LMIPKb8c1akm0xpBvWHZJt2zwk2VnLKdVPww-2F5X-2B9hfUPC5U7ih2dsMFQ6DxiiPCtrdj0HQ-3D-3D )

Handy Twitter ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKaX-2FU2oXhnvLnp3gZfkeb2AF7vRpkoN40hgM4hNyDSth_s5UH8bhnBaopYjthcNSRcZw7LRk5n3QTpqBbPD3NnVMZJJ25t9MFh6dZEv9V3SKydVM-2BApdE2Bi01oCG92RIQuceuIXKLhz-2B0yZyWsexx2YSL-2F-2B6nQWMr-2FgW8VMwHEpOg6-2FOVVaETnXdkkFiO-2BmXfbjeEzEFYVm-2B6-2F64j-2F-2B-2Bp5O-2FiXXIDA4dbEaZmJCWREJG5TYLdE-2FuXY4gB46L8E-2FBJ7O7uRhTvI3M7ZvztRMur2nNPkXaYNNaPQWomSEIoDSIII834kcfyUAq-2Bz7x1qB7iHGaUfnNTxouN9gw0rrwWHV19zuIfk2oU74emurSZlHdfLsSoTMtAA4NLoBOQnkWI5FD0nKipZxwaZHjvzAIR-2BzXBdLS0FUws-2B9c8LGpRWb0QF5bzKXQ9H4xVnL8jgyOmg-3D-3D )
Handy Facebook ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKfa9DXUWP0mdASikrPI0DmDoKViAyBoQIsV4x7PT02KC_s5UH8bhnBaopYjthcNSRcZw7LRk5n3QTpqBbPD3NnVMZJJ25t9MFh6dZEv9V3SKydVM-2BApdE2Bi01oCG92RIQuceuIXKLhz-2B0yZyWsexx2YSL-2F-2B6nQWMr-2FgW8VMwHEpOg6-2FOVVaETnXdkkFiO-2BmXfbjeEzEFYVm-2B6-2F64j-2F-2B-2Bp5O-2FiXXIDA4dbEaZmJCWREJG5TYLdE-2FuXY4gB46L8E-2FBJ7O7uRhTvI3M7ZvztRMur2nNPkXaYNNaPQWomSEIoDSIv5JYYmY7klUnUnJE0oxVruIjM8R-2Fq-2F6uxcdRgH-2Fj2FO5zJJSPibDluSwfs9zLz80iqaMUaepoH-2F-2Fz1vkbgMB80RsGQZx04aWytN7PphhWOJ5ULQkFhWogn1AD7UUbBB-2BtmeLNs5b6IaLpYPBkBDUVA-3D-3D )
Handy Instagram ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKfeBoaKL8Ev6spOpwM7gM6S-2F8a-2BuAMyY5qXEGPy9TRAc_s5UH8bhnBaopYjthcNSRcZw7LRk5n3QTpqBbPD3NnVMZJJ25t9MFh6dZEv9V3SKydVM-2BApdE2Bi01oCG92RIQuceuIXKLhz-2B0yZyWsexx2YSL-2F-2B6nQWMr-2FgW8VMwHEpOg6-2FOVVaETnXdkkFiO-2BmXfbjeEzEFYVm-2B6-2F64j-2F-2B-2Bp5O-2FiXXIDA4dbEaZmJCWREJG5TYLdE-2FuXY4gB46L8E-2FBJ7O7uRhTvI3M7ZvztRMur2nNPkXaYNNaPQWomSEIoDSIEVqKuhPwxkc69YBeqBTlgVRcJquW9SyWfdyYkgeBQ4-2Be54Oonjxab-2B311amlfKtLRe-2FINf710lDfs6sCnRGG0v-2BTDiuVYUV-2BMpve98vBQ33M-2FC7f0jx5dA-2BnYHGXnh30osAFIYPTkXJN2X25441qrA-3D-3D )

Our Services ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcsbv8X8Oszigzr5NNtGKza3MQJ44OHPcJikSh-2BVUrFwzQO4xaArAScjwh7B1X-2Bws5DZzdjanMyViAICvTlcFLTkw-3D_s5UH8bhnBaopYjthcNSRcZw7LRk5n3QTpqBbPD3NnVMZJJ25t9MFh6dZEv9V3SKydVM-2BApdE2Bi01oCG92RIQuceuIXKLhz-2B0yZyWsexx2YSL-2F-2B6nQWMr-2FgW8VMwHEpOg6-2FOVVaETnXdkkFiO-2BmXfbjeEzEFYVm-2B6-2F64j-2F-2B-2Bp5O-2FiXXIDA4dbEaZmJCWREJG5TYLdE-2FuXY4gB46L8E-2FBJ7O7uRhTvI3M7ZvztRMur2nNPkXaYNNaPQWomSEIoDSIAFbnSSz7vYSywKfAdKhOe841-2BsbdSQd7FIQqSOmuWFHRcB-2B94XDoOxnkOUtAUg6CzADGne2W320WBQuvS9-2Bcel2oQH1hY4C31MOorSOZ65G-2BhRFq4qmuKmCVb188BUanozuQ0Xu3j2Zn5jq1zKR7pw-3D-3D )
helpcenter ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcse4Lp6fgbkd2iUk5hd2lBMUpBCYqNi1V7ydYheQ49Mw4W-2FJwIs-2FOCxm2wmUesDoFsLAcQPHKGpgX9GOqDdMK5RE-3D_s5UH8bhnBaopYjthcNSRcZw7LRk5n3QTpqBbPD3NnVMZJJ25t9MFh6dZEv9V3SKydVM-2BApdE2Bi01oCG92RIQuceuIXKLhz-2B0yZyWsexx2YSL-2F-2B6nQWMr-2FgW8VMwHEpOg6-2FOVVaETnXdkkFiO-2BmXfbjeEzEFYVm-2B6-2F64j-2F-2B-2Bp5O-2FiXXIDA4dbEaZmJCWREJG5TYLdE-2FuXY4gB46L8E-2FBJ7O7uRhTvI3M7ZvztRMur2nNPkXaYNNaPQWomSEIoDSIj6UemE9q2OeFFFdV9yH7EJv6jvRNf4OuHmt4RPT9f2cl-2Fgg7GOxtcQVlRxoxtMo-2Fhb0xNcUymiGlohYa-2FC3OHfeaGhbpouYsiPNi5z4JDr2IdI7l89z7XuJ6hnNNspWgejdcB0mkvCQhcSk9ud5D6g-3D-3D )
Download Handy iOS app ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKe-2B4bz-2FAZDzUh1KL03FtyJ2uqoInuMQFjnKVNRO5FQSo-2FpakL1Y4hX85UGZ2zp5KD-2BI8hjWgTPijyltMY2jEortmwgrC-2F2r8jq6s0-2Bya9iXK_s5UH8bhnBaopYjthcNSRcZw7LRk5n3QTpqBbPD3NnVMZJJ25t9MFh6dZEv9V3SKydVM-2BApdE2Bi01oCG92RIQuceuIXKLhz-2B0yZyWsexx2YSL-2F-2B6nQWMr-2FgW8VMwHEpOg6-2FOVVaETnXdkkFiO-2BmXfbjeEzEFYVm-2B6-2F64j-2F-2B-2Bp5O-2FiXXIDA4dbEaZmJCWREJG5TYLdE-2FuXY4gB46L8E-2FBJ7O7uRhTvI3M7ZvztRMur2nNPkXaYNNaPQWomSEIoDSIjdxifHZII69pHIFuSCZG2V5ASB1hf-2FuXH2reGbR-2BSxA92PyDq2BnX1-2FzaPIAMOToQNwiOa-2B-2BVXRwnGDF6mboIehQz-2FEOxUZI3QsliEjQXnenekRhXHfwOMlnBNkbkyhSVncIaYdWl2Ug05g8686Klg-3D-3D )
Download Handy Android app ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKeJcuYvtamgIYRZeccCPxkcFs2tKreRwShvBbhgLgpeznxEEVKVOltp8oC6Ig4DUHnf-2ByPOZsMz-2F8ivVr-2FUyO-2Fo-3D_s5UH8bhnBaopYjthcNSRcZw7LRk5n3QTpqBbPD3NnVMZJJ25t9MFh6dZEv9V3SKydVM-2BApdE2Bi01oCG92RIQuceuIXKLhz-2B0yZyWsexx2YSL-2F-2B6nQWMr-2FgW8VMwHEpOg6-2FOVVaETnXdkkFiO-2BmXfbjeEzEFYVm-2B6-2F64j-2F-2B-2Bp5O-2FiXXIDA4dbEaZmJCWREJG5TYLdE-2FuXY4gB46L8E-2FBJ7O7uRhTvI3M7ZvztRMur2nNPkXaYNNaPQWomSEIoDSIz7JuZepVr1sv1huSLfv3pEenCF118MmgCpdsNuajZLV37PQXQWcZwy4mMXd9-2BFRob3sGJazP7OEnnTP0kSvVvVG0Zm-2FUMFLaAVYFIf8iHOH6hryCYoINu5rZsva9gnVnGIm9rH0OBgI77DLKjCVuAQ-3D-3D )

Refer a Friend, Earn $50! ( xhttps://sgemail.handy.com/wf/click?upn=YsKWC7yTmiePOc2Pn-2Fa7R9V1Z-2FmspGRWKf5-2BNbJAcZuLZGz8MM1bTALYgBeeFogRy7AGwMT0R9RgzqFAR0taDV2mxNZC183vLo10oJ4jrl62VC5ZEK8f9-2FimJ4ErLRJFtBaPdxxGW4y5Kg4isuxRoVO-2BwMhi5auKgqzPwOAwtaY-3D_s5UH8bhnBaopYjthcNSRcZw7LRk5n3QTpqBbPD3NnVMZJJ25t9MFh6dZEv9V3SKydVM-2BApdE2Bi01oCG92RIQuceuIXKLhz-2B0yZyWsexx2YSL-2F-2B6nQWMr-2FgW8VMwHEpOg6-2FOVVaETnXdkkFiO-2BmXfbjeEzEFYVm-2B6-2F64j-2F-2B-2Bp5O-2FiXXIDA4dbEaZmJCWREJG5TYLdE-2FuXY4gB46L8E-2FBJ7O7uRhTvI3M7ZvztRMur2nNPkXaYNNaPQWomSEIoDSIUxUw36fwOEzpV6hJv9slRo3hTr-2B2ZrMUKhDmTrLLnIYr41omt5-2FXsabZlpWpSPnGylrLrRyjzXibzBeh5HxadoKXrjEdVh5dhjmwDASU-2FGOjCikj6T9VGnljpm6U7Yfch-2FrQX6WiMP1edA70bDlXQw-3D-3D )|Privacy Policy ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKXE0Lx8wVhm5qiHGXjJOgd7oLwhjwvzCLbE0HeWhRyGB_s5UH8bhnBaopYjthcNSRcZw7LRk5n3QTpqBbPD3NnVMZJJ25t9MFh6dZEv9V3SKydVM-2BApdE2Bi01oCG92RIQuceuIXKLhz-2B0yZyWsexx2YSL-2F-2B6nQWMr-2FgW8VMwHEpOg6-2FOVVaETnXdkkFiO-2BmXfbjeEzEFYVm-2B6-2F64j-2F-2B-2Bp5O-2FiXXIDA4dbEaZmJCWREJG5TYLdE-2FuXY4gB46L8E-2FBJ7O7uRhTvI3M7ZvztRMur2nNPkXaYNNaPQWomSEIoDSI-2BP1TNUPL6zWsvqIQkKbJkR8U8htxplX58pnZIumHNTfMs18JzEkkwMDhNrnaGc4CEM93J7WpbmwQXdfPyeSo3zE3GoDic5G-2BL3aTESYgRB0hlAE4LaxXuw1XidOjqIoIajiU5CuDwK4RHSiclTlc7A-3D-3D )|Unsubscribe ( https://sgemail.handy.com/wf/click?upn=wz-2FQ7Wmj26-2Boily69xWn-2FdB3gxvuT-2Fcn2o1CsCXSMqzTVlu8lrEjD2X6MEa5PfWyf8x1RyVy-2FwnlILu36OvRd-2BeH6IflPIrnekOYPyZCdVM-3D_s5UH8bhnBaopYjthcNSRcZw7LRk5n3QTpqBbPD3NnVMZJJ25t9MFh6dZEv9V3SKydVM-2BApdE2Bi01oCG92RIQuceuIXKLhz-2B0yZyWsexx2YSL-2F-2B6nQWMr-2FgW8VMwHEpOg6-2FOVVaETnXdkkFiO-2BmXfbjeEzEFYVm-2B6-2F64j-2F-2B-2Bp5O-2FiXXIDA4dbEaZmJCWREJG5TYLdE-2FuXY4gB46L8E-2FBJ7O7uRhTvI3M7ZvztRMur2nNPkXaYNNaPQWomSEIoDSIfgfcuYI6b5QvAO1NzwhsDQHnCidRRtCxVn5C8gBglfgZkwiS1IRPZQ5VykFfswMVPFDK2PWWk3h9yJTl9cG-2F1aEyC3L-2Fs54xe1qWn7ce-2FZt2X-2BfAT7FofG9NJ-2BW6P-2BSQSnGcXgoJP8ZfBimRJ98Lxw-3D-3D )

*By clicking this email, this allows us to send you the occasional marketing email, with goodies like special offers and limited-time services.
**Valid for new customers only. New customers receive $55 off their first booking. Must click through the 'Claim' url or use provided referral code, AARON9231, at checkout. Not combinable with other offers. Handy reserves the right to alter or end this promotion at any time, including but not limited to any noted discount amounts.

Handy, through the Handy platform, offers information & a method to obtain the above services, but does not itself provide these services. The provision of these services is up to the independent professionals, scheduled through the Handy Platform.
handy.com ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcseJZkXaGdRcWLa8SGTMwMTwgoOqsD8c4LW4PJHfa5XvNhV91IOu7BoVwnt-2FvzqlT3hviWxTDZJDtK9iqkY6Hnhk-3D_s5UH8bhnBaopYjthcNSRcZw7LRk5n3QTpqBbPD3NnVMZJJ25t9MFh6dZEv9V3SKydVM-2BApdE2Bi01oCG92RIQuceuIXKLhz-2B0yZyWsexx2YSL-2F-2B6nQWMr-2FgW8VMwHEpOg6-2FOVVaETnXdkkFiO-2BmXfbjeEzEFYVm-2B6-2F64j-2F-2B-2Bp5O-2FiXXIDA4dbEaZmJCWREJG5TYLdE-2FuXY4gB46L8E-2FBJ7O7uRhTvI3M7ZvztRMur2nNPkXaYNNaPQWomSEIoDSIbn6I7YJ86FGXVBJviwDizUOaG9YToZuj9gQJCy-2FX3TQl5moKJYYCK-2BQy5zAyR7rcftilTznq5BhI-2Fj8bkPi0ZDGMXiF7euvPScDPQxCbGSFVINBTWHu7YsYTQopXojlXITLABW2omoAQevL5oL3SsA-3D-3D )
