### ISSUE TITLE
Mapping a value to the return rather than the entire object. 

### ISSUE THREAD

**Issue by zackarychapple** [angular-ui/ui-select#130]
I would like to just persist the item.codeId to the ng-model for myObject.stateCode, hopefully this binding would also select the correct option in the drop down when the value already exists.   How do I set it up to do that?

Below is my current code. 

``` html
<ui-select ng-model="myObject.stateCode" id="stateCode">
    <ui-select-match placeholder="Select a state...">{{$select.selected.codeDescription}}</ui-select-match>
    <ui-select-choices repeat="item in constants.states | filter: $select.search" value="{{$select.selected.codeId}}">
        <div ng-bind-html="item.codeDescription | highlight: $select.search"></div>
        <small ng-bind-html="item.codeId | highlight: $select.search"></small>
    </ui-select-choices>
</ui-select>
```

**Comment by nicolas15000** [comment]
Hello ! Me too i've got the same problem, i have all of the latest versions ...

The ui select doesnt display the loaded value .

This is my UI Select code :+1: 
[<div class="input-group">
					<span class="input-group-addon">Station</span>
				<ui-select  theme="selectize"  ng-model="produit.idstation">
				<ui-select-match placeholder="Selectionnez ou Recherchez...">{{$select.selected.nom}}</ui-select-match>

					<ui-select-choices repeat="station.nom as station in stations  | filter: {nom: $select.search}">
						 <div ng-bind-html="station.nom | highlight: $select.search"></div>
					  <small ng-bind-html="station.telephone | highlight: $select.search"></small>
					</ui-select-choices>
				</ui-select>
				</div><br> ](url)
