### ISSUE TITLE
Disabling ui-select applies .ng-hide to input box

### ISSUE THREAD

**Issue by danpantry** [angular-ui/ui-select#1302]
Is there any reason for this? I would have expected the input box  to remain visible but just be grayed out.

**Comment by danpantry** [comment]
In order to hack-fix remedy this, I've removed the `ng-hide="$select.disabled"` directive from the `bootstrap/select-multiple.tpl.html` template on my local copy. Is the only 'real' work-around to supply a custom template via themes?

**Comment by mgleed** [comment]
+1 any css workaround?

**Comment by wesleycho** [comment]
Having the input be displayed when disabled actually results in text display bugs involving CSS - is there a compelling reason why it must be shown?

**Comment by danpantry** [comment]
Because otherwise the input box disappears completely and thus looks very strange - especially to the user. We've had questions about this from our end users, which is why I removed it

I'll try and throw together a plunkr tomorrow when I am back in the office.

**Comment by lukasolson** [comment]
You can see this on the [example](http://angular-ui.github.io/ui-select/demo-multiple-selection.html) page by clicking on "Disable ui-select" and looking at the input under "Deselect callback with single property binding".

**Comment by lukasolson** [comment]
(Specifically, this is very apparent when you're using `multiple` and `disabled` simultaneously.)

**Comment by lukasolson** [comment]
@wesleycho Any updates on this? I think we can at least drop the needs info/plunkr labels at this point. I'm happy to help in any way I can.

**Comment by user378230** [comment]
Closing as resolved by #1717
