### ISSUE TITLE
Error thrown when the blur event happens during the time of opening the dropdown menu

### ISSUE THREAD

**Issue by hitigon** [angular-ui/ui-select#1303]
if the data set is relatively large (my case is 1000 ~ 2000), the dropdown menu takes time to be shown, during the time, if click other elements (i.e. trigger the blur event), there is an error thrown from line 523 in uiSelectController.js due to empty set of choices, but I think the error should be silenced in case of "unfinished requests "

```
throw uiSelectMinErr('choices', "Expected multiple .ui-select-choices-row but got '{0}'.", choices.length);
```

Env:
```
angular #1.4.7
bootstrap #3.3.5
ui-select #0.13.2
```

**Comment by hitigon** [comment]
#224

**Comment by wesleycho** [comment]
Closing as a duplicate.
