### ISSUE TITLE
[Selectize] Input box is not hidden when selected data is 0 (as number)

### ISSUE THREAD

**Issue by phabdev** [angular-ui/ui-select#1304]
When selectize theme is used, if the selected data is `0` (as number) input box is not hidden and the bar is not well shown.
I noticed that the criterion to hide the input box is
```javascript
ng-hide="!$select.searchEnabled || ($select.selected && !$select.open)"
```
It should be: "hide it if search is disabled or hide it if something is selected and the box is closed", but it doesn't work if `$select.selected` is `0` (as `0` is false in javascript).
So i think that is should be something like
```javascript
ng-hide="!$select.searchEnabled || (($select.selected || $select.selected===0) && !$select.open)"
```
I tried only with selectize theme. Didn't check if it is handled with other themes.

**Comment by wesleycho** [comment]
Can you open a PR with this change?

**Comment by Jefiozie** [comment]
Added this fix.
