### ISSUE TITLE
Readyonly feature

### ISSUE THREAD

**Issue by atentis** [angular-ui/ui-select#1305]
It would be really nice if we could use the readonly attribute with the multiselect. ng-disabled grays out the entire select. It would be nice to see previous selections made before it is set to read only.

Thanks

**Comment by ErikDubbelboer** [comment]
You mean something like [ui-disable-choice](https://github.com/angular-ui/ui-select/wiki/ui-select-choices) ?

**Comment by atentis** [comment]
@ErikDubbelboer No, let me explain a little better with a scenario. 
User goes to add record screen and sets a couple uptions in the multi select. 
User goes back to edit this screen but they can only view what was set in the multi select previously and not make any changes.

Thanks

**Comment by user378230** [comment]
`ng-disabled` works fine in demo http://plnkr.co/edit/juqoNOt1z1Gb349XabQ2?p=preview 

It shows selected items when you click between "Enable ui-select"/"Disable ui-select" what is wrong with this?

**Comment by atentis** [comment]
@user378230 I am no longer working on this project but on the version of the select I was using was graying out the entire control so you couldn't see the selected options. I will close this since you provided the plunker that shows this situation working. 

Thanks
