### ISSUE TITLE
Bug when inculde the module angular-animate

### ISSUE THREAD

**Issue by nicolasu** [angular-ui/ui-select#1306]
Hello,

I can't use a second time the search with text when i add the module ngAnimate 1.4.7

The text focus is not working. You can do a right click then push escape button on the keyboard to use it again but it's not swag.

Demo: http://plnkr.co/edit/FK6ZM8Xx8e7bdXTEYXNP

Remove ngAnimate and it is working fine.

ngAnimate is useless in the demo but in my real application i need it for other component.

**Comment by StuartBAutotrader** [comment]
I also have this problem.

**Comment by SerjoPepper** [comment]
+1

**Comment by santosguilherme** [comment]
+1

**Comment by user378230** [comment]
Appears to be working against latest (`v0.19.6`) so closing.
