### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by fcristel** [angular-ui/ui-select#1309]
Is there a way to search on special characters, like the ones in Spanish language for example?

What i would need is if I type the letter **i** for example, it should search for **i**, **I** and also **í** and **ì**, etc.

**Comment by erikdubbelboer** [comment]
This is not something for ui-select to handle. You have to either write your own `refresh` function to do the search or you have to write your own [angular filter](https://code.angularjs.org/1.4.6/docs/api/ng/filter/filter) for the `repeat` attribute.

The string search you mention is not something that's very easy. The best way is to remove all special characters from the string before doing the searching, see: http://stackoverflow.com/questions/990904/javascript-remove-accents-diacritics-in-strings

**Comment by fcristel** [comment]
OK, very helpful link.

I've managed to go around the searching part using the link you provided. I've added one more property to my searched object, with the transformed text using the <code>removeDiacritics</code> function, and now the search results are as expected.

The only drawback is that I can't highlight all the searched text anymore, but writing a good filter for the highlight should do the trick.

Thank you very much!

**Comment by fabiowitt** [comment]
Hello @fcristel , would you mind sharing your approach?

Thanks

**Comment by juannorris-santex** [comment]
Hi!

In case anyone gets here trying to find a highlight filter with accent support (like me), here is a filter I've coded based on ui-select's highlight filter, which seems to be working fine.

```javascript
    function customHighlight() {
        function escapeRegexp(queryToEscape) {
            return ('' + queryToEscape).replace(/([.?*+^$[\]\\(){}|-])/g, '\\$1');
        }

        return function (matchItem, query) {
            if (matchItem && query) {
                // Get the normalized and escaped version of the search query
                query = escapeRegexp(normalize(query));

                // Find the first occurrence of the given query
                var index = normalize(matchItem).indexOf(query);

                if (index !== -1) {
                    // Get the substring to be replaced
                    var toBeReplaced = matchItem.substring(index, index + query.length);

                    // Globally replace the substring with its highlighted version
                    return matchItem.replace(
                        new RegExp(escapeRegexp(toBeReplaced), 'gi'),
                        '<span class="ui-select-highlight">$&</span>'
                    );
                }
            }

            return matchItem;
        };
    }
```

The filter depends on a ```normalize``` function (probably not the best name), that takes a string and returns its lowercase non-accented version, which can be done with the link provided by @erikdubbelboer.

```javascript
normalize('Soporte Académico')
"soporte academico"
```

Hope someone finds it helpful :)

**Comment by juannorris** [comment]
Hi!

In case anyone gets here trying to find a highlight filter with accent support (like me), here is a filter I've coded based on ui-select's highlight filter, which seems to be working fine.

```javascript
    function customHighlight() {
        function escapeRegexp(queryToEscape) {
            return ('' + queryToEscape).replace(/([.?*+^$[\]\\(){}|-])/g, '\\$1');
        }

        return function (matchItem, query) {
            if (matchItem && query) {
                // Get the normalized and escaped version of the search query
                query = escapeRegexp(normalize(query));

                // Find the first occurrence of the given query
                var index = normalize(matchItem).indexOf(query);

                if (index !== -1) {
                    // Get the substring to be replaced
                    var toBeReplaced = matchItem.substring(index, index + query.length);

                    // Globally replace the substring with its highlighted version
                    return matchItem.replace(
                        new RegExp(escapeRegexp(toBeReplaced), 'gi'),
                        '<span class="ui-select-highlight">$&</span>'
                    );
                }
            }

            return matchItem;
        };
    }
```

The filter depends on a ```normalize``` function (probably not the best name), that takes a string and returns its lowercase non-accented version, which can be done with the link provided by @erikdubbelboer.

```javascript
normalize('Soporte Académico')
"soporte academico"
```

Hope someone finds it helpful :)

**Comment by user378230** [comment]
@juannorris how about adding to the FAQs https://github.com/angular-ui/ui-select/wiki/FAQs :smile:

**Comment by juannorris** [comment]
@user378230 Sure :D Do you want me to add it? How do you handle wiki changes?
