### ISSUE TITLE
Make select-choices box bigger than the input box?

### ISSUE THREAD

**Issue by xingped** [angular-ui/ui-select#1311]
Is there a way to let the choices box expand to as big as it needs to be to prevent the text of choices being chopped off?

**Comment by jlandry** [comment]
I believe that the multiple should do that.
    <ui-select  multiple >

**Comment by xingped** [comment]
It doesn't as far as I can tell.

http://plnkr.co/edit/8ZIrKI7M5UGzgtsZwCYZ?p=preview

**Comment by jlandry** [comment]
I see you mean expand the text box's width or wrap the text.

**Comment by pburrows** [comment]
Does this fix it? It does for me:

```
.ui-select-bootstrap>.ui-select-choices{
    width: auto !important;
}
```

**Comment by wesleycho** [comment]
One should be able to do this via CSS.

Closing as a support issue.
