### ISSUE TITLE
Tagging: Existing tag not selected when typing in the search box

### ISSUE THREAD

**Issue by mr-unicoder** [angular-ui/ui-select#1312]
I faced an issue when using this great component as a tagging input as follows:
Assume the tags data source is [{id: 1, tagName: "Tag 1"}, {id: 2, tagName: "Tag 2"}, {id: 3, tagName: "Tag 3"}]
when i type "Tag 2" in the search box then press enter, the existing tag is not selected, it always considers it as a new tag.
how can i solve that ?

**Comment by wesleycho** [comment]
Can you post a reproduction in Plunker?
