### ISSUE TITLE
Not working with custom interpolateProvider configuration

### ISSUE THREAD

**Issue by m3hul** [angular-ui/ui-select#1321]
error: ```Controller 'ngModel', required by directive 'uiSelectSingle', can't be found!```

with config: ```$interpolateProvider.startSymbol('[[').endSymbol(']]');```

code: ```<ui-select>
                            <ui-select-choices repeat="company in companies" ng-model="company.data">
                                [[ company.comp_name ]]
                            </ui-select-choices>
                        </ui-select>```

**Comment by user378230** [comment]
`ng-model` should be on `ui-select` not `ui-select-choices`.

Closing.
