### ISSUE TITLE
ui-select broken with angular 1.5.0 beta2

### ISSUE THREAD

**Issue by LeleDev** [angular-ui/ui-select#1325]
Ui-select doesn't work with latest angularjs updates

**Comment by carlos-** [comment]
Is this related with #1128?

**Comment by LeleDev** [comment]
It seems not

**Comment by crissdev** [comment]
In what is it broken? Updating the examples to use `1.4.8` seem to work just fine. Since I intend to use this in a production environment it would be very helpful if anyone can provide more info. Thanks.

http://plnkr.co/edit/4EsCcN8z3OZKYM1qjp84?p=preview
http://plnkr.co/edit/sFPmLg13rXqMuRLI7jqh?p=preview

**Comment by LeleDev** [comment]
Ok you are right, with 1.4.8 is working, only with 1.5.0 beta2 I get the following error:

```
Error: [ui.select:transcluded] http://errors.angularjs.org/1.5.0-beta.2/ui.select/transcluded?p0=Expected%201%20.ui-select-match%20but%20got%20'%7B0%7D'.&p1=0
    at http://localhost:9001/src/app/app_files/bower_components/ui-select/dist/select.js:119:12
    at http://localhost:9001/src/app/app_files/bower_components/ui-select/dist/select.js:972:19
    at http://localhost:9001/src/app/app_files/bower_components/angular/angular.min.js:55:319
    at http://localhost:9001/src/app/app_files/bower_components/angular/angular.min.js:60:159
    at O.d (http://localhost:9001/src/app/app_files/bower_components/angular/angular.min.js:57:164)
    at k (http://localhost:9001/src/app/app_files/bower_components/angular/angular.min.js:62:248)
    at http://localhost:9001/src/app/app_files/bower_components/ui-select/dist/select.js:960:9
    at ea (http://localhost:9001/src/app/app_files/bower_components/angular/angular.min.js:76:209)
    at w (http://localhost:9001/src/app/app_files/bower_components/angular/angular.min.js:64:64)
    at http://localhost:9001/src/app/app_files/bower_components/angular/angular.min.js:72:176
```

The problem if you use this library for production is that it seems to have been quite abandoned from the maintaners... I regret to have chosen this library for my project due to the lack of support (that's why also I'm lazy to report broken stuff in the proper way, since nobody seems to care about it)

**Comment by crissdev** [comment]
@LeleDev Thanks for your feedback. I hope to find some good alternatives without messing around with $apply. Please let me know if you know about some of them :-)

**Comment by LeleDev** [comment]
You could give a try to the old ui-select directive repository code (when it was a wrapper for the nice select2 library: https://github.com/select2/select2) at this page: https://github.com/angular-ui/ui-select2/blob/master/src/select2.js

**Comment by nickmorton** [comment]
It seems to have been caused by this change for 1.5.0-beta.1 [Lazily compile the `transclude` function](https://github.com/angular/angular.js/commit/652b83eb226131d131a44453520a569202aa4aac)

You can prove it by setting eager=true in the debugger.

**Comment by llafuente** [comment]
The workaround is really simple.

Add class to ui-select-match and ui-select-choices with the same name

See the diff @ https://github.com/inetsys/ng-formalizer/commit/e18630297a50efaf0bb629cb26cfc6eea1d841d5

**Comment by nickmorton** [comment]
Nice one! Works for me.

**Comment by Luddinus** [comment]
@llafuente It works, but WHY?

**Comment by Luddinus** [comment]
Select2 theme does not works (it does not show the search icon etc.)

**Comment by bogdanalexe90** [comment]
I have the same problem with `angular-1.5.0-rc.0` I opened an issue for them here:
https://github.com/angular/angular.js/issues/13527

**Comment by steambros** [comment]
@llafuente Thanks for the easy workaround. Works for me with `angular-1.5.0-rc.0`.

**Comment by brunolimawd** [comment]
Thanks @llafuente, Works for me with `AngularJS v1.5.0-rc.0` :+1:

**Comment by amantilas** [comment]
Hi, just checking if there are any plans to resolve within ui-select without using the work-around described above, as the Angular issue has been moved to the Ice Box.

**Comment by kurtommy** [comment]
@llafuente Thanks for the easy/crazy workaround. Works for me with angular-1.5.0-rc.0.

**Comment by sv311** [comment]
This is broken with 1.4.8 when loading data from server.  Check this plunker with async simulation:

http://plnkr.co/edit/dEqYOvKEt7Dp6OaBXGCO?p=preview

**Comment by valterkraemer** [comment]
Had difficulties getting bootstrap theme to work with angular-1.5.0-rc.0 . Finally got it.

Here's a working Plunker if others still have problems.

http://plnkr.co/edit/bpSBAZzS8BVIK4roTFLd?p=preview

**Comment by chrisvel** [comment]
+1 here

**Comment by CesarLanderos** [comment]
this is still happening in the 1.5.0 release :(

![captura de pantalla de 2016-02-05 17 21 43](https://cloud.githubusercontent.com/assets/815951/12862170/8bcabaee-cc2e-11e5-8b0a-b64ce5e627c9.png)

**Comment by ConcurrentHashMap** [comment]
The workaround from @llafuente still works with the 1.5.0. Thanks for sharing!

**Comment by avgalon** [comment]
Thanks man, works great with 1.5.
Can you please share on why exactly it works?

**Comment by hut8** [comment]
@avgalon it works because part of the compilation process takes elements called `ui-select-match` (and other `ui-select-*`) and applies the `class="ui-select-*"` attributes. In this case, that part of the transclusion happens *after* the part that looks for elements with those classes, which of course is wrong. So this isn't a bad workaround at all, I don't think.

I had been debugging this last night and I thought it was because I had moved these into templates that were loaded asynchronously (there are other bugs in this project for the same thing which give the same error message). Then I realized that I had upgraded my Angular version as well (to 1.5.0), which is actually what caused it. So I can confirm this also works on 1.5.0.

**Comment by misaizdaleka** [comment]
I'm trying to override select directives so that these classes are automatically added as a part of the compilation process, rather than me adding all the classes manually in the html. No luck for the time being :(

**Comment by bubenshchykov** [comment]
@llafuente thanks a lot, this little magic worked :)
@hut8 thanks for explaining the magic!

**Comment by misaizdaleka** [comment]
Here's my fix so that you don't have to manually add classes everywhere, since this will add them automatically. 

```
angular.module('ui.select').config(function($provide) {
    $provide.decorator('uiSelectChoicesDirective', function($delegate) {
        var directive = $delegate[0];

        var templateUrl = directive.templateUrl;

        directive.templateUrl = function(tElement) {
            tElement.addClass('ui-select-choices');
            return templateUrl(tElement);
        };

        return $delegate;
    });

    $provide.decorator('uiSelectMatchDirective', function($delegate) {
        var directive = $delegate[0];

        var templateUrl = directive.templateUrl;

        directive.templateUrl = function(tElement) {
            tElement.addClass('ui-select-match')
            return templateUrl(tElement);
        };

        return $delegate;
    });
});
```

**Comment by chrisfosterelli** [comment]
Should we update the title "ui-select broken with angular 1.5.0" since 1.5.0 is now stable, not beta anymore?

Anyone who is using npm to install angular is now most likely being auto-updated to a version of angular that breaks with ui-select, so this is likely going to affect a lot more people now.

**Comment by avgalon** [comment]
Thanks hut8.

**Comment by Narretz** [comment]
Um, setting a class on an element is a workaround, not a fix. The problem is that ui-select reaches into the transcluded content before it has been compiled. It should instead wait until the transcluded content is ready. The children should require the ui-select directive and call a function in the ui-select controller when they have been linked successfully. At least that's how I would do it.

**Comment by dviramontes** [comment]
The diff by @llafuente solved in my case. 
Using ui-select 0.13.3 
and angular 1.5.0

**Comment by earivasz** [comment]
@llafuente Thanks for the solution works for me with angular 1.5.0.

**Comment by joshjwalker** [comment]
@misaizdaleka where did you put that to get it to work? I have a ton of selects throughout a platform I'm working on, and adding classes is unreasonable

**Comment by ipavlyk** [comment]
@llafuente, I spent a lot of time searching for solution and got nothing.  But your post save a lot of my time. Thx a lot, man)

**Comment by misaizdaleka** [comment]
@joshjwalker just put in your main js file. In my case, it was app.js.

**Comment by aaronroberson** [comment]
The fix has been published in v0.14.3.

**Comment by chrisfosterelli** [comment]
Thanks @aaronroberson and @Narretz!

**Comment by K1N5L4Y3R** [comment]
@llafuente Thanks for the solution! It works for me with angular 1.5.0.

**Comment by Just-Rookie** [comment]
@llafuente Thanks, it works for me with Angualr 1.5.0.  But I want to know why it works when I add the class to ui-select-match and ui-select-choices with the same name. can you tell me ? Thanks a lot!

**Comment by user378230** [comment]
> llafuente Thanks, it works for me with Angualr 1.5.0. But I want to know why it works when I add the class to ui-select-match and ui-select-choices with the same name. can you tell me ? Thanks a lot!

Its a workaround not a solution (the solution is update to ui-select > v0.14.3)

See PR #1430 for details on why adding classes work.

**Comment by Just-Rookie** [comment]
@user378230 Thanks!

**Comment by crissdev** [comment]
In case someone really knows what the heck I'm doing wrong please share...This does not work.

```jade
ui-select.form-control(multiple ng-model="searchFilters.someProperty")
  ui-select-match(placeholder="{{::'Choose...' | translate}}") {{$item.text | translate}}
  ui-select-choices(repeat="filterOption.value as filterOption in searchFilters.someList track by filterOption.value")
    span {{filterOption.text | translate}}
```

`someList` is an array like `[{value: 'xxxx', text: 'xxxxx'}]`
`searchFilters.someProperty` is an array.
`translate` directive is from `angular-gettext`

All I get is `Syntax Error: Token 'track' is an unexpected token at column 31 of the expression....`

Thx

**Comment by Narretz** [comment]
@crissdev posting in closed issues is not the best way to get attention to your issue

**Comment by heridev** [comment]
you're right not so cool writing on closed issues.

but any of the solutions included in this thread worked for me :(, so I ended up downgrading the ui-select2 version:
```
Installing rails-assets-angular-ui-select 0.13.0 (was 0.14.2)
``` 
and it's working now

**Comment by user378230** [comment]
@heridev did you see my reply? https://github.com/angular-ui/ui-select/issues/1325#issuecomment-192249909

**Comment by RichardPinheiro** [comment]
@llafuente nice work my friend!

**Comment by gop-aroy** [comment]
Thank you @llafuente

**Comment by bala2e** [comment]
Hi All,
Kindly check this solution  [https://github.com/angular-ui/ui-select/issues/1467](this) too
