### ISSUE TITLE
Issues when using values `''` and `false`

### ISSUE THREAD

**Issue by fiznool** [angular-ui/ui-select#1328]
I have a bunch of items as so:

``` js
scope.items = [{
  label: '-- None Selected --',
  value: ''
}, {
  label: 'Yes',
  value: true
}, {
  label: 'No',
  value: false
}];

scope.model = '';
```

My HTML:

``` html
<ui-select ng-model="model">
  <ui-select-match>{{ $select.selected.label }}</ui-select-match>
  <ui-select-choices repeat="item.value as item in items track by item.value">{{ item.label }}</ui-select-choices>
</ui-select>
```

I'm expecting when the select box loads up to see the `--None Selected--` item, since my model is set to the empty string, `''`. However, due to [this line](https://github.com/angular-ui/ui-select/blob/4467b8238866f85003f8815f44a7ca8563222043/src/uiSelectSingleDirective.js#L28) using a double equals instead of a triple equals, the `No` item is actually displayed, since the formatter traverses from the end of the items array to the beginning, and when it finds the item with the `false` value, it compares `false == ''` which returns `true`.

Is there any historical reason why this is a double equals instead of a triple equals? Would you accept a PR which changes this to triple equals?

**Comment by wesleycho** [comment]
Can you post a reproduction via Plunker just for assistance with debugging for anyone who wants to look at this closer?

This does sound like an issue though.

**Comment by fiznool** [comment]
Here is a plunkr showing the issue.

http://plnkr.co/edit/XosVjr?p=preview

**Comment by user378230** [comment]
The suggested fix appears to work in plunkr, will also need a test though. 

@fiznool can you put together a PR?

**Comment by fiznool** [comment]
@user378230 submitted a PR.
