### ISSUE TITLE
Tabindex is incorrect, user must tab multiple times to move to the ui-select input.

### ISSUE THREAD

**Issue by jdonisvitch** [angular-ui/ui-select#1336]
I've found an issue with this library in my project, with the tabindex being incorrectly set. I've seen it come up and be closed multiple times, but I haven't found a way to work around it, without removing the library and simply using a bootstrap dropdown.  We are using bootstrap and the bootstrap theme. 

*Expected: When the user tabs (on a keyboard) through the form fields, moving from one input to another, only takes one click on the tab button. 

*Currently: When the user tabs (on a keyboard) through the form fields, moving from one form-control to another, it takes two clicks on the tab button. 

I've dug relatively deep into this and can submit a PR if this fix has not been started, or already made.

**Comment by VytautasB** [comment]
This is relevant to me as well. @jdonisvitch, could you share the fix?

**Comment by k7sleeper** [comment]
We've detected the same problem. It occurs when using `ui-select`together with `angular-aria`.
We fixed this problem by adding a `tabindex='-1'` to `bootstrap/match.tpl.html`:
```
<i class=\"caret pull-right\" ng-click=\"$select.toggle($event)\" tabindex='-1'>
```
When `angular-aria` sees `ng-click` it adds a tabindex if there's no tabindex set. That's not desired for that element.
