### ISSUE TITLE
Placeholder FOUC - Flash Of Unstyled Content

### ISSUE THREAD

**Issue by gandaldf** [angular-ui/ui-select#1340]
Hi all, using ui-select I noticed that sometimes when I fast-reload a page with ui-select in it, may happen that the string "{{$select.placeholder}}" appears for a couple of seconds in place of the final placeholder.
There is some way to solve this? (maybe with ng-bind?) ...I've tried with ngGloak but it doesn't change! :-/
I know I should reproduce it but it's very diffcult for me... because I think it's something related with the page weight and with a simple demo it wouldn't happens.

**Comment by mikeerickson** [comment]
have you added the ng-cloak CSS to your desired CSS file?  Ng-cloak should surely do the trick.  

You can also set the object via ng-hide and set flag in controller to enable

**Comment by gandaldf** [comment]
Oh god... the problem exists only when I leave the Firebug tools (on Firefox) open...
I'm so sorry, I didn't noticed it before... too much work for today.
I close the issue.
