### ISSUE TITLE
Clear/Remove all items from multiple select bootstrap theme

### ISSUE THREAD

**Issue by jsheebs104** [angular-ui/ui-select#1341]
Is there ANY way to remove all items that are currently selected at once from the multi-selector?
It currently looks like you have no way of doing this.

**Comment by Kepro** [comment]
yes of course... there is a two way binding... look in my demo for you 
http://plnkr.co/edit/DkeH6CO4OWJKbW2Ie1UN?p=preview

**Comment by jsheebs104** [comment]
Sweet. Thanks.

**Comment by jsheebs104** [comment]
Actually it's not working in bootstrap theme.

HTML:
<ui-select multiple ng-model="selectedMeasurements" theme="bootstrap" ng-change="updateMeasurement(selectedMeasurements)" ng-disabled="!measurementsLoaded">
                        <ui-select-match placeholder="Choose measurements..."> {{$item.MeasurementName}}</ui-select-match>
                        <ui-select-choices repeat="measure as measure in departmentInfo">
                            {{measure.MeasurementName}}
                        </ui-select-choices>
                    </ui-select>

                <button ng-click="resetMeasurements()">Reset</button>
                </div>

js:

        $scope.resetMeasurements = function () {
            $scope.updateMeasurement([]);
        }

        $scope.updateMeasurement = function (measurements) {
            $scope.chartAdjusted = true;
            $scope.selectedMeasurementsArray = measurements;

            strMeasArray = JSON.stringify(measurements);
            $scope.selectedMeasurements = measurements;

**Comment by jsheebs104** [comment]
Actually it's not working in the bootstrap theme when I try to reset the model in the controller: 
HTML:
```
<ui-select multiple ng-model="selectedMeasurements" theme="bootstrap" ng-change="updateMeasurement(selectedMeasurements)" ng-disabled="!measurementsLoaded">
                        <ui-select-match placeholder="Choose measurements..."{{$item.MeasurementName}}</ui-select-match>
                        <ui-select-choices repeat="measure as measure in departmentInfo">
                            {{measure.MeasurementName}}
                        </ui-select-choices>

<button ng-click="resetMeasurements()"></button>
```

js:

```
        $scope.resetMeasurements = function () {
            $scope.updateMeasurement([]);
        }

        $scope.updateMeasurement = function (measurements) {
            $scope.chartAdjusted = true;
            $scope.selectedMeasurementsArray = measurements;

            strMeasArray = JSON.stringify(measurements);
            $scope.selectedMeasurements = measurements;
````

I dunno what's going on. I'm sure I'm doing something wrong. Any help would be appreciated!

**Comment by Kepro** [comment]
it's also working on bootstrap theme... see here http://plnkr.co/edit/DkeH6CO4OWJKbW2Ie1UN?p=preview

**Comment by jsheebs104** [comment]
Look. I'm doing the same thing here and it. is. not. working.

![capture](https://cloud.githubusercontent.com/assets/14280506/11696832/f30d31c2-9e7b-11e5-8cad-041057761e1d.PNG)

**Comment by ProLoser** [comment]
`x.selectedMeasurements = []`

Use an object property, don't put primitives directly onto scope

**Comment by jsheebs104** [comment]
ok. still learning here. sorry for the trouble.
