### ISSUE TITLE
How to customize group label?

### ISSUE THREAD

**Issue by yuanda** [angular-ui/ui-select#1344]
![image](https://cloud.githubusercontent.com/assets/2967550/11629534/c6d7b8e0-9cc6-11e5-85d8-805af628a7d6.png)

As shown in the image, the list is grouped by country, how can I customize the group label so to make it larger then the selection items?

[Plunker](http://plnkr.co/edit/e2yMJI5LpyjghWlYG2Kr?p=preview)

I also posted a question on [StackOverflow](http://stackoverflow.com/questions/34136194/how-to-customize-group-label-in-angular-ui-select)

Thanks in advance.

**Comment by arahansen** [comment]
The answer in StackOverflow is correct. ui-select provides a css selector as `.ui-select-choices-group-label`.

The default font-size in the Plunker is `font-size: 12px;`

So,

```css
.ui-select-choices-group-label {
  font-size: 20px;
}
```
would increase the size of the group label.

**Comment by yuanda** [comment]
Thank you @arahansen

**Comment by user378230** [comment]
You can also modify [`_THEME_/choices.tpl.html`](https://github.com/angular-ui/ui-select/blob/dfa096975a6daba21ac5484129602e8387ebce56/src/bootstrap/choices.tpl.html)

Closing as answered.
