### ISSUE TITLE
Autocomplete="false" Does not work in Edge Browser

### ISSUE THREAD

**Issue by zeDoctor** [angular-ui/ui-select#1346]
On the Edge browser in Windows 10, autocomplete="false" does not work on the inputs, causing bizarre behavior in which auto-complete suggestions show up on the dropdown.

Autocomplete="off" seems to work however, and according to [w3c autocomplete](http://www.w3schools.com/tags/att_input_autocomplete.asp) is supposed to be an on/off anyways, correct?

**Comment by tim-lukacik** [comment]
@zeDoctor I think this was done to support Chrome which until very recently was ignoring autocomplete="off" but respected "false" Unfortunately as you and others have noticed false is not respected by Edge. Kind of a mess! They need to switch it back but it doesn't look like the authors are very active anymore given the issues/pulls on this repo.

See the below commit:
https://github.com/angular-ui/ui-select/commit/a3e2e95735a58bad07cfaee5084a83610966356d

**Comment by MattiJarvinen-BA** [comment]
autocomplete="off" works in current chrome, so this can be fixed.
