### ISSUE TITLE
Selected 

### ISSUE THREAD

**Issue by miecio1212** [angular-ui/ui-select#1347]
http://plnkr.co/edit/K9alAMAzvUqCY7Or8RwY?p=preview
Here in your plnkr Selected doesn't works can you fix it ?

**Comment by chrisvel** [comment]
+1

**Comment by esetnik** [comment]
This is due to the scope changes in angular. You can fix the demo by changing to property assignment in the ng-model.

**Comment by user378230** [comment]
ng Model requires the dot notation see my comment in #1353 and wiki > FAQs page.
