### ISSUE TITLE
Two way binding does not work on directive scope

### ISSUE THREAD

**Issue by mattbeattie** [angular-ui/ui-select#1348]
When using ui-select in a directive, we've found that selections do not persist to the model if it is set on the scope of the directive. I've replicated this in the following plnkr:

http://plnkr.co/edit/zst1oVVKEhNjgsRj8mKL?p=preview

Steps as follows:
* Click into the input and select a value
* Observe that the value shows up in the input as expected
* The value does NOT show up in the the following array (`testVariable`), indicating that the selected value was not persisted to the model

**Comment by ERobishaw** [comment]
Actually, this has nothing to do with being in a directive, it's broader bug...
I forked your Plunker with the hack fix:
http://plnkr.co/edit/ozxN76zgeytBoejUPE0Y?p=preview



Binding will currently only occur, if you are binding to sub-object on the scope.
i.e.,:


in the controller:
scope.x = {};

in the html of the ui-select:
ngModel="x.whatever"

and in your general html to see the result:
<div>Selections are: {{x.whatever}}</div>
