### ISSUE TITLE
No style on choices hover

### ISSUE THREAD

**Issue by Seiifer** [angular-ui/ui-select#1349]
I read about a performance issue cause by the `mouseenter` event, however I didn't manage how to find how to fix this behavior :

There is no style applied to the select choices when the mouse is hovering them. (for multiple and simple select)

However, when filtering the choice using the keyboard and the search, the selected style is applied on the choice.

So how can I have the select choices style to change on mouse hover ?

Here is a piece of code I'm using :

``` html
<!-- Products -->
<div class="col-md-6">
  <label>Products</label>
  <ui-select name="products" multiple ng-model="p.newProject.products" sortable="true"
             ui-select-required>
    <ui-select-match placeholder="Select or search product...">{{$item.name}}</ui-select-match>
    <ui-select-choices repeat="product.id as product in p.productsList | filter: $select.search">
      <div ng-bind-html="product.name | highlight: $select.search"></div>
    </ui-select-choices>
  </ui-select>
  <p ng-show="newProjectForm.products.$invalid" class="errorInput">Project product(s) is required.</p>
</div>
<!-- ... -->
<!-- Priority -->
<div class="col-md-3">
  <label>Priority</label>
  <ui-select name="priority" ng-model="r.newRequest.priority" ui-select-required>
    <ui-select-match placeholder="Select or search priority...">{{$select.selected.name}}
    </ui-select-match>
    <ui-select-choices
            repeat="priority.trigram as priority in r.requestPrioritiesList | filter: $select.search">
      <div ng-bind-html="priority.name | highlight: $select.search"></div>
    </ui-select-choices>
  </ui-select>
  <p ng-show="newRequestForm.priority.$invalid" class="errorInput">Request type is required.</p>
</div>
```

Is that a normal behavior and can it be changed ?

**Comment by krister1028** [comment]
+1

**Comment by ernestopye** [comment]
+1

**Comment by user378230** [comment]
Did you try [`ngMouseenter`](https://docs.angularjs.org/api/ng/directive/ngMouseenter)/[`ngMouseleave`](https://docs.angularjs.org/api/ng/directive/ngMouseleave)?

You may need to modify [choices.tpl.html](https://github.com/angular-ui/ui-select/blob/master/src/bootstrap/choices.tpl.html) to get the desired styling.

**Comment by Neonchen** [comment]
+1

**Comment by wesleycho** [comment]
This is something best implemented in CSS - maybe worth adding CSS in the library itself with sensible defaults.

**Comment by user378230** [comment]
All styles have a CSS hover. so closing this as mouse enter/leave were intentionally removed for performance reasons.
