### ISSUE TITLE
Project status/progress

### ISSUE THREAD

**Issue by starf** [angular-ui/ui-select#1351]
I hate to be negative but there doesn't seem to be any progress here, can we agree that:
1) There are a massive amount of issues that need to be taken care of
2) ui-select is not a decent replacement for select2
?

Are we better off using another bootstrap-select project and doing things the native way? Or are there any other alternatives?

**Comment by simkessy** [comment]
You find anything?

**Comment by faceleg** [comment]
I'm using this module, @starf what do you find it lacks?

**Comment by sbokorna** [comment]
There's no "order by".
Do you know how can I do it?

**Comment by sibeliusseraphini** [comment]
who is maintaining this repo @dimirc ?

**Comment by user378230** [comment]
Closing as dupe of #884
