### ISSUE TITLE
ui-select does not fire a 'ready' event when finished initializing

### ISSUE THREAD

**Issue by logannc** [angular-ui/ui-select#1352]
My use case is setting `.on('blur', ...)` to the input tag in order to add the value as a tag even if the user clicks out. However, when I'd like to set that function, the DOM isn't at it's final state and the input tag isn't there. Right now I just `setTimeout(func() { $(...).on('blur', ...) }, 0)` and the DOM is complete by the time it runs. I'd like to bind to a 'ready' event and then set the event listener.

**Comment by logannc** [comment]
My new workaround is adding a new event at the end of the returned compile function for uiSelect. It doesn't tell me that *everything* is done, but I can undo my event listeners and reset them each time.

**Comment by wesleycho** [comment]
One can just write a custom directive to do this.

Going to close as a support issue.
