### ISSUE TITLE
Can´t select elements with mouse click when using TAGGING

### ISSUE THREAD

**Issue by oezkany** [angular-ui/ui-select#1357]
Hi,

I can not select any item of ui-select-choice list if I am using the tagging option.
Try out this example: https://github.com/angular-ui/ui-select/blob/master/examples/demo-tagging.html

Thanks.

**Comment by mattmcardle** [comment]
I just came across this issue too, although i don't think it is new as prior to today my version of ui-select hadn't been updated in over a month and the issue was present then.

**Comment by soyuka** [comment]
+1, using `tagging="scopeFn" tagging_label="false"` selecting a choice in the list calls the `scopeFn` function with an empty string but never calls `on-select`.
