### ISSUE TITLE
Not binding ngModel when using a new element instead of options element

### ISSUE THREAD

**Issue by guilherme6191** [angular-ui/ui-select#1367]
Guys,
I am having a hard time trying to use ui-select under my business rule.

The thing is: I will show options to the select, however, if the user wants to use another input, I have to be able to catch this new input on my element scope.

This is how I am using ui-select:
```
<ui-select ng-model="configEvent.patient" name="name" theme="bootstrap" id="namePatient"          required="">
    <ui-select-match placeholder="Select or search a patient">
        {{$select.selected.name}}
    </ui-select-match>
    <ui-select-choices repeat="item in patientArray | filter: $select.search">
            <div ng-bind-html="item.name | highlight: $select.search"></div>
    </ui-select-choices>
</ui-select>
```
When the user selects an element that is in the patientArray, it binds to my model "configEvent.patient" properly. When the user types a new element, it doesn't bind to the model and I am not able to get this new input through ng-click in a button.

Do you guys have a workaround or any idea to point me to the right direction?

Thank you!

**Comment by naomiajacobs** [comment]
+1

**Comment by AndreiShostik** [comment]
the same problem. you can fix it with $watch function.

**Comment by wesleycho** [comment]
Closing as a usage issue.

This is possible by making use of the refresh functionality and unshifting an item into the array.
