### ISSUE TITLE
activeIndex not set properly when using complex objects

### ISSUE THREAD

**Issue by bgrohman** [angular-ui/ui-select#1368]
If your model is a complex object (e.g. {a: 1, b: 2, c: 'foo'}) and your select choices are as well, then the controller's activeIndex property is not set correctly on initialization due to the use of `ctrl.items.indexOf(ctrl.selected)` (https://github.com/angular-ui/ui-select/blob/master/src/uiSelectController.js#L59). 

That line should use a deep comparison for complex objects (something like lodash's `_.isEqual` function).

**Comment by bgrohman** [comment]
Better yet, if you're using the `track by` syntax in the repeat for the choices, then the comparison could just use the given track by property to test for equality.

**Comment by Till86** [comment]
I might have the same issue. For me always the first element is highlighted and the hover hightlighting doesn't work than in a correct way

**Comment by bgrohman** [comment]
@Till86 Sounds like it might be the same issue to me.

**Comment by user378230** [comment]
I'm guessing this should be resolved by #1407 when it's merged (...tagging for reference)

**Comment by martinoss** [comment]
@Till86 I guess I'm having the same problem here and it does not seem to be solved in 0.14.9 where #1407 is merged into.

First item is always highlighted.

**Comment by wesleycho** [comment]
Can you post a reproduction via Plunker?

**Comment by bgrohman** [comment]
@wesleycho Here you are: http://plnkr.co/edit/A9CycQdGM0UBaP8Brd1F?p=preview

Notice that the ngModel is set initially. When you open the dropdown, though, an incorrect option is shown as the selected one.

**Comment by user378230** [comment]
@bgrohman your plunkr is still on v0.11.2

In v0.16.1 it works fine: http://plnkr.co/edit/OsXvuNnG8SauWXBMGMwn?p=preview

Can you confirm and close the issue?

**Comment by bgrohman** [comment]
@user378230 Yes, it's working correctly in your plunkr with the newer version. Thanks!
