### ISSUE TITLE
Tags without multiple doesn't work

### ISSUE THREAD

**Issue by pablocabo** [angular-ui/ui-select#1380]
It's not working the tags creation without multiple. You can see the demo http://plnkr.co/edit/m1SQXUxftBLQtitng1f0

Also happens with angular 1.4.7 and ui-select 0.13.2

**Comment by build3dparts** [comment]
it works only by pressing comma character at the end

**Comment by soyuka** [comment]
You have to set `taggingLabel` to false.

**Comment by wesleycho** [comment]
Closing as a duplicate issue.
