### ISSUE TITLE
First click selects item but has part of select list visible, then click outside closes list

### ISSUE THREAD

**Issue by envision** [angular-ui/ui-select#1381]
Hi,

It may be that my other styles are mixing this visually but it doesn't change the fact that something happens after clicking outside – as if the first click to choose leaves something on focus, or something...

![pic1](https://cloud.githubusercontent.com/assets/1790545/12217535/510e260c-b70c-11e5-8dbb-1b950a22d1b3.jpg)

![pic2](https://cloud.githubusercontent.com/assets/1790545/12217537/5444eaa4-b70c-11e5-9f63-596613579d29.jpg)

![pic3](https://cloud.githubusercontent.com/assets/1790545/12217538/587552e4-b70c-11e5-8f05-4ed6117e53ff.jpg)

**Comment by wesleycho** [comment]
Can you post a reproduction in Plunker and give more details? This is confusing as written.

**Comment by Jefiozie** [comment]
Closing it down as there has not been a update over a couple of months. Please create new issue if this is still a bug/ problem with a plunker and the details as requested..

Thanks for understanding.
