### ISSUE TITLE
autocomplete like google for suggestions with ui-select

### ISSUE THREAD

**Issue by shomid** [angular-ui/ui-select#1382]
I have a autocomplete like google for suggestions .
how do to add this feature in ui-select ?

**Comment by vaer-k** [comment]
I'm guessing you already know about ui-select-choices and search filters like the ones demonstrated on https://github.com/angular-ui/ui-select/blob/master/examples/demo-multi-select.html, but I wanted to point it out in case you'd missed it.

**Comment by user378230** [comment]
Closing due to lack of info.
