### ISSUE TITLE
Limit is not working on multiple selection

### ISSUE THREAD

**Issue by jitendrathakur** [angular-ui/ui-select#1387]

**Comment by user378230** [comment]
Seems to be working fine in latest version http://plnkr.co/edit/IdhcFthg0K1WC8JM4Zqz?p=preview

Please include more details when raising an issue preferably with examples.

**Comment by JBerges** [comment]
Hi!

I had the same issue, so I ended up here, but actually it was my mistake, maybe this info can help others.

What was happening in my case was that I was passing to the limit attribute the reference to the variable ( limit="variable")  instead of the value (limit="{{variable}}").
