### ISSUE TITLE
allow-clear not getting disabled with ng-disabled on ui-select directive

### ISSUE THREAD

**Issue by Sheeryada** [angular-ui/ui-select#1392]
Disabling ui-select with ng-disabled is not disabling the cross icon/button.

http://plnkr.co/edit/j5uqDFxxDbXNb2XMwaWW

Steps to reproduce (use above plunker):
1. Disable ui-select using toggle button at the top.
2. Try clicking cross icon/button when ui-select disabled.

PS: Noticed this issue only after upgrading to bootstrap 3.3.5 version and was not reproducible with bootstrap 3.3.2 version.

**Comment by jrparish** [comment]
I am also running into the same issue. My workaround using less - 

```
.ui-select-match {
  .ui-select-toggle[disabled] {
    .glyphicon-remove {
      display: none;
    }
  }
}
```

**Comment by user378230** [comment]
This is probably resolved by #1388 but it hasn't been released yet. You could verify by updating the plunkr with the version from the examples: http://angular-ui.github.io/ui-select/#examples

If you verify it, please update the issue so it can be closed. :smile:

**Comment by jrparish** [comment]
Updating the examples to use Bootstrap 3.3.5 works as expected 👍

**Comment by Sheeryada** [comment]
@jrparish Plunker present in the initial issue is using Bootstrap 3.3.5 and doesn't seem like solution for this issue.

**Comment by jrparish** [comment]
@Sheeryada - The ui-select fix hasn't been released yet, so your plunkr won't work since its using 0.13.2.
