### ISSUE TITLE
How to obtain the filtered list once applied using the filter object property?

### ISSUE THREAD

**Issue by Avien** [angular-ui/ui-select#1395]
I have a filter object defined in my controller, i.e:
```javascript 
this._filter = {'type':'PREMUM', id:5657}
``` 
which is used in the html:
```javascript
  <ui-select-choices repeat="item in multiSelect.items | filter:{name:$select.search}  | filter:multiSelect._filter | orderBy:'name' | limitTo: 200 track by item.name">
            <span ng-bind-html="item.label || item.name | highlight: $select.search"></span>
        </ui-select-choices>
```
This filter is dynamic and changes occasionally by the user, once the filter is applied I need to decide if the current selected items are valid to stay selected, to do so I need to have the filtered list.

I found that $select.items is the only property holding the filtered list
How I do I use it in my controller, or alternatively get an event or some other hook to the filtered list? 

Thanks

**Comment by user378230** [comment]
I don't think you can access the filtered list from `ui-select`. You will need to manually apply your filter to your list of items. See angular docs: [Using filters in controllers, services, and directives](https://docs.angularjs.org/guide/filter)

I'd suggest you filter your items manually in your controller and then send the result to `ui-select-choices` and use it to fix your selected items.

**Comment by Avien** [comment]
Then what's the point in using the filter property in the ui-select if I need to manually apply the filter?
I've forked the project and emitted an event when list is filtered:
```javascript
// See https://github.com/angular/angular.js/blob/v1.2.15/src/ng/directive/ngRepeat.js#L259
    $scope.$watchCollection(ctrl.parserResult.source, function(items,oldItems) {
      if (items === undefined || items === null) {
        // If the user specifies undefined or null => reset the collection
        // Special case: items can be undefined if the user did not initialized the collection on the scope
        // i.e $scope.addresses = [] is missing
        ctrl.items = [];
      } else {
        if (!angular.isArray(items)) {
          throw uiSelectMinErr('items', "Expected an array but got '{0}'.", items);          
        } else {
          //Remove already selected items (ex: while searching)
          //TODO Should add a test
          ctrl.refreshItems(items);
          ctrl.ngModel.$modelValue = null; //Force scope model value and ngModel value to be out of sync to re-run formatters
          if(ctrl.search =="" && items != oldItems) { //don't broadcast the event while searching
              $scope.$emit('uis:filter', items);
          }
        }
      }
    });
```

https://github.com/Avien/ui-select/tree/v0.13.4

**Comment by user378230** [comment]
I would guess most people don't need to access the filtered list at any point.

Glad to see you got it sorted though.

**Comment by Avien** [comment]
I need the filtered list to validate the already selected options (the ng-model)
If they are not in the new filtered list they should be removed
I would expect this behavior to already be implemented in the ui-select , when filtering , but its not

**Comment by wesleycho** [comment]
Filtering in the refresh method execution gives the user the most power for filtering choices. Any filter applied in the template here likely creates a loss of information, since one is in a child $scope.

I'm not sure if there is a good solution here excepting what was recommended.
