### ISSUE TITLE
CommonJS is broken

### ISSUE THREAD

**Issue by mujx** [angular-ui/ui-select#1406]
Using this module with browserify fails with:

```bash
/tmp/testing/node_modules/ui-select/dist/select.css:10
.ui-select-highlight {
^
ParseError: Unexpected token
```
Removing the required css should fix it.
https://github.com/angular-ui/ui-select/blob/master/index.js#L1

**Comment by Akkuma** [comment]
In the webpack world you need a style and css loader. The bump from 0.13.2 to 0.13.3 was not the correct thing to have done based on semver. This added new functionality that was not backwards compatible with 0.13.2 when using browserify and webpack. I'd recommend deleting that tagged release altogether and forcing people to 0.14.0 if they want it.

**Comment by aaronroberson** [comment]
@Akkuma I'll delete the 0.13.3 tag as you've suggested, I was having issue with the conventional-recommended-bump lib used for managing semver releases. @Akkuma, will adding a css loader for resolve this issue for Browserify?

**Comment by csvn** [comment]
@aaronroberson I got it working with a CSS loader and browserify: https://github.com/cheton/browserify-css

**Note**: Transforms aren't applied to files required from `node_modules`, so a global transform is required to import the CSS
```javascript
require('browserify')('main-file.js')
  .transform(require('browserify-css'), { global: true })
  .bundle()
  // write file;
```

**Comment by aaronroberson** [comment]
Thanks, I'll update the readme.md unless you'd like to create a PR yourself!

**Comment by SerjoPepper** [comment]
@csvn but this css will be bundled to `.js` file. It is wrong.

**Comment by SerjoPepper** [comment]
@aaronroberson It would be great that `dist/select.js` just exports 'ui.router'
```
module.exports = 'ui.router'
```

So I can include this in browserify:
```
angular.module('app', [require('ui-select/dist/select')])
```

**Comment by SerjoPepper** [comment]
For me this way works:
```
gulp.task 'jsAdmin', ->
  stream = browserify({
    entries: [...]
    transform: [['coffeeify', global: true]]
    extensions: ['.coffee']
  })
  .ignore('./node_modules/ui-select/dist/select.css')
  .bundle()
```

**Comment by danpantry** [comment]
The fact that you require `css-loader` or some similar thing for CommonJS environments should probably be documented.....

**Comment by CesarLanderos** [comment]
i am using jspm, jspm already has a css loader but you have to add a "!" at the end of the import/require:

```
require('select.css!');
```

i dont know if there is a way to tell jspm to apply the css loader on any import that has the `.css` extension.

**Comment by aaronroberson** [comment]
v0.14.3 no longer includes the CSS file by default and requires that you manually include it.

**Comment by aaronroberson** [comment]
Accept Your Gift! ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcsaB-2B1-2FyHdArrPm5zn4zScy3L72kT3Ljfvc1RkNh5c93HhNsBAbiDabFeHrIMZ0CXKklp1AX2OZjcnXVAxd1MLx58TH6J5d6BLj5uMrh7WiZPAkW060P70avw4HkIaKlm9E-2F3lcdFaKW4xyiU3il8lLIv7MdNxJO3enHtN1GQvXNKlQrHD10WwrzJh7uUA5-2BzYf1pcVWhSu88buOADL-2F7ffCPl6dAWG1ghz6PqQFSA7KyF1Rv-2BfdvR7aTAIPmri-2FIvDIJSqnq-2FleBG8wvkC7hpjTujxc0lI4XMMFkoQ4HC6gMbuR9C4fidBwsUji8FWmiug-3D-3D_s5UH8bhnBaopYjthcNSRcWeSn7lHsw58JxqACH1JpyxJ-2FID7BbcVzNgrXNuiColA-2FsnHj1vVcZHNSrWh1DDnycux-2BLyCTPtp8sntsWSee31Jy8KJNoO6qYQZ10d80h4h23YZHlcvRQv4TyXKBV9nvgN3TIHq2BAGCFlS7q6nik37C8gU2ExJ7G3uHVcOVb0RKy8TsyZNe4E85PR8YDqKb1704i32hLPSoP1oDF0VWGi0VgZY5MWHsA09TYxGzT39xlJmuyvFkzSEEJS-2FSx7ghCQ0nfeHOXHPxLygERFbsSxRLw0hsQ17wqN44KWrN6MMZ-2FYQZYfOxenWiU5uI8r4Pg5hCpGsu6O7D-2FIyOa8iHK-2Bk8kuechNjKh057TGmxAg0Jcv2ir3CWZUl7B9kGRG4rw-3D-3D )

Aaron sent you a $55 gift for Handy

With Handy, a spotless home is only a few clicks away. Just pick a service and choose a time—an experienced, background checked professional will take care of the rest. Click below to claim your $55 credit or use code AARON9231 at checkout.

Accept Your Gift! ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcsaB-2B1-2FyHdArrPm5zn4zScy3L72kT3Ljfvc1RkNh5c93HhNsBAbiDabFeHrIMZ0CXKklp1AX2OZjcnXVAxd1MLx58TH6J5d6BLj5uMrh7WiZPAkW060P70avw4HkIaKlm9E-2F3lcdFaKW4xyiU3il8lLIv7MdNxJO3enHtN1GQvXNKlQrHD10WwrzJh7uUA5-2BzYf1pcVWhSu88buOADL-2F7ffCPl6dAWG1ghz6PqQFSA7KyF1Rv-2BfdvR7aTAIPmri-2FIvDIJSqnq-2FleBG8wvkC7hpjTujxc0lI4XMMFkoQ4HC6gMbuR9C4fidBwsUji8FWmiug-3D-3D_s5UH8bhnBaopYjthcNSRcWeSn7lHsw58JxqACH1JpyxJ-2FID7BbcVzNgrXNuiColA-2FsnHj1vVcZHNSrWh1DDnycux-2BLyCTPtp8sntsWSee31Jy8KJNoO6qYQZ10d80h4h23YZHlcvRQv4TyXKBV9nvgN3TIHq2BAGCFlS7q6nik37C8gU2ExJ7G3uHVcOVb0RKy8TsyZNe4E85PR8YDqKb1704i32hLPSoP1oDF0VWGi0VgZY5MWHsA09TYxGzT39sDF9e43AwHblnXiGU8XLt7d22cYTWCdryyuYH6mb4FrICOGSOBvOAv7R8TBzI43TZVnBybGdaBXGdpx2xXmXLYKem3fl26LerfRY9neUZjKqQtsbPo4IzHyd0TGXmSABVYq42iTuneyB7V7-2FTVwXmQ-3D-3D )
Use your $55 gift on any of Handy's services
(use code AARON9231 at checkout):

View all of Handy's Services ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcsbv8X8Oszigzr5NNtGKza3MWDFialnox81TfwNCxNUNxhHKA-2BdMfFIp0irzQtrT5-2FC7EBZRmlTEE9RzPGGsa0-2BNerKUsc6-2FzrAdWKAQw-2BXzyldlAEwTjpfQF339Id5VSeQ2WO-2FQ9tSpKWE-2F-2BDilm3RY-3D_s5UH8bhnBaopYjthcNSRcWeSn7lHsw58JxqACH1JpyxJ-2FID7BbcVzNgrXNuiColA-2FsnHj1vVcZHNSrWh1DDnycux-2BLyCTPtp8sntsWSee31Jy8KJNoO6qYQZ10d80h4h23YZHlcvRQv4TyXKBV9nvgN3TIHq2BAGCFlS7q6nik37C8gU2ExJ7G3uHVcOVb0RKy8TsyZNe4E85PR8YDqKb1704i32hLPSoP1oDF0VWGi0VgZY5MWHsA09TYxGzT39MociOGa3EkECGjmoUazKbq5eckKUmo5o4EmHxLEdc6a8Jkw1czLE1OL8icJhp4alIRrGeKfjJXgnkacea-2FL2IxTsbD8qWHazZIZt8fVBIbM465sjLJJsQ3pS9rgHQakaT3Qdl-2FRKY4GWM4HdnuaZ7w-3D-3D )

Handy Twitter ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKaX-2FU2oXhnvLnp3gZfkeb2AF7vRpkoN40hgM4hNyDSth_s5UH8bhnBaopYjthcNSRcWeSn7lHsw58JxqACH1JpyxJ-2FID7BbcVzNgrXNuiColA-2FsnHj1vVcZHNSrWh1DDnycux-2BLyCTPtp8sntsWSee31Jy8KJNoO6qYQZ10d80h4h23YZHlcvRQv4TyXKBV9nvgN3TIHq2BAGCFlS7q6nik37C8gU2ExJ7G3uHVcOVb0RKy8TsyZNe4E85PR8YDqKb1704i32hLPSoP1oDF0VWGi0VgZY5MWHsA09TYxGzT392KIVgfTcsmSqi3x96KHacmQ1V8cQSI8GXusFgx4nyliAPiZo-2Bh2iyi9PTkObkitHJePuIKwFcjcNgITkrS849VFiRq2AtB1SAwRrCnHnB1QT-2BIwe3zGT4Jqc3jwBAkLtmqR5e4B89dZc6zCXQ33SZg-3D-3D )
Handy Facebook ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKfa9DXUWP0mdASikrPI0DmDoKViAyBoQIsV4x7PT02KC_s5UH8bhnBaopYjthcNSRcWeSn7lHsw58JxqACH1JpyxJ-2FID7BbcVzNgrXNuiColA-2FsnHj1vVcZHNSrWh1DDnycux-2BLyCTPtp8sntsWSee31Jy8KJNoO6qYQZ10d80h4h23YZHlcvRQv4TyXKBV9nvgN3TIHq2BAGCFlS7q6nik37C8gU2ExJ7G3uHVcOVb0RKy8TsyZNe4E85PR8YDqKb1704i32hLPSoP1oDF0VWGi0VgZY5MWHsA09TYxGzT39p2jdAFtgMwlNd-2Bda7BR47YGJqMqRd0XXGhwYUDRwHtVnUPYurGGaY3askU8-2FUeqDmw6KULyXdpOaC0-2F89eRryM9wYgfESJ8L5uJK-2FpEo9x1ErhRSzKgTvexACoQ9n000vHO08c7aOSPjR25ZkPQXOg-3D-3D )
Handy Instagram ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKfeBoaKL8Ev6spOpwM7gM6S-2F8a-2BuAMyY5qXEGPy9TRAc_s5UH8bhnBaopYjthcNSRcWeSn7lHsw58JxqACH1JpyxJ-2FID7BbcVzNgrXNuiColA-2FsnHj1vVcZHNSrWh1DDnycux-2BLyCTPtp8sntsWSee31Jy8KJNoO6qYQZ10d80h4h23YZHlcvRQv4TyXKBV9nvgN3TIHq2BAGCFlS7q6nik37C8gU2ExJ7G3uHVcOVb0RKy8TsyZNe4E85PR8YDqKb1704i32hLPSoP1oDF0VWGi0VgZY5MWHsA09TYxGzT39nTPdKL2MAVapHWgfNKm6jhtcJfRa0kCdO5cMT0rFgekOdcv7sTZDvcxl8yJsSF0Qd0bP2ngCOaywV3E7K2ChXYxRu28pZpT9f-2FqhS8j1xdDl7c8Suk958pcPHEwCU1xWlofo8SBAKaEDn2WsAWf07g-3D-3D )

Our Services ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcsbv8X8Oszigzr5NNtGKza3MQJ44OHPcJikSh-2BVUrFwzQO4xaArAScjwh7B1X-2Bws5DZzdjanMyViAICvTlcFLTkw-3D_s5UH8bhnBaopYjthcNSRcWeSn7lHsw58JxqACH1JpyxJ-2FID7BbcVzNgrXNuiColA-2FsnHj1vVcZHNSrWh1DDnycux-2BLyCTPtp8sntsWSee31Jy8KJNoO6qYQZ10d80h4h23YZHlcvRQv4TyXKBV9nvgN3TIHq2BAGCFlS7q6nik37C8gU2ExJ7G3uHVcOVb0RKy8TsyZNe4E85PR8YDqKb1704i32hLPSoP1oDF0VWGi0VgZY5MWHsA09TYxGzT39VMHIrnjTwF6rPA-2BcaISb-2BfqXzNWhSv1nMwXZnPrg6fxG97UTtBbI7qoJt0gWegnUtMz6xBQDHeiKNoGkL6Nq0Op2wFKhTCM-2FocLlk-2Fj-2FGF-2FBH4pEbbV852b809zQzfRb0lVYcjFgxn2xTqXGOJtaaw-3D-3D )
helpcenter ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcse4Lp6fgbkd2iUk5hd2lBMUpBCYqNi1V7ydYheQ49Mw4W-2FJwIs-2FOCxm2wmUesDoFsLAcQPHKGpgX9GOqDdMK5RE-3D_s5UH8bhnBaopYjthcNSRcWeSn7lHsw58JxqACH1JpyxJ-2FID7BbcVzNgrXNuiColA-2FsnHj1vVcZHNSrWh1DDnycux-2BLyCTPtp8sntsWSee31Jy8KJNoO6qYQZ10d80h4h23YZHlcvRQv4TyXKBV9nvgN3TIHq2BAGCFlS7q6nik37C8gU2ExJ7G3uHVcOVb0RKy8TsyZNe4E85PR8YDqKb1704i32hLPSoP1oDF0VWGi0VgZY5MWHsA09TYxGzT3931Z5Cp6orUU8MOglocgNh8gLmm2rvp2KKlcrJAsrukHkrt0OeNGAgRgff7yNWuOVe2qiaCFCaHWyzHisiOJ-2FLsHOrs7wYp5UPakd5WopPC2HB5UzXxf9xMR-2FaL-2FPgFtB8Yrrk1aeDwUBbntWIhJLcA-3D-3D )
Download Handy iOS app ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKe-2B4bz-2FAZDzUh1KL03FtyJ2uqoInuMQFjnKVNRO5FQSo-2FpakL1Y4hX85UGZ2zp5KD-2BI8hjWgTPijyltMY2jEortmwgrC-2F2r8jq6s0-2Bya9iXK_s5UH8bhnBaopYjthcNSRcWeSn7lHsw58JxqACH1JpyxJ-2FID7BbcVzNgrXNuiColA-2FsnHj1vVcZHNSrWh1DDnycux-2BLyCTPtp8sntsWSee31Jy8KJNoO6qYQZ10d80h4h23YZHlcvRQv4TyXKBV9nvgN3TIHq2BAGCFlS7q6nik37C8gU2ExJ7G3uHVcOVb0RKy8TsyZNe4E85PR8YDqKb1704i32hLPSoP1oDF0VWGi0VgZY5MWHsA09TYxGzT39-2B5Ke7E7-2FLx5Rjc6SE9-2BrtZei6Rt7NxajOMOWoKXNtQglCVfP8OtMJ2Zv4OrTSUmPO6-2BKOUoTjsJVvwxeonPyHevW6GOxvWxtT-2FuiGThzAe-2FV1GWhfg6e1NJJW6fBERlFPJ1L5j9BWv0ZcsmSWy7hDA-3D-3D )
Download Handy Android app ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKeJcuYvtamgIYRZeccCPxkcFs2tKreRwShvBbhgLgpeznxEEVKVOltp8oC6Ig4DUHnf-2ByPOZsMz-2F8ivVr-2FUyO-2Fo-3D_s5UH8bhnBaopYjthcNSRcWeSn7lHsw58JxqACH1JpyxJ-2FID7BbcVzNgrXNuiColA-2FsnHj1vVcZHNSrWh1DDnycux-2BLyCTPtp8sntsWSee31Jy8KJNoO6qYQZ10d80h4h23YZHlcvRQv4TyXKBV9nvgN3TIHq2BAGCFlS7q6nik37C8gU2ExJ7G3uHVcOVb0RKy8TsyZNe4E85PR8YDqKb1704i32hLPSoP1oDF0VWGi0VgZY5MWHsA09TYxGzT394n-2BpcABOE2yODhpZy1hmXKybbj-2BKm0R83iSTVc8d-2Ft6G-2B-2BS4P7-2B74K-2F8iX8tbZjy32NTkLJPCS-2B3zhsnh-2BMFF77mspJOJxGCO-2BcNPN34r2DOMolIn6sz2E-2BbV-2FraIQy2fFJzY69uldnhtwxv67kKUA-3D-3D )

Refer a Friend, Earn $50! ( xhttps://sgemail.handy.com/wf/click?upn=YsKWC7yTmiePOc2Pn-2Fa7R9V1Z-2FmspGRWKf5-2BNbJAcZuLZGz8MM1bTALYgBeeFogRy7AGwMT0R9RgzqFAR0taDV2mxNZC183vLo10oJ4jrl62VC5ZEK8f9-2FimJ4ErLRJFtBaPdxxGW4y5Kg4isuxRoVO-2BwMhi5auKgqzPwOAwtaY-3D_s5UH8bhnBaopYjthcNSRcWeSn7lHsw58JxqACH1JpyxJ-2FID7BbcVzNgrXNuiColA-2FsnHj1vVcZHNSrWh1DDnycux-2BLyCTPtp8sntsWSee31Jy8KJNoO6qYQZ10d80h4h23YZHlcvRQv4TyXKBV9nvgN3TIHq2BAGCFlS7q6nik37C8gU2ExJ7G3uHVcOVb0RKy8TsyZNe4E85PR8YDqKb1704i32hLPSoP1oDF0VWGi0VgZY5MWHsA09TYxGzT39IstLgMPlG3Ngg6iAfYHLWUWdxd-2Fun4e3xIwlanwrFvNfyR-2FeK-2Fvefzk080b4HT-2FL4wlI3heXNnm3llaf6IiXTy-2FzfNUP3RhXUf76cl0rfJKUEmfGtOMXbEysWzpD2E7h7fNL2-2BVqusATcZsq1zMGyw-3D-3D )|Privacy Policy ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKXE0Lx8wVhm5qiHGXjJOgd7oLwhjwvzCLbE0HeWhRyGB_s5UH8bhnBaopYjthcNSRcWeSn7lHsw58JxqACH1JpyxJ-2FID7BbcVzNgrXNuiColA-2FsnHj1vVcZHNSrWh1DDnycux-2BLyCTPtp8sntsWSee31Jy8KJNoO6qYQZ10d80h4h23YZHlcvRQv4TyXKBV9nvgN3TIHq2BAGCFlS7q6nik37C8gU2ExJ7G3uHVcOVb0RKy8TsyZNe4E85PR8YDqKb1704i32hLPSoP1oDF0VWGi0VgZY5MWHsA09TYxGzT39G7hFtBtjIHqlsJ-2FVpBZCUPqkXBsMXo6j70xNhJ2qJRjrWprQcInx9NAkLvljMo6SJ44a3O4PcihuYyuQOYCEpH5YipO9kG7qlerg78WZeXBfStNPq7F20lbIGa5vaQT9t39u4B0VT5lRTJX1LqyPkg-3D-3D )|Unsubscribe ( https://sgemail.handy.com/wf/click?upn=wz-2FQ7Wmj26-2Boily69xWn-2FdB3gxvuT-2Fcn2o1CsCXSMqzTVlu8lrEjD2X6MEa5PfWyMnEX7XfbLj4C-2B2ScobzYnomdG84CBjSgRJW-2BUsemQrs-3D_s5UH8bhnBaopYjthcNSRcWeSn7lHsw58JxqACH1JpyxJ-2FID7BbcVzNgrXNuiColA-2FsnHj1vVcZHNSrWh1DDnycux-2BLyCTPtp8sntsWSee31Jy8KJNoO6qYQZ10d80h4h23YZHlcvRQv4TyXKBV9nvgN3TIHq2BAGCFlS7q6nik37C8gU2ExJ7G3uHVcOVb0RKy8TsyZNe4E85PR8YDqKb1704i32hLPSoP1oDF0VWGi0VgZY5MWHsA09TYxGzT395LpaN6qC7eu4X5yD2ddZVzVVlen0-2FDgKC8qjuRRveUNGVmY1d2Hb-2F9eyd4gha7JDdtGM1p-2F1iSZ-2BsXlMd7czqCtGCKmDZgGrWG1LpiF7I-2F-2FQyhQUal-2BkSWt7VEe1tqmyLY6nCKREt5QgoKl9jOebeA-3D-3D )

*By clicking this email, this allows us to send you the occasional marketing email, with goodies like special offers and limited-time services.
**Valid for new customers only. New customers receive $55 off their first booking. Must click through the 'Claim' url or use provided referral code, AARON9231, at checkout. Not combinable with other offers. Handy reserves the right to alter or end this promotion at any time, including but not limited to any noted discount amounts.

Handy, through the Handy platform, offers information & a method to obtain the above services, but does not itself provide these services. The provision of these services is up to the independent professionals, scheduled through the Handy Platform.
handy.com ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcseJZkXaGdRcWLa8SGTMwMTwgoOqsD8c4LW4PJHfa5XvNhV91IOu7BoVwnt-2FvzqlT3hviWxTDZJDtK9iqkY6Hnhk-3D_s5UH8bhnBaopYjthcNSRcWeSn7lHsw58JxqACH1JpyxJ-2FID7BbcVzNgrXNuiColA-2FsnHj1vVcZHNSrWh1DDnycux-2BLyCTPtp8sntsWSee31Jy8KJNoO6qYQZ10d80h4h23YZHlcvRQv4TyXKBV9nvgN3TIHq2BAGCFlS7q6nik37C8gU2ExJ7G3uHVcOVb0RKy8TsyZNe4E85PR8YDqKb1704i32hLPSoP1oDF0VWGi0VgZY5MWHsA09TYxGzT39LpwXwKxo9-2BkY9duaBm-2B0wUWOusqBYycZkcbw-2BUaSVjaaOGtjHzYL133L3HIfLZWIUx5zoSrCE6ZKAemKndNtMpV-2B9LuDjPGvBcnfcdU41bebLqW3UlEoUkT2Ay245ElWAlx3fwylzVXgzMAQuEyqOA-3D-3D )
