### ISSUE TITLE
Switching from ui select to select input closes it

### ISSUE THREAD

**Issue by iuriikhrystiuk** [angular-ui/ui-select#1408]
Guys,

The problem could be seen on following plunker: http://plnkr.co/edit/Zv5uKfv5AiWYjc0gCWQw?p=preview

Steps are following: open ui-select. Do not select anything. Click to select control. It is opened and instantly closed. Some investigation in the sources showed, that there is a method, that tracks clicks on page and for some reason it does not include 'select' into its array of focusable items. 

The question is: can someone fix this issue? Because the workaround is quite complex.

**Comment by user378230** [comment]
I'm guessing https://github.com/angular-ui/ui-select/blob/master/src/uiSelectDirective.js#L154 is the line you are talking about.
> ```javascript
> var focusableControls = ['input','button','textarea'];
> ```

You could submit a PR to fix it.

**Comment by iuriikhrystiuk** [comment]
Ok, lemme work on it.

**Comment by iuriikhrystiuk** [comment]
Sorry for so many changes. This is the first time I am contributing into github project.
