### ISSUE TITLE
bower install fails on version 14.2 of angular-ui-select

### ISSUE THREAD

**Issue by gameboyzone** [angular-ui/ui-select#1412]
I have the following entry in bower.json under dependencies which fails -

"angular-ui-select": "~0.14.2"

Tried changing the version to 14.1 and then to 13.2 but all fail to install. Finally version 13.1 worked. Any idea what's the issue?

The version of bower installed is 1.7.7

**Comment by user378230** [comment]
I think PR #812 might be relevant here too...

**Comment by cmousset** [comment]
When I install versions 0.14.0 and upwards some unrelated controller karma test suddenly fails. 
Using 0.13.2 all tests pass. But unfortunately keyboard navigation is broken.
Command:
bower cache clean
bower install angular-ui-select#0.14.2 --save

**Comment by gameboyzone** [comment]
I realized my company has an internal Artifactory and hence 'bower install' was looking into the internal artifactory, not at Heroku's bower.io. Setting a proxy in Environmental variables resolved that issue for me.

@cmousset - That's a good suggestion too! Thanks.
