### ISSUE TITLE
ui-select requires a newer version of angular than is listed in bower

### ISSUE THREAD

**Issue by chrismarx** [angular-ui/ui-select#1415]
the bower.json for ui-select lists:

`"dependencies": {
    "angular": ">=1.2.18"
  },`

but on line 355-356, it calls $animate.on which wasn't added till 1.4:

`if (ctrl.$animate && ctrl.$animate.enabled(container[0])) {
        ctrl.$animate.on('enter', container[0], function (elem, phase) {`

Adding "&& ctrl.$animate.on" would fix this, or obvious upping to angular 1.4

Also, noticed this issue too, not sure if it's related - #1306

**Comment by aaronroberson** [comment]
Can you make a PR?

**Comment by jharting** [comment]
I sent a PR for this here: https://github.com/angular-ui/ui-select/pull/1456

**Comment by silentHoo** [comment]
Thank you @jharting :+1:
