### ISSUE TITLE
"most basic use of the directive" doesn't work

### ISSUE THREAD

**Issue by LordMidi** [angular-ui/ui-select#1417]
The binding of the most basic example doesn't work. At least the ng-model binding doesn't update as expected. The selection in the ui-select doesn't update the model.

see: https://github.com/angular-ui/ui-select/wiki/Getting-Started The most basic use of the directive in html ([plunker](http://plnkr.co/edit/K9alAMAzvUqCY7Or8RwY?p=preview))

This also happens in my project. The bound scope variable must be nested in an object on the scope to be updated as expected. (see: http://plnkr.co/edit/a3KlK8dKH3wwiiksDSn2?p=preview i.e. $.scope.**person.selected**)

Or am I getting something wrong here?

**Comment by user378230** [comment]
The plunkr and guide are incorrect, you need to use the nested model. See also: https://github.com/angular-ui/ui-select/issues/1353#issuecomment-175729671

___
_This is more a consequence of using ngModel than a ui-select issue, though the guide should really be updated._

**Comment by LordMidi** [comment]
I now found it also in the FAQ - https://github.com/angular-ui/ui-select/wiki/FAQs#ng-model-not-working-with-a-simple-variable-on-scope
