### ISSUE TITLE
Combine ui-select multiple with text input doesn't work

### ISSUE THREAD

**Issue by DavidHPalaxo** [angular-ui/ui-select#1421]
When i select something through ui-select, input fills ok, however when i type into input, ui-select is not selecting options properly.

http://plnkr.co/edit/FgPRChwWHlApFC5TeSQ6?p=preview

**Comment by user378230** [comment]
The input binds to a string, the multiple select is bound to an array. Update the plunkr to output selected in json format, you will see it is no longer an array after you edit the text in `<input>`

Change 
```html
<p>Selected: {{multipleDemo.selectedPeopleSimple}}</p>
```
To
```html
<pre>Selected: {{multipleDemo.selectedPeopleSimple | json}}</pre>
```

**Comment by wesleycho** [comment]
Closing as a support issue.
