### ISSUE TITLE
ISSUE: ui-choices combined with ng-click not passing repeated object

### ISSUE THREAD

**Issue by maxchernin** [angular-ui/ui-select#1426]
im trying to use this directive for a project, when i use ui-select-choices everything works well,
i also attached an ng-click attribute with a function on my controller.
on click the function is being executed - but the variable is not being passed.

can you advise?

                <ui-select-choices class="ui-select-choices"
                                   repeat="country in (hcNameLocation.generalContent.Address.Countries | filter: $select.search | orderBy: 'txt') track by country.val"
                                   ng-click="hcNameLocation.checkStates(country)">
                    <span>{{country.txt}}</span>
                    {{country.val}}
                </ui-select-choices>

-- checkstates is executed but country is passed undefined

**Comment by poonwu** [comment]
Probably you should use `on-select` event
https://github.com/angular-ui/ui-select/wiki/ui-select

not sure if this is what you intended to do.

**Comment by maxchernin** [comment]
exactly what i needed. missed it on the demos. thanks!

**Comment by wesleycho** [comment]
Closing as a support issue.
