### ISSUE TITLE
css is required alongside js

### ISSUE THREAD

**Issue by mastilver** [angular-ui/ui-select#1429]
this line: https://github.com/angular-ui/ui-select/blob/master/index.js#L1
is requiring css from a javascript file

you should use the `style` property instead so:
- it doesn't break when you try requiring the library
- you can use you own style-sheet if you want

Check out how bootstrap is doing it: https://github.com/twbs/bootstrap/blob/master/package.json#L20

**Comment by aaronroberson** [comment]
Great suggestion of the style element. Never seen that before, but will update. I removed the require from index.js in v0.14.3.

**Comment by mastilver** [comment]
Thank you!
