### ISSUE TITLE
Correct way to initialize with an option already selected?

### ISSUE THREAD

**Issue by andrewboni** [angular-ui/ui-select#143]
I'm trying to initialize a `ui-select` input field with a previously saved option. What's the right way to go about selecting the option in the form?

Right now I'm just doing an `ng-init` to populate and select a specific value. Thanks!

**Comment by MariDavila** [comment]
Wow. I've been searching for this answer for about two days. They key in my case was this:

"if you have a model bound to the select it will initialize with a value as long as the value in the model exists in the options for the select"

My initial value for my model WAS NOT one of the elements in the list, so initially there was no selected item. Thanks.

**Comment by awaisArachnys** [comment]
@MariDavila Doesn't this mean that you can't select anything else though? The initialized value will always be the selected value

**Comment by MariDavila** [comment]
@awaisArachnys Sorry I didn't answer before, just getting back from a trip.  Maybe I don't understand your question. With two way binding the way it works is that if the user selects something from the list, the model supporting the list will be set to the value. The selected value and the list of possible values comes from different places.
