### ISSUE TITLE
After selecting element in ui-select how to move focus to button on enter key?

### ISSUE THREAD

**Issue by amitdun** [angular-ui/ui-select#1437]
`<ui-select on-select="onSelected(this)" ng-model="availableList.selected" theme="bootstrap">
                        <ui-select-match placeholder="select or search in the list...">{{$select.selected}}</ui-select-match>
                        <ui-select-choices repeat="item in availableCmdList | filter: $select.search">
                            <span ng-bind-html="item | highlight: $select.search"></span>
                        </ui-select-choices>
                    </ui-select>`
every time I press enter key after selecting element from dropdown my ui-select has focus on itself.

**Comment by wesleycho** [comment]
Closing as a support issue.

It should be noted, after the user selects an element from the dropdown, ui select should have focus for accessibility reasons.
