### ISSUE TITLE
Multiple - allow custom template of selected items

### ISSUE THREAD

**Issue by kobiburnley** [angular-ui/ui-select#1438]
Allow full customization of selected items template, i.e not showing the "x" button...
I think it should look like this

```
 <ui-select multiple ..>
                <ui-select-match placeholder="Select items...">
                  <div ng-click="$item.unselect()">{{$item.name}}</div>
                </ui-select-match>
 </ui-select>
```

**Comment by user378230** [comment]
You can update the templates in the `$templateCache` (eg. https://github.com/angular-ui/ui-select/blob/master/src/bootstrap/match-multiple.tpl.html)

If you want to create a custom theme just for one instance of the ui-select control see my response in #1441

**Comment by user378230** [comment]
Assuming this is answered, closing.
