### ISSUE TITLE
Need use of CONTROL-KEY for  close or not close on every selection 

### ISSUE THREAD

**Issue by falinsin** [angular-ui/ui-select#1445]
In windows,  if you have a form multiselect option control you can push  the control-key for stick open the selection while you select elements from the list of options .

If you do not press the control-key , the list of option will close every option you select. 

Some angular components multiselections do this because they wrap a multiselect option control  but this angular ui-select do not respond to push the control-key and ignore it .

Please I am using this component and i need it behave this way standar in windows How can I do it? Any body could do it, Is there a way for alter the component?

This component have a directive called **close-on-select** can be setted to true or false but this is only  can be setted in the init of the component. and only for set one behavior or the other allways wihtout the use of the control-key for swtich.

Please we need to know if it is possible to add the control-key behavior or we need to change to other component.

Thanks in advance

**Comment by user378230** [comment]
You could modify ui-select to `$observe` the [close-on-select](https://github.com/angular-ui/ui-select/blob/master/src/uiSelectDirective.js#L40) attribute similar to how it is already done for some of the [other attributes](https://github.com/angular-ui/ui-select/blob/master/src/uiSelectDirective.js#L116):

```js
        attrs.$observe('taggingTokens', function() {
          if (attrs.tagging !== undefined) {
            var tokens = attrs.taggingTokens !== undefined ? attrs.taggingTokens.split('|') : [',','ENTER'];
            $select.taggingTokens = {isActivated: true, tokens: tokens };
          }
        });
```

You might be able to encapsulate this in another directive that does `require: uiSelect` and then reach the `$select`(/`uiSelectController`)

**Comment by falinsin** [comment]
thank you very much  for your help I'm going to try this idea

**Comment by falinsin** [comment]
I added the $observe in close-on-select. Now, if I change the value of close-on-select in the tag of the select it change the behavior, so far ok and is a step forward.

But the problem is that my client want the behavior like CHOSEN and all the native multiselect controls in Windows. That is, the list of selection stay open and you can  select multiples elements when you press the CONTROL KEY on KEYBOARD while you select elements in the list and if you select while you are not pressing CONTROL KEY the list close.

The problem know is that if I define an onkey control listener allways is asigned to an element en while a select an element to select it stop listenig.
Dont know how  the click while selecting an element can be linked with the fact that the control key is pressed for decide whether if the  close-on-select directive must be set true or false.

sorry but i think Im very close to the solution and I can't do it

Thank you very much for all your help si far.
