### ISSUE TITLE
how get the list of filtered elements for example, using a button

### ISSUE THREAD

**Issue by falinsin** [angular-ui/ui-select#1446]
I´m using this UI-SELECT as a multiple selection control.

In this control We know We can insert a string for filter the option list so the option list start filter and reduce this list of options  in order to match the string we insert.

This is very important because we use a lot of option in the list and is very convenient  for the users.

Teh question is:
But how can We get the entire filtered list of option and add all his options to the selection.

For example, we need to create a button and after we insert a string for filter and We get the list filtered then We Click on that button and select all the filtered option so We don´t need to select every filtered option one by one.

Is there an property in this angular select for get the filtered list?

Thanks in advance.

**Comment by user378230** [comment]
You can't access the filtered list from `ui-select`. You could manually apply your filter to your list of items and update your selected items array with the result. See angular docs: [Using filters in controllers, services, and directives](https://docs.angularjs.org/guide/filter)

**Comment by falinsin** [comment]
Thank you for your help. it is a good solution. 
Now my question is,  how could I get the string the user is inserting in the UI-SELECT search in order I can use for manually  filter the list and update my selected items?

Thanks again for your help

**Comment by user378230** [comment]
Hmm I didn't think of that! 

Maybe like #1445 you can create a directive to access `uiSelectController` and `$watch` `$select.$search`?

**Comment by falinsin** [comment]
I´ll try that way,   thank you
