### ISSUE TITLE
Unit tests it's not running in travis

### ISSUE THREAD

**Issue by viniciusdacal** [angular-ui/ui-select#1449]
It's easy to check it in any build log
https://travis-ci.org/angular-ui/ui-select/builds/110334334
![captura de tela 2016-02-19 as 14 29 24](https://cloud.githubusercontent.com/assets/2660570/13181656/409f7112-d715-11e5-9b23-56393f6e24eb.png)

**Comment by user378230** [comment]
They're running just not displayed in reported. (`karma-runner/karma/issues/1344`).
