### ISSUE TITLE
Using HTML5 data-* attributes breaks the multi-select and theme

### ISSUE THREAD

**Issue by migglu** [angular-ui/ui-select#1451]
I'm using a HTML5 validator, so I add data- in front of all of my attributes that are not standard HTML attributes. When I do this with the "multiple" attribute for ui-select, this causes uiSelectMatch directive to load an incorrect template.
I believe the error comes from here https://github.com/angular-ui/ui-select/blob/master/src/uiSelectMatchDirective.js#L12-L13 .

**Comment by user378230** [comment]
Related #1084
