### ISSUE TITLE
Undocumented dependency on Glyphicon

### ISSUE THREAD

**Issue by gberger** [angular-ui/ui-select#1452]
When using ` allow-clear="true"` on `ui-select-match`, a Glyphicon "remove" icon is used as the button to clear the selection.

This is not documented anywhere.

Ideally, users should be able to set their own template or class for the clear button.

**Comment by user378230** [comment]
I guess the dependency is implicit based on requiring bootstrap.

You can modify templates in the `$templateCache` or provide your own ([`bootstrap/match.tpl.html`](https://github.com/angular-ui/ui-select/blob/master/src/bootstrap/match.tpl.html) or [`bootstrap/match-multiple.tpl.html`](https://github.com/angular-ui/ui-select/blob/master/src/bootstrap/match-multiple.tpl.html) depending on which mode you are using)

**Comment by user378230** [comment]
Assuming this is answered based on the lack of a response. Closing.

**Comment by randdusing** [comment]
Specifying a property would be much more convenient than updating a template.

**Comment by user378230** [comment]
@randdusing feel free to submit a PR! 😃
