### ISSUE TITLE
Is there a way to select all the items in a multiple select?

### ISSUE THREAD

**Issue by ibbatta** [angular-ui/ui-select#1455]
I am trying to find a way to select all the options inside a select, but I can not. Is there an easy way to do that?
Sorry for the trouble, I am learning.

**Comment by user378230** [comment]
You could have a separate button which copies from your items array to your selected items array in your controller. (Outside of ui-select) 

For example from `availableColors` to`multipleDemo.colors` for this ui-select:

```html
<ui-select multiple ng-model="multipleDemo.colors">
    <ui-select-match placeholder="Select colors...">{{$item}}</ui-select-match>
    <ui-select-choices repeat="color in availableColors | filter:$select.search">
        {{color}}
    </ui-select-choices>
</ui-select>
```

**Comment by ibbatta** [comment]
@user378230 could you be more clear about your idea? Thanks

**Comment by ibbatta** [comment]
Ok resolved:

i've added the whole array to my ng-model. Thanks!

**Comment by meenakshijha** [comment]
@ibbatta How did you achieve this ? I want the user to select All / Unselect All option too.

Can you pls help? Thx
