### ISSUE TITLE
npm version

### ISSUE THREAD

**Issue by vmihailenco** [angular-ui/ui-select#1461]
Latest version in repo is https://github.com/angular-ui/ui-select/tree/v0.14.9, in changelog last version is v0.14.8, but npm has only v0.14.7.

**Comment by mastilver** [comment]
Yep same for 0.14.9

running `npm info ui-select` give me:

![image](https://cloud.githubusercontent.com/assets/4112409/13493421/f67c19b6-e135-11e5-9c4c-8331e9a4c7b9.png)

**Comment by user378230** [comment]
npm is up to date now https://www.npmjs.com/package/ui-select
