### ISSUE TITLE
Error when using ui-select-choices repeat without a filter

### ISSUE THREAD

**Issue by bogdanalexe90** [angular-ui/ui-select#1462]
Hi,
I receive an `$parse` error when using `<ui-select-choices repeat="item in itemList track by item.id">`
I managed to track down the problem and it seems to be the regex from `uisRepeatParser`.

The problem seems to be:
* `source: $parse(!match[3] ? match[5] : match[6]),`
* `match[3]` is `undefined`
* `match[5]` is `itemList track by item.id` 
* `$parse` throws the following error `Token 'track' is an unexpected token at column 17 of the expression [itemList track by item.id] starting at [track by item.id]`.

**Comment by user378230** [comment]
Fixed by #1477
