### ISSUE TITLE
Confusion on version numbers, bower & package

### ISSUE THREAD

**Issue by brandonjp** [angular-ui/ui-select#1465]
Sorry, if this is a dumb question, just trying to understand how things work and contribute if helpful... 

We were having the same issue as #1415 and trying to submit a PR, but got a little hung up on version number mismatch between `dist` js/css files and `bower.json` and `package.json`

where [`bower.json#L3`](https://github.com/angular-ui/ui-select/blob/3b1496cb73103c593ab54c1fd04f4d69bc7ed8f1/bower.json#L3) shows version at `0.13.2`
while [`dist/select.css#L4`](https://github.com/angular-ui/ui-select/blob/3b1496cb73103c593ab54c1fd04f4d69bc7ed8f1/dist/select.css#L4)  &  [`dist/select.js#L4`](https://github.com/angular-ui/ui-select/blob/3b1496cb73103c593ab54c1fd04f4d69bc7ed8f1/dist/select.js#L4) show version at `0.14.8`
and [`package.json#L10`](https://github.com/angular-ui/ui-select/blob/3b1496cb73103c593ab54c1fd04f4d69bc7ed8f1/package.json#L10) shows version at `0.14.9`

So...  

1. Should version numbers be matching across those?  (I've been looking at other projects, but can't quite determine what's most conventional)
2. Should the bower.json also be bumped in the gulp 'bump' task? 

Current state of our fork adds `bower.json` to `gulp bump` & also fixes #1415 : https://github.com/angular-ui/ui-select/compare/master...RideAmigosCorp:master  
Happy to create a PR, but was first just trying to understand 

Thanks

**Comment by silentHoo** [comment]
+1

**Comment by rafa-aguilar** [comment]
+1
