### ISSUE TITLE
Hide dropdown before search?

### ISSUE THREAD

**Issue by aske-cph** [angular-ui/ui-select#1466]
Hi, 

Is there a way to hide the dropdown before people enter anything?

I use the minimum-input-length attribute, but users gets confused by the dropdown and think they are the only options ( jeesh ). Therefore i want to hide the dropdown until the input minimum-input-length is reached.

I have tried:

` ng-show="$select.search.length > 1"`

On the ui-select-choices tag, but it gives me the error:

`Syntax Error: Token '$select' is an unexpected token at column 27 of the expression [$select.search.length > 1 $select.items.length > 0] starting at [$select.items.length > 0]`

**Comment by user378230** [comment]
Its probably trying to merge the value of the ng-show you added with the one that exists in the [choices.tpl.html](https://github.com/angular-ui/ui-select/blob/master/src/bootstrap/choices.tpl.html).

You could try hacking it by using `ng-show="$select.search.length > 1 &&"` I don't know for sure if that'd work.

Else you could modify/overwrite the [choices.tpl.html](https://github.com/angular-ui/ui-select/blob/3b1496cb73103c593ab54c1fd04f4d69bc7ed8f1/src/bootstrap/choices.tpl.html) in the `$templateCache`

**Comment by aske-cph** [comment]
Yes i think it was the template thing!

The easiest way to extend to my own behaviour was to copy the template from the select.js file, then modify this line in the template line:

from 

`ng-show=\"$select.items.length > 0\"
`
to

`ng-show=\"$select.search.length > 0\"
`
and then overwrite the template in my own applications run code block.
`
$templateCache.put("bootstrap/choices.tpl.html", "<ul class=\"ui-select-choices ui-select-choices-content ui-select-dropdown dropdown-menu\" role=\"listbox\" ng-show=\"$select.search.length > 0\"><li class=\"ui-select-choices-group\" id=\"ui-select-choices-{{ $select.generatedId }}\"><div class=\"divider\" ng-show=\"$select.isGrouped && $index > 0\"></div><div ng-show=\"$select.isGrouped\" class=\"ui-select-choices-group-label dropdown-header\" ng-bind=\"$group.name\"></div><div id=\"ui-select-choices-row-{{ $select.generatedId }}-{{$index}}\" class=\"ui-select-choices-row\" ng-class=\"{active: $select.isActive(this), disabled: $select.isDisabled(this)}\" role=\"option\"><a href=\"\" class=\"ui-select-choices-row-inner\"></a></div></li></ul>");`

**Comment by wesleycho** [comment]
Going to close in favor of the newly opened #1531 - that issue suggests a solution for this use case that would work well.
