### ISSUE TITLE
NoResult template

### ISSUE THREAD

**Issue by alfredopacino** [angular-ui/ui-select#1472]
Hi, in my select2 v4 (no angular.js) I had this setting:

```
domselector.select2(
...
escapeMarkup: function (markup) {
                return markup;
            },
            language: {
                noResults: function() {
                    return 'No results <a href="#">click</a>'
                }
            }
)
```

How can I set the noResult message in ui-select?

**Comment by performatric** [comment]
+1

**Comment by user378230** [comment]
Please search before creating new issues. 

https://github.com/angular-ui/ui-select/search?q=no+result&type=Issues

Many duplicates #831 #121 and some pull request #1011 #1028. There are probably many others if you search more, I just looked at the first page.

**Comment by alfredopacino** [comment]
Yes, I indeed searched for a solution without luck (all the issues looks unsolved)

**Comment by performatric** [comment]
And about me, I have searched so many problems (this, tagging without multiple in angular 1.5, ...), many tabs opened.. well... I was already tired of looking for solutions and I just saw this topic at the top, so I marked with "+1" sorry :) 

sorry my english too :(

**Comment by alfredopacino** [comment]
and about me,i'm just tired of this lack of productivity angular related..

**Comment by user378230** [comment]
As you can see from linked issues/pull requests there is no existing solution, but you can use code provided in pull requests or check issue comments for workarounds. Maybe they will help you :)
