### ISSUE TITLE
transclude is not a function 

### ISSUE THREAD

**Issue by dheerajkhokhar** [angular-ui/ui-select#1476]
ui-select breaks

![dropdown](https://cloud.githubusercontent.com/assets/6622096/13521419/575ee99c-e20e-11e5-9d36-3845042963e4.png)

Angularjs version used: angular.1.2.5.min.js

**Comment by user378230** [comment]
Which version of ui-select are you using? 

Can you make a reproduction plunkr? 

> (When creating github issues please always try and include as much information as possible)

**Comment by dheerajkhokhar** [comment]
Thanks you for the help... I solve this problem. Actually this error occurred because of 2 reason
1. conflict between 2 different js
2. duplicate data occured in ng-repeat.

Plunkr link : http://plnkr.co/edit/vhUCYaxKJ6A4oF4Tpchg?p=preview

**Comment by user378230** [comment]
Please close your issue if it was not a problem with ui-select

Thanks :smiley:
