### ISSUE TITLE
No CallBack found for UI-select on-close & on-open

### ISSUE THREAD

**Issue by jitendrathakur** [angular-ui/ui-select#1478]
I have to trigger a function on select of the item, I have written one custom callback but ui-selct being close on pressing "ESC" and other key buttons, It would be greate if you will create one call back for on-close and on-open.

**Comment by user378230** [comment]
There are already events for [open](https://github.com/angular-ui/ui-select/blob/0ddaad231994baac619556d0409167d10dc1595a/src/uiSelectController.js#L112) (`uis:activate`) and [close](https://github.com/angular-ui/ui-select/blob/0ddaad231994baac619556d0409167d10dc1595a/src/uiSelectController.js#L393) (`uis:close`)

**Comment by jitendrathakur** [comment]
Any example where i can use it on ctrl or directive on angularjs

**Comment by user378230** [comment]
They are standard angular events, take a look at the angular documentation or research on angular events. There is already information out there.

**Comment by jitendrathakur** [comment]
ui-select does not using $rootScope, Can you tell me how to use $on then?

**Comment by wesleycho** [comment]
You can use it wherever you have access to a $scope that is a child of ui select. One can write a custom directive and listen for this event in a child.

Closing as a usage issue.
