### ISSUE TITLE
Tooltip integration very hard for UI-select listed item

### ISSUE THREAD

**Issue by jitendrathakur** [angular-ui/ui-select#1479]
Tooltip integration very hard for UI-select listed item, I am trying to integrate foundation 5 tooltip, but plugin lazy loading not making way to load tooltip.

**Comment by user378230** [comment]
You need to provide more information, code and plunkr for example otherwise it will be impossible to help.

**Comment by jitendrathakur** [comment]
HTML

<ui-select-choices  >
                  <div class="row collapse"n>
                    <div class="columns small-9">{{test.name}}}</div>
                                   
                    <div class="columns small-3 has-tip" ata-tooltip data-options="hover_delay: 50;" " title="Tooltips are awesome, you should totally use them!">               

                      <div class="columns small-6">
                        <i class="type fa fa-bullseye"></i>
                      </div>
                      <div class="columns small-6">
                        <i class="type fa fa-ban "></i>
                      </div>
                    </div>                   
                  </div>
                </ui-select-choices>

JS
$(document).foundation('tooltip', 'reflow');
http://foundation.zurb.com/sites/docs/v/5.5.3/components/tooltips.html

Try this code.

**Comment by user378230** [comment]
The code you've provided is incomplete, I don't have time to make a plunkr/jsfiddle for you. 

Can you make one? The only thing I notice so far is that you have `ata-tooltip` and not `data-tooltip`. 

> _Unfortunately, no one here can do your work for you, so please try and make it as easy as possible for us to help you! Thanks! :smile:_
