### ISSUE TITLE
Dropdown should open UP instead of DOWN, when there is not enough space to render fully

### ISSUE THREAD

**Issue by slavinskas** [angular-ui/ui-select#148]
When there is not enough space for dropdown to render fully, it should be rendered to the top of the element, as it is default behaviour for select2.

**Comment by kedarbe** [comment]
+1

**Comment by seiyria** [comment]
+1 - I would enjoy being able to also force it to render upwards always, if possible.

**Comment by onemenny** [comment]
+1

**Comment by np82** [comment]
+1

**Comment by andywunderlich** [comment]
+1

**Comment by wald-tq** [comment]
+1

**Comment by FFelling** [comment]
This would definitely be nice to have.

This could also be a solution for the list falls behind overflow:hidden or overflow:auto containers #591.
"move drop down to base of <body> to stop it from being cut off (drop.js) #591"

**Comment by seiyria** [comment]
Might want to update the milestone here if this hasn't been addressed yet.

**Comment by fxck** [comment]
do want

**Comment by JeromeLam** [comment]
I've created a PR with code that adds an up direction depending on how much vertical space is left for rendering.  This works well for my local build.

Feel free to try it out on your own builds and upvote the PR if it works for you!

**Comment by gitnik** [comment]
:+1:

**Comment by cyrilf** [comment]
:+1: 

Just a simple question: As this issue is 9 months old, should I 

- wait hoping that you're going to fix/merge the PR soon 
- fork this repo (which I really don't want..)

?

Thanks!

**Comment by JeromeLam** [comment]
@cyrilf **brianfeister** self-assigned PR #836 about 10 days ago, so it may get merged soon.  Maybe you can leave a comment in the PR itself to generate more activity.

**Comment by cyrilf** [comment]
Merged! Thanks again @JeromeLam :wink:

**Comment by SerjoPepper** [comment]
@JeromeLam, hi
offsets calculated wrong when I have scroll on "body" element instead of "html"

offset.top + offset.height + offsetDropdown.height > $document[0].documentElement.scrollTop + $document[0].documentElement.clientHeight

should be replaced with

offset.top + offset.height + offsetDropdown.height > $document[0].documentElement.scrollTop + $document[0].body.scrollTop + $document[0].documentElement.clientHeight

**Comment by rachellej** [comment]
Same issue as @SerjoPepper -- and btw thanks for commenting the issue

**Comment by kwantopia** [comment]
Looks like if you use ui-select inside directives, on Chrome browsers the dropdown always goes up instead of dropping down.

**Comment by JoshSGman** [comment]
@kwantopia I'm having the same issue

**Comment by danduh** [comment]
Is there any option/setting to disable this feature?

**Comment by ManuelPutallaz** [comment]
same question than  @danduh : Is there any option/setting to disable this feature?

**Comment by greenwebdev** [comment]
Seeing the same issue as @kwantopia in Chrome, doing my head in. Any suggested fix?

**Comment by hyrumwhite** [comment]
Would love the ability to force it to always open down. Currently it's opening up no matter what I do.

**Comment by vladferix** [comment]
@hyrumwhite +1

**Comment by oshai** [comment]
@hyrumwhite +1

**Comment by BunsenMcDubbs** [comment]
@hyrumwhite +1

**Comment by calwi** [comment]
Same issue here, inside a modal, it always opens up and goes slightly out of the window. Would like to force 'direction-down'.

**Comment by sdir456** [comment]
+1

**Comment by pgeez** [comment]
with @calwi , please add the ability to force 'direction-down'

**Comment by anonomis** [comment]
@hyrumwhite +1

**Comment by tandrianoff** [comment]
with @hyrumwhite and @calwi  and @pgeez I also want to force either direction-down or direction-up.

**Comment by jraguilo** [comment]
I also really need the option to force "direction-down".

**Comment by dimirc** [comment]
Related to https://github.com/angular-ui/ui-select/pull/1212

**Comment by alexpeattie** [comment]
Just for anyone who found this issue looking for a way to force dropdowns to go down, this is now possible with #1213 :relaxed: - you just need to add `position='down'` to your `<ui-select-choices>` or globally:

~~~js
yourApp.config(function(uiSelectConfig) {
  uiSelectConfig.dropdownPosition = 'down';
})
~~~

**Comment by sbedulin** [comment]
@alexpeattie :+1: thanks

**Comment by ArulselviArangasamy** [comment]
select2 dropdown position want to down only display
