### ISSUE TITLE
tagging-label="false" causes tagging-token to remain in item

### ISSUE THREAD

**Issue by thielmal** [angular-ui/ui-select#1482]
See [this Plunkr](http://plnkr.co/edit/RGVcfSp1APd6nr43sgxv?p=preview).

If you enter some string followed by a ",", the "," remains in the item, alltough it should be stripped automatically. The problem is caused by [this line](https://github.com/angular-ui/ui-select/blob/9230b43d32662518d9eedf729aad5bb8561dc2d8/src/uiSelectController.js#L329), where "item", which already has the "," stripped is overwritten with "ctrl.search", which still contains the ",".

Workaround for now is to implement a tagging function that manually splits of the ",".

I don't really know how to go about a PR here, because I am not sure about the other cases in which this branch will be executed. Any Ideas?

**Comment by Jefiozie** [comment]
@thielmal , I came across this issue and I found out that it has already being fixed ( I believe). Could you verify this?

**Comment by user378230** [comment]
Assuming resolved based on above comment and lack of plunkr. 

Closing.
