### ISSUE TITLE
UI Select not showing up the selected element in dropdown (IE 11)

### ISSUE THREAD

**Issue by sumodhnair19** [angular-ui/ui-select#1485]
Hi,

I am having issue with the dropdown populated using UI select not able to show the element which had been selected earlier. This issue is only coming in IE11, I tried checking the same with the demo of UI select and unfortunately it has the same issue too.
Below is the screenshot of the issue in IE11 , I had selected "natasha" from dropdownlist and once I try to open it back again it would not show the same in dropdownlist as highlighted.
![issue_ui_select](https://cloud.githubusercontent.com/assets/6638580/13659856/1b53730e-e6ab-11e5-8205-86bf0b30aa10.PNG)

This is the same issue I am facing in my project, please let me know if there is any solution for the same. Thanks :)

**Comment by Jefiozie** [comment]
Hi @sumodhnair19,

So I had a look if I can reproduce this issue but unfortunately I cannot.
Here is a demo maybe you can check if it is already solved or if I have a wrong version. 
Demo: http://plnkr.co/n9ZlgzUcLIfSKQMx13YB

![image](https://cloud.githubusercontent.com/assets/17835373/16276386/65252e46-38ae-11e6-8e5f-9cc7b76f3304.png)

**Comment by Jefiozie** [comment]
@sumodhnair19  Any feedback or is this issue closed?

**Comment by sumodhnair19** [comment]
@Jefiozie  I had a change in requirement in the project I was working on so I didn't give much emphasis on it. As I can check in the demos I am not able to reproduce the issue now. It is fixed now. Thanks

**Comment by mostafaasad** [comment]
what was the resolution, could you please explain?
