### ISSUE TITLE
Dynamic classes for multi selection

### ISSUE THREAD

**Issue by davideanderson** [angular-ui/ui-select#1491]
I want to be able to style the selected options differently, base on the selection.

I tried this:

 ```
<ui-select-match ng-class="{'pending-selection': $item.pending}">{{$item.name}}</ui-select-match>
```

And even tried this:

```
<ui-select-match pending-selection="{{$item.pending}}">{{$item.name}}</ui-select-match>
```

However, it appears that '$item' is not in scope for the span.ui-select-match tag (where the ng-class/pending-selection get inserted into the template), as the ng-repeat is created inside that tag.

I am converting from using the original jQuery Select2 implementation, and I am able to do the dynamic classes because I can attach a class to each 'option', but I haven't been able to figure out how to do the same thing with to angular-ui-select.

**Comment by user378230** [comment]
Have you tried placing it **_inside_** `ui-select-match`?

eg.
```html
<ui-select-match>
    <span ng-class="{'pending-selection': $item.pending}">{{$item.name}}</span>
</ui-select-match>

```

**Comment by user378230** [comment]
Assuming answered, closing.

**Comment by davideanderson** [comment]
Sorry.  No, it was not answered.  Doing a span inside like that only changes the style of the writing on the 'button', not of the button itself.

**Comment by user378230** [comment]
You probably need to customise the [match-multiple.tpl.html](https://github.com/angular-ui/ui-select/blob/master/src/bootstrap/match-multiple.tpl.html) template then.

**Comment by user378230** [comment]
Assuming answered, closing.
