### ISSUE TITLE
When an Option is selected in Controller li Option UI in dropdown list is not highlighted accordingly

### ISSUE THREAD

**Issue by Pavan1889** [angular-ui/ui-select#1493]
$scope.person = {};
  $scope.people = [
    { name: 'Adam',      email: 'adam@email.com',      age: 12, country: 'United States' },
    { name: 'Amalie',    email: 'amalie@email.com',    age: 12, country: 'Argentina' },
    { name: 'Estefanía', email: 'estefania@email.com', age: 21, country: 'Argentina' },
    { name: 'Adrian',    email: 'adrian@email.com',    age: 21, country: 'Ecuador' },
    { name: 'Wladimir',  email: 'wladimir@email.com',  age: 30, country: 'Ecuador' },
    { name: 'Samantha',  email: 'samantha@email.com',  age: 30, country: 'United States' },
    { name: 'Nicole',    email: 'nicole@email.com',    age: 43, country: 'Colombia' },
    { name: 'Natasha',   email: 'natasha@email.com',   age: 54, country: 'Ecuador' },
    { name: 'Michael',   email: 'michael@email.com',   age: 15, country: 'Colombia' },
    { name: 'Nicolás',   email: 'nicolas@email.com',    age: 43, country: 'Colombia' }
  ];

// here im selecting the option, it is being selected in dropdown
  $scope.person.selected = { name: 'Samantha',  email: 'samantha@email.com',  age: 30, country: 'United States' };

// BUT the problem is UI for that option is not highlighted ( i.e class "select2-highlighted" is not being applied to that li)

**Comment by deeg** [comment]
Please post a plunkr reproducing the issue so we can look into fixing it for you.
