### ISSUE TITLE
Can't select elements with click when when using `tagging`

### ISSUE THREAD

**Issue by BrentWheeldon** [angular-ui/ui-select#1496]
I am having the same issue as https://github.com/angular-ui/ui-select/issues/1357 using 0.16.0 (from bower).

I see that this was fixed in https://github.com/angular-ui/ui-select/pull/1439, but I can't find that commit either in the 0.16.0 tag, nor master. Am I missing something?

**Comment by wesleycho** [comment]
This does seem missing - not sure what happened to it - @aaronroberson any idea why it's not appear in the history in `master`?

**Comment by aaronroberson** [comment]
That's odd, I'll look into it later today once I get the chance!

**Comment by Vnthf** [comment]
I have a same problem

**Comment by issamm** [comment]
Hi, the issue 1439 seems to be still present : tried with v1.6.1.

A handler function is missing ('keyup' event) inside the uiSelectSingle directive.
=> It has been included on the attached file, and it seems to work correctly.
Pull request coming soon...
[select.js.txt](https://github.com/angular-ui/ui-select/files/210357/select.js.txt)

**Comment by user378230** [comment]
@issamm your PR might already be covered by #972

**Comment by issamm** [comment]
This is what I was going to say, lol. Thank you.
We did almost the same modification (but his commit is cleaner ;) ).

**Comment by hagayl** [comment]
I'm facing this issue as well, doesn't seem to be fixed yet (v1.6.1).
It's caused by setting the tagging-label to false (`tagging-label="false"`).
A workaround for the meantime can be setting it to an empty string instead: `tagging-label=""`

**Comment by gamebox** [comment]
Thanks for that easy quickfix @hagayl

**Comment by jspizziri** [comment]
Thanks @hagayl!

**Comment by stefanmeschke** [comment]
If you leave tagging-label blank it isn't possible to add anything which is not in the list of items. I need the ui-select for selecting an item or add a new item.

**Comment by aaronroberson** [comment]
Can someone create a new PR please?
