### ISSUE TITLE
Fix changelog, bower.json, and release process

### ISSUE THREAD

**Issue by deeg** [angular-ui/ui-select#1497]
- [x] Changelog should be generated for latest releases.
- [x] Dist files files should have correct version number at top.
- [x] bower.json file should have correct bower package name. (angular-ui-select instead of ui-select)
- [x] remove version from bower.json file as it is not needed
- [x] stop /dist files and changelog from showing in everyone's PRs by modifying build process

**Comment by Jefiozie** [comment]
HI @deeg , would like to help me on this? Maybe explain a little bit more? I can do the work but missing some knowledge about the build process.

**Comment by deeg** [comment]
I'm not sure if things have changed since I have created this issue.

You could probably close it unless you know anything in the list still needs to be done. Sorry I don't have the time to look into it more.

**Comment by Jefiozie** [comment]
@deeg , thanks for the feedback double checked and all things are done.
