### ISSUE TITLE
<div ui-select-choices...> broken in angular v1.5.0

### ISSUE THREAD

**Issue by tangfang** [angular-ui/ui-select#1499]
In the 1.5.0 version of angular
`<div ui-select-choices......></div>` is not supported.
must use `<ui-select-choices......></ui-select-choices>`

**Comment by user378230** [comment]
Which version of ui-select are you using?

**Comment by tangfang** [comment]
@user378230 0.15.0 version of ui-select

**Comment by tangfang** [comment]
http://stackoverflow.com/questions/34805257/angular-compile-in-link-function-gives-an-error-rangeerror-maximum-call-stack#

**Comment by wesleycho** [comment]
This sounds like it might be a duplicate of the double compile problem.

**Comment by user378230** [comment]
Closing as resolved by #1555 as per https://github.com/angular-ui/ui-select/issues/1580#issuecomment-215276541
