### ISSUE TITLE
refresh closes dropdown

### ISSUE THREAD

**Issue by remmeier** [angular-ui/ui-select#1511]
Not yet sure where to look for the problem, but when I use 

` <ui-select-choices  refresh="refreshElements($select.search)"  repeat="item in elements">
        <span>{{::(item | formatItem)}}</span>
  </ui-select-choices>`

whereas refreshElements updates the elements array based on the provided $select.search (using a remote rest call).

Every time some search string is entered and $select.search changes, refreshElements gets properly called. But after the call completes and updates the elements array, the dropdown disappears instead of showing the refined search. My entered search string gets cleared. After that refresh is called again with an empty String to search.

I checked the source code a bit, but e.g. ctrl.close() is never called. Nevertheless, the drop down disppaears and it seems that ctrl.open is set to false. Any pointers where to look for the problems would be appreciated as I was unable to find any recent example/documentation of the feature.

**Comment by wesleycho** [comment]
Can you post a reproduction in Plunker?
