### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by wiibaa** [angular-ui/ui-select#1512]
Hello,

a few question about the recent versions:

* 0.14.10 is mentioned in the changelog but not tagged so nonexistent for bower
* the latest tag is 0.**16**.0 but the changelog mention 0.**15**.0, so can I point my bower.json to 0.16.0 or should wait for the proper 0.15 tag ?

Thanks you

**Comment by user378230** [comment]
Use the latest version._v0.16.0_ at time of writing. 

Not sure why we skipped ahead to v0.16.0 but there was probably a reason.
