### ISSUE TITLE
Unneeded empty drop-down in Angular 1.5.2 and ui-select 0.15.0 (0.16.0) 

### ISSUE THREAD

**Issue by pkuklin** [angular-ui/ui-select#1520]
Bug description: when click on ui-select empty drop-down appears.
http://joxi.ru/KAg8LRXsg3v74r

0.14.9 version does not have such an issue, you can check it here: 
http://plnkr.co/edit/QdEP2MAj351bGNoHNZ03?p=preview

**Comment by user378230** [comment]
https://github.com/angular-ui/ui-select/commit/e65995f1eb2e190e71c9226a2f754671a7277c86 looks guilty.

**Comment by boillodmanuel** [comment]
fixed by PR #1598 (packaged in 0.17.1)

**Comment by user378230** [comment]
Thanks for the confirmation! 

Closed.
