### ISSUE TITLE
Confusion in bower and package versions

### ISSUE THREAD

**Issue by rafa-aguilar** [angular-ui/ui-select#1521]
Hi,

The bower version and the package version are different:

**Bower: "version": "0.14.1"
Package: "version": "0.16.1"**

bower angular-ui-select#*     mismatch Version declared in the json (0.14.1) is different than the resolved one (0.16.1)

This is an error? If not, why have this difference?

Thanks for this amazing plugin!

**Comment by IvanCoronado** [comment]
:+1:

**Comment by LeleDev** [comment]
+1

**Comment by wesleycho** [comment]
Bower uses tags to determine the version currently, and from what I understand, that is not likely to change.

Either the value should be removed from bower.json, or the number needs to be kept up to date with the releases.

**Comment by user378230** [comment]
@aaronroberson can you look at this for the next release?

**Comment by aaronroberson** [comment]
Since our gulp task updates bower I will go ahead and bump the bower version up and keep them in sync from here on out. Is that ok with you as well @deeg?

**Comment by deeg** [comment]
@aaronroberson, yeah that sounds good. I think you could also just remove the version property if you didn't want to keep it up to date. I don't think it matters either way.
