### ISSUE TITLE
track by $index broken with angular 1.5

### ISSUE THREAD

**Issue by gorghoa** [angular-ui/ui-select#1522]
### Bug description:

When using `track by $index` for the `repeat` attribute, with angular < 1.5, ui-select used to generate an id of the form

```
<div id="ui-select-choices-row-0-2" …>
```

Now, with angular 1.5(.2) we get :

```
<div id="ui-select-choices-row-0-" …>
```

The last digit is missing. It should be replace by the value of `$index`, but `$index is undefined`. 

### I’ve written a test for the issue :

gorghoa/ui-select@d627eef45755d7ac0e4c81a231989f576d0512c8

The test is ok with angular 1.4.10, broken with 1.5

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5.2

Let me know if I can do more.
thanks!

**Comment by wesleycho** [comment]
Cross-linking #1525 - they are identical, although I add a Plunker reproduction. I noticed this in my work app, and it caused some QA automation to fail.

**Comment by user378230** [comment]
From #1525 
> ### Bug description:
> 
> When using the regular `repeat` attribute in `ui-select-choices` with ng-repeat syntax, the `id` attribute repeats `ui-select-choices-row-0-`, leading to selector issues. Note that this does not occur when the optgroup feature is used.
> 
> ### Link to minimally-working plunker that reproduces the issue:
> 
> Type `New York` into the input and inspect the `id` attributes of the repeated elements at any point where there are 2+ results in the dropdown.
> 
> http://plnkr.co/edit/yp78QItKCbZPlcorihtW?p=preview
> 
> ### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS
> 
> Angular: 1.5.2
> 
> UI-Select: 0.16.0
> 
> Bootstrap/Select2/Selectize CSS (if applicable): N/A
> 
---
From editing the plunkr it looks like using `ng-attr-id` would fix it, don't know if that would break anything else, though I doubt it would.

**Comment by user378230** [comment]
So the change works but annoyingly the test only works in isolation (`iit(...)`) and not when run as part of the entire suite. :angry:
