### ISSUE TITLE
Demo/Examples linked to in README is out of date

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/ui-select#1524]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

See title :) - the demo Plunkers are using Angular 1.2, pretty old version.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/a3KlK8dKH3wwiiksDSn2?p=preview
http://plnkr.co/edit/juqoNOt1z1Gb349XabQ2?p=preview
https://github.com/angular-ui/ui-select/tree/master/examples

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

N/A

**Comment by user378230** [comment]
I've added a new wiki page: 
>#### [6. Accessing `$select`](https://github.com/angular-ui/ui-select/wiki/Accessing-%24select) 

Which might be useful for some, probably still needs a little work but it might help reduce some of the minor feature requests we get.

**Comment by user378230** [comment]
Resolved by #1558, the project description should probably be updated with a link the gh-pages site.
