### ISSUE TITLE
Duplicate of the same id in choices

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/ui-select#1525]
### Bug description:

When using the regular `repeat` attribute in `ui-select-choices` with ng-repeat syntax, the `id` attribute repeats `ui-select-choices-row-0-`, leading to selector issues. Note that this does not occur when the optgroup feature is used.

### Link to minimally-working plunker that reproduces the issue:

Type `New York` into the input and inspect the `id` attributes of the repeated elements at any point where there are 2+ results in the dropdown.

http://plnkr.co/edit/yp78QItKCbZPlcorihtW?p=preview

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5.2

UI-Select: 0.16.0

Bootstrap/Select2/Selectize CSS (if applicable): N/A

**Comment by user378230** [comment]
Quoted in #1522 so going to close this.
