### ISSUE TITLE
Accept HTML in placeholder

### ISSUE THREAD

**Issue by dimirc** [angular-ui/ui-select#154]

**Comment by kimardenmiller** [comment]
:+1:

**Comment by pihomeserver** [comment]
+1

**Comment by styopdev** [comment]
+1

**Comment by Jefiozie** [comment]
Closing it down as it is a old issue. Please create new issue if this is still a bug/ problem.
Also i'm trying to get a good overview of recent bugs.

Thanks for understanding.
