### ISSUE TITLE
Memory Leak when removing ui-select nodes

### ISSUE THREAD

**Issue by edieval** [angular-ui/ui-select#1545]
Angular: 1.4.9
UI-Select: 0.16.1
Bootstrap : 3.3.5

When i remove a ui-select element from DOM, it seems to be a memory leak (see with chrome timeline after some Garbage Collect during test).

 [Plunker](http://plnkr.co/edit/vObW6cAzRuRbgEnA8ph7?p=preview)

![capture d ecran de 2016-03-31 17-48-49](https://cloud.githubusercontent.com/assets/15011703/14181808/ea07f4cc-f768-11e5-927e-c1c0edf1ab48.png)

**Comment by wesleycho** [comment]
This is relevant: https://github.com/angular-ui/ui-select/pull/1538 - I think this is fixed now in `master`, can you try current `master` by building it manually and seeing if it fixes your problem?

**Comment by edieval** [comment]
I've update my [plunker](http://plnkr.co/edit/vObW6cAzRuRbgEnA8ph7?p=preview) with current master and it's solved on JS Heap but not on Nodes.

![capture2](https://cloud.githubusercontent.com/assets/15011703/14202107/7a538d1a-f7f6-11e5-9ac3-d6437f6571e1.jpg)

**Comment by edieval** [comment]
Ok, i did a mistake in my clean function.
Now the memory leak is solved with the current master build !
![capture3](https://cloud.githubusercontent.com/assets/15011703/14203046/e83ae670-f7fb-11e5-9a00-0f611f02c49b.jpg)

Thanks wesleycho
