### ISSUE TITLE
Items in list are not set to active when hovering

### ISSUE THREAD

**Issue by KelseySheely** [angular-ui/ui-select#1548]
### Bug description:
Items in list are not set to active when hovering. It seems that the setActiveItem method is not being defined.  It is being set on ng-mouseenter on lines 227 and 235, but the method seems to have been removed.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/fU663cxG6KB5G9kcIJpJ

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS
Angular: 1.2.18

UI-Select: 0.16.1

Bootstrap: 3.1.1

**Comment by user378230** [comment]
These have actually been removed since (#1523 - you can follow the history/context back through there)

Closing.

**Comment by fiznool** [comment]
Is there any workaround to restore the previous behaviour? This is preventing me from upgrading to the latest version of the library.
