### ISSUE TITLE
Outdated Meteor package

### ISSUE THREAD

**Issue by xMisax** [angular-ui/ui-select#1549]
Please update from 0.12  to 0.16.1 in meteor package...;/

Please...

**Comment by wesleycho** [comment]
I'm not sure who maintains the Meteor package.

I can't say I support publishing to any other package manager other than npm and maybe non-intrusive ones that don't involve constant updating like bower (although bower is on its way out long term also) though.

**Comment by user378230** [comment]
Agreed, unless the publish can be automated in some way, npm and bower are probably going to be enough.

Going to close, as its not actually an issue since this project doesn't appear to own the meteor package. You are welcome to submit a PR, automating the Meteor publish (if its possible to do).
