### ISSUE TITLE
new options not working

### ISSUE THREAD

**Issue by yanivlllev** [angular-ui/ui-select#1552]
I'm having difficulties in implementing the new options for ui-select (ui select no choice / ui select header and footer) - i don't see any changes in the behavior and in the view... except weird lines (attaching a screenshot)

![screen](https://cloud.githubusercontent.com/assets/12447235/14255844/ced94c9e-fa9e-11e5-903c-19003a1b11f4.jpg)

i also tried to use your existing plunker here with the updated js and css CDN files - it's not working there as well.
am i missing something?

This is my ui-select html:
 ```
<ui-select ng-model="project" tagging-label="false" tagging="projectTagTransform" 
     on-select="uiselectProject($item,$model)" required="required" select-tag-on-blur>
    
    <ui-select-match placeholder="Choose existing or create new">
        <div ng-bind-html="$select.selected.name | highlight: $select.search"></div>
    </ui-select-match>

    <ui-select-header>
        Top of the list!
    </ui-select-header>

    <ui-select-choices repeat="project in projects | filter: {name: $select.search} ">
        <div ng-bind-html="project.name  | highlight: $select.search"></div>
    </ui-select-choices>

    <ui-select-no-choice>
        This is my no choice!
    </ui-select-no-choice>

</ui-select>
```

version: 
angular: `"version": "1.4.9"`
ui-select: `"version": "0.16.1"`

**Comment by user378230** [comment]
Neither feature is available in v0.16.1 please see CHANGELOG.md for latest changes.

ui-select-no-choice: #1011 merged into master not yet released
ui-select-header/footer: #1323 not yet accepted/merged
