### ISSUE TITLE
Multiselect: Select & Delete multiple items at once

### ISSUE THREAD

**Issue by dimirc** [angular-ui/ui-select#156]
Depends on https://github.com/angular-ui/ui-select/pull/138

Select & Delete multiple items at once — Hold down option on Mac or ctrl on Windows to select more than one item to delete.

Reference:
http://brianreavis.github.io/selectize.js/

**Comment by Jefiozie** [comment]
Closing this one down as there is not a response for a long time. If needed reopen please. :smile:
