### ISSUE TITLE
Splitting on Paste only supports first token

### ISSUE THREAD

**Issue by logannc** [angular-ui/ui-select#1566]
### Bug description:
Splitting on pasted data only supports splitting on the first token.

### Link to minimally-working plunker that reproduces the issue:
[literally any working tagging ui-select instance - see select.js ln 826]

UI-Select: 0.16.1

This isn't a bug in that the code is doing something unexpected, so much as it is unexpected that the code would be written this way. An improvement would be to iterate over splitting tokens and split on the first token that exists in the string.

**Comment by logannc** [comment]
For example,

```
for (let token of ctrl.taggingTokens.tokens) {
    var separator = KEY.toSeparator(token) || token;
    var items = data.split(separator);
    if (items && items.length > 1) {
        var oldsearch = ctrl.search;
        angular.forEach(items, function (item) {
              var newItem = ctrl.tagging.fct ? ctrl.tagging.fct(item) : item;
              if (newItem) {
                  ctrl.select(newItem, true);
              }
          });
          ctrl.search = oldsearch || EMPTY_SEARCH;
          e.preventDefault();
          e.stopPropagation();
          break; // only split by one token
      }
}
```

**Comment by user378230** [comment]
Can you submit a PR for this (with relevant tests)? (Assuming you weren't going to already :smile:)

**Comment by logannc** [comment]
Is the ES6 `for (let .. of ..)` syntax allowed?
