### ISSUE TITLE
Failed to load template - selectize/select-multiple.tpl.html

### ISSUE THREAD

**Issue by ashubabu** [angular-ui/ui-select#1569]
I am trying to use ui-select element with _selectize_ theme and multiple attribute. However, I keep getting the error in loading **selectize/select-multiple.tpl.html**. I had a look at the _select.js_ file in the _dist_ folder here - [https://github.com/angular-ui/ui-select/tree/master/dist](url) and I cannot see the template for select-multiple.tpl.html supported under  _selectize_ theme (**$templateCache.put** only contains _selectize/select.tpl.html_) . 
Is multiple-select not supported under _selectize_ theme yet?

**Comment by user378230** [comment]
It is not. Feel free to submit a PR to add support! :smile:

Closing as duplicate of #295

**Comment by amit-natani** [comment]
Which theme is suitable for multi select?

**Comment by user378230** [comment]
@amit-natani bootstrap or select2
