### ISSUE TITLE
README should use npm install ui-select

### ISSUE THREAD

**Issue by anthonygarvan** [angular-ui/ui-select#1574]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
If you follow the readme, running `npm install angular-ui-select`, you get some older, unmaintained npm repo which is not compatible with angular 1.5+. Most newcomers will naively run `npm install angular && npm install angular-sanitize && npm install angular-ui-select`, which results in version incompatibilities.

### Link to minimally-working plunker that reproduces the issue:
[plunkr](http://plnkr.co/edit/K9alAMAzvUqCY7Or8RwY?p=preview)

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS
Running naive install with npm gives:
Angular: 1.5.5

UI-Select: 0.12.1

Bootstrap/Select2/Selectize CSS (if applicable): N/A

**Comment by user378230** [comment]
Whoops, I must have copied the bower one when I updated the README, can you submit a PR?
