### ISSUE TITLE
Clear button jump to new line

### ISSUE THREAD

**Issue by maxbundchen** [angular-ui/ui-select#1576]
When the selected text is bigger than the select element the clear button jump to a new line. In the original Select2 the text get truncated with ellipsis before the clear button. Is possible duplicate this feature? It's looks like a css adjust.

**Comment by user378230** [comment]
Can you please update your post to follow the [**issue template**](https://github.com/angular-ui/ui-select/blob/master/.github/ISSUE_TEMPLATE.md) and provide the version numbers and a demo plunkr?

This will make it easier for anyone who wants to submit a PR fix. 

If you know a fix, please feel free to open a PR yourself, thanks!

**Comment by maxbundchen** [comment]
Here is the [plunkr](https://plnkr.co/edit/H87bI8nPfagKyjguT9qP?p=preview).

As you can see the long names should be truncated (ellipsis is a good option as used in the original select and select2 jquery components). Also the clear button is in the wrong place. I'm trying solve this with css but at the moment I couldn't find any solution.

bootstrap: 3.3.6
ui-select: 0.16.1
angular: 1.5.3

**Comment by user378230** [comment]
There was a previous attempt #1337 but it pushed the clear button to a new line, maybe it will help you start.
