### ISSUE TITLE
Select 2 with Bootstrap demo bug

### ISSUE THREAD

**Issue by ejbaker** [angular-ui/ui-select#1577]
### Bug description:
Using [the select 2 with Bootstrap link found here](http://angular-ui.github.io/ui-select/#examples), you will find that the "multiple" option does not actually _appear_ to work. Selecting options there results in skinny little buttons with no text content, and seemingly blanks out the "Selected" text at the top of the page.

The problem is that everything else on the page is a single select, and that all of the displays expect it to also be singular. So, "ctrl.person.selected.name" is used, but selected does not have a "name" property, because "selected" has become an array of objects rather than a single object.

### Link to minimally-working plunker that reproduces the issue:
[Plunker link](http://plnkr.co/edit/KmUbr6UWnGR7u763slfk?p=preview) (This is just a copy of the demo plurk for select2.)

**Comment by user378230** [comment]
This could be resolved by switching it to one of the multiple demo's data, for example:
```html
<ui-select multiple sortable="true" ng-model="ctrl.multipleDemo.selectedPeople" theme="select2" class="form-control" title="Choose a person">
  <ui-select-match placeholder="Select or search a person in the list...">{{$item.name}}</ui-select-match>
          
```

If you wanted to submit a PR fix the relevant file is: [`demo-select2-with-bootstrap.html`](https://github.com/angular-ui/ui-select/blob/b7f2afe39e9a112eb54dad448f62af38c7bf7b74/docs/examples/demo-select2-with-bootstrap.html)

**Comment by ejbaker** [comment]
Ahhh, thanks. [Done!](https://github.com/angular-ui/ui-select/pull/1578) (Though my method for displaying the multiple select may not be the most efficient.)
