### ISSUE TITLE
can we have new release with no-choice?

### ISSUE THREAD

**Issue by IvanCoronado** [angular-ui/ui-select#1579]
You have a cool feature in master [ui-select-no-choice](https://github.com/angular-ui/ui-select/blob/master/src/uiSelectNoChoiceDirective.js), can we have a new release with this feature?

**Comment by Grade** [comment]
+1

**Comment by siva-I** [comment]
Also ui-select-no-choice is working only with bootstrap theme. Can we include the same for selectize and select2 themes?

**Comment by siva-I** [comment]
@khanhto
Could you please advise if this feature can be expanded to selectize and select2 themes?

**Comment by user378230** [comment]
This should have been released as part of v0.17.0 but I believe the npm version was still outdated. 

This should be released as of v0.17.1

**Comment by santosguilherme** [comment]
Worked for anyone? here is still not showing anything.

**Comment by Grade** [comment]
Working for me. Try to download new release v0.17.1

**Comment by santosguilherme** [comment]
I have already downloaded this version, the directive "uiSelectNoChoice" is in file "dist/select.js", but when the search returns no results, it does not appear.

`<ui-select ng-model="elementExtensions.ator" theme="bootstrap" fix-focus-ui-select>
    <ui-select-match allow-clear="true" placeholder="{{::'TYPE_FOR_SEARCH' | translate}}">
      {{$select.selected.name}}
    </ui-select-match>
    <ui-select-choices refresh="loadAsyncActors($select.search)" refresh-delay="300"
                       repeat="actor in actorPropertyViewControl.availableActors">
      <div ng-bind-html="actor.name | highlight: $select.search"></div>
    </ui-select-choices>
    <ui-select-no-choice>
      Dang! We couldn't find any choices...
    </ui-select-no-choice>
  </ui-select>`

**Comment by santosguilherme** [comment]
Doesn't work with ui-select add no-choice, [plunker link](http://plnkr.co/edit/T2HsEvQW1fBQJz3hg2dh?p=preview).

**Comment by santosguilherme** [comment]
@Grade, can you post your code?

**Comment by Grade** [comment]
I tried. But it doesn't work in plunker as well. But it works when I just run it in browser (Chrome, Firefox)

**Comment by santosguilherme** [comment]
Plunker example also doens't run here :/

**Comment by khanhto** [comment]
@santosguilherme I have been busy these days and this pull request was created very long ago (nearly a year). At that time, it was working properly. I'm not sure if it's still working today. I'll check it when I have time.

**Comment by khanhto** [comment]
@siva-I sorry for the late reply, this feature should be fairly easy to be extended to selectize and select2 themes, but I'm not sure when I'll get back to this.
