### ISSUE TITLE
Mouseenter (selection) doesn't work in 1.2.16+ using IE8

### ISSUE THREAD

**Issue by sambomartin** [angular-ui/ui-select#158]
On mouseenter the selected item moves to the last one.  The mouseover event fires for each row in the collection - always leaving the last one selected.

Current work-around is to use 1.2.15.

**Comment by Josh68** [comment]
@careywalker, your code (minor modification based on version) worked for me with 0.9.6. I'm going to look to see if this could apply cleanly to the latest version, because it wouldn't seem to cause a merge issue.

**Comment by gillius** [comment]
#754 seems to work for me. We have no choice to support IE8 and IE11 now during a enterprise migration to IE11, and Angular 1.2.16 has a bug impacting IE11, but upgrading beyond select 0.2 doesn't work in IE8, and it doesn't work in Angular past 1.2.16. So now we will use @Josh68's code.

**Comment by jroom36** [comment]
https://github.com/Josh68/ui-select/commit/8317a0c55e25f629427b212e6e696a78c0a82dd5
This fixed for me follow issue:
"On mouseenter the selected item moves to the last one. The mouseover event fires for each row in the collection - always leaving the last one selected."

angular js 1.2.28
select.js from https://github.com/Josh68/ui-select

**Comment by cgonul** [comment]
I am sorry but it is still not working by my side. Can you eleborate an example. I am helpless. Thank you very much.
