### ISSUE TITLE
Files in dist folder versions do not match tag

### ISSUE THREAD

**Issue by bman61** [angular-ui/ui-select#1581]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
tag 0.16.0 dist files contain version 0.15.0
e.g. https://github.com/angular-ui/ui-select/blob/v0.16.0/dist/select.js
/*!
 * ui-select
 * http://github.com/angular-ui/ui-select
 * Version: 0.15.0 - 2016-03-15T17:20:10.014Z
 * License: MIT
 */

tag 0.16.1 dist files contain version 0.16.0
e.g. https://github.com/angular-ui/ui-select/blob/v0.16.1/dist/select.js
/*!
 * ui-select
 * http://github.com/angular-ui/ui-select
 * Version: 0.16.0 - 2016-03-23T20:51:56.609Z
 * License: MIT
 */

Could not find any docs in this repository indicating that this version/tag difference is intentional

### Link to minimally-working plunker that reproduces the issue:
N/A - just look at the dist folder files for any tag

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: N/A

UI-Select: 0.16.1, 0.16.0, ...

Bootstrap/Select2/Selectize CSS (if applicable): N/A

**Comment by user378230** [comment]
Fixed 66a2a5e8cae3421cf2c25cc56492e5674b7eeda3
