### ISSUE TITLE
Nuget package for 0.16.1 

### ISSUE THREAD

**Issue by samousavih** [angular-ui/ui-select#1584]
Could you please update the nuget package to 0.16.1 because there is an issue with using the ui-select 0.16.0 as an attribute and anglur 1.5.5.

The issue is the page freezes and seems to be because of an infinite loop somewhere.
But it is working with 0.16.1.

**Comment by user378230** [comment]
The nuget package isn't maintained who maintains this repository. You'll have to ask them to update the package directly. 

Closing this based on #513 (npm/bower/github are the only official release channels)
