### ISSUE TITLE
Css .ui-select-choices-row:hover making it hard to read dropdown items

### ISSUE THREAD

**Issue by pawankeer** [angular-ui/ui-select#1586]
### Bug description: When we take the mouse over a drop-down item that is already selected (blue background). The background turns grey. This makes the text hard to read.

select.css:
Changed the following to fix it temporarily
.ui-select-choices-row:hover {
  background-color: #3875d7;
  color: #fff;
}
### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular:1.3.15

UI-Select:0.16.1

Bootstrap/Select2/Selectize CSS (if applicable): theme = Select2 0.16.0

**Comment by user378230** [comment]
Can you post a plunkr and repro steps? Maybe a screenshot? I can't seem to see it in the [examples](http://angular-ui.github.io/ui-select/#examples): http://angular-ui.github.io/ui-select/demo-basic.html

**Comment by pawankeer** [comment]
This is how it looks when I select it -
![1](https://cloud.githubusercontent.com/assets/16655175/14997852/ce3aba86-114e-11e6-89ee-f3a985d8b1a4.png)

When I do a mouse over the currently selected option I can't read the text because of the css -
![2](https://cloud.githubusercontent.com/assets/16655175/14997888/f9ff6fd6-114e-11e6-9186-e36740f02f4e.png)

And when I take the mouse over a different option, both get highlighted -
![3](https://cloud.githubusercontent.com/assets/16655175/14997959/4de66082-114f-11e6-94d5-52ab452c1fc5.png)

**Comment by user378230** [comment]
Can you create a plunkr? I still can't see this happening in http://angular-ui.github.io/ui-select/demo-basic.html

Maybe you are using a different version of select2.css to the [examples](http://angular-ui.github.io/ui-select/#examples)?

**Comment by bigbigworld** [comment]
I also have this problem. thank for @pawankeer ,your  temporarily solution can fix my bug.

**Comment by jacksonrdlc** [comment]
+1

**Comment by user378230** [comment]
@jacksonrdlc can you post a plunkr or similar? A +1 isn't very useful here and no one has posted a repro sample yet.

**Comment by alfredcalayag** [comment]
@user378230 @pawankeer , Here's a plunker that reproduces the issue: http://plnkr.co/edit/xTHmqhXY8I8OZMXZUuMt?p=preview

Here's what I'm finding out:
All `<li>` options are assigned a `.ui-select-choices-row` css class. When an item is selected, the `.select2-highlighted` class is added and applies the blue background.  On hover over any choice element, this activates `.ui-select-choices-row:hover` and applies the gray background (i'm seeing #f5f5f5 in my version).  In our problem scenario, it is _this_ class that overwrites the blue background with the gray one (regardless if it selected or not). You can inspect the element with your browser's debugger tools for these classes and toggle the hover action.

My solution:  Load the `select2.css` script *AFTER* the ui-select's css script.  I believe this is an order of precedence issue with css which in this scenario the code that appears later would override the previous if both have the same specificity: http://stackoverflow.com/questions/25105736/what-is-the-order-of-precedence-for-css.  In the plunker example above, I deliberately loaded the select2.css script first.

**Comment by user378230** [comment]
@alfredcalayag Looking at the examples `select2.css` is [**already loaded after**](https://github.com/angular-ui/ui-select/blob/master/docs/partials/_header.html#L32) `select.css` (ui-select) so your plunkr has been created incorrectly. Thanks for finding out the problem though, it will help future users! :+1: 

Closing this as a usage issue. 
## Future users:
Please load `select2.css` after `select.css` (or submit a PR with a proper fix).

**Comment by alfredcalayag** [comment]
@user378230 yes, that's correct.  I changed the loading order (incorrectly) to explicitly to reproduce the issue and share.  Thanks and hope this was helpful.
