### ISSUE TITLE
Automate npm releases

### ISSUE THREAD

**Issue by user378230** [angular-ui/ui-select#1587]
We should be able to automate npm releases via travis as per: https://docs.travis-ci.com/user/deployment/npm/ (releasing on tags only)

FYI: https://docs.travis-ci.com/user/deployment/#Deploying-to-Multiple-Providers

Ping @aaronroberson I'm guessing you'd need to set your key since the `ui-select` package belongs to you? Any chance you could look at this? 

We could also probably do with a (v.0.17.0) release since a bunch of PRs have merged since the last release.

**Comment by aaronroberson** [comment]
I've updated travis to deploy to npm on tag change.

**Comment by user378230** [comment]
Confirmed working with v0.17.1 too. Cheers!

**Comment by aaronroberson** [comment]
Great!!!
