### ISSUE TITLE
TypeError: Cannot read property 'source' of undefined with custom templates

### ISSUE THREAD

**Issue by katemihalikova** [angular-ui/ui-select#1597]
### Bug description:
When the ui-select is being rendered, error is shown in console:

```javascript
TypeError: Cannot read property 'source' of undefined
    at Array.<anonymous> (select.js:1840)
    at ngModelWatch (angular.js:26943)
    at Scope.$digest (angular.js:17064)
    at Scope.$apply (angular.js:17337)
    at done (angular.js:11572)
    at completeRequest (angular.js:11778)
    at XMLHttpRequest.requestLoaded (angular.js:11711)
```

This happens only when using custom templates that need to be fetched.
Seems related to #1440.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/Xk6lyhMoqWRAhDg7IK6h?p=preview

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS
Angular 1.5.5
UI-Select 0.16.1
Any CSS

**Comment by user378230** [comment]
This might be as simple as checking for `parserResult` is there before trying to access the `source` property. 

[uiSelectSingleDirective.js#L21](https://github.com/angular-ui/ui-select/blob/55e82e8f6008b6a1823263c20ca4a70e1dabb626/src/uiSelectSingleDirective.js#L21)

eg: 
```js
var data,
  locals = {},
  result;
  if($select.parserResult && $select.parserResult.source) {
    data = $select.parserResult.source(scope, { $select : {search:''}}); //Overwrite $search
  }
  if(data) {
    ..
```
Can you submit a PR?

**Comment by katemihalikova** [comment]
Will do, thanks for investigation.
