### ISSUE TITLE
Latest version not pushed to NPM

### ISSUE THREAD

**Issue by jaeggir** [angular-ui/ui-select#1599]
Version pushed to npm is not the latest release. It looks like version 0.16.0, I would expect 0.17.0.

How to reproduce?
Add ui-select as dependency to your project, set ui-select version to 0.17.0 and install all dependencies with ```bower install```. You may check bower_components/angular-ui-select/dist/select.js to verify the version.

**Comment by user378230** [comment]
Fixed 66a2a5e8cae3421cf2c25cc56492e5674b7eeda3
