### ISSUE TITLE
Need a way to reset input

### ISSUE THREAD

**Issue by zackarychapple** [angular-ui/ui-select#160]
Is there a way we can add a clear button on an x icon to clear the current set value.  
Possibly a <ui-select-reset> element that we can add any markup in, text or icon. Then that gets added to the placeholder text div but floating off to the right.  Sometimes we want to be able to reset our dropdowns.

**Comment by dimirc** [comment]
This was solved with https://github.com/angular-ui/ui-select/pull/287

**Comment by seiyria** [comment]
`allow-clear` does not seem to fire the `on-select` event and I can't seem to find an `on-clear` event. Is this intended?

**Comment by niraj-thakur** [comment]
Do we have any method by which we can reset the ui-select element back to its placeholder value?
