### ISSUE TITLE
Add multiple items with one copy&paste

### ISSUE THREAD

**Issue by DerekYangYC** [angular-ui/ui-select#1602]
I'd like to add multiple items in `ui-select` at once

If I copy+paste "Hawaii, Alaska" into the select-multiple, then I get:
```
No results found
```
In this case I expect the result to be:

```
(x)Hawaii  (x)Alaska
```

Is there a way to insert comma-separated items via one copy+paste? I do not need new value so `tagging` doesn't seem an option to me.

**Comment by user378230** [comment]
As it currently is, I don't think so.

There is a [`paste`](https://github.com/angular-ui/ui-select/blob/b7f2afe39e9a112eb54dad448f62af38c7bf7b74/src/uiSelectController.js#L615) function that is run though, which you can set during the [`config`](https://github.com/angular-ui/ui-select/blob/b7f2afe39e9a112eb54dad448f62af38c7bf7b74/src/uiSelectController.js#L19). You might then be able to run your own splitting of the string then add it to controller manually some how. 

[Here](https://github.com/angular-ui/ui-select/blob/b7f2afe39e9a112eb54dad448f62af38c7bf7b74/src/uiSelectController.js#L590) is the relevant code if you want to look at submitting a PR to allow copy/paste in non-tagging.

**Comment by DerekYangYC** [comment]
I tried the tagging feature first. so I add `tagging paste="onInputPasted(text)"` into `ui-select`. But when I pasted "Hawaii, Alaska" to the input it seems not able to separate the words by comma.

Anything I did it wrong?

Also, I looked at the [codes](https://github.com/angular-ui/ui-select/blob/b7f2afe39e9a112eb54dad448f62af38c7bf7b74/src/uiSelectController.js#L590) you mentioned but I'm not able to find where to set `ctrl.taggingTokens.isActivated` to be true, in order to trigger the detokenization process of the input text (like Hawaii, Alaska)

**Comment by user378230** [comment]
`ctrl.taggingTokens.isActivated` will only be `true` if you are in `tagging` mode. 

The detokenisation process is only enabled when in tagging mode. But the `paste` function is only called when tagging is __not__ enabled. So, you need to convert your string manually and add items manually to your selected items array, in your paste function. 

You can follow the process flow in the paste function yourself here: https://github.com/angular-ui/ui-select/blob/b7f2afe39e9a112eb54dad448f62af38c7bf7b74/src/uiSelectController.js#L576

**Comment by DerekYangYC** [comment]
It seems the `paste` function was **NOT** called when I pasted a string into the input without tagging mode enabled.

```html
<ui-select multiple paste="onCountriesPasted(text)" ng-model="country">
</ui-select>
```

Controller:
```js
$scope.onCountriesPasted = function(text) {
        log.debug(`pasted text is ${text}`);
    };
```

I can't see the log printing out. Anything I miss?

**Comment by nlavergne** [comment]
I'm using a watcher in my angular controller to "fix" this, triggered whenever the value of the model changes. This example supports coma only as a value separator, but can be adjusted to fit your needs.

```javascript
// Accept multiple comma separated values for the emails filter
     $scope.$watch('filters.emails', function(newVal, oldVal) {
        // take the last entry
        if (newVal && newVal !== oldVal) {
            if (newVal.length > 0) {
                var val = newVal[newVal.length - 1];

                if (_.contains(val, ',')) {
                    var valIndex = newVal.indexOf(val);
                    var valSplit = _.filter(_.map(val.split(','), function (v) {
                        return v.replace(/(\r\n|\n|\r)/gm,"").trim();
                    }), function(v) {
                        return v !== '' && v !== ' ' && v !== ',' && v !== ';';
                    });
                    $scope.filters.emails.splice(valIndex, 1);
                    $scope.filters.emails = newVal.concat(valSplit);
                }
            }
        }
     });
```

The only thing I still have to figure out is how to have IE supporting line breaks in pasted value, but it has nothing to do with the current issue.

**Comment by Skinner927** [comment]
You should instead be doing
`<ui-select multiple paste="onCountriesPasted" ng-model="country">`

Paste needs a reference to a function on scope.

**Comment by DerekYangYC** [comment]
@Skinner927 Unfortunately `tagging-tokens` alone is not working but `paste` handler solve it. Thank you very much!
It turns out I made a silly mistake by calling the paste handler like `paste="onCountriesPasted(text)"` rather than passing it like `paste="onCountriesPasted`.
