### ISSUE TITLE
dist/select.min.js is out of date

### ISSUE THREAD

**Issue by Blaze34** [angular-ui/ui-select#1605]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
`dist/select.min.js` is out of date.
I saw difference with match.tpl.html
In min.js:
`<div class="ui-select-match" ng-hide="$select.open"`
In src/bootstrap:
`<div class="ui-select-match" ng-hide="$select.open && $select.searchEnabled"`
ng-hide="$select.open"

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5.5

UI-Select: 0.17.0

**Comment by user378230** [comment]
Fixed 66a2a5e8cae3421cf2c25cc56492e5674b7eeda3
