### ISSUE TITLE
Code Quality

### ISSUE THREAD

**Issue by brunowego** [angular-ui/ui-select#1606]
I appreciate this project and I wish contribute with the code style. Are now accepting pull requests for better the code quality? Thanks.

---
I mean, jshint. 👍

**Comment by user378230** [comment]
Though all contributions are greatly appreciated, fixes/refactors around important issues (#1537) would definitely help much more! Changes to code style do not add as much value to end result as fixes do.

**Comment by brunowego** [comment]
Ok, I appreciate your feedback. Thanks.
