### ISSUE TITLE
no-choice.tpl.html is missing from select2 and selectize

### ISSUE THREAD

**Issue by deepak342** [angular-ui/ui-select#1608]
In the latest release v0.17.1, the no-choice.tpl.html is missing from the $templateCache for the themes "Select2" & "selectize". It seems to be available only for bootstrap

Error:
Failed to load template: select2/no-choice.tpl.html

**Comment by user378230** [comment]
Would you like to submit a PR with templates for these two themes? If its similar to the bootstrap template they should be quite simple files. 

_If you also fork one of the [example plunkrs](http://angular-ui.github.io/ui-select/#examples) with a demo so I can verify without pulling down the changes then I can merge it in much quicker._

**Comment by santosguilherme** [comment]
@deepak342, It works with the theme bootstrap?

**Comment by deepak342** [comment]
@santosguilherme It does with the bootstrap theme but not with the other two('select2' & 'selectize').

**Comment by stefannikolic** [comment]
Hi for me also uiSelectNoChoice works with bootstrap theme but it is not working with select2 and selectize theme. Will there be solution for uiSelectNoChoice directive for ui-select v. 0.17.1 soon?

**Comment by bubenshchykov** [comment]
+1

**Comment by user378230** [comment]
Please don't +1 issues, you can use github reactions to express your support for a bug fix. In this case you may find it more constructive to submit a PR as the fix isn't too complicated.

**Comment by stefannikolic** [comment]
@user378230 Hi I created a Pull request for uiSelectNoChoice support for Select2 theme: https://github.com/angular-ui/ui-select/pull/1704

Can you please review it and see if it is ok?
