### ISSUE TITLE
ui-select-no-choice doesn't work for multiselect

### ISSUE THREAD

**Issue by turistua** [angular-ui/ui-select#1614]
### Bug description:

while using ui-select-no-choice directive it doesn't apply for multiselect mode (bootstrap theme).

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.4.2

UI-Select: 0.17.1

**Comment by kirgy** [comment]
I am getting the same problem occur, but when using the select2 theme. Setting the theme to "bootstrap" solves this for me.
