### ISSUE TITLE
Angular2 and Roadmap

### ISSUE THREAD

**Issue by LeonardoGentile** [angular-ui/ui-select#1616]
Hi,
In #1096 @ProLoser mentioned the complexity that the project had reached and he suggested some interesting points. Even before in #884 quite some concernes were raised about the status of the project, in fact @brianfeister said that it was starting to be quite difficult to merge old and new PRs due to the complexity of the project. These two issues have been there for a year or more.

In the meanwhile the Roadmap was lastly updated on Nov 26, 2014.

For those of us already looking forward to the Angular2 switch would be very interesting to know if there is any short/long planning or an open discussion going on about the future of this project, especially if you could see an Angular2 version of it or not.

As I've understood to keep on improving this version for angular1 many things should me modularized and complexity broken down, and for angular2 I guess it seems to be a completely re-write almost from zero if I'm not wrong. 

Some project as https://github.com/OptimalBPM/angular-schema-form-dynamic-select are based on ui-select and before looking for an A2 re-write it seems a good idea to check the status and the roadmap of this project.

Thanks

**Comment by user378230** [comment]
There isn't any planning/discussion/roadmap for an angular2 version going on as far as I know. 

Current efforts are focused on resolving issues with the library...

**Comment by LeonardoGentile** [comment]
See also: #784

**Comment by ganqqwerty** [comment]
don't know about the roadmap but the amount of unmerged pull requests is obnoxious. Even solution of the bugs are not merged, who is in the team of the project anyway?

**Comment by ProLoser** [comment]
Who would like to be? I see a lot of people complain, but I don't see many people stepping up and really taking ownership of the project as a whole
