### ISSUE TITLE
Updating disabled or hidden ui-select multiple inputs breaks width (0.17.1)

### ISSUE THREAD

**Issue by twhit027** [angular-ui/ui-select#1617]
### Bug description:

With the changes to `sizeSearchInput` in 0.17.1, updating disabled or hidden multi-select inputs will set the width to 10px permanently.

### Link to minimally-working plunker that reproduces the issue:

The width of the input in the following plunker is indicated in red.
http://plnkr.co/edit/lQLLozS6DhnPXXzmuWXJ?p=preview

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5.5

UI-Select: 0.17.1

Bootstrap/Select2/Selectize CSS (if applicable): 3.1.1

**Comment by Jevonius** [comment]
I've just come across a variant of this, where the ui-select boxes are in a panel that can be hidden (but starts visible).

We've jumped from 0.12 to 0.17.1, but I don't think this is an entirely new issue. We've always had trouble with multiple ui-select boxes on the same page, and the width of the input/placeholder panel acting strangely (seemed to clear up after the various ajax requests on the page completed and angular completed another digest cycle).
