### ISSUE TITLE
Input field not showing the first time

### ISSUE THREAD

**Issue by stibay** [angular-ui/ui-select#1618]
![untitled](https://cloud.githubusercontent.com/assets/6984747/15463082/3de46a9e-20c7-11e6-838b-c14ac207d775.png)

As you can see from the first picture the input field is not rendering correctly the first time I click the dropdown box. I have to click in the white textbox without anything changing and then to the right of it (on the blank space) before the input box renders like the second picture. If I close and open the dropdown the second time the input field is rendered correctly.

Also on a sidenote, is it possible to add the helper text like "Please enter x or more characters" ? 

Here is the code:
`<ui-select ng-model="addItem.Company"
                                                               theme="select2"
                                                               autofocus="true"
                                                               append-to-body="true"
                                                               style="width: 100%;">
                                                        <ui-select-match placeholder="Company">{{ $select.selected.Name }}</ui-select-match>
                                                        <ui-select-choices repeat="company in companies | filter: $select.search"
                                                                           refresh-delay="0"
                                                                           minimum-input-length="2"
                                                                           refresh="searchCompanies($select.search)">
                                                            <div ng-bind-html="company.Name  | unsafe | highlight: $select.search"></div>
                                                        </ui-select-choices>
                                                    </ui-select>`

**Comment by fxding** [comment]
+1
same problem
