### ISSUE TITLE
Publish latest versions to NPM

### ISSUE THREAD

**Issue by mjschranz** [angular-ui/ui-select#1623]
Hey Everyone.

Just wondering why the last versions of the module have not been published to npm. For those of us who use webpack not having access to the latest version is quite problematic.

Thanks!

**Comment by user378230** [comment]
`ui-select` v0.17.1 is the latest version and is already published to npm

https://www.npmjs.com/package/ui-select

**Comment by mjschranz** [comment]
Ah I confused myself and looked at https://www.npmjs.com/package/angular-ui-select instead it looks.
