### ISSUE TITLE
place an item outside of the scrollable area?

### ISSUE THREAD

**Issue by arkarkark** [angular-ui/ui-select#163]
I'd like to place an item outside of the scrollable area so that it's always visible
I'll use this for a "Create New" option that I want to always be easily accessible.
Is that possible? Is there a better design pattern?

**Comment by Jefiozie** [comment]
As this issue is really old and there are many other issue i'm closing this down (also last comment was in 2014) . I think it is best to reopen a new issue with the newest version of ui-select and use that issue for a new enhancement. 

Thanks.
