### ISSUE TITLE
Cannot use {{expression}} in repeat

### ISSUE THREAD

**Issue by robertmirro** [angular-ui/ui-select#1640]
### Bug description:
It appears that the `repeat` attribute of `<ui-select-choices>` no longer supports an expression because of this logic that has been added to the `compile` phase and results in the error message displayed in this issue's summary above:
https://github.com/angular-ui/ui-select/commit/f5b986b1a0889da46642eb1103556f23e0368254#diff-cb9a7c7fe5ff2e1d351218d2344d3421R33

I don't see `repeat` documented here so can't determine if expressions are supposed to be explicitly supported now or if that functionality has been intentionally removed:
https://github.com/angular-ui/ui-select/wiki/ui-select-choices

Results in the following:
```
Error: [ui.select:iexp] Expected expression in form of '_item_ in _collection_[ track by _id _]' but got '{{$ctrl.repeatCondition}}'.
```
### Link to minimally-working plunker that reproduces the issue:
Here is an attempt to use an expression as the `repeat` attribute with 0.17.1 that results in an error:
`<ui-select-choices repeat="{{repeat}}"`
http://plnkr.co/edit/WxBnQGgeXjNi9KQV3Knd?p=preview

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular:
`1.5.3`

UI-Select:
This issue is being reported for `0.17.1`.
The missing behavior exists in `0.14.8` (our current version) and seems to be introduced on 0.17.1.

**Comment by user378230** [comment]
I believe the intent of the `repeat` attribute was to mimic the `ng-repeat` expression provided by angular to allow users to specify their choices. 

I don't imagine that it was explicitly intended to support expressions (`ng-repeat` does not do this either) but probably just a side effect of the way it was original designed. 

Moving to the `compile` phase prevented the double compilation of the choices directive which I believe is probably more important than supporting expressions in `repeat`

**Comment by jose-brito-ptc** [comment]
I'm also experiencing the same issue while using ui-select with angular-formly. Here's my code:

`<ui-select-choices data-repeat="{{to.ngOptions}}" group-by="{{to.groupByProp}}">`

A possible workaround is to replace "{{to.ngOptions}}" with `option[to.valueProp] as option in to.options | filter: $select.search`, but that goes against the purpose of using formly. However, even using the workaround, I still get another error with the group-by attribute:

`Error: [$parse:syntax] Syntax Error: Token '{' invalid key at column 2 of the expression [{{to.groupByProp}}] starting at [{to.groupByProp}}].`

Any suggestions for both of these issues?

**Comment by user378230** [comment]
You might be able to try something like this [SO answer](http://stackoverflow.com/a/28749005)

>
 ```js
app.directive('ngVarRepeat',function($compile){
  return {
    priority:1001, //must be higher than 1000 (priority of ng-repeat)
    compile:function($elm,$attrs){
      var expression = $attrs.ngVarRepeat;
      $elm.removeAttr('ng-var-repeat'); // remove attribute so we can recompile it later
      return function(scope,elm,attrs){
        $elm.attr('ng-repeat',scope.$eval(expression));
        $compile($elm)(scope);
      }
    }
  }
})
```

**Comment by robertmirro** [comment]
@user378230 Thanks for the response!

We wrapped `ui-select` in our own component to further extend it and then used that component heavily in multiple apps.  :flushed:

**Comment by user378230** [comment]
@robertmirro Feel free to share if you have any success :+1: sure others would appreciate it.

**Comment by jose-brito-ptc** [comment]
Hi @user378230 why close this issue and label it "wontfix"? The solution above may not be ideal, since we are dealing with nested ng-repeat.

**Comment by user378230** [comment]
As stated above the `ng-repeat` directive doesn't support expressions and `repeat` in `ui-select` functions in the same way.  

The change in the `ui-select` library was implemented to optimise/improve performance of the library which I affects more users than supporting this edge case. That is why I marked as wontfix :)

**Comment by jrharshath** [comment]
@user378230 So that means the `repeat` attribute will no longer mimic the `ng-options` directive, like it states in the documentation?
