### ISSUE TITLE
Select multiple entries using ctrl key

### ISSUE THREAD

**Issue by mawaheb-seraj-devtech** [angular-ui/ui-select#1648]
### Bug description:
I have a list with a `multiple` attribute to it as shown below, now, I can't actually make multiple selections by holding down the Ctrl key.

    <ui-select multiple id="selectCountry" class="edit-select-control-gray not-highlighted" 
     ng-model="comp.selectedCountries" theme="bootstrap">
        <ui-select-match placeholder="Choose a Country">{{$item.name}}</ui-select-match>
        <ui-select-choices repeat="country in countries | filter:$select.search | orderBy:'name'">
        {{country.name}}
      </ui-select-choices>
    </ui-select>

I don't want to use the `close-on-select="false"`.

**Comment by user378230** [comment]
This isn't a feature of the library... I've updated the issue title to reflect this.

You could consider submitting a PR that adds this functionality if you would like. :smiley:
