### ISSUE TITLE
ui-select-match placeholder doesn't work with ng-bind

### ISSUE THREAD

**Issue by Halfist** [angular-ui/ui-select#1663]
**Bug description:** placeholder for ui-select-match works only with {{}} notation, not with best practices recommended ng-bind one. I use "data-" prefix for each non-standard HTML5 attribute, so HTML is valid for W3C validator, this shouldn't be an issue. Though, if it is, then this is one more issue.

**Plunker:** http://plnkr.co/edit/RfM10exQ4HdAOaqllKrc?p=preview.

**AngularJS:** 1.5.5.
**UI-Select:** 0.14.8.
**Select2 CSS:** 3.5.4.
**Bootstrap:** 3.3.6.

**Comment by user378230** [comment]
The placeholder is an attribute, so it can't be bound with ng-bind. 

The ui-select is broken because of incorrect usage of ui-select-match, the following works:
```html
<ui-select-match data-placeholder="Select a person">
    <span data-ng-bind="$select.selected"></span>
</ui-select-match>
```

**Comment by Halfist** [comment]
Closing the issue.

Thanks.
