### ISSUE TITLE
Basic example with google geocoding not working

### ISSUE THREAD

**Issue by silentFred** [angular-ui/ui-select#1664]
Hi there,

The geocoding example in the basic examples does not work (does not fire refresh or load any options). It also occasionally makes the searchable area 10pixels and thereafter it becomes unusable.

Link so plunkr: http://plnkr.co/edit/ajBKnQeecaqvgHeyAeBP?p=preview

**Comment by silentFred** [comment]
Turns out the refresh method was not referenced via ctrl. Created the fix here: http://plnkr.co/edit/YmQ39Nu5CgEzJwdUrBGt?p=preview

I think someone added some John Papa style and missed that method in the template ;)

**Comment by user378230** [comment]
You could submit a PR with a fix, the relevant file is: https://github.com/angular-ui/ui-select/blob/master/docs/examples/demo-basic.html 

I can merge once its up.

**Comment by Jefiozie** [comment]
Added this quick fix to give better documentation to this control. Hope you don't mind.

**Comment by user378230** [comment]
@Jefiozie if you have some time it would be awesome if you could check the other examples, for example I noticed https://github.com/angular-ui/ui-select/blob/master/docs/examples/demo-multiple-selection.html was broken (first one) thanks for your efforts :+1:

**Comment by Jefiozie** [comment]
@use, sure I will have a look, should I check them and If i have some improvements add just one PR?
