### ISSUE TITLE
ui-select multiple disabled state hides placeholder text incorrectly

### ISSUE THREAD

**Issue by longzheng** [angular-ui/ui-select#1667]
### Bug description:
When using ```ui-select in``` ```multiple``` mode, if ```ui-select``` is **disabled**, the ```ui-select-match``` placeholder text is incorrectly hidden using ```ng-hide```

Multiple, placeholder text, ui-select enabled
![image](https://cloud.githubusercontent.com/assets/484912/16119477/02f7ed5a-341f-11e6-83af-4c5bcaf79bea.png)

Multiple, placeholder text, ui-select disabled
![image](https://cloud.githubusercontent.com/assets/484912/16119485/0bdc375a-341f-11e6-92ee-6bce80e9e215.png)

This behavior works correctly for non-multiple ui-selects
![image](https://cloud.githubusercontent.com/assets/484912/16119546/5156db6e-341f-11e6-9290-afec4e6b1c59.png)

### Link to minimally-working plunker that reproduces the issue:
http://angular-ui.github.io/ui-select/demo-tagging.html
- Clear values from input
- Click on "Disable ui-select"
- Actual: placeholder text disappears
- Expected: placeholder text remains

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5.0

UI-Select: 0.18.0

### Fix
Remove this ```ng-hide``` from the ```select-multiple``` template https://github.com/angular-ui/ui-select/blob/master/src/bootstrap/select-multiple.tpl.html#L12

There is no equivelant ng-hide for the non-multiple ```select``` template https://github.com/angular-ui/ui-select/blob/master/src/bootstrap/select.tpl.html

**Comment by Jefiozie** [comment]
I'm looking at your issue and #1156  has a similiar thing but here it was a CSS adjustment.
Do you agree that we need to make a adjustment that is the same for all themes?

**Comment by longzheng** [comment]
I think overriding a ``ng-hide`` with CSS ``display: initial !important`` is more of a hack.

The fact that non multiple templates don't have the same ng-hide leads me to believe it is a mistake on the ng-hide.

**Comment by Jefiozie** [comment]
Agree on that I will add my pr as I already had a commit.
