### ISSUE TITLE
(tagging) paste not working if tagging-label="false" and tagging-tokens are set

### ISSUE THREAD

**Issue by torstenrudolf** [angular-ui/ui-select#1668]
### Bug description:
when using the tagging feature paste is not working if `tagging-label="false"` and `tagging-tokens` are set. see [this plunker](http://plnkr.co/edit/kauNS7YjckRfi616k4PT?p=preview)

I believe this is because the paste event calls `ctrl.select(item)` (see [uiSelectController.js#L614](https://github.com/angular-ui/ui-select/blob/v0.18.0/src/uiSelectController.js#L614)) for each item after splitting the pasted string. But in [uiSelectController.js#L356](https://github.com/angular-ui/ui-select/blob/v0.18.0/src/uiSelectController.js#L356) in the case of `ctrl.taggingLabel === false` `ctrl.select` overrides the passed in `item` with the current `ctrl.search` which was set empty in the `paste` event handler earlier. Therefore the passed in `item` is lost and note used.

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS
angularjs: 1.5.0
ui-select: 0.18.0

**Comment by pixeloution** [comment]
I've just run into this issue myself -- going to have a look @ your pull request and hopefully it does the trick ;)

**Comment by dmitry-dedukhin** [comment]
+1
