### ISSUE TITLE
(tagging) minimum string length to create tag

### ISSUE THREAD

**Issue by lewi12s** [angular-ui/ui-select#1671]
How to set minimum required string length for tag creation? For eg. I want to create tag (label in input bar) if string length is greater than 3.

I came up with workaround to add one if statement to tagging function:

```
function tagging(text) {
   if (text.length < 3) {
    return;
  }
}
```
but sometimes I get null value in my ng-model array.

how to handle this in proper way?

**Comment by user378230** [comment]
You still need to return something if length > 3

```
function tagging(text) {
   if (text.length < 3) {
    return;
  }
  return text; 
}
```
If you are, and you're getting a problem with null values post a plunkr example.
