### ISSUE TITLE
Initially-selected option gets permanently removed from dropdown list

### ISSUE THREAD

**Issue by andyperlitch** [angular-ui/ui-select#1675]
### Bug description:

When an initial value is provided (e.g., ng-model is specified prior to the directive compiling), it is shown as chosen, but then does not appear in the list thereafter.

### Link to minimally-working plunker that reproduces the issue:
[The "basic" demo with a single line modification and version update](http://plnkr.co/edit/WloUx7Gb7J4NzaNtYmLs?p=preview)

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS
Angular: 1.5.0
UI-Select: 0.17.1

![ui-select-issue](https://cloud.githubusercontent.com/assets/1390651/16250262/d6a50700-37d0-11e6-8c5c-65bf6b7772e4.gif)

(sorry for the slowed-down gif, not sure why its slow)

**Comment by andyperlitch** [comment]
More info: I'm 100% sure it has to do with [lines 234-249 of uiSelectController.js](https://github.com/angular-ui/ui-select/blame/cf27a961c6a3e6a6f6f09107c67b11bba7fd3e3c/src/uiSelectController.js#L234-L249), but I'm not familiar enough with the codebase to make an acceptable fix.

**Comment by andyperlitch** [comment]
This issue actually duplicates #1660, so my apologies. I'll close mine, but perhaps my plunker and issue title will be of some use to people with the same problem..

**Comment by muni510** [comment]
add  remove-selected="false" option to ui-select directive

<ui-select ng-model="ctrl.person.selected" theme="bootstrap" remove-selected="false">
