### ISSUE TITLE
How to access ui-select controller?

### ISSUE THREAD

**Issue by timc13** [angular-ui/ui-select#1679]
In following this thread https://github.com/angular-ui/ui-select/issues/201, I see people trying to access the `ui-select` controller with the `.controller()` method.

I'm trying this in the `postLink` of a wrapper directive and even if I use a timeout, I still cannot get a controller instance.  I've tried `el.controller('uiSelect')`, `el.controller()`, and `el.controller('ngModel')`

Is there any reliable way to access the `ui-select` controller (or even better, the `ng-model` controller)?

**Comment by user378230** [comment]
You mean like: [Accessing $select](https://github.com/angular-ui/ui-select/wiki/Accessing-%24select)?

**Comment by timc13** [comment]
not exactly...that only works for a directive that is on the `ui-select` element.  i have a `showError` directive that's on a parent used to toggle a css class on an outer `div`:

```
angular.directive('showError', () => {
  return {
    restrict: 'A',
    require: '^form'
    link: function (scope, el, attrs, formCtrl) {
      const inputEl = el[0].querySelector("[name]");
      const inputNgEl = angular.element(inputEl);
      const ngModelCtrl = inputNgEl.controller('ngModel');

      if (ngModelCtrl) {
        const toggleInvalid = e => {
          el.toggleClass('invalid', ngModelCtrl.$invalid);
        };
        scope.$on('form:submit', toggleInvalid);
        ngModelCtrl.$viewChangeListeners.push(toggleInvalid);
      }
    }
  }
});
```

the HTML like so:
```
<div class="col-md-8" show-error>
  <label>Description</label>
  <input type="text" ng-model="vm.description" name="description">
</div>
<div class="col-md-8" show-error>
<label>Industry</label>
  <ui-select required theme="selectize" ng-model="vm.industry" name="vm.industry">
    <ui-select-match placeholder="Choose...">
      <span>{{$select.selected}}</span>
    </ui-select-match>
    <ui-select-choices repeat="industry in vm.industries | filter: $select.search">
      <span ng-bind="industry"></span>
    </ui-select-choices>
  </ui-select>
</div>
```

This works for `input` and `text` and `select` but i cannot seem to access the `ngModelController` from `ui-select`

**Comment by user378230** [comment]
For more general Angular questions you might have more success on stackoverflow
