### ISSUE TITLE
Typeahead selected item missing in drop down list.

### ISSUE THREAD

**Issue by hwangTPN** [angular-ui/ui-select#1681]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular : 1.5.5, UI-Select: 0.18.0 (0.16.1 works)

Angular:

UI-Select:

Bootstrap/Select2/Selectize CSS (if applicable):

**Comment by allanpoppe** [comment]
I'm facing this issue too.

**Comment by static-max** [comment]
Same for me, worked with 0.14.8 and stopped working after upgrading to 0.17.1

**Comment by ehsaanwelcome** [comment]
same for me

**Comment by hwangTPN** [comment]
@allanpoppe not yet. I just downgraded to 0.16.1 as my feature is requested in rush.

**Comment by user378230** [comment]
Possible duplicate #1672 ?

Please include a plunkr as requested in the issue template.

**Comment by harry-kalligeros** [comment]
A quick workaround is to make your markup like this:
`<ui-select remove-selected="false" .... >`

**Comment by user378230** [comment]
Assuming resolved as of v0.18.1
