### ISSUE TITLE
Minimum Input Length not working?

### ISSUE THREAD

**Issue by bgadiel** [angular-ui/ui-select#1682]
### Bug description:
I have ~1500 items in my drop down list in bootstrap modal. 
When I show all the items in a drop down list, there is a delay of 2 seconds for every action the user does.
When trying to limit the amount of items to show by using 'minimum-input-length', there is no change (i.e - full list is displayed).
I tried debugging 'ctrl.activate' function in select.js and I noticed that in line 393 there is different behavior when comparing to Multiple Selection's [Plunker](http://plnkr.co/edit/?p=preview):
Line 393: 'if (ctrl.$animate && ctrl.$animate.on && ctrl.$animate.enabled(container[0]))'
On [official Multiple's (exmaple](http://plnkr.co/edit/?p=preview):) 'ctrl.$animate.enabled(container[0])' returns undefined, therefore, continues to line 415 $timeout.
On [my app](https://plnkr.co/edit/H0kbeR4kHfZFjsBnpjBC?p=preview): 'ctrl.$animate.enabled(container[0])' returns true and then shows the drop-down list.

### My HTML Markup:
```
<ui-select multiple ng-model="vm.salesPlayContent.mapped_markets" theme="select2" style="width: 630px;" title="select market">
                    <ui-select-match placeholder="Select market...">{{ $item.name }}</ui-select-match>
                    <ui-select-choices repeat="market in vm.salesPlayContent.available_markets | filter: {name: $select.search}" minimum-input-length="4">
                        <div ng-bind-html="market.name | highlight: $select.search"></div>
                    </ui-select-choices>
                </ui-select>
```

### Versions

Angular: 1.4.5

UI-Select / select.js: 0.17.1

Angular UI-Select: 0.18.0

Bootstrap/Select2/Selectize CSS (if applicable): 
Select2: 3.5.4
select2-bootstrap-css: 1.4.6
Selectize: 0.12.1

**Comment by user378230** [comment]
Your plunkrs are empty :disappointed: did you try in v0.18.0?

**Comment by bgadiel** [comment]
Which variable represents my plunkrs?
If you mean container[0]. then in both cases ( Plunker / my app) it has data.
Not sure why function 'enabled' returns a value... I'll try 0.18 as well.

**Comment by bgadiel** [comment]
version 0.18.0 does not change anything.

**Comment by user378230** [comment]
Oh, you aren't using the `refresh` functionality though:

>| option | description | value |
|---|---|---|
| `minimum-input-length` | **Minimum characters required before `refresh` function is triggered** | integer (or interpolated expression: `{{ 1 + 1 }}`) | 

(Wiki: https://github.com/angular-ui/ui-select/wiki/ui-select-choices)

**Comment by bgadiel** [comment]
Could you be more specific where I should use it?
Didnt see it being used on AngularJS ui-select's Plunkr exmaple.

**Comment by user378230** [comment]
http://angular-ui.github.io/ui-select/demo-basic.html (first ui-select)

**Comment by bgadiel** [comment]
The example shows using GET on refresh. I don't use GET as I already have all the data in 'items'.
Could you please help modifying my plunker so it will use min-characters correctly?

**Comment by bgadiel** [comment]
Is the performance issue related to ng-repeat creating too many watchers?

**Comment by Jefiozie** [comment]
I think this is the same issue as you have on stackoverflow. 
Let us continue here with the discussion? 

[Stackoverflow Link](http://stackoverflow.com/questions/38077516/slow-behaviour-of-angular-ui-selects-drop-down-list-when-big-list-of-items-in-m)

**Comment by bgadiel** [comment]
sure.
I am not sure how to fix my issue.
So at the monent I am thinking of switching to diff library.
If you have any ideas how to fix, I would love to try them out.
Thanks,
Gideon
בתאריך 29 ביוני 2016 5:13 אחה״צ,‏ "J.Bosch" <notifications@github.com> כתב:

**Comment by Jefiozie** [comment]
A possible way forward with the performance is to load +/- 25 items and when the user start searching lookup the value in the complete list of 1500+. Second I think I have seen some comments that track by $index will help (don't know for sure). 

On the min length maybe have a look at #274 or maybe @user378230 has a idea.

**Comment by Jefiozie** [comment]
@bgadiel  Did you already had a fix/ workaround for the min-length?

**Comment by rafaelhz** [comment]
I solve that using a LimitTo, checking  the search length:

` limitTo: ($select.search.length <= 2) ? 0 : undefined"`
```
<ui-select-choices 
  repeat="item in ctrl.items | filter: $select.search | limitTo: ($select.search.length <= 2) ? 0 : undefined">
  ...
</ui-select-choices>
```

**Comment by bgadiel** [comment]
Great work!
בתאריך 12 ביולי 2016 5:04 אחה״צ,‏ "Rafael Zeffa" <notifications@github.com>
כתב:

**Comment by Jefiozie** [comment]
@bgadiel  issue can be closed as you have a answer?
