### ISSUE TITLE
ui-select-no-choice doesn't work for the multiple

### ISSUE THREAD

**Issue by hiteshbalraw** [angular-ui/ui-select#1684]
Hi,

I am using version 0.17.1. As, described in the documentation I have used [ui-select-no-choice](https://github.com/angular-ui/ui-select/wiki/ui-select-no-choice) but it seems like it is working for single only, not for the muliple.

Is above behaviour is expected?

Also, I have tried header and footer also but it looks like it is not part of 0.17.1(as mentioned https://github.com/angular-ui/ui-select/wiki/ui-select-header-and-footer#important-this-is-currently-not-merged-into-master), any idea when can we expect it?

**Comment by user378230** [comment]
See [CHANGELOG.md](https://github.com/angular-ui/ui-select/blob/master/CHANGELOG.md) support for bootstrap multiple added in v0.18.0 (no select2 no choice support yet - please create PR if you like to add)

Header footer has problems in angular v1.5 see end of #1323 for details
