### ISSUE TITLE
bug in multiple select?

### ISSUE THREAD

**Issue by jc-vogel** [angular-ui/ui-select#1686]
When using multiple select, I get an error about an undefined property: $select.selected. 
when rendering ui-select (multiple) the $select.selected is reset.
I think the line '$select.selected = ngModel.$viewValue;' should come before the if-statement. Otherwise, if it's not an array, it will be fixed, and immediately overwritten with the wrong or undefined data. Or am I missing something?

select.js, line 1546:
```
ngModel.$render = function() {

        // Make sure that model value is array

        if(!angular.isArray(ngModel.$viewValue)){

          // Have tolerance for null or undefined values

          if(angular.isUndefined(ngModel.$viewValue) || ngModel.$viewValue === null){

            $select.selected = [];

          } else {

            throw uiSelectMinErr('multiarr', "Expected model value to be array but got '{0}'", ngModel.$viewValue);

          }

        }

        $select.selected = ngModel.$viewValue;

        $selectMultiple.refreshComponent();

        scope.$evalAsync(); //To force $digest
      };
```

**Comment by user378230** [comment]
Should be resolved by #1709 closing.
