### ISSUE TITLE
Initially selected item not in list of choices

### ISSUE THREAD

**Issue by joelbinn** [angular-ui/ui-select#1689]
### Bug description:
I am using ui-select where there is a pre-selected item (using ui-select-match).
But, when using ui-select with a pre-selected item, the pre-selected item is not included in the choices of the ui-select-choices list. In addition, it does not become selectable in the list if the selection is changed.

However, this works fine in 0.17.1, so this must be something that has been introduced in 0.18.0.

Best regards and keep up the good work!

### Link to minimally-working plunker that reproduces the issue:
[Plunker illustrating the bug](http://plnkr.co/edit/tFE8P3xPNUreceL7ircB?p=preview)
### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS
Angular:
1.5.6
UI-Select:
0.18.0
Bootstrap CSS:
3.3.6

**Comment by user378230** [comment]
Possible duplicate of #1672?

**Comment by joelbinn** [comment]
Yep, it is a duplicate. Closing this issue.
