### ISSUE TITLE
Tagging mode broken in latest release

### ISSUE THREAD

**Issue by offtopic** [angular-ui/ui-select#1693]
In ui-select v0.18.0 the Tagging mode is broken and causes more than 10 digest loops.
Steps to reproduce with plnkr:
http://plnkr.co/edit/SNOI0DmFDAah2AvwHseY?p=preview

1) type `"a"` `<Enter>`
2) type `"aa"` 
3) Look at the console:

`VM3851 angular.js:13236 Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"{active: $select.isActive(this), disabled: $select.isDisabled(this)}","newVal":{"active":true,"disabled":true},"oldVal":{"active":true,"disabled":false}}],[{"msg":"{active: $select.isActive(this), disabled: $select.isDisabled(this)}","newVal":{"active":true,"disabled":false},"oldVal":{"active":true,"disabled":true}}],[{"msg":"{active: $select.isActive(this), disabled: $select.isDisabled(this)}","newVal":{"active":true,"disabled":true},"oldVal":{"active":true,"disabled":false}}],[{"msg":"{active: $select.isActive(this), disabled: $select.isDisabled(this)}","newVal":{"active":true,"disabled":false},"oldVal":{"active":true,"disabled":true}}],[{"msg":"{active: $select.isActive(this), disabled: $select.isDisabled(this)}","newVal":{"active":true,"disabled":true},"oldVal":{"active":true,"disabled":false}}]]`

This scenario is working with the officials samples with version v0.16.1 and within
http://plnkr.co/edit/Wa5BP8pkhH03EF0dzgrs?p=preview also with v0.16.1

**Comment by nkovacic** [comment]
+1 Have the same issue.Occurs when new tag is created and then you start typing the same tag again.

**Comment by giovanibarili** [comment]
+1 Have the same issue.Occurs when new tag is created and then you start typing the same tag again.

**Comment by suricactus** [comment]
+1 can confirm, same issue here.

**Comment by user378230** [comment]
Thanks for the report, we have a reproduction scenario now so we need a PR rather than +1's :smiley:

**Comment by akempes** [comment]
When I remove the `disabled: $select.isDisabled(this)` from the bootstrap/choices.tpl.html template  everything works fine again.

I tracked it down to the `ctrl.activate` function. If the `ctrl.open = true;` is removed the problem isn't appearing...

This is not a fix but maybe someone else can use this as a lead... I'm not familiar with the code.

**Comment by user378230** [comment]
@akempes That's exactly what we needed! Thanks!

Here is an updated plunkr http://plnkr.co/edit/VmiHZuyebEUc5JcHayF5?p=preview

Adding a check if its a tag appears to have resolved it.
```js
 ctrl.isDisabled = function(itemScope) {
    ...
    if (itemIndex >= 0 && (!angular.isUndefined(ctrl.disableChoiceExpression) || ctrl.multiple)) {
      item = ctrl.items[itemIndex];
      if(item.isTag) return false;
      isDisabled = !!(itemScope.$eval(ctrl.disableChoiceExpression)) || _isItemSelected(item); // force the boolean value
      item._uiSelectChoiceDisabled = isDisabled; // store this for later reference
    }
   ...
  };
```

Can I get confirmation this works for people? 

/ping  @suricactus @giovanibarili @nkovacic @offtopic

**Comment by akempes** [comment]
@user378230 It's working for me! Thanks!! I just hadn't got the time to really dive into this problem...

**Comment by giovanibarili** [comment]
It's not working

[localhost-1468000642082.txt](https://github.com/angular-ui/ui-select/files/354812/localhost-1468000642082.txt)

**Comment by user378230** [comment]
@giovanibarili are you using the updated version in **my** plunkr? 

It appears to work for @akempes...

**Comment by giovanibarili** [comment]
@user378230, no, i'm tested in my application. At real, my problem is occur when selected an item and digit any words.

**Comment by user378230** [comment]
@giovanibarili you did not use my updated plunkr to test then? I updated my plunkr only... :confused:
