### ISSUE TITLE
Lost default selected element in 0.18.0

### ISSUE THREAD

**Issue by yeluoqiuzhi** [angular-ui/ui-select#1701]
### Bug description:
Lost default selected element in 0.18.0.
as you see in my plunker,first element would disapear in the <ui-select-choices> list
### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/GouR6xLD7dPfanOR2uuG?p=preview

**Comment by user378230** [comment]
Duplicate #1660
