### ISSUE TITLE
Keyboard only appears on iPad after tapping twice on select field

### ISSUE THREAD

**Issue by tbanjos** [angular-ui/ui-select#1702]
When I open an application using ui-select with bootstrap theme on iPad, I tap on the select field and the field is focused but the keyboard is not displayed. I have to tap a second time to have the keyboard displayed and be able to type. 
This only happens the first time after the page is loaded, the next times I only need to tap once on the field and the keyboard is displayed correctly. 

It can be reproduced with the project's own plunker demo:
http://plnkr.co/edit/GFEtxnDgSk73oag96Szn?p=preview

Angular: 1.5.0
UI-Select: 0.18.0
Bootstrap: 3.1.1

Might be related to #1339 and #1259.

Tested with Safari and Chrome 50.0.2661.95, iOS 9.2.

**Comment by user378230** [comment]
Duplicate #603
