### ISSUE TITLE
Interpolation for repeat not working after 0.17.0

### ISSUE THREAD

**Issue by nkovacic** [angular-ui/ui-select#1705]
There is a problem with inserting repeat arguments with interpolation ({{}}), which worked on 0.17.0 version of ui-select.
Creating a generic form with [angular-formly](http://angular-formly.com/#/example/integrations/ui-select-angular-1-4) plugin is affected by this bug, beacuse you cannot set the repeat of ui-select with code.

Example: http://plnkr.co/edit/RnICBMiD89Agmt4BUgGn

**Comment by user378230** [comment]
Duplicate #1640
