### ISSUE TITLE
All items are re-rendered when filtering or adding items to the array

### ISSUE THREAD

**Issue by alexbrad** [angular-ui/ui-select#1721]
When filtering or changing the array of items externally (by either adding or removing items), all the items are re-rendered. This happens because of the _GroupNgRepeatExpression_. Groups are tracked by $$hashKey and new groups are created whenever the array changes.

A solution would be to track groups by group name, since it is unique by definition. This can produce a significant performance improvement for large arrays of items. Is there any I am overlooking for which "track by $group.name" is not an option?

**Comment by vlio20** [comment]
+1
