### ISSUE TITLE
Disable wildcard search and only allow matching search

### ISSUE THREAD

**Issue by Znow** [angular-ui/ui-select#1728]
Hi

I have looked through nearly all the issues, searched and what not, here and on select2 site.

I cannot seem to find the feature, where I can disable wildcard search, so results with the exact specified search string only appears, instead of results that contains the search string appears.

Is this a hidden feature, or maybe it is missing?

Thanks in advance

Kind regards

**Comment by user378230** [comment]
This is handled by the filter applied to the item list, the [`| filter:$select.search`](https://docs.angularjs.org/api/ng/filter/filter) in 
```html
<ui-select multiple limit="3" tagging ng-model="LimitedResult.selectedItems">
    <ui-select-match placeholder="Select up to 3 items">{{$item}}</ui-select-match>
    <ui-select-choices repeat="thisItem in listOfItems | filter:$select.search">
        {{thisItem}}
    </ui-select-choices>
</ui-select>
```

You need to use a filter that matches on the whole text string. 

I advise you as follow up questions on StackOverflow or similar for a quicker/better response, as filters are just a standard angular feature and not specific to this library.

**Comment by Znow** [comment]
@user378230 I figured out the solution, with some extensive search. But it does not appear to work after all.

Please see this link: http://cookbook.angularjs.de/recipes/the-filter-filter/

It says, that I can append: "filter:{property: $select.search}:true"

![image](https://cloud.githubusercontent.com/assets/265719/16894927/678c11e8-4b66-11e6-9f61-76077319373e.png)

![animation](https://cloud.githubusercontent.com/assets/265719/16894954/43ab51b6-4b67-11e6-9687-5e29cee8abc7.gif)

But, then, the dropdown wont open. It works fine, without ":true".

![animation2](https://cloud.githubusercontent.com/assets/265719/16894968/8240ddb0-4b67-11e6-9e7a-44c789b452d9.gif)


```html
<ui-select ng-model="vm.mealFood[day][meal].name" theme="bootstrap" style="width: 300px;" title="Vælg fødevare...">
                                        <ui-select-match placeholder="Vælg fødevare...">{{$select.selected.danishName}}</ui-select-match>
                                        <ui-select-choices repeat="food in vm.foods | filter:{ danishName: $select.search }:true">
                                            <span ng-bind-html="food.danishName | highlight: $select.search"></span>
                                        </ui-select-choices>
                                    </ui-select>
```

**Comment by user378230** [comment]
As I said, maybe better to ask on stackoverflow. You could test also with simple `ng-repeat`
