### ISSUE TITLE
Controller 'uiSelect', required by directive 'uiSelectSort', can't be found!

### ISSUE THREAD

**Issue by AnatoliyLitinskiy** [angular-ui/ui-select#1729]
Here this error appears when child state is been opened

(just click on go to sub link and see console output)
https://embed.plnkr.co/yjCvvyIpGgwCUljy214X/

Tip: I'm not using $modal service.

You've closed ticket with same name:
https://github.com/angular-ui/ui-select/issues/1287#issuecomment-217652649

**Comment by user378230** [comment]
>`...ui-select/v0.13.2/dist/select.min.js...` 

We are on v0.18.1 now, can you confirm the issue still occurs on the latest version? (and post an updated plunkr) 

Thanks! :+1:

**Comment by modernptz** [comment]
I have the same issue with last version of ui-select, but old ui-router 0.2.15 and angular 1.2.30

**Comment by user378230** [comment]
Can you make a repro sample that doesn't rely on another library (except angular)?

**Comment by modernptz** [comment]
Actually it's issue about ui-select usage with ui-router, so I can't because it makes no sense

**Comment by Maximaximum** [comment]
I've got the same problem while trying to create my own directive that communicates with uiSelect

**Comment by Oliver-Gibson** [comment]
i had the same issue using the following code:

`<ui-select-match ng-bind="$item.name"></ui-select-match>`

ng-bind seems unusable hear.
