### ISSUE TITLE
Unable to (re)select an item with remove-selected set to false

### ISSUE THREAD

**Issue by pierregaste** [angular-ui/ui-select#1739]
### Bug description:
```remove-selected=false``` seems to have a bug when you select an item and unselect the same item. You couldn't select again. Item was not disabled but click has not effect.

Steps to reproduce:

1. Go to http://plnkr.co/edit/o0JWRLkoMbMBkFi0crqh (same as documentation)
2. Go to the _Disabling instead of removing selected items_ section
3. Select _Amalie_ and remove _Amalie_ from the list.
4. Try to select _Amalie_ again. Not working.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/o0JWRLkoMbMBkFi0crqh
### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5.8

UI-Select: 0.18.1

Bootstrap/Select2/Selectize CSS (if applicable): Bootstrap

**Comment by Jefiozie** [comment]
Hi @pierregaste ,

Had a look at this issue and indeed this is a problem in the latest version.
Have made some changes  could you verify if this solves your problem.

[Verify plunker example](http://plnkr.co/edit/GdmfOE8C51od3hqxhjlk?p=preview)

If it fix your problem I will commit my changes (after creating some tests)

**Comment by pierregaste** [comment]
Hi @Jefiozie!

Thanks for your answer!
I confirmed that your changes fixed the issue. I can't reproduce the bug anymore.

Thanks!
