### ISSUE TITLE
How to make ui-select ignore ngAnimate ?

### ISSUE THREAD

**Issue by ps3331333** [angular-ui/ui-select#1741]
I found what I believe it's a bug: when ui-select element it's in an Angular UI modal I have to click twice for the cursor to show in the input field. I read other threads, and removing ng-Animate from the application fixed the problem.

But I need the animation in other parts of my application. How to disable ng-Animate only for ui-select? How to disable the animation feature in ui-select?

This is the markup:

    <ui-select ng-model="dsSelected.sk">
         <ui-select-match>
		<span ng-bind="$select.selected.nm"></span>
        </ui-select-match>
    	<ui-select-choices refresh="funcAsync($select.search)" refresh-delay="0" 
												repeat="item in (dsList | filter: $select.search)">
                              <span ng-bind="item.nm"></span>
         </ui-select-choices>
       </ui-select>

**Comment by Jefiozie** [comment]
Maybe just add `$animate.enabled(false, element);` in your select.js?

**Comment by ps3331333** [comment]
where should I add it? here?

    compile: function(tElement, tAttrs) 
       $animate.enabled(false, tElement);

**Comment by Jefiozie** [comment]
I have used it once but this was in the link part that did help me (for a other problem of course).

**Comment by ps3331333** [comment]
here I added it but didn't work :(

uis.directive('uiSelectSingle', ['$timeout','$compile','$animate', function($timeout, $compile,$animate) {
  return {
    restrict: 'EA',
    require: ['^uiSelect', '^ngModel'],
    link: function(scope, element, attrs, ctrls) {
    	
      $animate.enabled(false, element);

**Comment by Jefiozie** [comment]
Maybe it is a version related thing? Can you share a plunker where you can reproduce this issue?
Also try it on stackoverflow.

> // changes the enabled state for an element and its children
$animate.enabled(element, true);
$animate.enabled(element, false);

[$animate documentation](https://docs.angularjs.org/api/ng/service/$animate)

**Comment by ps3331333** [comment]
this worked for me, returning always null:

  // Use $injector to check for $animate and store a reference to it
  ctrl.$animate = (function () {
      return null;
  })();
