### ISSUE TITLE
parse in ng-model only one field

### ISSUE THREAD

**Issue by teo89** [angular-ui/ui-select#1745]
I have the follow select 
```
<div ui-select ng-model="edit.data.status"
							name="status" search-enabled="false">
							<div ui-select-match>
								<span ng-bind="$select.selected.text"></span>
							</div>
							<div ui-select-choices repeat="item in edit.statusList" >
								<div ng-bind="item.text"></div>
							</div>
						</div>
```
But I can not make ng-model to take only one of item from selected object. There is any way to do that. In old select we have had the "q-options-model-value" 

I find that: http://plnkr.co/edit/Tj3SVw89qWyivjJz5Iyd?p=preview but i don't know how it works
I have version angular-ui-select: 0.18.1 angular: 1.5.8

**Comment by user378230** [comment]
Your question isn't very clear, but maybe you a trying to bind only a single property to your `ng-model`? 

In which case you need to use correct syntax in repeat:

```
person.email as person in people 
```
Here `ng-model` value will be email.

If that answer, then let us know so we can close. Thanks.

**Comment by teo89** [comment]
Hello, yes that was my question thank you.
