### ISSUE TITLE
Assigned value missing from options for Single Property Binding

### ISSUE THREAD

**Issue by oxsam1412** [angular-ui/ui-select#1747]
Issue found with **Angular** v1.5.8 + **ui-select** v0.18.0
Simulated issue: http://fiddle.jshell.net/oxsam/bf1saLo2/3/

No issue with **Angular** v1.4.8 + **ui-select** v0.11.2
http://fiddle.jshell.net/oxsam/bf1saLo2/1/

**Comment by user378230** [comment]
Can you confirm issue is present in **latest** version? (v0.18.1)

**Comment by oxsam1412** [comment]
Looks good with v0.18.1. Thanks!
