### ISSUE TITLE
ui-select dropdown searchbox appears temporarily during the page load

### ISSUE THREAD

**Issue by sarathkumar6** [angular-ui/ui-select#1750]
It is hard to get the screenshot. During the page load or reload the drop-down with the search box appears for a fraction of second and disappears like a flash. Any reasons for that? Is it any existing issue?

**Comment by sarathkumar6** [comment]
Is it because of the flicker effect during page load(showing unfinished angular code?

**Comment by user378230** [comment]
Probably a usage issue, causing by slow connection/loading.

**Comment by sarathkumar6** [comment]
@user378230 I tried using ng-cloak but it is not working in IE and firefox coincidentally works in chrome. May be something wrong in the way using ui-select?

**Comment by sarathkumar6** [comment]
The flicker effect was caused due to the transparency of the dropdown. I've used opacity as 0 in the respective css class and it disappeared. Closing the issue.
