### ISSUE TITLE
ui-select width doesn't match up with Bootstrap grid length

### ISSUE THREAD

**Issue by nishantroy** [angular-ui/ui-select#1752]
[Working PLNKR](https://plnkr.co/edit/UOGaNGjEdpo2SZ5DOYHG?p=preview)

Steps to reproduce error: 

- Select a graph type
- Click Add Filter

The ui-select boxes don't fit in the bootstrap divs surrounding them. 

Do they not inherit the width/height?

**Comment by user378230** [comment]
Duplicate #1685?

**Comment by Jefiozie** [comment]
Had a quick look on your plunker but the select.js is a custom version or not?

**Comment by Jefiozie** [comment]
@nishantroy  adding the css as mentioned in #1685 by @user378230 iis also fixing this problem.

`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.4/select2-bootstrap.css">`

**Comment by nishantroy** [comment]
Thanks!
