### ISSUE TITLE
When ui-select-no-choice is not provided, the default element is always displayed

### ISSUE THREAD

**Issue by mdarveau** [angular-ui/ui-select#1753]
### Bug description:

@khanhto Since https://github.com/angular-ui/ui-select/commit/fcd1eb48e5b4dbe6d0305abcefb6c038901863ab, my UI has alignment problems. I tracked the bug down to some CSS on the ```ui-select-no-choice``` div. Turns out that if the ```ui-select-no-choice``` is not present, the default one (from ```src/bootstrap/select.tpl.html```) is placed in the DOM but *without* the ng-show attribute thus always present. 

Check the example in http://plnkr.co/edit/?p=preview and look at the DOM:
![image](https://cloud.githubusercontent.com/assets/390071/17459652/a160dade-5c0f-11e6-84c3-59084097f1de.png)

The ```ui-select-no-choice``` is present in the DOM and the ng-show is not applied. I guess that something is wrong in ```src/uiSelectDirective.js```.

Angular: 1.5.6

UI-Select: 0.18.1

Bootstrap: 3.3.6

**Comment by mdarveau** [comment]
Workaround: explicitly add a div with ```ui-select-no-choice``` and it will be hidden properly.

**Comment by khanhto** [comment]
That pull request was posted long ago, I really don't remember. From what you described, maybe we could apply ng-show to `select.tpl.html` to fix them problem. Can you confirm and post another pull request?

**Comment by user378230** [comment]
Your plunkr link is not valid...

As it is a styling issue, maybe a screenshot of the broken ui-select also.

**Comment by user378230** [comment]
Assuming user resolved their issue, closing.

**Comment by mdarveau** [comment]
Create PR https://github.com/angular-ui/ui-select/pull/1784
