### ISSUE TITLE
Missing caret in multiple selection (Bootstrap theme)

### ISSUE THREAD

**Issue by tompascall** [angular-ui/ui-select#1754]
### Bug description:

Caret is missing in multiple selection mode using Bootstrap theme.  
  
While in simple selection mode the `ui-select-match` directive generates the following element: `<i class="caret pull-right">`, in multiple mode this element is completely missing.

### Link to minimally-working plunker that reproduces the issue:

You can see it at the official example: [multiple selection](http://angular-ui.github.io/ui-select/demo-multiple-selection.html)

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular:
1.5.0
UI-Select:
0.19.1
Bootstrap/Select2/Selectize CSS (if applicable):
Bootstrap: 3.1.1

**Comment by user378230** [comment]
This appears to be intentional styling decision, its also not in select2

**Comment by Stoffel-KT** [comment]
If we do need it, is there a way to still include it?
