### ISSUE TITLE
Bootstrap themed multi-select not styled properly

### ISSUE THREAD

**Issue by batjko** [angular-ui/ui-select#1755]
### Bug description:

Using the bootstrap theme (Bootstrap is properly installed), the input box is unstyled and gets pushed down by selected tags (multiple mode).
Some of the elements, like the div that shows the choices, clearly accept the Bootstrap. And behind the unstyled input field is a properly styled form-control element. 
It's just this stupid input field that shouldn't be there. 

How do I get rid of it without losing functionality?
I'm not sure if this is a bug with the multi-select? Any advise is much appreciated.

**Before selection:**
![image](https://cloud.githubusercontent.com/assets/7287076/17510555/565144f2-5e17-11e6-999e-1f4a5e594f41.png)

**Dropdown during selection:**
![image](https://cloud.githubusercontent.com/assets/7287076/17510567/615fa2b2-5e17-11e6-8b84-179fd50cff3b.png)

**After selecting two items:**
![image](https://cloud.githubusercontent.com/assets/7287076/17510572/6b74b9a4-5e17-11e6-9de6-9697622b4985.png)

### Code snippet
```html
<ui-select multiple="true" close-on-select="true" theme="bootstrap" ng-model="selectedStatuses" ng-disabled="disabled" on-select="ctrl.onStatusSelect($item)" on-remove="ctrl.onStatusDeselect($item)">
  <ui-select-match allow-clear="true" placeholder="Available Statuses">{{$item.name}}</ui-select-match>
  <ui-select-choices repeat="status in (ctrl.statusArray | filter: $select.search) track by status.id" position="auto">
    <div ng-bind-html="status.name | highlight: $select.search" class="form-control"></div>
  </ui-select-choices>
</ui-select>
```

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: **1.5.0**

UI-Select: **0.18.1**

Angular-Bootstrap: **1.1.2**

**Comment by user378230** [comment]
You missed:

>### Link to minimally-working plunker that reproduces the issue:

maybe you forgot to include `select.css`

**Comment by batjko** [comment]
Hi there, 
Yes it seems the missing select.css is the problem. I have it included in the app, but it's structured in a very convoluted way (lots of includes and aggregates of dependencies via gulp) so I'm not sure why it doesn't get loaded. 

I'll close this off for now. Thanks for the tip.
