### ISSUE TITLE
automatic assignment of ng-model matches in multiple

### ISSUE THREAD

**Issue by aibekmamatov** [angular-ui/ui-select#1756]
#### link to PLunker
[https://plnkr.co/edit/jWnLCGrhFEtywqMfArt2?p=preview](https://plnkr.co/edit/jWnLCGrhFEtywqMfArt2?p=preview)

After loading datas (Roles) ui-select-match doesn't automatically assign the values.

```jade
ui-select(ng-model='entry.doc.approval.roles_id', theme='bootstrap', multiple='true')
  ui-select-match(placeholder='Select roles...')
    span {{$index+1}}. {{$item.data.approval_name || $item}}
  ui-select-choices(repeat='role._id as role in (Roles | filter:{data:{approval_name:$select.search}}) track by role._id', stock-dict='Roles')
    span(ng-bind="role.data.approval_name")
```

```javascript
TypeError: Cannot read property '_id' of undefined
    at checkFnMultiple (select.js:1600)
    at Array.<anonymous> (select.js:1616)
    at ngModelWatch (angular.js:27547)
    at Scope.$digest (angular.js:17277)
    at Scope.$apply (angular.js:17552)
    at done (angular.js:11697)
    at completeRequest (angular.js:11903)
    at XMLHttpRequest.requestLoaded (angular.js:11836)
```

for example:
if i have ng-value:
```javascript
entry.doc.approval.roles_id = ["e4c6dca9-758e-43c8-b199-7d25b7e69296"]
```

and after loading datas of Roles
```javascript
Roles = [
  {
    _id:"e4c6dca9-758e-43c8-b199-7d25b7e69296",
     "data": {
        "approval_name": "Director"
      }
  }
]
```

it returns in ui-select-match:

##### 1. e4c6dca9-758e-43c8-b199-7d25b7e69296

but this should have been:

##### 1. Director

_______________________

**Comment by user378230** [comment]
@aibekmamatov Please provide plunkr as requested in issue template.

**Comment by aibekmamatov** [comment]
@user378230 all is ready

**Comment by user378230** [comment]
I had a look at this and it is because you use `role._id as` and `track by role._id` you can only use one or the other. 

Together they don't work, this is similar to `ngOptions. Will leave this open so I remember to add a note to wiki.

**Comment by aibekmamatov** [comment]
@user378230 thank you, it works.

**Comment by user378230** [comment]
[Usage warning added](https://github.com/angular-ui/ui-select/wiki/ui-select-choices/#warning-select-as-and-track-by)
