### ISSUE TITLE
in multiple select mode, the search text is not cleared until you focus on the input again

### ISSUE THREAD

**Issue by ericdecarli** [angular-ui/ui-select#1760]
### Bug description:
with multi select enabled, if you start typing in the input and select a choice, the text you searched in the input remains, even with uiSelectConfig.resetSearchInput = true, until you click/focus the search input again

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/cQJiIwW7zMZpYmm4NAhl?p=preview

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5

UI-Select: 0.19.1

Bootstrap/Select2/Selectize CSS (if applicable): all

**Comment by user378230** [comment]
I think @Jefiozie tried to fix this, or something similar, in #1746 let's see if he can have a look 😃

**Comment by Jefiozie** [comment]
Did a quick check and I looks like there is a difference between my initial commit and the one that is committed in the merge. Will have a look later today (i hope)

**Comment by Jefiozie** [comment]
So I had a look made some changes and here is a example [plunker](http://plnkr.co/edit/MnZlINXec0AFwG1WvYiZ?p=preview) you can test.
Struggling with the tests for this spcific issue and how to implement it so need some time for this.
Hopefully will have this before end of this week.
