### ISSUE TITLE
How to set the width of the options list?

### ISSUE THREAD

**Issue by ps3331333** [angular-ui/ui-select#1768]
I have a ui-select with a list that is too wide, how to adjust the width?

**Comment by Jefiozie** [comment]
I think you missed the template for creating a issue :wink: 

Can you share a plunker?

**Comment by ps3331333** [comment]
Please see [plunk](http://plnkr.co/edit/ihdM2jYCtJlwj6TpKUup?p=preview) 

I'd like to make the list of options less wide, what's the CSS element?

**Comment by Jefiozie** [comment]
It will get the css of the bootstrap libariy and I think the width is minimum 160px.
Have a look at the class '.dropdown-menu', still I believe this is not something where you should use this channel for.

Hopefully you have enough information if not maybe you could ask it on stackoverflow.

**Comment by user378230** [comment]
> Hopefully you have enough information if not maybe you could ask it on stackoverflow.

Agreed. Closing as usage issue.
