### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by markusguenther** [angular-ui/ui-select#1769]
### Bug description:
You recommend to install ui-select with npm, but the npm package is really outdated and needs a new release.

I am not sure if the issue is right at this place, but I thought that the npm package also belongs to the team.

https://www.npmjs.com/package/angular-ui-select

Would be great to use the npm way without adding the github repository ;)

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5.8

UI-Select: 0.12.100 but wants lastest

**Comment by Rankel** [comment]
Hello the correct npm package name is ui-select.

https://www.npmjs.com/package/ui-select

**Comment by user378230** [comment]
> Installation Methods

>npm

>```
$ npm install ui-select
```
>bower

>```
$ bower install angular-ui-select
```

Closing.
