### ISSUE TITLE
Dropdown and input text showing up on a different line

### ISSUE THREAD

**Issue by dishant8** [angular-ui/ui-select#1771]
Hey,
  I am new to ui-select. So execuse me if my issue is very trivial. 

I am following simple steps for setting up ui-select. But I seem not to solve the issue of this css. Input text and drop down are not in sync. This might be a bootstrap issue, though not sure. 

![ui-select-1](https://cloud.githubusercontent.com/assets/11712691/17667979/46dd4f44-62d5-11e6-823f-34d819b48cb1.JPG)

![ui-select-2](https://cloud.githubusercontent.com/assets/11712691/17667946/1c8b57a4-62d5-11e6-8083-7da5fd3e58c0.JPG)

This is the ui-select tag.

    <ui-select ng-model="test"  theme="bootstrap">
    
    <ui-select-match placeholder="Select">
        {{$select.selected}} 
    </ui-select-match>

    <ui-select-choices repeat="experiment in testExperiments | filter : $select.search">
        {{experiment}}
    </ui-select-choices>
    </ui-select>

I went through the issues but did not find any relevant solution. Let me know if you need anything else from my side

**Comment by user378230** [comment]
You should ask general support questions on somewhere like stackoverflow, github is primarily for bug reports/feature requests.

Make sure you are including `select.css`

**Comment by dishant8** [comment]
ok. Thank you.

**Comment by abobwhite** [comment]
I am hitting this issue. @user378230 How did you make the case that this was not a bug?

**Comment by user378230** [comment]
@abobwhite this issue doesn't appear on our examples as far as I can see so it's a usage/set up issue not a bug.

**Comment by abobwhite** [comment]
@user378230 It actually was a ui-select issue for bootstrap. I had to add this:

.ui-select-container.form-control {
    padding: 3px 3px !important;
  }

The issue is documented here: https://github.com/angular-ui/ui-select/issues/1559
