### ISSUE TITLE
bootstrap v4 css error

### ISSUE THREAD

**Issue by qq645381995** [angular-ui/ui-select#1781]
use bootstrap v4  select style no ok

**Comment by user378230** [comment]
Bootstrap v4 is still in alpha, no point trying to support it yet. Furthermore your issue lacks and detail, no screenshots/plunkr. 

Closing.

**Comment by qq645381995** [comment]
Now there is support for 4 that style is certainly very ugly, and do not need screenshots, just do not know when you support 4

**Comment by user378230** [comment]
I've updated wiki to state users require bootstrap v3, thanks! :smiley:

**Comment by qq645381995** [comment]
Error: [$sce:unsafe] Attempting to use an unsafe value in a safe context.
