### ISSUE TITLE
reset the ui-select

### ISSUE THREAD

**Issue by niraj-thakur** [angular-ui/ui-select#1786]
Do we have any method by which we can reset the ui-select element back to its placeholder value ?

**Comment by Jefiozie** [comment]
As described in the template  of creating a new issue:

> The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

I think you could better ask these kind of questions at stackoverflow.

**Comment by niraj-thakur** [comment]
Okay Thanks
