### ISSUE TITLE
Enable disabled items and remove them when clicked

### ISSUE THREAD

**Issue by andersonmelo** [angular-ui/ui-select#1789]
In the example "Disabling instead of removing selected items" ( http://angular-ui.github.io/ui-select/demo-multiple-selection.html ), would be possible to enable the items that have been disabled after clicking again? You would have to remove them from the list (ui-select-match).
![disabling](https://cloud.githubusercontent.com/assets/14007217/18105562/3971e1aa-6ed6-11e6-9cd3-539053143801.jpg)

**Comment by Jefiozie** [comment]
I think you are asking on how to change the behavior of the disable after selecting, right?

As described in the initial template for a new issue this is just for bugs or features. Other questions it is best to ask these on stackoverflow.

See the issue template:

> The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

**Comment by andersonmelo** [comment]
When you disable the item that is in the "ul", remove the "input".
Sorry, but it would be interesting if it were implemented in ui-select.

**Comment by Jefiozie** [comment]
@user378230 ,  do you think this will be a good feature? Maybe as directive?

**Comment by andersonmelo** [comment]
I solved the problem temporarily by adding`ng-click=\"$selectMultiple.removeChoice($select.selected.indexOf($select.items[$index]));$event.stopPropagation();\"`

But please add this functionality in the ui-select, it would be very useful.

**Comment by user378230** [comment]
Duplicate #1651

**Comment by wellaya** [comment]
@andersonmelo where is the place we need to add you mentioned code
