### ISSUE TITLE
Cannot close ui-select-no-choice dialog

### ISSUE THREAD

**Issue by brockclayton** [angular-ui/ui-select#1792]
### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.4.8

UI-Select: 0.18.0

Bootstrap/Select2/Selectize CSS (if applicable):

**Comment by user378230** [comment]
Github issues are reserved for feature requests and bug reports. You will probably have a better response for angular queries on somewhere like stackoverflow. 

Thanks :smiley:
