### ISSUE TITLE
onSelect callback is executed when limit is reached in multiple mode

### ISSUE THREAD

**Issue by orestisioakeimidis** [angular-ui/ui-select#1794]
### Bug description:

The `onSelect` callback is executed when `limit` is reached for multiple select. That shouldn't be the case because nothing is actually selected.
### Link to minimally-working plunker that reproduces the issue:

[Example](https://plnkr.co/edit/cA1HjRkYEzSmXX4P5Dcx?p=preview)
### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5.8

UI-Select: 0.19.4

**Comment by Jefiozie** [comment]
What do you believe is the best way to fix this. Just a check on the limit but then the items in the list are still clickable? Or disable all the items?

**Comment by orestisioakeimidis** [comment]
I think that all items should also be disabled. You have reached the limit and you are not allowed to select any more, so it makes sense to disabled them.

**Comment by orestisioakeimidis** [comment]
What is the status of this case?

**Comment by Jefiozie** [comment]
Sorry didn't have a lot of  time. I agree on the disabled state when you are on the defined limit.  Maybe you can make a PR? Happy to review?
