### ISSUE TITLE
Keep Placeholder activated in multipleSelect component

### ISSUE THREAD

**Issue by fabioel** [angular-ui/ui-select#1796]
Hello!
I stumbled upon a problem today that is caused by the following lines:
`uiSelectMultipleDirective.js`

```
ctrl.getPlaceholder = function(){
        //Refactor single?
        if($select.selected && $select.selected.length) return;
        return $select.placeholder;
      };
```

I would like to have my placeholder activated even after I selected the first option in a multiple select component. Is there a plan to refactor this? Maybe to use a property like: `keepPlaceholder`

Thanks!

**Comment by user378230** [comment]
See discussion in #1433 Can you put together a PR with tests for it?

**Comment by DmitryGonchar** [comment]
@user378230 Which approach is better to fix this?

Should we move `getPlaceholder` to uiSelectSingle and change `$selectMultiple.getPlaceholder()` to `$select.getPlaceholder()` in all three templates?

Or, another option is to add
```
if($select.getPlaceholder)
          return $select.getPlaceholder();
```

into existing function

**Comment by Jefiozie** [comment]
Hi @DmitryGonchar I think it is best to go for the first option. Are you going to make the PR?

Thanks.

**Comment by DmitryGonchar** [comment]
@Jefiozie I will have time only at the weekend. Are you sure option 1) will not break some other use cases? Or is it all covered with tests?

**Comment by mouss-delta** [comment]
Hi, I would also need this feature for ui-select multiple, I have navigated through the three tickets concerning this feature (the current one, [#1433](https://github.com/angular-ui/ui-select/pull/1433) and [#1612](https://github.com/angular-ui/ui-select/issues/1612)). And I am not sure, the feature is present for ui-select non-multiple and not present for ui-select multiple, that's it?

**Comment by mouss-delta** [comment]
Any update on that ticket please?

**Comment by DmitryGonchar** [comment]
@Jefiozie what about answers for https://github.com/angular-ui/ui-select/issues/1796#issuecomment-286695077?

Option 2 seems to be a safer one if you are not sure

**Comment by DmitryGonchar** [comment]
@fabioel and others 
When this PR is merged - you can get the desired behavior (on damand) with something like this:

```
angular.module('myApp').directive('myAppUiSelectPlaceholderAlwaysVisible', function() {
  return {
    require: 'uiSelect',
    link: function($scope, $element, attrs, $select) {
      $select.getPlaceholder = function () {
        return $select.placeholder;
      }
    }
  }
});
```

And then add this directive to the `<ui-select>` html element where this behavior is needed

Or you can override this function globally, of course

**Comment by mouss-delta** [comment]
Hi @DmitryGonchar thanx for your fix I have tested it locally by copying/pasting your code, and it works well. Any idea when is scheduled the next release with your pull request, this ticket is nearly one year old?

**Comment by DmitryGonchar** [comment]
When @Jefiozie merges it, I am not the maintainer.

**Comment by rhyskoedijk** [comment]
+1 on merging this please. @Jefiozie
