### ISSUE TITLE
ng-model not working with a simple variable on $scope

### ISSUE THREAD

**Issue by tkrotoff** [angular-ui/ui-select#18]
Inside [`demo.html`](https://github.com/angular-ui/ui-select/blob/master/demo/index.html#L38), if you replace `ng-model="data.custom"`:

``` HTML
<ui-select ng-model="data.custom">
  ...
</ui-select>
```

by `ng-model="myItem"`:

``` HTML
<ui-select ng-model="myItem">
  ...
</ui-select>
```

`$scope.myItem` never gets set.
It's like [`ngModelCtrl.$setViewValue(newVal)`](https://github.com/angular-ui/ui-select/blob/master/src/select.js#L57) cannot bind to a simple variable `$scope.myItem`.

It will work only if `ng-model` is an object:
- `demo.js`: `$scope.myItem = {}`
- `demo.html`: `ng-model="myItem.data"`

I could not figure out why, any idea?

**Comment by thiagodelgado111** [comment]
Sorry for bringing it back to life again, but... $parent arent updating my model also

```js
function controller(){
   $scope.editingGeneralCondition = {};
}
```

```js
<ui-select name="generalCondition" ng-model="$parent.editingGeneralCondition" ng-required="true" theme="bootstrap">
```

Most probably, I'm making some foolish mistake here.

**Comment by ProLoser** [comment]
@thiagodelgado111 just do `obj.property` instead of `$parent.property`
