### ISSUE TITLE
Event on-select not fired if data selected in controller

### ISSUE THREAD

**Issue by gabrieleciech** [angular-ui/ui-select#1801]
### Bug description:
As the title points out the on-select event is not fired if the selected data is set in the controller and not in the view.

### Link to minimally-working plunker that reproduces the issue:
See the official plunker that shows how the event on selection works and then uncomment line number 154. As you can see the event calls counter remains to 0 and not to 1 as am I expecting.

Is this an issue or an intended behaviour?
Thanks

**Comment by user378230** [comment]
This is intended, onSelectCallback is called when users **select** an option.
