### ISSUE TITLE
Docs- multiple selection's items are not shown after selection

### ISSUE THREAD

**Issue by tamir3021** [angular-ui/ui-select#1804]
There appear to be a bug in displaying the selected items in multiple selection example page:
http://angular-ui.github.io/ui-select/demo-multiple-selection.html

**Comment by user378230** [comment]
Looks fine to me, can you provide screenshot or something? Maybe a dependency didn't load for you or something. 

Closing for now.

**Comment by tamir3021** [comment]
@user378230 , I'm attaching a screenshot of the issue. As you can see, the binding to the text that supposed to display the selected items is not working.
![uiselect](https://cloud.githubusercontent.com/assets/13499847/18587807/68872942-7c2c-11e6-8647-72073ea070d8.png)

**Comment by tamir3021** [comment]
I believe the problem lies with the paragraph being bound to a wrong object, one that doesn't match the ng-model's.
If necessary, I'll be more than happy to PR.

**Comment by user378230** [comment]
Screenshots help! I think this will be fixed by #1793

**Comment by tamir3021** [comment]
Yes, seems like it.
