### ISSUE TITLE
How to search on translated labels

### ISSUE THREAD

**Issue by svpace** [angular-ui/ui-select#1811]
### Bug description:
Cannot make search work with localized labels (ie. angular-translate)

### Link to minimally-working plunker that reproduces the issue:
Just concatenated 'translated_' before the items for demonstration purposes

https://plnkr.co/edit/wCTjtjXkSi6ujKgVTfBi?p=preview

Typing 'translated' in the serach box filters out all options. Apparently the filter is being aplied to the original items instead of the translated ones.

All the expressions bellow results in "Expected expression in form of '_item_ in _collection_..." erros:
- "item as ('translated_' + item) in items"
- "('translated_' + item) for item in items"
- "translated_' + item in items track by item"

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular 1.5.8:

UI-Select: 0.19.4

Bootstrap/Select2/Selectize CSS (if applicable): Bootstrap 3.3.7

**Comment by user378230** [comment]
`repeat` attribute in `ui-select` doesn't support complex values. You could maybe try translating the item first or using some kind of custom filter that does translate then filter.

**Comment by majli** [comment]
@svpace, how did you solve the issue after all?

**Comment by svpace** [comment]
Not very elegantly I'm afraid. Basically I pre-translated all options in the controller and stored as a key value object:
```
<ui-select name="authority" ng-model="vm.keys" multiple>
	<ui-select-match>
		{{$item.value}}
	</ui-select-match>
	<ui-select-choices repeat="item.key as (key, item) in vm.items | filter: {'value': $select.search}">
		<div ng-bind-html="item.value | highlight: $select.search"></div>
	</ui-select-choices>
</ui-select>
```
