### ISSUE TITLE
[Append to body] disable parent scroll when append to body

### ISSUE THREAD

**Issue by trangchuvn** [angular-ui/ui-select#1812]
Hi Guy!
at the moment, if we set the "append to body" option is true, when the users scroll, the positions of select box is not changed. so it's wrong. Like this
http://i1112.photobucket.com/albums/k490/trangchuvn_2000/download.png
I think when the users open the select box, we will disable the parent scroll. it's a good solution (same with select2). Can you tell me how to do it please? Thank you

**Comment by user378230** [comment]
`uis:activate` is broadcast when ui-select is opened [see here](https://github.com/angular-ui/ui-select/blob/0bcd70a335791db756f25efbdcdf96bd5bdaf947/src/uiSelectController.js#L114). 

For further help might be better to ask on somewhere like stackoverflow.
