### ISSUE TITLE
Bootstrap 4 theme

### ISSUE THREAD

**Issue by silentFred** [angular-ui/ui-select#1815]
Hi all,

I'm keen to contribute a Bootsrap 4 theme. Where do I begin? And anything I need to know before I start? Is it too soon for a BS4 theme? I'm on a project converting to BS4 and it would be beneficial to have this.

Cheers,

**Comment by silentFred** [comment]
I'm thinking of rather adding an optional way of externalizing the theme templates. That way, anyone can implement their own flavor without incorporating it into ui-select

**Comment by arkin-** [comment]
We also came here looking for a Bootstrap 4 theme 👍

**Comment by davidnknight** [comment]
+1

**Comment by peio72** [comment]
+1

**Comment by user378230** [comment]
> I'm thinking of rather adding an optional way of externalizing the theme templates. That way, anyone can implement their own flavor without incorporating it into ui-select

@silentFred You can already do this, see [`src/uiSelectDirective.js#L9`](https://github.com/angular-ui/ui-select/blob/master/src/uiSelectDirective.js#L9):

```js
    templateUrl: function(tElement, tAttrs) {
      var theme = tAttrs.theme || uiSelectConfig.theme;
      return theme + (angular.isDefined(tAttrs.multiple) ? '/select-multiple.tpl.html' : '/select.tpl.html');
    }
```
Simply specify your own theme name (eg. `bootstrap4` and it will load those templates). 

You'll probably want to run the templates into the template cache as ui-select does in [`dist/select.js#L2376`](https://github.com/angular-ui/ui-select/blob/master/dist/select.js#L2376)

**Comment by user378230** [comment]
Closing this as BS4 is still in alpha, I don't see much point to maintain against an unstable dependency. 

PRs can still be submitted or better, open a new repo and provide a link. :smiley:

**Comment by bmontgomery** [comment]
I started on a fork that is intended to support a Bootstrap 4 theme. https://github.com/bmontgomery/ui-select

**Comment by Pehesi97** [comment]
Is anyone developing a bootstrap 4 theme as its in beta?

**Comment by g3n35i5** [comment]
+1

**Comment by Siniliote** [comment]
+1

**Comment by andzejsw** [comment]
I just added some css, cause js was toggling needed class!
`.ui-select-bootstrap.open .dropdown-menu {
  display: block;
}`

**Comment by francisfontoura** [comment]
I started to work on a pure css adapter that intends to make `bootstrap` theme fully support Bootstrap v4. https://github.com/francisfontoura/angularjs.ui-select.bootstrap4.shim.css
