### ISSUE TITLE
Hello. Is it possible for multiselect to get into inputbox focus even if user clicks on white area above the row where input is created. If I have already items selected I'd like not to ask user where he should click.

### ISSUE THREAD

**Issue by drogovoy** [angular-ui/ui-select#1819]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular:

UI-Select:

Bootstrap/Select2/Selectize CSS (if applicable):

**Comment by Jefiozie** [comment]
Really?  Can you close it down and make a real issue?
