### ISSUE TITLE
Select2 theme support

### ISSUE THREAD

**Issue by silentFred** [angular-ui/ui-select#1821]
Hi there,

Anyone know what version of select2 styling is supported? 

Cheers,

**Comment by Jefiozie** [comment]
I just replyed on your chat on gitter.

Example is telling: http://cdnjs.cloudflare.com/ajax/libs/select2/3.4.5/select2.css

**Comment by silentFred** [comment]
@user378230 or @aaronroberson What do you think about giving an option to externalize theme templates? I initially wanted to contribute a Bootstrap 4 theme. Later on our designers gave me some nice css customizations for Select2. Turns our quite a lot changes from Select2 3.x to 4.x and the ui-select templates don't work at all.

Thoughts?

**Comment by Jefiozie** [comment]
You have found out that this was already possible right? If so can you close this one down?

**Comment by silentFred** [comment]
@Jefiozie sure thing
