### ISSUE TITLE
Selected item is not being marked as selected in the choices

### ISSUE THREAD

**Issue by SpencerKaiser** [angular-ui/ui-select#1829]
### Bug description:

After selecting an option from the dropdown (or in my case, after retrieving dropdown data using `refresh`), the selected option is not marked as selected in the dropdown. Instead, the first item in the list is shown as selected (or will be selected on return).

Sorry if this is a duplicate but I've been searching for hours and haven't found anything helpful. Ideally, you would be able to specify a key with which to match the selected item and the corresponding item in the dropdown. If this exists, it's not clearly documented. If it doesn't exist, please add this functionality if possible!!

The issue is reproducible in the ui-select plunker ["Bind to Single Property"](http://plnkr.co/edit/x9pHRB?p=preview) as well as most of the other plunkers. To reproduce, open the ui-select and choose "Adrian" then open the ui-select again and "Adam" will be marked as selected. This plunker binds the model to a specific value of the object, but even if you change it to where the selected object is the exact object from the dropdown, the issue persists.

UI-Select: 0.19.3

EDIT: Example [Plunker](http://plnkr.co/edit/WU40fM?p=preview) which is discussed below

**Comment by Jefiozie** [comment]
Hi @SpencerKaiser ,  with marked I believe you mean the blue Highlighted color?

**Comment by SpencerKaiser** [comment]
Exactly. From a user's perspective the currently selected item in the drop down should be highlighted after reopening a drop down which was previously interacted with. Does that make sense? 

I've noticed the issue is completely reproducible if the matching object in the drop down and and model value have different shapes (like an additional key). 

Ideally, I'd be able to specify a `match-by` key like `id` which would be the value that the drop down uses to highlight the currently selected value.

**Comment by Jefiozie** [comment]
okay, and when searching the highlighting should go to the searched item?

**Comment by SpencerKaiser** [comment]
Exactly, so I guess the first item in the list?

**Comment by Jefiozie** [comment]
Just did a check against the newest version 19.4. Looks like it is working already:
Can you verify this? [Plunker](http://plnkr.co/edit/AFqflBwGGaTwKV2Y9V93?p=preview)

**Comment by Jefiozie** [comment]
@SpencerKaiser, did you have some time to check out if this problem is resolved in the latest version?

**Comment by SpencerKaiser** [comment]
I'll check first thing in the morning so you can close this up if it works. Sorry for the delay!

**Comment by SpencerKaiser** [comment]
@Jefiozie Hey Jeffrey, so [I modified that plunkr](http://plnkr.co/edit/WU40fM?p=preview) to show the exact situation I'm dealing with and hopefully it'll highlight the issue. 

Let's say I need some sort of ui-specific attribute on my items (`country` in my example) but the item I returned from the server doesn't have that attribute... if I set the value of the ui-select to the differently-shaped, server-returned object, it cannot match that item against an option from the list.

What I'm suggesting is to allow a key to be specified that the ui-select uses to find the corresponding match in the dropdown, regardless of shape. Something like this:

`<ui-select-choices ... highlight-selected-by-key="email">`

This could be out of scope for this project, but I would be very very happy if this became a feature! And thanks for taking the time to work with me on this!

**Comment by user378230** [comment]
No need for a new attribute, highlighting should be made to work with `track by` if it is specified, otherwise it should just do an object comparison. 

I think that might be triggered at [uiSelectController.js#L94](https://github.com/angular-ui/ui-select/blob/master/src/uiSelectController.js#L94)

**Comment by SpencerKaiser** [comment]
@user378230 I just tried to update [the plunker I referenced above](http://plnkr.co/edit/WU40fM?p=preview) and I couldn't get it to work. Any chance you could take a look at it and see if you can get it to function with `track-by`? If you can get it to work in that example, I'd be pretty pumped haha

**Comment by Jefiozie** [comment]
Thanks for pointing that out @user378230 didn't know/ see that.

**Comment by user378230** [comment]
@SpencerKaiser 
> I just tried to update the plunker I referenced above and I couldn't get it to work. Any chance you could take a look at it and see if you can get it to function with track-by? If you can get it to work in that example, I'd be pretty pumped haha

I updated select.js in the plunkr with the changes in my previous reply and then used `track by person.name` in the `repeat` attribute.

**Comment by SpencerKaiser** [comment]
@Jefiozie I just updated (my plunker)[http://plnkr.co/edit/WU40fM?p=preview] with the solution @user378230 suggested and it worked! Can we get this change added to the project??

@user378230 Thank you for your help!!

**Comment by Jefiozie** [comment]
I don't know @user378230 is the maintainer of this project so if this is a thing they want to support maybe.

**Comment by user378230** [comment]
> @Jefiozie I just updated my plunker with the solution @user378230 suggested and it worked! Can we get this change added to the project??
> 
> @user378230 Thank you for your help!!

You definitely could do! All it will take is a PR with tests 😄, we also need a few other places updated to use track by if specified though. eg:

https://github.com/angular-ui/ui-select/blob/master/src/uiSelectMultipleDirective.js#L119
https://github.com/angular-ui/ui-select/blob/master/src/uiSelectSingleDirective.js#L27
https://github.com/angular-ui/ui-select/blob/master/src/uiSelectController.js#L249
https://github.com/angular-ui/ui-select/blob/master/src/uiSelectController.js#L333

Anywhere it checks if the item is in the source list basically.

**Comment by SpencerKaiser** [comment]
@user378230 I'd love to contribute, I just feel like I would be stealing your work though! I just saw the test directory so I have some examples to work from. When I get a chance I'll make the change and create a PR.

**Comment by user378230** [comment]
> @user378230 I'd love to contribute, I just feel like I would be stealing your work though! I just saw the test directory so I have some examples to work from. When I get a chance I'll make the change and create a PR.

Check the commit history, you'll see most work in the last 6 months is not mine, if you want something fixed you'll need to submit a PR for it. 👍

**Comment by Jefiozie** [comment]
Hi @SpencerKaiser , did you have find the time to submit this PR? 😄

**Comment by Jefiozie** [comment]
@SpencerKaiser , did you see my previous comment?

**Comment by SpencerKaiser** [comment]
@Jefiozie I did end up getting around to it 😔 I haven't forgotten but we've been pretty slammed on our current project and I haven't had too much free time. Feel free to close this issue if you'd like, I think there is enough context in your responses to help other users and hopefully I'll get a chance to get a PR together at some point in the future. Thank you again for your help!!!

**Comment by Jefiozie** [comment]
@SpencerKaiser , thanks for yout reply. Will close it down for now if somebody feels to make a PR or you find the time for the PR reopen it.
