### ISSUE TITLE
To many elements in dom

### ISSUE THREAD

**Issue by emikelsoft** [angular-ui/ui-select#183]
Is it possible to add the items dynamically to the dom only when needed, e.g. when the user searches or opens the searchresult? The problem is if you have a lot of ui-select elements on a single page you produce a lot of bindings /watches and it quickly slows down the performance. In our special case we have 6 ui-selects for currencies and another 6 for countries, this leads to +2500 items in the dom and slowing down the page.

**Comment by edenchen123** [comment]
this change might cause another serious performance issue,
if I have 500 items each time when i open and close the dropdown list all these 500 items will be re-rendered and destroyed again and again.....

**Comment by edenchen123** [comment]
//.attr('ng-if', '$select.open') //Prevent unnecessary watches when dropdown is closed

**Comment by dimirc** [comment]
@edenchen123 originally we were using ng-show but that was causing that even if the dropdown is closed, to have all the watches fired. In case you only have 1 or 2 ui-select on the page it wont be an issue, but if using multiple controls with many items, then that was a big performance hit.
