### ISSUE TITLE
There is no setting options for minimum-input-length !

### ISSUE THREAD

**Issue by kenanyildiz** [angular-ui/ui-select#1833]
### Bug description:
When I want to setup ui-select as general from Config, everything is OK except one thing. There is no minimum-input-length options. I want to be general a config to setup all ui-select in my project. I can set for example `uiSelectConfig.refreshDelay = 1000` but, i can't set `uiSelectConfig.minimumLengthInput = 3;` In my opinion, its can have this params. Other hand, i have to create another service named called uiSelectConfigService own project. Its heard me wrongly.

**Comment by user378230** [comment]
Hi @kenanyildiz! You could submit a PR to fix this. It seems like it was missed whenever that feature was implemented :smile:
