### ISSUE TITLE
Bootstrap style for multi-select is broken

### ISSUE THREAD

**Issue by jgoux** [angular-ui/ui-select#184]
Hello.
I want to thanks all of the contributors for the multi-select feature! :+1: 
I have a little problem with the bootstrap theme. I use bootswatch's themes in my application (Paper) and it seems that the multi-select doesn't support it much.
It's exactly the same markup as bootstrap and the ui-select dropdowns **without** multi-select work just fine.
On the screen you can see two "single" ui-select and the multi-select at the third position : 
![multi-select](https://cloud.githubusercontent.com/assets/1443499/4219000/789bf50e-38f6-11e4-994c-bb856e36541a.jpg)

As you can see, the text input is cut and there is no caret icon. I noticed that ui-select set a fixed width to the text input but if I manually set width:100% to it, it's fine.

I'll be very grateful if anyone can show me a solution. ^^

**Comment by user378230** [comment]
I'm closing this as a legacy issue as its close to two years old now and doesn't have a repro sample. 

If you believe its still relevant please reopen with a plunkr (or similar) against the latest version of ui-select (currently v0.15.0)
