### ISSUE TITLE
Array of strings isn't working.

### ISSUE THREAD

**Issue by seungwooshin** [angular-ui/ui-select#1840]
### Bug description: I think the "Array of strings" example in http://angular-ui.github.io/ui-select/demo-multiple-selection.html is not working. When I click on the select box the dropdown list simply does not open. As a result, I am able to deselect colors that are already put in there, but am not able to select any color.

I am using the latest version of Chrome and have tested on multiple machines.

**Comment by Jefiozie** [comment]
I think the example is broken I thought there was a pr with the fix. But doesn't look like it.
Can you maybe submit a pr?

**Comment by Jefiozie** [comment]
Hi did you see my previous comment?

**Comment by seungwooshin** [comment]
Hi, I believe the source code at https://github.com/angular-ui/ui-select/blob/master/docs/examples/demo-multiple-selection.html is already correct. Do you know why http://angular-ui.github.io/ui-select/demo-multiple-selection.html is not synced with that?

**Comment by Jefiozie** [comment]
Yes I believe so. The maintainers should push it to the plunker examples.

**Comment by Jefiozie** [comment]
@seungwooshin  but i think this issue can now be closed right as it is fixed in the code.

@user378230 , do you know if this needs to be pushed still to the example pages?

**Comment by Jefiozie** [comment]
@seungwooshin it is fixed now can you close the case?
