### ISSUE TITLE
Tagging behaviour on click or on key Enter is different

### ISSUE THREAD

**Issue by Jefiozie** [angular-ui/ui-select#1844]
### Bug description:
When using a multiple select and use tagging and a custom label the behavior of the on click or on enter is different.
### Link to minimally-working plunker that reproduces the issue:
[Example plunker](http://plnkr.co/edit/6nLiW3RrvCD1zONF8wKn?p=preview)

Steps to reproduce:

1. type a custom word in de the first dropdown.
2. Hit enter
3. the added item is only the word you just typed.
4. Type a custom word again.
5. Now select it with the mouse click.
6. you have the word + the label added to the list.

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular:1.5
UI-Select:19.4
Bootstrap/Select2/Selectize CSS (if applicable):
Bootstrap

**Comment by Jefiozie** [comment]
@user378230 , don't believe this is default behavior or the behavior we want right? If needed i can have a look for a fix?

**Comment by user378230** [comment]
See #1806 

(Yes it needs fixing :smile:)

**Comment by Jefiozie** [comment]
Missed that one will close this one down than. :smile:
