### ISSUE TITLE
_ is not working inside Angular ui-select select2 theme search box

### ISSUE THREAD

**Issue by suryamuppalla** [angular-ui/ui-select#1847]
For the first time when I type " _ " keyword along with text it is allowed in search box before I select any item from the list dropdown. But after selecting one item from the list, if suppose I want to search items again then it is not allowing me to type " _ " key in the search box

Kindly help me.

**Comment by user378230** [comment]
Can you follow the instructions in the issue template and provide a link to an example/plunkr that demonstrates the problem.

Will reopen when you provide a demo, thanks.
