### ISSUE TITLE
ui-select-no-choice  causes freeze in input using version 0.19.5

### ISSUE THREAD

**Issue by ctwoolsey** [angular-ui/ui-select#1849]
### Bug description:
When using "ui-select-no-choice" directive, the select/input box will freeze not allowing user to use backspace or type more.  The freeze happens when the "ui-select-no-choice" gets activated. This goes away by using Angular 0.19.4.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/143DHto51RkOBhk9pCmX?p=preview

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5.8

UI-Select: 0.19.5

Bootstrap/Select2/Selectize CSS (if applicable):
BS:  2.2.0  BS CSS: 3.1.1
sanitize 1.3

**Comment by naXa777** [comment]
It's reproducible even without `<ui-select-no-choice>`.

**Comment by user378230** [comment]
There was a major issue with `v0.19.5` (I think this was it) please upgrade to the latest version `v0.19.6` and your issue should be resolved.
