### ISSUE TITLE
Ui-select-choices element removed permanently from template in some cases

### ISSUE THREAD

**Issue by zollinger** [angular-ui/ui-select#1851]
### Bug description:

If ui-select with grouped options is nested within an ng-if that gets toggled a couple of times quickly without first activating the dropdown, the ui-select-choices-row element will be permanently removed from the template and thus, the options will be empty.

Simply removing the code that removes those elements from the template solves this immediate issue:
https://github.com/angular-ui/ui-select/pull/1850

This code is supposed to prevent a memory leak, however there was some refactoring done here since and I don't see why this should be a problem now. Maybe the author of  
https://github.com/angular-ui/ui-select/pull/1365 could create a plunker to reproduce the memory leak?

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/cpMpE6M9MU9FUfhCEoQN?p=preview

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5.8

UI-Select: 0.19.6

Bootstrap/Select2/Selectize CSS: n/a

**Comment by user378230** [comment]
Thanks will look at getting the PR merged asap
