### ISSUE TITLE
A little confusion with release versions

### ISSUE THREAD

**Issue by Vohidjon** [angular-ui/ui-select#1854]
I tried to download v0.19.5 from [releases page](https://github.com/angular-ui/ui-select/releases) . However, after unpacking tar.gz file I see v0.16.4 in comments

/*!
 * ui-select
 * http://github.com/angular-ui/ui-select
 * Version: 0.19.4 - 2016-10-19T19:26:25.444Z
 * License: MIT
 */
Which version is this? Thanks

**Comment by user378230** [comment]
You mean v0.19.4 not v0.16.4 I assume

Sometimes the version numbers in the /dist folder are not updated with the correct number during the gulp build process but the built files themselves should have the correct code though.

Note: `v0.19.6` is the latest version.
