### ISSUE TITLE
Feature Request: Allow items to be selected multiple times

### ISSUE THREAD

**Issue by chrisparton1991** [angular-ui/ui-select#1855]
### Bug description:
An item cannot be selected multiple times, and I can't find a configuration to enable this behaviour.

This has been discussed before, but I haven't been able to find a clear answer on whether or not this use case is supported.

I'm building an LED animation sequencer, and I want users to be able to specify colours for various effects (e.g. fill lights with a Blue-Red-Blue gradient).

Ideally I'd like to be able to select the same item multiple times, like this (mockup):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img width="307" alt="multiple" src="https://cloud.githubusercontent.com/assets/13063119/20480526/fbe61106-b036-11e6-997e-0eb04477c284.png">

### Link to minimally-working plunker that reproduces the issue:
https://plnkr.co/edit/cTOcau8kJhTECgAuPM7W?p=preview

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS
**Angular:** 1.5.8
**UI-Select:** 0.19.7
**Bootstrap/Select2/Selectize CSS (if applicable):** Bootstrap 3.3.7

**Comment by chrisparton1991** [comment]
I've had a crack at implementing this, just by changing the ui-select Plunkr:
https://plnkr.co/edit/7KyteAUvcV8Yfw22CDo1?p=preview

I'm happy to raise my changes as a PR if there's interest.

**Comment by user378230** [comment]
To be honest I don't think this quite fits with the direction of the component, sorry.

You might instead want to look at the typeahead components available in angular-strap or angular-ui/bootstrap as all you are really after here is the auto-suggestions part. 

If there is significant interest we can look at reopening but for now I think this a rather niche requirement so I'm going close.

**Comment by chrisparton1991** [comment]
Thanks for your consideration @user378230. I've implemented this feature in my fork. The feature and unit tests can be seen at https://github.com/chrisparton1991/ui-select/commit/154d308a119dbe76d551c31639c3ada005c28966 in case anyone wants this in the future.

Have a great day!

**Comment by user378230** [comment]
I just thought, if you're using object you can just have a select callback that adds a new copy of item to the select list with one of properties different, this will register it as a different object and let the user select it again.

**Comment by chrisparton1991** [comment]
Thanks for the suggestion @user378230. I had considered this too but I was concerned about edge cases and maintainability (e.g. removing extra items when they are unselected, handling arbitrary amounts of duplicate selection, handling multiple ui-select instances using the same dataset etc).

The solution I implemented in my work is working great for me so far, so I'll stick with that. If I find some show stopping issue I'll look into the callback approach. Also the callback approach could be good for people who can't use a fork of the repo in their project for whatever reason.

Here's mine in action (I need to add more colours, but the concept is there):
<img width="215" alt="multi" src="https://cloud.githubusercontent.com/assets/13063119/20593044/e3d7454e-b284-11e6-9341-347bb8b48006.png">
