### ISSUE TITLE
select.min.js via npm repository not working

### ISSUE THREAD

**Issue by ErickWendel** [angular-ui/ui-select#1859]
Downloading via npm is not working (via bower works normally)

### Link to minimally-working plunker that reproduces the issue:
![error via npm](https://cloud.githubusercontent.com/assets/8060102/20720558/c084139a-b646-11e6-8eaa-f616e5130e2f.PNG)

 
"angular": "^1.5.9", 
"ui-select": "^0.19.6"

**Comment by user378230** [comment]
You're not loading the correct npm module... look at your paths.
