### ISSUE TITLE
Tagging and empty field

### ISSUE THREAD

**Issue by lkuklis** [angular-ui/ui-select#1860]
### Bug description:
When you type any text in tagged control with spaces and fastly hit enter than you receive an empty tag added to list ([screenshot](https://i.imgur.com/tAuPSK0.png)) [screenshot](https://i.imgur.com/R55E6CR.png) For me seems like a bug.

### Link to minimally-working plunker that reproduces the issue:
[http://plnkr.co/edit/z8KDrqwFUGbO2jWRA5Ni?p=preview](http://plnkr.co/edit/z8KDrqwFUGbO2jWRA5Ni?p=preview)
I have taken plunker from other issue and I have added tagging attribute.

**Comment by user378230** [comment]
Dupe #1267
