### ISSUE TITLE
Click on selector icon does not open droppown

### ISSUE THREAD

**Issue by DioNNiS** [angular-ui/ui-select#1862]
### Bug description:
Issue appears on the lastest version of the component ("ui-select": "0.19.6").
Issue reproduced only if bootstrap theme is used and search edit box is disabled.

### Link to minimally-working plunker that reproduces the issue:
Try official example: http://angular-ui.github.io/ui-select/demo-disable-search.html

**Comment by Jefiozie** [comment]
Hi @DioNNiS , tested this in chrome look like it is working. Maybe i'm using the wrong browser?

**Comment by SparksFyz** [comment]
related to #1797

**Comment by DioNNiS** [comment]
@Jefiozie issue reproduced on Mac
Chrome 54.0.2840.98
Firefox 50.0.2

Looks like issue really related to #1797

**Comment by dsisoev** [comment]
Hi guys,
I think that this issue related with:

```javascript
  // Toggle dropdown
  ctrl.toggle = function(e) {
    if (ctrl.open) {
      ctrl.close();
      e.preventDefault();
      e.stopPropagation();
    } else {
      ctrl.activate();
    }
  };
```

I just changed it to:
```javascript
  // Toggle dropdown
  ctrl.toggle = function(e) {
    if (ctrl.open) {
      ctrl.close();
    } else {
      ctrl.activate();
    }
    e.preventDefault();
    e.stopPropagation();
  };
```
And all works well.

Thanks.

**Comment by Jefiozie** [comment]
Maybe one of you guys can have a look and make a PR for it? Maybe @dsisoev ?

**Comment by Jefiozie** [comment]
Looks like the pr #2011 has fixed the problem. Could you verify?

**Comment by amarmechai** [comment]
yes, the pr #2011 fix the problem for me. thanks

**Comment by Jefiozie** [comment]
Closing down @amarmechai  checked if this issue is fixed. If needed it can be reopend.
