### ISSUE TITLE
The release v0.19.6 contains the release code v0.19.5

### ISSUE THREAD

**Issue by khusamov** [angular-ui/ui-select#1867]
The [release v0.19.6](https://github.com/angular-ui/ui-select/releases/tag/v0.19.6) contains the release code v0.19.5:
```
/*!
 * ui-select
 * http://github.com/angular-ui/ui-select
 * Version: 0.19.5 - 2016-10-24T23:13:59.434Z
 * License: MIT
 */
```

As a result, [editing (issue 453)](https://github.com/angular-ui/ui-select/issues/453) was not included in the release v0.19.6.

**Comment by eventengine** [comment]
+111!!

**Comment by bman61** [comment]
FYI Every tag release dist folder contains the previous version number

**Comment by eventengine** [comment]
> FYI Every tag release dist folder contains the previous version number

What is that fu**ing mean?! 0_o

**Comment by bman61** [comment]
All v0.19.6 dist files contain Version: 0.19.5
All v0.19.5 dist files contain Version: 0.19.4
All v0.19.0 dist files contain Version: 0.18.1

When a developer is debugging in the browser and looking at the ui-select source file they tend to use the version # in the file itself and not some obscure knowledge that a defective process to release a new build tag contains the previous release # and therefore the developer should know that when they see 0.19.5 it really means they are looking at the 0.19.6 release. Simple and obvious. Not.

**Comment by Jefiozie** [comment]
I understand the confusion but as this is already from 0.18.1) i'm closing the issue as we won't fix this right now. 

If somebody is willing to have a look at it and make a PR i'm happy to review
