### ISSUE TITLE
Fully bluring and focus control

### ISSUE THREAD

**Issue by Si7ius** [angular-ui/ui-select#1871]
I use label as placeholder in inputs. When input is focused label rises up on input. So I want to do that also in ui-select. But I can't detect focusing and bluring the select. After initial blur ui-select changes to search input and after second blur it really blurs. uis-open-close didn't help. So how to detect does it fully blured or not?

**Comment by Jefiozie** [comment]
Hi, 

As described in the issue template we would like to have a full description with plunker and version.
In the case we can have a look at the issue and reproduce the issue much quicker. 

Please update your issue as requested in the issue template.

> The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein. 
> ### Bug description:
> ### Link to minimally-working plunker that reproduces the issue:
> ### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS
> Angular:
> UI-Select:
> Bootstrap/Select2/Selectize CSS (if applicable):
> 

Thanks :smile:
