### ISSUE TITLE
wrong calculate width of dropdown

### ISSUE THREAD

**Issue by bmsdave** [angular-ui/ui-select#1874]
### Bug description:
wrong calculate width of dropdown if set attr append-to-body=true

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/ZW8ICdBGHvBXwr6oEQuw?p=templates

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS:
Angular 1.3+
UI-Select 0.19.5
Bootstrap 3.3.7

**Comment by bmsdave** [comment]
https://github.com/angular-ui/ui-select/pull/1873 this pull request fix it

**Comment by bmsdave** [comment]
Some changes here?

**Comment by Jefiozie** [comment]
See PR
