### ISSUE TITLE
track by object.property is not working

### ISSUE THREAD

**Issue by itaditya** [angular-ui/ui-select#1875]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
Using "| filter: $select.search track by person.name" is giving the error given in link.
[Angular error link](https://docs.angularjs.org/error/$parse/syntax?p0=track&p1=is%20an%20unexpected%20token&p2=35&p3=tag.name%20%7C)

**Comment by Jefiozie** [comment]
@itaditya  can you share a plunker for this?

**Comment by itaditya** [comment]
Sorry, I'm unable to provide it as I removed the code with another plugin

**Comment by Jefiozie** [comment]
Okay, well to see if this is a bug / issue there needs to be a plunker. If you cannot provide one i think it is best to close this down. And re-open/ create a issue when the issue occurs again.  Or do you have a other solution for reproduction?

**Comment by itaditya** [comment]
Ok then
