### ISSUE TITLE
Add carot in between two selected values using left and right key.

### ISSUE THREAD

**Issue by ArunVashishtha** [angular-ui/ui-select#1883]
I am trying to add cursor between two elements in angular ui select with multiple options.So, Is there any solution to append a new element between pre-select options in angular ui-select?

eg. - I have selected two options - Apple, Banana    in ui-select now i would like to add new element in between both of these elements  like - Apple,Mango, Banana. without removing Banana.

**Comment by Jefiozie** [comment]
Hi @ArunVashishtha , As far as I know there is not a default feature for this. Don't think this will be a feature that will be implemented. Maybe you can ask around on stackoverflow?

Hope I provided some information and you can continue to fix your feature 😄 

p.s. the general purpose is to report bugs of the ui-select as this is not a default option I think it is best to close this issue if you have enough info. Thanks.
