### ISSUE TITLE
Use with Webpack

### ISSUE THREAD

**Issue by morious** [angular-ui/ui-select#1884]
Trying to use UI Select with Webpack 2.
Module is loading properly but the component does not seem to render as expected.
No errors in console.

Has anyone been able to use ui select with webpack 2?

Thanks!

**Comment by morious** [comment]
Closing as non issue had an error somewhere else....

**Comment by benjaminmbrown** [comment]
@morious Having a similar issue with webpack 2 & ui-select. I'm betting it is similar to what you experienced. Do you remember what you did to resolve?

**Comment by jbeaudoin11** [comment]
Same..
![image](https://user-images.githubusercontent.com/10903391/32022973-f3bdb41a-b9a5-11e7-88c5-77c8fb6065d0.png)

There is an invisible (white) textfield between the label and the rectangle..
I'm using webpack 3.. Maybe there is a problem with css-module too ?

**Comment by benjaminmbrown** [comment]
@jbeaudoin11  I found it just now. the CSS isn't packaged with the ui-select.js, so you need to add it separately. 

I found the simplest way to do this is adding an alias for the css in webpack's resolve:

`  resolve: {
    alias: {
      'ui-select-css': path.resolve('./node_modules/ui-select/dist/select.css')
     },`

Then, you can import this alias into your module:

`import 'ui-select-css;`

And it should pick up the CSS. This solved some other questions / issues I was running into as a new webpack user. Let me know if it works for you.

**Comment by jbeaudoin11** [comment]
It removed the box but still doesn't work well..
The invisible textarea is still there, still invisible, and doesn't act like a select/dropdown... It's a span so i can't interact with it

**Comment by benjaminmbrown** [comment]
@jbeaudoin11  Awesome, glad I could help. Hope it helps others too.

**Comment by jbeaudoin11** [comment]
I though i had a js problem but doesn't looks like it..
I think it's not compatible with bootstrap 4, when i use select2 theme it works well but doesn't with b4..
