### ISSUE TITLE
spinner-class should use glyphicon

### ISSUE THREAD

**Issue by brianchance** [angular-ui/ui-select#1893]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

The spinner-class should use the glyphicon class instead of declaring the font on ui-select-refreshing. If you try to replace `glyphicon-reverse` with a font awesome (`fa fa-spinner fa-pulse fa-fw`) does not work because ui-select-refreshing declares the font.

Spinner class should be `glyphicon glyphicon-refresh ui-select-spin`

and ui-select-refreshing should be
```
.ui-select-refreshing {
    position: absolute;
    right: 0;
    padding: 8px 27px;
 }
```

I can do a PR if you like.

Angular: 1.5.8

UI-Select: 0.19.5

Bootstrap/Select2/Selectize CSS (if applicable): Bootstrap 3.2

**Comment by Jefiozie** [comment]
Hi @brianchance , can you so a example plunker on the desired solution? Thanks.

**Comment by brianchance** [comment]
I think this should do it... http://plnkr.co/edit/bp2LTqnrYE0rJV0mhw5b?p=preview 

1st select uses a local declaration for what the current .ui-select-refreshing is
2nd select has updates to the select.js and select.css (noted)
3rd builds on 2nd by replacing with font awesome

**Comment by Jefiozie** [comment]
okay, so basically you want to change the css class and the default css config for the refresh function. 
The reason for this is that in the ui-select as is you cannot change the font.

Correct?

**Comment by brianchance** [comment]
yes.

**Comment by Jefiozie** [comment]
okay, looks like a valid bug. Can you make the PR?
