### ISSUE TITLE
customize template for not allowed

### ISSUE THREAD

**Issue by sh977218** [angular-ui/ui-select#1896]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
If it's not allowed to edit.  Can there be an option to have a customized template.

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular:

UI-Select:

Bootstrap/Select2/Selectize CSS (if applicable):

**Comment by Jefiozie** [comment]
@sh977218 , I think you are meaning that you want to make a custom template to support as example bootstrap 4. See: [1815](https://github.com/angular-ui/ui-select/issues/1815#issuecomment-256035354)

Hope this will help you, if i'm misunderstanding your question please let me know.

**Comment by Jefiozie** [comment]
Closing it down as there is no feedback or any other action needed. If more information is needed please reopen issue.
