### ISSUE TITLE
Problem With Multi Select

### ISSUE THREAD

**Issue by carlosCeron** [angular-ui/ui-select#190]
Hi, Guys

i use this code, the angular-ui-select 0.3.0 and try on this example with multi select arrays , the combobox show me the colors but when choose one, no add like pills in the field justlike this.

i use, Array of strings with angular-ui-select 0.3.0, anyone know what it's the problem Thanks

http://plnkr.co/edit/juqoNOt1z1Gb349XabQ2?p=preview 

![1](https://cloud.githubusercontent.com/assets/2660128/4234589/78ab8cae-39b8-11e4-8815-6ace12564f9c.png)
![2](https://cloud.githubusercontent.com/assets/2660128/4234587/7871cc6c-39b8-11e4-839b-3db5ef673564.png)
![3](https://cloud.githubusercontent.com/assets/2660128/4234588/7887bd4c-39b8-11e4-84a2-8304ca3ffb88.png)

**Comment by user378230** [comment]
Closing this issue as over a year old and on an outdated version of ui-select. 

If you believe its still relevant please reopen with a plunkr (or similar) against the latest version of ui-select (currently v0.15.0)
