### ISSUE TITLE
CSS Selectors

### ISSUE THREAD

**Issue by neysimoes** [angular-ui/ui-select#1901]
There are very specific CSS selectors, which disturbs the styling of the component. It really is necessary to have selectors such as:

`.ui-select-multiple.ui-select-bootstrap input.ui-select-search`

It really necessary?

**Comment by neysimoes** [comment]
![captura de tela 2017-01-31 as 14 32 15](https://cloud.githubusercontent.com/assets/5016853/22474094/1b349b6e-e7c2-11e6-931d-0cf5732a831b.png)

Four selectors and IMPORTANT?!?!

**Comment by Jefiozie** [comment]
Hi is this a bug , question or what is it? Maybe you could be a little more specific instead of just opening a issue and not really describe the issue you have? Thanks

**Comment by Jefiozie** [comment]
Closing it down as there are no actions or feedback. If needed you can reopen this issue.
