### ISSUE TITLE
UI-Select not working with Angular 1.4.8.

### ISSUE THREAD

**Issue by lvasilev1** [angular-ui/ui-select#1904]
I am experiencing the following issue in ui-select with Angular 1.4.8, I have some values populated in the drop-down and the 'ng-model' attribute is linked to an object 'order.table' defined in my controller (app.js). I am trying to print out the value of 'main.order' as I select different values in the drop-down,  but nothing shows up. If I change to Angular 1.4.3 it works fine. Here is a link to the Plunker that reproduces the problem. If you want to see that it works with Angular 1.4.3, replace 1.4.8. with 1.4.3. on line 10 of file index.html:

[http://plnkr.co/edit/FUW33kSr8QNZV1LrT8K5?p=preview](http://plnkr.co/edit/FUW33kSr8QNZV1LrT8K5?p=preview)

Angular: 1.4.8.

UI-Select: 0.19.5

Bootstrap/Select2/Selectize CSS (if applicable): 3.3.4

What's causing this?

**Comment by Jefiozie** [comment]
Hi @lvasilev1 , 

I checked this with the example page and changed the latest angular version to angular 1.4.3.
Don't see the problem there can you check this example out en describe the difference on it?
 [Example PLunker](http://plnkr.co/edit/8rEpyxiXJVGMcjqrgSsV?p=preview)
Thanks

**Comment by lvasilev1** [comment]
@Jefiozie,

The problem is happening when I use angular 1.4.8. I tried using all of the includes form your Plunker in mine and it is still not working.

**Comment by Jefiozie** [comment]
Looks like it has some thing todo with `ng-maxlength="40"`. Removed that one and it worked.

**Comment by lvasilev1** [comment]
Wow sure enough! That's a bizarre issue. Any idea idea why this would cause a problem with 1.4.8?

**Comment by Jefiozie** [comment]
No idea, don't get the use case also why you would like to do this in this way?

**Comment by lvasilev1** [comment]
What do you mean? My use case is simple, I just need to have a searchable drop-down with some pre-defined values, I need to know which value the user selected, and perform some action when they switch values. That's all.

**Comment by Jefiozie** [comment]
Indeed I was not clear, I don't get why the ngMaxLength is on the ui-select. Based on the use case you describe I don't see why it should be there.

Can we close this issue as we found the cause, don't see this as a real ui-select bug(for now). 
Let me know what you think.

**Comment by lvasilev1** [comment]
Yes, thank you. I got sidetracked, but the issue is resolved.
