### ISSUE TITLE
How to add ng-pattern to input field of ui-select

### ISSUE THREAD

**Issue by oziian** [angular-ui/ui-select#1907]
It is possible?
`<ui-select ng-model="value.selected" ng-pattern="/^[a-zA-Z\s\-]*$/" theme="bootstrap" reset-search-input="false" on-select="selected($select)">
    <ui-select-match>{{value.selected.name}}</ui-select-match>
    <ui-select-choices repeat="item in values track by $index" refresh="refreshAutocomplete($select.search)" refresh-delay="500">
        <div ng-bind-html="item.name | highlight: $select.search"></div>
    </ui-select-choices>
</ui-select>`

**Comment by Jefiozie** [comment]
Hi, 

Can you maybe be a little bit specific on what the question is and what the use case it?
Then people can have a look at it. 

Thanks.

**Comment by oziian** [comment]
I want to limit input in ui-select input field. Must be available to enter only the characters a-zA-Z, a dash, and space

**Comment by Jefiozie** [comment]
Okay, and you tried the pattern already? I don;t know any way to do this in the ui-select it self.

**Comment by oziian** [comment]
I can't try pattern, because I don't know how add pattern property to input input field in ui-select.

**Comment by Jefiozie** [comment]
Right okay, don't think this will work. The `ngpattern ` is bind to the `model `and you want to use it on search. I think you could do something like this with a custom filter. A example: [filter example](http://stackoverflow.com/questions/35902023/create-an-angular-regex-filter).

**Comment by oziian** [comment]
What do I actually need. Users of the service, people from different countries, and can enter a value in their own language. Words are not in English break requests. I can check the value after the input, but I would like to conduct a field as using "pattern" (http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_pattern).
As a result I need to restrict the entry of banned symbols, or warn the user.

**Comment by Jefiozie** [comment]
There is no functionality that will support this at this moment and I don't think there will be any changes to resolve this. 

Maybe you could handle it by making a custom filter/ directive or something?

**Comment by oziian** [comment]
I think, we can close this ticket. I added a check using ng-change.
