### ISSUE TITLE
Multi dropdown sortable don`t work in mobile

### ISSUE THREAD

**Issue by neekeeir** [angular-ui/ui-select#1910]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular:

UI-Select:

Bootstrap/Select2/Selectize CSS (if applicable):

**Comment by Jefiozie** [comment]
Closing it down, please open a issue as asked in the template.

Thanks :smile:
