### ISSUE TITLE
the cursor acting wierd when i open two dopdown or more

### ISSUE THREAD

**Issue by linkstops** [angular-ui/ui-select#1913]
i'm using select2 v3.4.8 coz i'm using angular ui.select, So when i open two select2 or more in the same time the cursor refreshing wirdly and the page go to down(footer),
Could someone help me out how to force select2 to close automaticly when i open another one, or how to stop that wird acting of cursor (focus in all opened select2 at the same time) when multiple select 2 are opened in the same page.

**Comment by Jefiozie** [comment]
Hi, 

As described in the issue template please provide a plunker so that people can reproduce this issue. 
For now i will close this issue down if needed you can reopen it.

Thanks :smile:
