### ISSUE TITLE
Mobile keyboard opening for `search-enabled: false`

### ISSUE THREAD

**Issue by PezCoder** [angular-ui/ui-select#1927]
### Bug description:
For mobile devices & having `search-enabled="false"` on ui-select, on clicking on select box it opens the mobile keyboard which is not an expected behaviour.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/oHWnJFvcgc2SV6UXm7b5?p=preview
^ Took the plunker from official docs & I just put `search-enabled="false"` on ui-select, no other changes.
Open the above plunker in mobile & click on select box, it should open the keyboard.

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: ^1.4.8

UI-Select: ^0.19.6

Bootstrap/Select2/Selectize CSS (if applicable):
Using bootstrap css

Device: Android v4.2.3

### Hypothesis & possible solution
<img width="692" alt="screen shot 2017-03-01 at 12 51 45 pm" src="https://cloud.githubusercontent.com/assets/8057916/23450366/cc155dea-fe80-11e6-8a3f-5b235a6473ce.png">
I'm seeing the above in the dom, for the above mentioned settings, which i think is unnecessary.
Rather than disabling it, we shouldn't even render the input box if `search-enabled` is false.

### Temporary fix (until this is fixed)
```css
input[type="search"], .ui-select-focusser {
    display: none;
}
```

**Comment by Jefiozie** [comment]
Hi , so i tried to reproduce this issue but I cannot find the same behavior. 
I don't agree on the disabled part the disabled can be triggered in multiple ways so this is a won't fix.
Is the workaround not the best solution for your use case at this moment?

Second i want to mention that mobile is not a specific target for this library so if somebody (or you) makes a pr i'm happy to review.

**Comment by PezCoder** [comment]
@Jefiozie What i want to say is if a developer has decided to not show the search bar by passing `search-enabled="false"` then why are we even rendering that, it creates unnecessary scope variables.
What do you think ?

**Comment by mohamadnajiya** [comment]
Hello,

You can always check if  searchEnabled is true then focus the element in select.js

```
  ctrl.focusSearchInput = function (initSearchValue) {
      ctrl.search = initSearchValue || ctrl.search;
      if (ctrl.searchEnabled) {
          ctrl.searchInput[0].focus();
      }
   
  };
```

And don't forget to add skipFocusser="true"  to your element.

**Comment by Amidda** [comment]
I can confirm the exact same unexpected result. Using search-enabled="false" and skip-focusser="true"

I have not been able to prevent the android keyboard from opening on activating the dropdown. This issue is not present in my iphone testing environment.

**Comment by mohamadnajiya** [comment]
Amidda,

Have you updated the focusSearchInput function in select.js file as mentioned above.
And try to use the below function after dropdown selection:
```
 setTimeout(function () {
            $(':focus').blur();
        })  
```

**Comment by ptmono** [comment]
I have same problem. It make slow in android to open keyboard input.
