### ISSUE TITLE
Issue with ui-select search input width

### ISSUE THREAD

**Issue by sainath168** [angular-ui/ui-select#1929]
Not sure exactly this comes on top of [#533](https://github.com/angular-ui/ui-select/issues/533) or [#1111](https://github.com/angular-ui/ui-select/issues/1111.)
Actually I guess that ui-select search input width is re-calculated after each tag is selected in the field. But will that be taking into consideration about the left and right margin/padding present inside the field. Let's say my requirement is something like http://plnkr.co/edit/KFfnv94f5eqBR0lKJxz0 (See stylings).
If you look, when we select tag then the cursor comes into next line, but tags you select are in correct position problem is only with search input width. Any idea?

Version of Angular (1.4) and UI-Select(0.12.1)

**Comment by Jefiozie** [comment]
Please update to the latest version of ui-select and verify if this is still a issue. 
For now closing it down as version 0.12.1 is already a really old version. 
If you need more help on your question regarding 0.12.1 i recommend stackoverflow.

Thanks
