### ISSUE TITLE
Create a Mobile Fallback to use default dropdown

### ISSUE THREAD

**Issue by brycefranzen** [angular-ui/ui-select#1941]
Not to remove the select2 functionality entirely, but to make it use the native mobile select dropdown instead of the select2 dropdown. However, all events should still fire as if selected from the select2 dropdown.

**Comment by Jefiozie** [comment]
Based on comments in [1069](https://github.com/angular-ui/ui-select/issues/1069#issuecomment-197324238) It is not something we are going to work on now. Main priority is to get enough bugs resolved and a stable library.

Will label it as wont fix and enhancement for future purposes.
