### ISSUE TITLE
Require select.css in node_modules

### ISSUE THREAD

**Issue by 50l3r** [angular-ui/ui-select#1942]
When i try to import 'ui-select' in my index.js with webpack it only loads the select.js file

`import uiselect from 'ui-select';`

This is the index.js in 'node_modules/ui-select/index.js:

```
require('./dist/select.js');
module.exports = 'ui.select';
```

Why dont load select.css like this:

```
require('./dist/select.js');
require('./dist/select.css');
module.exports = 'ui.select';
```

**Comment by Jefiozie** [comment]
Hi, I dont think there is any specific reason for this. Probably this was never needed (or no request of it). 
Could you provide a PR and maybe have a look if this will work for web and node? 

Thanks.

**Comment by 50l3r** [comment]
I use webpack and i need to import .js and .css file.

It's just a thing

**Comment by Chklang** [comment]
This require was remove by this commit : https://github.com/angular-ui/ui-select/commit/81b0f03b17fe5f99923f60de739e606046fe854c

I don't understand why me too

**Comment by Jefiozie** [comment]
So I had a look and I looks like it was a specific choice to remove this. [See this comment](https://github.com/angular-ui/ui-select/issues/1406#issuecomment-185871932)

**Comment by Jefiozie** [comment]
I think this is the answer on your question right?

**Comment by Jefiozie** [comment]
Clsoing it  down as I believe the answer is given.
