### ISSUE TITLE
Infinite Scroll with UI-select2 and angular -- Search is not working

### ISSUE THREAD

**Issue by akaash2512** [angular-ui/ui-select#1948]
I am using angular1 and ui-select2 dropdown theme.

I needed infinite scroll feature so i have added same function as well.

But the default search feature is not working with infinte scroll.

Can anyone please help ?

Please see issue here. Select2 dropdown with infinite scroll. Please check:
http://plnkr.co/edit/OwhFCyHz0mO1yZMj5UW5?p=preview

Angular: 1.2.18

UI-Select:  /*!
 * ui-select
 * http://github.com/angular-ui/ui-select
 * Version: 0.11.2 - 2015-03-17T04:08:46.474Z
 * License: MIT
 */

**Comment by Jefiozie** [comment]
HI @akaash2512 I think this is more a stackoverflow question as we dont have a infinite scroll by default. 
(see [Got a question or problem?](https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) Also i think it is best to upgrade to the latest version as the one you are using.

**Comment by chjones56** [comment]
I added the propsFilter to your ui-select-choices tag and it seem to work pretty good..

I changed this: 
    <ui-select-choices repeat="item in hugeList | limitTo:infiniteScroll.currentItems track by $index" 

to this: 
        <ui-select-choices repeat="item in hugeList  _**| propsFilter: {name: $select.search, email: $select.search}**_ | limitTo:infiniteScroll.currentItems track by $index"

**Comment by Jefiozie** [comment]
Thanks for the feedback. Closing the issue as it is resolved.

**Comment by sevmardi** [comment]
Hopefully you dont mind me following up on this one. I have implemented Infinite Scroll as well and following the chain what @chjones56  mentioned regarding search. The issue I am facing is the way the list is coming in. Let me show you. 
The list coming in like this.


![capture](https://user-images.githubusercontent.com/5328285/27433476-31b54f48-5755-11e7-9456-a9b2bb85e5eb.PNG)



If I do 


```
<ui-select-choices repeat="item in plates| propsFilter: {serial_number: $select.search} |  limitTo:infiniteScroll.currentItems track by $index" ui-disable-choice="item.selected == true"  refresh-delay="0"  infinite-scroll="addMoreItems()" infinite-scroll-distance="2" >
<div ng-bind-html="item.plate.serial_number | highlight: $select.search "></div>
</ui-select-choices>
```
This won't work given the serial_number is in an inner array.  How could I achieve this?
