### ISSUE TITLE
[$injector:unpr] Unknown provider: eProvider <- e <- uiSelectHeaderDirective after updating from  0.19.5 to 0.19.6

### ISSUE THREAD

**Issue by Sibiraj-Codes** [angular-ui/ui-select#1967]
### Bug description:
I updated from 0.19.5 to 0.19.6 today. I am getting the following error 

```
angular.js?_dp=1491996177792:14525 Error: [$injector:unpr] Unknown provider: eProvider <- e <- uiSelectHeaderDirective
http://errors.angularjs.org/1.6.4/$injector/unpr?p0=eProvider%20%3C-%20e%20%3C-%20uiSelectHeaderDirective
    at angular.js?_dp=1491996177792:66
    at angular.js?_dp=1491996177792:4789
    at Object.getService [as get] (angular.js?_dp=1491996177792:4944)
    at angular.js?_dp=1491996177792:4794
    at getService (angular.js?_dp=1491996177792:4944)
    at injectionArgs (angular.js?_dp=1491996177792:4969)
    at Object.invoke (angular.js?_dp=1491996177792:4995)
    at angular.js?_dp=1491996177792:8110
    at forEach (angular.js?_dp=1491996177792:403)
    at Object.<anonymous> (angular.js?_dp=1491996177792:8108)
```

Is there any breaking changes made.

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular-1.6.4
Bootstrap-3.3.7
UI select- 0.19.6

**Comment by Jefiozie** [comment]
Hi, 

There are no breaking changes only a new feature where you can add header/ footer.
Could you post a example plunker? So that I can have a look?

**Comment by hochi-vivovii** [comment]
This very same issue happens on me when I was on 0.19.6 updating to 0.19.7.

A temporary solution is to fall back to 0.19.6

**Comment by Jefiozie** [comment]
It is a problem in the new feature see [footer](https://github.com/angular-ui/ui-select/blob/master/src/uiSelectFooterDirective.js#L1)

Same goes for the header. will make a fix for this.

**Comment by hochi-vivovii** [comment]
I made a patch,
please review this PR https://github.com/angular-ui/ui-select/pull/1968

**Comment by Jefiozie** [comment]
@hochi-vivovii thanks in the mean time I had made the changes also. Will close yours down it contains the `dist/* `files.

**Comment by Jefiozie** [comment]
Reopen as this is not resolved yet.

**Comment by gpierrick** [comment]
Confirming I am getting the same issue

**Comment by zucker-rdrg** [comment]
Same issue ;/ patch version update breaks my app

**Comment by batista** [comment]
related issues? #1972 #1971 #1970

**Comment by hochi-vivovii** [comment]
@Jefiozie will there be a newer release to patch this? meanwhile do we just fall back to 0.19.6?

**Comment by Jefiozie** [comment]
Yes i think this is best. Still looking for the best option to resolve all problems. 
THinking about removing the complete tag but no sure if this will trigger npm etc. (pretty new to this all 😞 )

**Comment by batista** [comment]
@Jefiozie to remove tag on npm use [dist-tag](https://docs.npmjs.com/cli/dist-tag) in this case should be something like `npm dist-tag rm ui-select 0.19.7`. 
I'm no npm expert though, so please get confirmation from an alternative source before running it.

for bower i have no idea if that's even possible.

**Comment by thinkingmedia** [comment]
I think a 0.19.8 revert would be best. People like me will forget to remove the version lock from their bower or npm files.

**Comment by hochi-vivovii** [comment]
Agree coz now my project is stuck on 0.9.16 and would like to unlock asap.

**Comment by thinkingmedia** [comment]
You can overwrite bower's latest version.

```
bower install --save angular-ui-select
// then replace but do not save
bower install angular-ui-select#0.19.6
```

Next time you do an update it'll be upgraded to latest. Just wait until the fix is published.

**Comment by Jefiozie** [comment]
I'm looking at the problem now. 
Reverting is probably best so checking that option.

Can people verify that default behaviour is back to normal in this [plunker](http://plnkr.co/edit/EpC1JXwxPPOmAbrLerHR?p=preview)

**Comment by Jefiozie** [comment]
Updated the plunker examples could somebody verify this is working again?
Then I can push the changes.

**Comment by lchanouha** [comment]
@Jefiozie I don't have any errors anymore with "Version: 0.19.7 - 2017-04-15T14:28:36.649Z"

**Comment by shankarregmi** [comment]
@Jefiozie Still getting the same error. Tried versions `0.19.5`, `0.19.6` and `0.19.7` . With clean bower install as well. and NO LUCK.

**Comment by Jefiozie** [comment]
@lchanouha thanks for the verifying.

Hope i can send a new version pretty soon.

**Comment by tkserver** [comment]
For reference, I got: Error: $injector:strictdi Explicit annotation required on 0.19.7 and the error went away with version 0.19.6 on Angular 1.4.8.

**Comment by Jefiozie** [comment]
Just pushed a new version where I reverted the head/ footer feature hope this will solve all issues.

Please let me know.

**Comment by thinkingmedia** [comment]
@Jefiozie I'm not fetching the new version via bower. It's still installing 0.19.7.

**Comment by Jefiozie** [comment]
On [npm](https://www.npmjs.com/package/ui-select) is see that it is updated. 

However our versioning is a bit strange. When releasing `0.19.8` in the file itself is a reference to `0.19.7`.
Can you verify if this is the case?

This should be present in the `select.js` file:
```
 /*!
 * ui-select
 * http://github.com/angular-ui/ui-select
 * Version: 0.19.7 - 2017-04-15T14:28:36.649Z
 * License: MIT
 */
```

**Comment by thinkingmedia** [comment]
@Jefiozie This was a mistake on my part. I misread the bower output messages. I did receive 0.19.8 via bower update.

Thank you so much for your great plugin and help.

**Comment by Jefiozie** [comment]
Closing this issue as it seems to be resolved. See comments above. if not please let me know i will update / reopen the issue.

**Comment by msingh6** [comment]
Hi @Jefiozie , I have used code from [](https://jsfiddle.net/betonetotbo/0yfhe7pf)/, so can please share the details as in which files i have to be change for header and footer the code and what code. It will be so helpful if you provide it accordingly.

**Comment by Jefiozie** [comment]
The header and footer feature is removed from the latest as there ware many problems with it. Hopefully it will be in next release.
