### ISSUE TITLE
Weird behaviour in version 0.19.7

### ISSUE THREAD

**Issue by ldusoswa** [angular-ui/ui-select#1970]
options appearing above the dropdown.

![image](https://cloud.githubusercontent.com/assets/6940301/24957490/c6d4d7b0-1f83-11e7-9bca-8d5509a4f870.png)

layout/rendering issues

![image](https://cloud.githubusercontent.com/assets/6940301/24957544/f0bdb66e-1f83-11e7-8f77-fe9e7355bba0.png)

For now we have statically defined version 0.19.6. It would be great if semantic versioning was enforced in this codebase where possible. I know that sometimes bug fixes carry functionality changes with them and i don't know the details in this case, but it seems like this should at least be a minor version bump, if not a major version.

**Comment by Sibiraj-Codes** [comment]
yes.. Some CSS needs to be fixed

**Comment by ldusoswa** [comment]
Thanks for the quick response. And thanks for making a great lib.

**Comment by jkjha** [comment]
This killed my 2 hours. :(

**Comment by zuzusik** [comment]
we have exactly the same issues

**Comment by nakamurabh** [comment]
We re having the same problem

**Comment by jkjha** [comment]
This issue is with 0.19.7, which I have also faced suddenly as I have mentioned "latest" in bower for ui-select.
Use specific version ie 0.19.6 unless this issue is resolved. v0.19.6 works fine.

**Comment by Jefiozie** [comment]
Just pushed a new version where I reverted the head/ footer feature hope this will solve all issues.

Please let me know.

**Comment by nakamurabh** [comment]
0.19.8 version fixed the layout issue

**Comment by Jefiozie** [comment]
@ldusoswa can you verify if the v0.19.8 fixed your issue?

Thanks.

**Comment by Jefiozie** [comment]
Closing the issue down as I believe this should be resolved and the other issue that open about this problem are resolved. If not please let me know and we will have a further look.
