### ISSUE TITLE
V0.19.7 throws strictdi error

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [angular-ui/ui-select#1971]
starting from v0.19.7 I started getting
`Error: [$injector:strictdi] function(uiSelectConfig) is not using explicit annotation and cannot be invoked in strict mode`

**Comment by zuzusik** [comment]
I can confirm this.

**Comment by pamigomp** [comment]
+1

**Comment by adybionka** [comment]
We had the same problem in our project.

**Comment by adybionka** [comment]
We have the same problem in our project. Back to 0.19.5.

**Comment by Jefiozie** [comment]
Just pushed a new version where I reverted the head/ footer feature hope this will solve all issues.

Please let me know.

**Comment by Jefiozie** [comment]
@ivanvoznyakovsky can you verify that the issue is resolved?

**Comment by Jefiozie** [comment]
Closing the issue down as I believe this should be resolved and the other issue that open about this problem are resolved. If not please let me know and we will have a further look.
