### ISSUE TITLE
Remove broken 0.19.7 from NPM

### ISSUE THREAD

**Issue by zuzusik** [angular-ui/ui-select#1972]
Looks like 0.19.7 is [completely](https://github.com/angular-ui/ui-select/issues/1970) [broken](https://github.com/angular-ui/ui-select/issues/1971)

Why not removing it from NPM until fix is ready? According to npm stats almost 5000 people have already downloaded this broken version. This is completely not good.

**Comment by batista** [comment]
and bower as well for those of us that are stuck with it!

**Comment by hochi-vivovii** [comment]
Fallback to "0.19.6", without `~` and `^`, will fix the issue.

**Comment by Jefiozie** [comment]
Just pushed a new version where I reverted the head/ footer feature hope this will solve all issues.

Please let me know.

**Comment by biggus-dickus** [comment]
@Jefiozie, I downloaded the *v. 0.19.8* today, the issue with Unknown provider was no longer encountered.

**Comment by Jefiozie** [comment]
@biggus-dickus thanks for your reply, did this also resolved the UI problem?

**Comment by biggus-dickus** [comment]
@Jefiozie, apparently, it did. I just used the <ui-select> with its core functionality (no advanced or new features), and everything worked fine.

**Comment by Jefiozie** [comment]
thanks for verifying. Closing it down as the issue should be resolved. If not please let me know will reopen the issue.
