### ISSUE TITLE
when i change the version form  "^v0.19.4" to v0.19.5 ( v0.19.6 or v0.19.7),all not found.

### ISSUE THREAD

**Issue by smart-dream** [angular-ui/ui-select#1975]
ENORESTARGET No version found that was able to satisfy v0.19.5
ENORESTARGET No version found that was able to satisfy v0.19.6
ENORESTARGET No version found that was able to satisfy v0.19.7

how can fix it

**Comment by Jefiozie** [comment]
Hi, 

I don't know what you mean can you be a bit more specific. 
Next we had some problems with the last version. Just pushed a new one where a major issue has been resolved.

**Comment by Jefiozie** [comment]
Closing this issue down as I believe this issue could be resolved with the lastest version. If not please let me know.
