### ISSUE TITLE
how to change ng-if to ng-show in option

### ISSUE THREAD

**Issue by littlebox692** [angular-ui/ui-select#1979]
![222222222222222222222](https://cloud.githubusercontent.com/assets/25901256/25224558/5753c710-25f1-11e7-897f-ff08e6f6451f.PNG)
`    <div class="form-group">
        <label class="col-sm-3 control-label">toys</label>
        <div class="col-sm-7">
            <ui-select ng-model="VM.editData.toy" theme="selectize">
                <ui-select-match><span ng-bind="$select.selected.text"></span></ui-select-match>
                <ui-select-choices repeat="item.value as item in (VM.editConfig.toys | filter:$select.search)">
                    <span ng-bind="item.text"></span>
                </ui-select-choices>
            </ui-select>
        </div>
    </div>`

I wanna to use ng-show not ng-if within option label,cuz I need to show/hide this dom rather than remove it.what should I do? addition:angularjs--1.4.8 ui-select--0.13.2

**Comment by Jefiozie** [comment]
I think this is the same question as on [stackoverflow](https://stackoverflow.com/questions/43515917/how-to-change-ng-if-to-ng-show-within-ui-select)? 

Closing it fow now as it looks the same.
