### ISSUE TITLE
Question: Is gonna be a Angular 2 or 4  version?

### ISSUE THREAD

**Issue by aebmknrl** [angular-ui/ui-select#1981]
First of all i want to thank to you for your great work. I use this great directive with all my projects on AngularJS.

Just a question, if is gonna be a Angular 4 or 2 version avaliable soon...

Thanks a lot!

**Comment by Jefiozie** [comment]
Hi,

Thank you for the awesome words about our repo.
At the moment we don't have any plans to make it available for the new Angular.
But we are looking at the options to go this way.

Hope I have answered you question, if not please feel free to comment.

**Comment by aebmknrl** [comment]
Thanks for your answer my friend and for take your time to answer me.
Well i hope that Angular 4 version of this directive comes soon. I don't know at high level Angular 4 but if you need some help ... i'm here. 

Best Reggards

**Comment by ShinDarth** [comment]
Hello, it would be nice to have latest Angular (4+) support
