### ISSUE TITLE
Refresh Spinner for Multiple Selection

### ISSUE THREAD

**Issue by boundlessgeo-yancy** [angular-ui/ui-select#1985]
### Bug description:
When using `spinner-enabled="true"`, the spinner does not appear when using the multiple selection mode of ui-select. The spinner is simply not included in the `select-multiple.tpl.html`.

### Link to minimally-working plunker that reproduces the issue:
Current code: http://plnkr.co/edit/9NeYtHLJ1SANZZhN1rAC?p=preview
Fix: http://plnkr.co/edit/Rp8mNkOXbzntdugkP1yO?p=preview

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular:
1.5.10
UI-Select:
0.19.8/latest
Bootstrap/Select2/Selectize CSS (if applicable):
bootstrap:3.3.6

**Comment by ViieeS** [comment]
@Jefiozie Doesn't work for bootstrap theme. Needs to publish a new release with the latest changes! Also needs to rebuild `/dist`.
```html
<div class="ui-select-container ui-select-multiple ui-select-bootstrap dropdown form-control" ng-class="{open: $select.open}">
  <div>
    <div class="ui-select-match"></div>
    <input type="search"
           autocomplete="off"
           autocorrect="off"
           autocapitalize="off"
           spellcheck="false"
           class="ui-select-search input-xs"
           placeholder="{{$selectMultiple.getPlaceholder()}}"
           ng-disabled="$select.disabled"
           ng-click="$select.activate()"
           ng-model="$select.search"
           role="combobox"
           aria-expanded="{{$select.open}}"
           aria-label="{{$select.baseTitle}}"
           ng-class="{'spinner': $select.refreshing}"
           ondrop="return false;">
  </div>
  <div class="ui-select-choices"></div>
  <div class="ui-select-no-choice"></div>
</div>
```
