### ISSUE TITLE
Item remains active inside dropdown after model clear

### ISSUE THREAD

**Issue by andrei-dracea** [angular-ui/ui-select#1987]
### Bug description:
After setting the select model to `null`, the item remains as active in the dropdown. You can see this bug in the example plunkr below. Just select something from the list, then click `Clear ng-model`, then open the dropdown. I believe this is not expected behaviour. It also happens when you change the data source, the previously selected position in the dropdown remains active.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/zxf7mvhFVbvKKspyB8kU

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS
Angular: 1.6.4

UI-Select: 0.19.8

Bootstrap/Select2/Selectize CSS (if applicable): Bootstrap 3

**Comment by troywoy** [comment]
@andrei-dracea, I just ran into this issue myself. Have you been able to find a workaround, or are you still waiting to hear about a bug fix?

**Comment by KarelCemus** [comment]
I am interested in this too. Is there any progress or known workaround?

**Comment by Jefiozie** [comment]
Hi guys agree that it looks like a bug. As far as I can see not yet somebody has worked on this. Anybody interested in giving it a go?
