### ISSUE TITLE
Show selected (tagging/multiple) choices outside of dropdown

### ISSUE THREAD

**Issue by Znow** [angular-ui/ui-select#2018]
Hi!

I'm in need of the feature, to have the selected choices (tagging/multiple) to appear outside of the select dropdown, instead of in the field.

I have searched and could not find anything related.

So, when I select an item in the list, it will for example, appear in a div right next to the dropdown, instead of inside the dropdown as per this example: [http://plnkr.co/edit/ajlfAtvqZzr9yds1lwBJ?p=preview](http://plnkr.co/edit/ajlfAtvqZzr9yds1lwBJ?p=preview).

Is this a feature that is already existing or needs to be developed?

Ideal, would be to be able to "move" ```<ui-select-choices></ui-select-choices>``` out of the ```<ui-select></ui-select>``` directive.

Kind regards

**Comment by Jefiozie** [comment]
Hi @Znow it is not a feature we have and I don't we think we are going to develop this. We are trying to maintain functionality and solve bugs and not added new features.

I hope you understand. Did I answer you question? If so could you close down the issue or leave a comment

Thanks.
