### ISSUE TITLE
display choices after user types up to 3 characters

### ISSUE THREAD

**Issue by ukenpachi** [angular-ui/ui-select#2046]
I am using version ~0.19.4 with angular js 1.5.3 I am wondering if it is possible to only display the dropdown list only when a user has type up to 3 or more characters?  if so which attribute is it? I have looked in https://github.com/angular-ui/ui-select/wiki and cannot find anything. Thank you so much

**Comment by ckosloski** [comment]
There is `minimum-input-length`.
See [here](https://github.com/angular-ui/ui-select/wiki/ui-select-choices)

**Comment by Jefiozie** [comment]
Agree this should be the functionality you are looking for. 

Closing the issue down as i believe the question has been answered.
