### ISSUE TITLE
ui-select on mobile doesnt  work

### ISSUE THREAD

**Issue by Irfanbsse2060** [angular-ui/ui-select#2047]
On desktop its working perfectly fine . but when i open page on mobile, Default value of ui-select doesnt work.it shows empty

**Comment by Jefiozie** [comment]
This project ws not completely adjust to work on mobile.  Maybe you can have a look at stackoverflow how other people solved there problems. 
Next to this, this is not a real issue your are submitting as asked in the issuer template. (see below)

> The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein. 
> ### Bug description:
> ### Link to minimally-working plunker that reproduces the issue:
> ### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS
> Angular:
> UI-Select:
> Bootstrap/Select2/Selectize CSS (if applicable):
> 


Please use this in advance for now i'm closing this issue as I don't see how we can help you we this question. If needed you can create a new one with a full description of this issue.
