### ISSUE TITLE
ng-model is not getting changed

### ISSUE THREAD

**Issue by sanketsaurav** [angular-ui/ui-select#205]
I'm trying to achieve something very straightforward:
```
<ui-select multiple ng-model="company.stack" theme="bootstrap">
    <ui-select-match>{$$item.name$}</ui-select-match>
    <ui-select-choices repeat="technology in technologies | filter: $select.search">
        <div ng-bind-html="technology.name | highlight: $select.search"></div>
    </ui-select-choices>
</ui-select>
```
When changing the objects, the changes are not reflected in the model `company.stack`. I tried changing it to `$parent.company.stack`, but it still doesn't work. What am I missing?
I'm using AngularJS v1.3.0-beta.17.

**Comment by mmoy92** [comment]
@tannerlinsley It appears you can fix this by manually instantiating the model within the controller (demo.js)
```javascript
$scope.friends = {};  // Need to instantiate model within controller.
```
I also had to change the multi-select to hold the field of an ng-model object, instead of the object itself:
```javascript
<ui-select multiple ng-model="friends.multi" ...>
```

http://plnkr.co/edit/TPoTfAbzRXKskj2gh0Oz?p=preview

**Comment by andorov** [comment]
still appears to be an issue.  @mmoy92 's solution worked for me.

**Comment by ninrod** [comment]
@mmoy92 solution worked for me. But it is still an issue as of [v0.13.2] (https://github.com/angular-ui/ui-select/releases/tag/v0.13.2)

**Comment by user378230** [comment]
As per FAQs ngModel requires dot notation. 

Closing.
