### ISSUE TITLE
Versions in CDN do not match file versions

### ISSUE THREAD

**Issue by tvStatic** [angular-ui/ui-select#2052]
### Bug description:

Almost all versions in the CDN appear to actually point to the previous version, with the exception of 0.20.0 which points to 0.19.3.

For example, [the 0.20.0 link](https://cdnjs.cloudflare.com/ajax/libs/angular-ui-select/0.20.0/select.js) shows 0.19.3 as the version in the file documentation.

```
/*!
 * ui-select
 * http://github.com/angular-ui/ui-select
 * Version: 0.19.3 - 2016-08-17T06:16:41.345Z
 * License: MIT
 */
```

And has identical file contents to 0.19.3, found using [the 0.19.4 link](https://cdnjs.cloudflare.com/ajax/libs/angular-ui-select/0.19.4/select.js).

This means that 0.19.8 and 0.20.0 are currently not accessible via CDN. 

In my random testing, it appears that most links refer to the previous version in the file contents. I noticed that 0.9.1 matches correctly, and there may be others but I didn't check exhaustively.

**Comment by Jefiozie** [comment]
This is a known issue and it will probably not be changed. 
I think there was a problem somewhere on releasing this library and this is the reason why 0.20 is already public.
 
Thanks for making this issue other people can read this and see that this is for now as is.
