### ISSUE TITLE
lost focus if append to body

### ISSUE THREAD

**Issue by Paktusin** [angular-ui/ui-select#2078]
Hi. If I set on multiselect append to body=true when the list is DroppingDown Focus is dissapear from input  field. And i need click again.
example:
```
<ui-select id="test" multiple class="form-control"
ng-model="modalEvent.rooms"
ng-required="settings.required_room"
append-to-body="true"
theme="bootstrap">
<ui-select-match placeholder="Выберите помещение">
{{$item.full_address_name}}
</ui-select-match>
<ui-select-choices 
repeat="room in settings.filtered_a_rooms| parentRoomFilter: frooms | propsFilter:{name:$select.search}">
<div ng-bind-html="room.full_address_name | highlight: $select.search">
</div>
</ui-select-choices>
</ui-select>
```

```
in function positionDropdown(){
......
$document.find('body').append(element);
probably add line >>  element.find('input').select();
......
}
```

**Comment by ysaakpr** [comment]
same issue for me as well,

<ui-select ng-model="params.filter()[name]" theme="selectize" ng-disabled="$filterRow.disabled" reset-search-input="true" style="width: 100%;" title="{{$parent.$column.data.placeholder || \'Select\'}}" append-to-body="true" remove-selected="true" spinner-enabled="true"> <ui-select-match placeholder="{{$parent.$column.data.placeholder || \'Select\'}}" allow-clear="true">{{$select.selected.text}} <span ng-click="$event.stopPropagation();$select.select(undefined);" class="ui-select-clear">x</span> </ui-select-match> <ui-select-choices repeat="item.id as item in $parent.$column.data.data | filter: $select.search track by item.id" refresh="$parent.$column.data.refresh($select.search)" refresh-delay="500" position="down"> <span ng-bind-html="item.text | highlight: $select.search"></span> <small ng-bind-html="item.secondary | highlight: $select.search"></small> </ui-select-choices> </ui-select>'

**Comment by ysaakpr** [comment]
https://github.com/angular-ui/ui-select/commit/5283c71fb14e956e9cf380ac96397c6d484d257a

Looks like when append to body true, focus is on dropdown...but is that a right way

**Comment by ysaakpr** [comment]
[May be related](https://github.com/angular-ui/ui-select/issues/1039)
