### ISSUE TITLE
request to support ordering / sorting match array

### ISSUE THREAD

**Issue by btmurrell** [angular-ui/ui-select#209]
I have a need, but don't see anyone else talking about it.  I need to provide the ability to reorder the selected items in my multi-select set.  current behavior is they are in the order selected by the user.  

i would like to enhance the ui-select directive to allow drag & drop reordering of selected items.  i am considering a  creating a pull with an implementation of one of the angular draggable directives (see below) to augment ui-select.  

before i embark on my effort, i wanted to ask the community if anyone has this on the roadmap, or if anyone thinks one of the existing directives would be better or worse for this functionality.

http://codef0rmer.github.io/angular-dragdrop/#/
http://ngmodules.org/modules/ngDraggable
http://www.directiv.es/Angular-DragDrop

thanks in advance for any solicited comments, advice, warnings, etc.

**Comment by pgrm** [comment]
I'm going to use ui-select (or select2) in my angular JS application and also need drag&drop support. Did you have any luck with it so far?

**Comment by amcdnl** [comment]
@btmurrell Ya, I'd like this feature too but it really should be a plugin on top of ui-select so I dont think it would ever make it in this project.

**Comment by pgrm** [comment]
I don't know when and by whom it was added, but there is the option `sortable="true"` which enables exactly this feature. The documentation is missing, but when you download the code and run the examples, it's shown in `demo-multi-select.html`

I guess we can close this now.

**Comment by cmlenz** [comment]
For the record, this feature was added in 0.10 and was contributed by @homerjam in #651. I agree that this issue should be closed now.

**Comment by stevematyas** [comment]
It would be really helpful if someone could provide some documentation for the "sortable" feature. I'm still trying to figure out why the ng-model is not updated (modelValue) while the `viewValue` is. See #974.
