### ISSUE TITLE
Form $dirty set to true while searching the choices

### ISSUE THREAD

**Issue by xjtumalin** [angular-ui/ui-select#2114]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
There's a ui-select in a form, when you type in something to search the choices, the $dirty of the form will be set to **true** even you didn't make any selection. I tried on UI-Select official example, it's still happening.

I think to type something to search choices but not select anyone shouldn't be thought the form has been changed.

### Link to minimally-working plunker that reproduces the issue:
This example plunker just copied from the official example.
http://plnkr.co/edit/Inyno8?p=preview

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS
Angular:  1.5.0

UI-Select:  0.19.8

Bootstrap/Select2/Selectize CSS (if applicable):

**Comment by venkataraghu** [comment]
This is expected behavior. as the user interacted with the form, it is supposed to be dirty. https://docs.angularjs.org/api/ng/type/form.FormController#$dirty

**Comment by xjtumalin** [comment]
@venkataraghu , thank you for the reply.
Yes, you're correct from programmer's perspective, but from a user's perspective, it's not.
So I think I have to compare every field value to see if it's changed.
