### ISSUE TITLE
Multiselect issue with ng-show initialised to false [Quick fix and demo inside]

### ISSUE THREAD

**Issue by laguiz** [angular-ui/ui-select#214]
If an `ui-select multiple` is initialised with `ng-show="false"` then input placeholder width is set to 0.

Based on version 0.7.0 - 2014-09-09T01:02:43.608Z

Demo bugged version : http://plnkr.co/edit/Cv1NI0MkUP7ZFX2Ravqv?p=preview
Demo quick fixed version : http://plnkr.co/edit/YCMF0CEb0Xs4rIsTDNsq?p=preview

To summarised it's 2 lines of code to ensure that the minimum with it not `0`. **However** if the ng-model array (here `colors`) is not empty when init then the initialised `width` is too big and it creates a new line instead of proper sized placeholder. Not sure how to do better to avoid conflict with `ng-show`.

Should I create a pull request?

**Comment by jjm340** [comment]
Which two lines of code?  It's not obvious from your demo...

**Comment by prakhar-goel** [comment]
try using ng-if instead of ng-show. It solved for me.

**Comment by wesleycho** [comment]
Closing as duplicate of #212
