### ISSUE TITLE
i have jquery select2 applied in my project but now i want to implement that same in angular js without using jqueryt

### ISSUE THREAD

**Issue by riteshhirapara** [angular-ui/ui-select#2182]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular:

UI-Select:

Bootstrap/Select2/Selectize CSS (if applicable):

**Comment by riteshhirapara** [comment]
Can anyone please help me to achieve multiple select in angular js just like jquery select2? but i don't want to mix jquery with angular js.

**Comment by pierregaborieau** [comment]
This is from your message, please take a moment to read it and you'll find help elsewhere:

> The issues forum is **NOT** for support requests. It is for bugs and feature requests only.
> Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
> existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

If everyone created issues to ask for help, there would be no time to fix bugs...
You should close/delete this issue.
