### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined in early $digest cycle before scope properties are resolved

### ISSUE THREAD

**Issue by davisford** [angular-ui/ui-select#219]
I'm getting this stack trace with a simple array of strings with the multiple option:

![screen shot 2014-09-24 at 11 19 01 am](https://cloud.githubusercontent.com/assets/186677/4390586/49940d2e-43fe-11e4-8ae8-36aa3004ca13.png)

Markup:

``` html
<ui-select multiple="multiple" ng-model="user.roles" theme="bootstrap">
  <ui-select-match placeholder="Select a role...">{{$item}}</ui-select-match>
  <ui-select-choices repeat="role in roles |filter:$select.search">{{role}}</ui-select-choices>
</ui-select>
```

Controller code:

``` javascript
var user;
Roles.query().$promise.then(function (res) { $scope.roles = res.roles });
// roles looks like ['user', 'admin', 'superuser']

Accounts.get({id: id}).$promise.then(function (u) {
  $scope.user = user = u;
});
// user looks like { name: 'foo', email: 'foo@bar', roles: ['user'] }
```

It looks like the directive is expecting the bound objects to be all there before they are ready. In my experience building directives, the $digest cycle always fires early and the bound scope objects can be null -- so I always code defensively against that.

I can make it go away if I pre-initialize:

``` javascript
$scope.user = { roles: [] }; 
$scope.roles = [];
// other code that fetches via $resource
```

It seems odd that I have to do that, though?

**Comment by stevematyas** [comment]
What was the fix that was made?

**Comment by roko-p** [comment]
+1

**Comment by rupak-avainfotech** [comment]
Hi guys
How to fixed it.

**Comment by lumayara** [comment]
I am having the same issue.. It has been a couple of days and still could not solve it:
`<ui-select multiple ng-model="addRecipient.selection" theme="bootstrap" title="Choose Recipients" class="multipleSelect">
                        <ui-select-match placeholder="Select Additional Recipients...">{{$select.selected.Title}}</ui-select-match>
                        <ui-select-choices repeat="additional in Managers | filter:$select.search">
                            {{additional.Title}}
                        </ui-select-choices>
                    </ui-select>`
and in my controller:
`$scope.addRecipient = {}; `
I tried so many things.. but nothing seems to work.
