### ISSUE TITLE
Getting "Template for directive 'uiSelectMatch' must have exactly one root element. select2/match.tpl.html"

### ISSUE THREAD

**Issue by DineshkumarT** [angular-ui/ui-select#225]
How to fix the error?
Error: [$compile:tplrt] Template for directive 'uiSelectMatch' must have exactly one root element. select2/match.tpl.html

Have no clue why this error is occuring.

This error occurs only if the theme is "select2"

Thanks

**Comment by Worthy7** [comment]
Hmmm this isn't true @dimirc, I just npm installed it, and used the dist/selectize.js, and it is trying to pull the select.tpl.html file too. So the templates are not built into the js file.
