### ISSUE TITLE
Transclusion error in the link function of ui-select

### ISSUE THREAD

**Issue by DineshkumarT** [angular-ui/ui-select#227]
link: function (scope, element, attrs, ctrl, transclude) {
          transclude(scope, function (clone) {
            element.append(clone);
          });
        }

transclude is throwing undefined error. 

Becasue of the above error,the dropdown is not showing any choices.

is there any alternative to fix it.

**Comment by askhogan** [comment]
Getting this error on v1.2.8

**Comment by wesleycho** [comment]
Closing due to age of issue - this may also be a duplicate.

Feel free to open a new issue with adequate reproduction on Plunker if this is still an issue.
