### ISSUE TITLE
UI-Select multiple search box has 0px width

### ISSUE THREAD

**Issue by mattjames-counterpart** [angular-ui/ui-select#230]
When I create my ui-select within a hidden object (a second tab, in this case), the width of the search box (and place holder, and clickable area) has a width of 0px. 

Here is the actual control that I'm creating, though I don't have a full set of code that I can share.

```
<ui-select multiple name="roles" ng-model="user.roles" theme="bootstrap" ng-required="true">
    <ui-select-match placeholder="Select roles...">{{$item.name}}</ui-select-match>
    <ui-select-choices repeat="item.id as item in roleList">
        <div>{{item.name}}</div>
    </ui-select-choices>
</ui-select>
```

After it's created, I can see the input control as such:

```
<input style="width: 0px;" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" class="ui-select-search input-xs ng-pristine ng-valid" placeholder="Select roles..." ng-disabled="$select.disabled" ng-hide="$select.disabled" ng-click="$select.activate()" ng-model="$select.search" type="text">
```

 Is there any way to correct this, or force it to recalculate width when the area is shown?

**Comment by jbonigomes** [comment]
I am having this issue, I am using ui-select version 0.12.0, here is a plunker (sorry I had to use v0.11.2 there):

http://plnkr.co/edit/idO0RPa041vHXTcEEt0q?p=preview

Steps to replicate:

- Click the 'Click me!' button
  - The first time the dropdown opens the tags input box only displays the first letter in the placeholder text
- Click the 'Click me!' button again:
  - The entire placeholder text appears correctly

Thanks a lot.
