### ISSUE TITLE
Need to be able to add items to a selection list

### ISSUE THREAD

**Issue by daden** [angular-ui/ui-select#231]
We have a use-case in which the end-user needs to be able to find items in the selection list or add a new item if it doesn't already exist. By creating a wrapper directive, I can now add items to the selection list but am wondering if there is any work-in-progress to add this as a built-in feature as the wrapper directive approach is less than ideal.

Aside: We also have a need for validation which I see is on the roadmap. Is there any sense of when this might be available?

**Comment by dimirc** [comment]
Tagging feature is already implemented
