### ISSUE TITLE
Dropdown is displaying with empty options - Selectize theme

### ISSUE THREAD

**Issue by DineshkumarT** [angular-ui/ui-select#232]
![empty_options](https://cloud.githubusercontent.com/assets/8824303/4426350/61d59dc0-45b2-11e4-935d-79f83f7f1a31.JPG)

Empty dropdown is displaying because of the undefined error for "transclude"

link: function (scope, element, attrs, ctrl, transclude) {
          transclude(scope, function (clone) {
            element.append(clone);
          });
        }
      };

Please provide your solution to fix this issue

Thanks

**Comment by laxmisalunkhe** [comment]
Updated bower.json from 1.2.16 to 1.2.18. Have a link [chnagelog](https://github.com/angular/angular.js/blob/v1.2.18/CHANGELOG.md)
