### ISSUE TITLE
multiple mode - on-deselect event

### ISSUE THREAD

**Issue by parliament718** [angular-ui/ui-select#239]
It there any way to capture deselect event when in "multiple" mode (when user clicks the X to remove the tag)? Reason being because I persist each addition/removal immediately to the server so when user selects, "on-select" callback triggers a post to save the single tag to the server immediately... if that fails I remove it from the UI. 

I essentially need to do the same with "on-deselect" which makes perfect sense in "multiple" mode... if $http removal call fails, I need to add it back to the UI (or even better to prevent removal in the first place until a promise resolves with success.)

I tried a hack like watching the collection, and readding the item back into the "selected" array, but the selection in the UI does not update.

       service.removeTag(tagId)
                            .then((success) => { $scope.loading = false; },
                            (error) => {
                                $scope.loading = false;
                                //removed failed, reinsert
                                $scope.selectedTags.splice(removedIndex, 0, removedTag); 
                            });

**Comment by wesleycho** [comment]
Closing as addressed - feel free to open a new issue if there is still a need for this.
