### ISSUE TITLE
Search input focus not switching between two select dropdowns

### ISSUE THREAD

**Issue by benri** [angular-ui/ui-select#253]
There's a bug when you have two select dropdowns with search, and you open one dropdown but before hitting enter or clicking a selection, you click the other dropdown and start typing, the text focus is still on the first dropdown.

Try in this plunkr:
http://plnkr.co/edit/wicNNsEWN3VC05PtlEKx?p=preview

The first dropdown closes when clicking outside, but the text focus is not lost, nor is the focus shifted to the second dropdown

**Comment by BP18** [comment]
:+1:

**Comment by dimirc** [comment]
This PR should fix it https://github.com/angular-ui/ui-select/pull/668
