### ISSUE TITLE
Wait for the first open to first load remote data

### ISSUE THREAD

**Issue by diogodomanski** [angular-ui/ui-select#271]
Currently, if <ui-select-choices> has "refresh" attribute, its expression is performed as soon as the directive is instanciated.

It would be useful if there was a parameter to inform <ui-select-choices> to perform the "refresh" expression only when the <ui-select> gets focus (and dropdown is opened) or the user changes input value (and taking into account the "refresh-delay" attribute).

**Comment by dimirc** [comment]
Related to PR https://github.com/angular-ui/ui-select/pull/557

**Comment by Jefiozie** [comment]
As the PR is merged please verify if it fix your problem. For now I will close the issue if needed you can reopen.

**Comment by DmitryGonchar** [comment]
@Jefiozie this issue is to have an option to "**first** load remote data on first open of dropdown", not on page init. According to the official demo behavior and the code in the PR, this use case is still not supported. So probably makes sense to leave this issue open

**Comment by Jefiozie** [comment]
@DmitryGonchar  i think this is already possible. When using the `refresh="fetchFromServer($select.search, $select.open)"` like this you already can verify if the ui-select is open or not. If it is you can load the data you want. Correct me if i'm wrong see also the dicussion here: [1845](https://github.com/angular-ui/ui-select/pull/1845#issuecomment-258615839)

**Comment by DmitryGonchar** [comment]
Thanks. I think this was not mentioned in the docs
