### ISSUE TITLE
Inproper selection behavior on scroll if mouse hovering over list

### ISSUE THREAD

**Issue by kikonen-fiksu** [angular-ui/ui-select#282]
If mouse is hovering over dropdown list and list is scrolled using UP or DOWN key then behavior is inproper.

What happens:
- say dropdown fits 7 elements and mouse is hovering over 3rd visible element
- If dropdown content is scrolled up or down (via keys) then when scroll happens, selection jumps into element under mouse hovering position, and selection moving via arrow keys continues from there

=> Causes very irritatingly "jumping" selection when browsing through elements.

**Comment by Ganasist** [comment]
I just experienced this behavior now. Is there a way around it?

**Comment by dimirc** [comment]
Should be solved with https://github.com/angular-ui/ui-select/pull/1211
