### ISSUE TITLE
Focus stealing

### ISSUE THREAD

**Issue by kikonen-fiksu** [angular-ui/ui-select#283]
In some case selector widgets may stuck into "focus stealing" mode. I.e. When trying to select another field in form (with mouse) ui-select field keeps stealing focus back (so attempt to select another field and type text there ends up typing in ui-select field).

Noticed with bootstrap theme, didn't yet figure steps required to trigger bug.

**Comment by BP18** [comment]
:+1:

**Comment by ahendel** [comment]
We've also having this issue

**Comment by bettercallsteve** [comment]
Temp fixed by changing:

```javascript
 $select.close(angular.element(e.target).closest('.ui-select-container.open').length > 0); 
```
To:
```javascript
$select.close(true);
```

**Comment by dimirc** [comment]
This PR should fix it https://github.com/angular-ui/ui-select/pull/668
