### ISSUE TITLE
Strange behavior with fast DOWN + ENTER

### ISSUE THREAD

**Issue by kikonen-fiksu** [angular-ui/ui-select#284]
Hitting quickly DOWN + ENTER, will cause (randomly) one of these

1) Dropdown closed with original selected value
=> expected case

2) Dropdown left open
- dropdown flashes quickly open (DOWN)
- dropdown closes (ENTER)
  => but then it flashes back open

3) Selection changes into first element in selection dropdown and it becomes selected value.

Seems to be happen more easily with large collections

**Comment by dimirc** [comment]
Any change you could create a plunker to reproduce it?

**Comment by Jefiozie** [comment]
Closing it down as it is a old issue. Please create new issue if this is still a bug/ problem.
Also i'm trying to get a good overview of recent bugs.

Thanks for understanding.
