### ISSUE TITLE
Unresponsive script when using data- prefix on ui-select-choices

### ISSUE THREAD

**Issue by jlfama** [angular-ui/ui-select#285]
When using the directive with attributes instead of elements, if you add a "data-" prefix to the attributes it works fine until you add the prefix to ui-select-choices. When data- is added there, it kills the page with an unresponsive script.

I made a plunkr showing the behaviour:
http://plnkr.co/edit/hGbUIj

**Comment by dimirc** [comment]
Should be solved with https://github.com/angular-ui/ui-select/pull/579
