### ISSUE TITLE
Similarities to bootstrap

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/ui-select#29]
Hah, after developing this quite a bit, it's hard to ignore the obvious similarities to ui-typeahead, so I have to concede that to @pkozlowski-opensource 

The one major difference I'm seeing is that we're leveraging this `theme` property and have a way for people to customize the template on-the-fly when they call the directive. 

I still would also like to see a tagging behavior however and at this time neither solution supports one.

Anyway, I would be curious to see if an on-the-fly template approach could be added to ui-typeahead (optionally of course). Although simple differences such as the input being a button when inactive vs a textbox, etc.

I am curious to see what middle-ground can be approached. If I had the ability to customize templates in ui-typeahead as easily as I can here, I might reconsider folding this repo and just creating a selection of themes for the bootstrap version(?).

Whatever, just random thoughts.

**Comment by Jefiozie** [comment]
Hi guys, any problems when I close down this issue? A lot of bugs and looking for a way to get a good overview what is recent. Thanks
