### ISSUE TITLE
No selectize theme multiple selection templates.

### ISSUE THREAD

**Issue by RobiFerentz** [angular-ui/ui-select#295]

**Comment by tannerlinsley** [comment]
Hey.  This is critical!

**Comment by tannerlinsley** [comment]
:+1:

**Comment by deezaster** [comment]
selectize is the most beautiful theme!

**Comment by mickeyvip** [comment]
+1

**Comment by zgotts** [comment]
+1. Would prefer to use the Selectize theme for multiple select with the ui-select directive!

**Comment by mixalisAn** [comment]
+1

**Comment by sbuljac** [comment]
+1

**Comment by JudeAntony** [comment]
+1

**Comment by user378230** [comment]
Please don't +1, use git hub reactions if you must. Better yet, consider submitting a PR! :smiley:

Thanks
