### ISSUE TITLE
Weird creation of multiple selection items when selecting one item.

### ISSUE THREAD

**Issue by RobiFerentz** [angular-ui/ui-select#296]
In multiple select, when I choose an item from the list, the input is populated with several (non-removable) items, with the same content. The number of items created in the UI seems to match the number of properties on the selected item.

I'm using 0.8.2 with Angular 1.3.rc5.

**Comment by dimirc** [comment]
I just check it now and using just multiple is working, as this is an old issue, maybe it was fixed during all this time. Feel free to reopen the issue if you have it again
