### ISSUE TITLE
Roadmap and design

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/ui-select#3]
I threw this together to pretty much scrape some features I am hoping this repo eventually is capable of doing: https://github.com/angular-ui/ui-select/wiki/Roadmap

One of the the things I'm focused on right now is easy-to-customize data, access to internal data, and templates.

One concern is the ability to specify a custom list-item template (currently possible) and a custom selected template (not possible, just uses a button). Perhaps we should break this up into multiple tags?

``` html
<ui-select>
  <selected></selected>
  <options>
    <li ng-repeat="..."></li>
  </options>
</ui-select>
```

These child-directives COULD in fact be optional, and if not specified, simply generate `<li><a>{{value}}</a></li>`

Secondly, if you don't specify `<selected>` or `<options>` but you DO specify a template we could use THAT one for both. Perhaps instead of making you create the `<li>` tag and it's related attributes we can do it for you and you simply specify the contents of each list-item and the selected-item?

**Comment by dubcanada** [comment]
+1 for "Is there a way to do the equivalent of ui-select2's createSearchChoice? I need to allow a person to enter a name if it isn't in the list of existing options."

**Comment by michaelhoes** [comment]
+1 for "Is there a way to do the equivalent of ui-select2's createSearchChoice? I need to allow a person to enter a name if it isn't in the list of existing options." or the selectize 'item Creation' function

**Comment by j-walker23** [comment]
+1. Just hacked the tagging feature to give this kind of behavior, lol wasn't pretty. +1 for this and thanks for tagging!

**Comment by brianfeister** [comment]
@j-walker23 @michaelhoes @dubcanada @lasimon This is available in v0.9.8.

**Comment by mnomansadiq** [comment]
Hi, It is not working with angular verision: 1.2.10

**Comment by j-walker23** [comment]
Thank you @brianfeister, you guys are the difference between a shitty day programming and a smooth day.

**Comment by ashish612** [comment]
Does select2 support using matchers (finding all the texts starting with) like the jquery select supports?

**Comment by homerjam** [comment]
Can I help with maintaining this repo?

**Comment by shyamal890** [comment]
@homerjam Talk with @aaronroberson he is the one maintaining the library now I think.

**Comment by fru** [comment]
First of all thanks everyone for this awesome component! Are there any plans to port this to angular 2? is help wanted in that area? 
p.s. There is already a stackoverflow question on the subject: http://stackoverflow.com/questions/37921979/ui-select-replacement-in-angular2

**Comment by Jefiozie** [comment]
@fru  I don't think there are any plans on angular 2 yet. At the moment we are trying to handle all the bugs.

**Comment by Jefiozie** [comment]
Closing it down as it is a very old issue for now this repo is focusing on handling the bugs. 
Help is welcome 👍
