### ISSUE TITLE
SelectChoices are showing, but the selected one is not sticking (not visible) after selection

### ISSUE THREAD

**Issue by developer10** [angular-ui/ui-select#304]
Here's my issue. Select choices are there, but when you choose one, the ui-select is left blank. Potentially important note: I'm using this inside an <accordion> directive (ui-bootstrap).

Plnkr: http://plnkr.co/edit/5nk4BnYoO52En7P6kPu9

My ui-select is as follows:

    <ui-select search-enabled="true" ng-change="updateMedu()" style="width: 100%" ng-model="medications.chosenMedications.metadata.conceptGroup.conceptProperties">
        <ui-select-match placeholder="Please click to choose or start typing dosage value..">{{$item}}</ui-select-match>
        <ui-select-choices repeat="cp in medications.chosenMedications.metadata[key].conceptGroup[1].conceptProperties | filter: $select.search">
            {{cp.synonym}}
        </ui-select-choices>
    </ui-select>

Note: The above "key" contained in `metadata[key]` is a key (index) of an outer/surrounding ngRepeat directive (not displayed here).

Note: I'm getting the below data through a service-factory. That being the case, I tested with below mock of the array and selected option didn't stick either.

Note: My model (and supplied array/object) for my ui-select directive is like this:

//        $scope.medications.chosenMedications.metadata = [
//        {
//            conceptGroup: [
//                {
//                    conceptProperties: [
//                        {synonym: "Item One"},
//                        {synonym: "Item Two"},
//                        {synonym: "Item Three"}
//                    ]
//                },
//                {
//                    conceptProperties: [
//                        {synonym: "Item A"},
//                        {synonym: "Item B"},
//                        {synonym: "Item C"}
//                    ]
//                }
//            ]
//        }
//        ] ;

**Comment by ramesaliyev** [comment]
Have same issue with "multiple" mode.

**Comment by jrbecart** [comment]
I have the same problem but works with "multiple" mode.
Any solutions ?

**Comment by wesleycho** [comment]
Closing as fixed - feel free to open a new issue if this is still a problem with reproduction based on the latest release.
