### ISSUE TITLE
dropdown appears cutoff when used inside a div with overflow: auto

### ISSUE THREAD

**Issue by pjfsilva** [angular-ui/ui-select#308]
Problem:
When ui-select is used inside a div with overflow: auto defined it doesn't appear "on top" of the div but instead is contained inside that div that obviously causes usability problems.

Example: http://plnkr.co/edit/cAZ548
click on the select to open it: the dropdown is inside the red div but it should be "always on top" of everything.

Solution:
The default <select> from HTML always appears on the top of everything and the original jquery select2 already solved the problem (angular-ui/ui-select2 also solves the problem).

The problem is simple: ui-select uses a relative positioning where it needs to use absolute positioning to "break out" from the overflow div. jquery select2 solves this in a very smart way by appending the list to the body element, effectively avoiding any div parents with overflow or relative positioning that can cause other problems. (an absolute div inside a relative div isn't anymore absolute to the whole document: http://css-tricks.com/absolute-positioning-inside-relative-positioning/ )

Using absolute positioning can also cause problems because if this dropdown is used inside a modal window that is draggable or if the user scrolls the page: the dropdown (select2-drop) position needs to be adjusted to the new position of the content.

select2 solves using a "select2-drop-mask" around the whole document and when a user clicks anywhere closes the dropdown which is a good way to deal with this because the default <select> from HTML also does this.

select2 example working fine: http://plnkr.co/edit/4jERkO - click on the select: content is on top of everything.

I believe the solution is already on jquery select2 plugin and it's just a matter of borrowing the good ideas from them. I couldn't find the issue that originated that specific fix on select2, but this seems to be a good lead: https://github.com/ivaynberg/select2/issues/149

My end goal is to use the select inside a Bootstrap modal window (modal-body has overflow auto content) that would be draggable but I simplified my test case to this specific scenario.

I'll be happy to help and provide more clarification as I investigated this quite a bit.

**Comment by Tim-Erwin** [comment]
This does the trick for me:
```
    .ui-select-choices {
        position: fixed;
        top: auto;
        left: auto;
        width: inherit;
      }

**Comment by wesleycho** [comment]
Closing as a duplicate.

**Comment by ibecir** [comment]
Tim-Erwin thanks dude, this stupid issue took me 3 days to resolve.

**Comment by ibecir** [comment]
@Tim-Erwin thanks dude, this stupid issue took me 3 days to resolve.

**Comment by JBongars** [comment]
on div.btn-group add style="z-index:auto;" like so: 

````html
<span class="input-group-btn">
  <div class="btn-group" style="z-index: auto">
    <button type="button" class="btn btn-default dropdown-toggle" dropdown-menu-hover data-toggle="dropdown" data-close-others="true">
      - Select Alert -
      <i class="fa fa-angle-down"></i>
     </button>
    <ul class="dropdown-menu pull-left" role="menu" style="height: 400px; overflow: auto;">
      <li ng-repeat="item in vm.options">
        <a ng-click="vm.addDetail('menu', item)">{{item.description}}</a>
      </li>
    </ul>
  </div>
</span>
````

**Comment by jayminpanchal** [comment]
@Tim-Erwin thanks. I was finding solution from last 2 days. thanks again.

**Comment by gsmdenis** [comment]
can using waterfall js and easy to fix :-)
