### ISSUE TITLE
Two selects (bootstrap theme): focus issue on click

### ISSUE THREAD

**Issue by ubarkai** [angular-ui/ui-select#309]
1. Go to http://plnkr.co/edit/BpQohOxoSIsP8ExFderH (taken from demo but both selects are in the Bootstrap theme)
2. Click first select: focus appears correctly.
3. Click second select: focus returns to first select. 
4. Need to click again to focus on the second element.

**Comment by wesleycho** [comment]
Closing due to age - feel free to open a new issue with reproduction up to date with the latest release if this is still a problem.
