### ISSUE TITLE
when using multiple with data from the server, we can select several time the same element

### ISSUE THREAD

**Issue by mastilver** [angular-ui/ui-select#332]
When I retrieve data from the server, items don't have the same pointer reference as items from the previous called (obviously).

Although Ui-select is using them to find out if two element are the same.

The developper should be able to define attribut that are specific to each item (i.e id)

see this plunker http://plnkr.co/edit/6TvR9VeW6l57cp0lCiCR?p=preview
you can select the same place several time

**Comment by PowerKiKi** [comment]
Should be solved via #256
