### ISSUE TITLE
Populate multiple select

### ISSUE THREAD

**Issue by jgoux** [angular-ui/ui-select#333]
Hi,
I serialized a form to be able to reload it when needed.
All the *single* select are repopulated, but not the *multiple* select, even if the $scope is populated.
Here is a plunker with my issue : http://plnkr.co/edit/vL9L2XWeziTPuX4KxwmP?p=preview (select people in the first input then click "copy selected people")

**EDIT** : Better example here : http://plnkr.co/edit/vL9L2XWeziTPuX4KxwmP?p=preview

**Comment by ahmer-yasin** [comment]
i have one issue when i save data in db it save objectc in array for using ui select 
but i retrive the data it will never selected how can i fix it

**Comment by stevehu** [comment]
I need more context info to fully understand your question. However I guess what you sent to the server and what you retrieved from the server are different. 

Thanks,

Steve


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: ahmer-yasin <notifications@github.com> </div><div>Date:01-19-2015  10:04 AM  (GMT-05:00) </div><div>To: angular-ui/ui-select <ui-select@noreply.github.com> </div><div>Cc: stevehu <stevehu@gmail.com> </div><div>Subject: Re: [ui-select] Populate multiple select (#333) </div><div>
</div>i have one issue when i save data in db it save objectc in array for using ui select 
but i retrive the data it will never selected how can i fix it

**Comment by ahmer-yasin** [comment]
this is point to select plan it will save but when i want to edit plan i m retriving data 
data is retrive but it will not show selected
 <ui-select multiple
                                  ng-model="consultation.consultation_plan"
                                  id="consultation_plan"
                                  theme="select2"
                                  ng-disabled="disabled"
                                  style="width: 100%;">
                         <ui-select-match placeholder="Select plano...">{{$item.name}}</ui-select-match>
                         <ui-select-choices repeat="p in plan | filter:$select.search">
                          {{p.name}}
                          </ui-select-choices>
                         </ui-select>

**Comment by ahmer-yasin** [comment]
let me show you screen shot for code

**Comment by ahmer-yasin** [comment]
![screenshot from 2015-01-19 20 16 01](https://cloud.githubusercontent.com/assets/5410527/5802577/1c65cf1a-a018-11e4-9722-891d4e57f83d.png)

**Comment by ahmer-yasin** [comment]
the problem is not for saving and retriving 
problem is to show data already selected

**Comment by ahmer-yasin** [comment]
<ui-select multiple
                                  ng-model="consultation.consultation_plan"
                                  id="consultation_plan"
                                  theme="select2"
                                  ng-disabled="disabled"
                                  style="width: 100%;">
                         <ui-select-match placeholder="Select plano...">{{$item.name}}</ui-select-match>
                         <ui-select-choices repeat="p in plan | filter:$select.search">
                          {{p.name}}
                          </ui-select-choices>
                         </ui-select>

**Comment by stevehu** [comment]
I have record a short video to show you have angular-schema-form-ui-selet
behaves in my framework and I cannot find what is the issue in your code as
we are using it in different ways. You can always dig into my code to
figure out how it works in schema form.

http://youtu.be/lz8fPcY_VJY

Thanks,

Steve

**Comment by PowerKiKi** [comment]
Should be solved via #256

**Comment by zukasmichael** [comment]
please help,
how to make tags to be available if tag is not in ui-select-choice list ? (tag list can be populated on refresh event)

this tag "anything else" does not appear http://plnkr.co/edit/o0pAujq9u4gCq2X96WEZ?p=preview 
ui-select Version: 0.9.7

thank you !
