### ISSUE TITLE
How to set initial value?

### ISSUE THREAD

**Issue by ghost** [angular-ui/ui-select#334]
I tried everything.
Adding value="" in <ui-select-choices> doesn't seem to work as in: closed: #143

```
                   <ui-select ng-model="calendars.selected" on-select="getSelectedCalendar($item)" theme="selectize" ng-disabled="disabled" style="width: 300px;">
                        <ui-select-match placeholder="Select or search calendar...">{{$select.selected.summary}}</ui-select-match>
                        <ui-select-choices repeat="cal in calendars | filter: $select.search">
                            <span ng-bind-html="cal.summary | highlight: $select.search"></span>
                        </ui-select-choices>
                    </ui-select>
```

I want it when it loads to have first option selected as an example. Any ideas?

**Comment by vishnucse** [comment]
No.. Giving console err like Cannot read property '0' of undefined

**Comment by sallampalli** [comment]
What if your ng-model is just the ID , but your dropdown values are list of Objects ?

**Comment by CornejoReyes** [comment]
If you only want the id of an object, or other property, only do this:
```
<ui-select-choices repeat="cal.id as cal in calendars | filter: $select.search">
          <span ng-bind-html="cal.summary | highlight: $select.search"></span>
 </ui-select-choices>
```
Notice thath `cal.id` in `repeat="cal.id as cal in calendars | filter: $select.search"` is the property you want to assign to ng-model.
