### ISSUE TITLE
Weird behaviour when setting multiple="multiple"

### ISSUE THREAD

**Issue by garethdown44** [angular-ui/ui-select#337]
If you set multiple="multiple" the control appears to allow multiple selection but actually causes weird behaviour when selecting an item. Specifically it splits a string value into letters and makes the letters the selected items, like the image below.

I realise that this is probably unsupported and not the documented way to do it, but I think it should be one way or the other - it should complain or not work at all if you set multiple="multiple", or it should work as if you've just set "multiple" with no value.

`<ui-select multiple="multiple" ng-model="multipleDemo.colors" theme="bootstrap" ng-disabled="disabled" style="width: 300px;">
    <ui-select-match placeholder="Select colors...">{{$item}}</ui-select-match>
    <ui-select-choices repeat="color in availableColors | filter:$select.search">
      {{color}}
    </ui-select-choices>
  </ui-select>`

![image](https://cloud.githubusercontent.com/assets/145924/4752618/853924e8-5aad-11e4-8a5c-b1c46dae2451.png)

**Comment by richfergus** [comment]
I experienced the same issue +1

**Comment by richfergus** [comment]
The behavior comes from the fact that the model is bound to items as simple strings. ui-select expects an array i.e 
`["Blue","Red"]`
not
`'Blue', 'Red'`

[See plunker both working and not working](http://plnkr.co/edit/QZ186YziACq2kqXFJSoa?p=preview)

**Comment by garethdown44** [comment]
That wasn't what the issue was. The issue was that it behaved differently whether you set:

<select multiple="mutiple">

or

<select multiple>

(see the referenced issue #371 too)

However, after testing multiple="multiple" in your plunker on the first example reveals that it's been fixed now, so this can be closed.

**Comment by richfergus** [comment]
Ok, sure looks like the same behaviour to me.
