### ISSUE TITLE
How to disable the ui-select?

### ISSUE THREAD

**Issue by brunomacf** [angular-ui/ui-select#34]
It seems that ng-disabled is not working with the current version of ui-select!

**Comment by akcasoy** [comment]
i have the recent version of ui-select. By using multiple option and ng-disabled, the field is greyed out but seems like this:

<img width="355" alt="screen shot 2016-02-12 at 22 23 16" src="https://cloud.githubusercontent.com/assets/12121451/13020723/4980ff64-d1d7-11e5-826c-20d6ddde805d.png">

**Comment by yunjiali** [comment]
Got same problem as @akcasoy

**Comment by user378230** [comment]
@yunjiali see #1432
