### ISSUE TITLE
ui-select unflags FormController's $pristine state

### ISSUE THREAD

**Issue by reifi** [angular-ui/ui-select#341]
$watcher on $select.selected will $setViewValue() which will unflag $pristine and set $dirty, allthough it's the initial $watcher and there is no preselection.

https://github.com/angular-ui/ui-select/blob/master/src/select.js#L771

This would fix it:
<pre>
scope.$watchCollection('$select.selected', function(newCol) {
            if (ngModel.$pristine && newCol.length === 0)  {
              // preserve $pristine state for empty values, don't setViewValue
            } else {
              ngModel.$setViewValue(Date.now()); //Set timestamp as a unique string to force changes
            }
</pre>

**Comment by kether667** [comment]
+1

**Comment by kether667** [comment]
duplicate of #289

**Comment by KevinPHughes** [comment]
I don't think this is a duplicate of 289, that one has been incorporated into the latest version and I'm still seeing an issue.

If you load the 'options' or the ng-model value asynchronously the form will always be dirty: 

http://plnkr.co/edit/Iv1H4T5OYkLr1uevTe6g?p=preview

**Comment by kether667** [comment]
There's no fixes in 289 in master yet and it's the same issue, form is always dirty

**Comment by cmlenz** [comment]
#289 was fixed via #509. This issue should be closed, too.

**Comment by gerardp** [comment]
I have the same problem.
My form is always dirty !

**Comment by benri** [comment]
For those who need a quick fix, manually put 'ng-pristine' class in the html, then when something is selected it'll go away

**Comment by wesleycho** [comment]
Closing as fixed - if this is still an issue, feel free to open a new issue with reproduction based on the latest release.

**Comment by samuelcastro** [comment]
Same issue here using `"ui-select": "~0.19.4"`
