### ISSUE TITLE
ui-select initialize fail when the ngModel value is over the limitTo filter

### ISSUE THREAD

**Issue by yixblog** [angular-ui/ui-select#343]
problem plunker:http://plnkr.co/edit/seYgCTj5okknDdl3RzBk?p=preview
when i set the ngModel value when initialize,and the ui-select repeat items has limitTo filter
if the initialize value is out of the top limit number then the name will not display

**Comment by loliver** [comment]
If we add a limit property to the $select object (and controller etc), we can set it to an absurd number (I used 1,000,000) to remove the limit when doing ngModel.$formatters.unshift (alternatively, in 1.4.x we can set it to null and it'll return the full array).

In my testing the performance is still far better than when I was loading the ~1300 items in to the box and it functions correctly. I'll rewrite it in the src files and do a pull request and link here.

**Comment by jordyvaneijk** [comment]
Hello I'm using v0.12.1 of UI-Select but this is still present. Is there a fix which i can use so i can use limitTo? because we have huge performance issues when having collections with over 500 items...

I hope someone can tell me more..

**Comment by dilerarc** [comment]
+1 problem still exists

**Comment by jordyvaneijk** [comment]
After some time  i decided to make my own limitTo... This is a very simple implementation. 
I used the standard limitTo coming witch angular and added my own items with a union before the limit was done. This returns list of items with you limit on it + the list with items specified. Which will be filtered out by UI-select control because they are already in the list.

**Comment by dilerarc** [comment]
@jordyvaneijk Could you provide a piece of code please? I don't quite understand your solution.

**Comment by dilerarc** [comment]
@jordyvaneijk Oh, i got it, thanks man!

**Comment by dilerarc** [comment]
@jordyvaneijk But now I have an exception while searching items in my select
`[ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: o in $select.items, Duplicate key: undefined:undefined, Duplicate value: undefined`

**Comment by wesleycho** [comment]
This is already doable by using the `refresh` functionality.

Going to close this as a usage issue.

**Comment by kristerd** [comment]
@wesleycho I don't understand how this is doable using the refresh functionality, can you please elaborate?

**Comment by ankur8007** [comment]
Can you please help how to resolve this issue, I am facing similar issue with limitTo ?

**Comment by voohoo** [comment]
I would also like help on this issue.
