### ISSUE TITLE
Size off by one pixel when using mode multiple with bootstrap theme

### ISSUE THREAD

**Issue by uwolfer** [angular-ui/ui-select#345]
Example: http://plnkr.co/edit/mSgUMEexv4utln3HKpQb?p=preview

When adding a bootstrap clear button (on the right), you can clearly see that the height is off by one px (33 instead of 34).

The following CSS rule causes this issue:

``` css
.ui-select-multiple.ui-select-bootstrap {
    height: auto;
```

Removing "height: auto;" fixes the issue as long as the is only one line of selected items, but it breaks things if you select more items.

**Comment by wesleycho** [comment]
Can you post an updated Plunker based on the latest release?

**Comment by Jefiozie** [comment]
As this is a very old issue I think it is best to close for now. If needed please make a new issue and add a updated plunker as requested.
