### ISSUE TITLE
ui-utils highlight filter conflicts with ui-select highlight filter

### ISSUE THREAD

**Issue by santyclaz** [angular-ui/ui-select#352]
[**ui-utils** highlight filter](http://angular-ui.github.io/ui-utils/#/highlight) has a naming collision with the **ui-select** *highlight filter*.

**ui-utils** throws on the class `ui-match` while **ui-select** throws on the class `ui-select-highlight`.

**Comment by iVova** [comment]
I had the same issue.

**Comment by rzschech** [comment]
+1

**Comment by andreadicagno** [comment]
+1

**Comment by antch** [comment]
To workaround this I just added:

    .ui-select-choices .ui-match {
        font-weight: 700; /* Must mirror the ui-select-highlight style due to naming conflict with 'highlight' filter */
    }

**Comment by wesleycho** [comment]
ui-utils removed the filter it looks like, closing as resolved.
