### ISSUE TITLE
ui.select doesnt work with ng-hide ?

### ISSUE THREAD

**Issue by visrosoftware** [angular-ui/ui-select#364]
take this example.

http://plnkr.co/edit/5TYgZD0uoOQQS6g4pqjj?p=preview

**Comment by zhenyi2697** [comment]
Same issue here, it's because the width of input is 0.
See this ticket: https://github.com/angular-ui/ui-select/issues/212

**Comment by wesleycho** [comment]
Going to close as a duplicate.
