### ISSUE TITLE
Demo for AsyncData with multiple choice and ng-required with group-by

### ISSUE THREAD

**Issue by hatpick** [angular-ui/ui-select#368]
I need to show the group names like this:
My data is being fetched from server and is like this:
```for options: {label: string value, group: int value}```
```for optgroup: {id: int value, name: string value}```

```
<optgroup label="Group 1">
<options>Opt1</options>
<options>Opt2</options>
<options>Opt2</options>
<options>Opt3</options>
</optgroup>
<optgroup label="Group 2">
<options>Opt4</options>
<options>Opt5</options>
<options>Opt6</options>
<options>Opt7</options>
</optgroup>
```

**Comment by wesleycho** [comment]
Closing, as there are examples of using all but ng-required - ng-required likely requires something else, as it is something that is built into the input and select directives.
