### ISSUE TITLE
writing an own directive which uses ui-select doesn't work

### ISSUE THREAD

**Issue by maku** [angular-ui/ui-select#372]
Hi,

I have a problem with writing an own directive which uses **ui-select** . e.g. I would like to use an element like

`` 
<m-select ng-model="item.id"  placeholder="Please select item..." list="list"></m-select>
``

The problem is that the model value is NOT written back after a selection is done.

Example is on plunkr: http://plnkr.co/edit/dJpEtxLsbNWNI8260Q4D?p=preview

BTW, In this example I also used a directive which converted the model.value between object and id...

e.g. 
choices in form of objects = [{"id": 20,"label": "abc"},{"id": 21,"label": "def"}]
model value in form of an id: var model = { "testId": 20 }

**Comment by user378230** [comment]
As mentioned, `ng-model` requires a **dot**. See wiki and http://stackoverflow.com/questions/17606936/angularjs-dot-in-ng-model

---
Closing as a legacy issue over a year old.
