### ISSUE TITLE
ng-disabled option in angular ui-select shrinks the text box

### ISSUE THREAD

**Issue by swetahs** [angular-ui/ui-select#379]
I am using angular ui-select directive and trying to disable it with ng-disabled option.

```
<ui-select multiple ng-model="address.selected"
             theme="bootstrap"
             ng-disabled="true"
             reset-search-input="true"
             style="width: 300px;">
```

Here is the plunker http://plnkr.co/edit/julETCG4zCGAxFJ0PSBF?p=preview

Size of the text box shrinks with ng-disabled="true".

**Comment by soosap** [comment]
+1

**Comment by ravishivt** [comment]
+1

**Comment by Sylox** [comment]
:+1:

**Comment by MiguelMike** [comment]
+1

**Comment by faisalferoz** [comment]
setting the min-height will be more consistent when tags span multiple lines. Here is the code for bootstrap (sass) theme
```
.ui-select-multiple.ui-select-bootstrap {
  min-height: $input-height-base;
}
```

**Comment by MiguelMike** [comment]
It should be solved without additional CSS.

When disabled and empty the placeholder text could be set to ` ` (a single space), thus preventing the element from collapsing.

**Comment by icfantv** [comment]
this appears to be a bug in ui-select that removes the placeholder on disable.  regular HTML does not remove the placeholder when the field is disabled:
```
<div>
  <input class="form-control" type="text" data-ng-disabled="disabled" placeholder="Placeholder text"/>
  <button class="btn btn-default" data-ng-click="disabled = !disabled">Toggle</button>
</div>
```

**Comment by ProLoser** [comment]
Works for me.

![screen shot 2015-07-10 at 2 20 50 pm](https://cloud.githubusercontent.com/assets/67395/8629304/ee8018ac-270e-11e5-8aa0-e977ca3d1ae2.png)

**Comment by ozzx62** [comment]
+1. @ProLoser This issue only happens to bootstrap theme.

**Comment by abobwhite** [comment]
+1 just had to use hacked-in CSS to fix this

**Comment by shahzadns** [comment]
<code>
.ui-select-multiple.ui-select-bootstrap {
    min-height: 31px;
}
</code>

It works But still Placeholder doesn't shows up.

ui-select puts <code>ng-hide="$select.disabled"</code> on input field, which therefore adds <code>"ng-hide"</code> class.

So, in addition to above, I have to apply following style as well. Then, it looks perfect.
<code>
.ui-select-multiple .ui-select-search.ng-hide{
  width: 100%;
  display: inline-block !important;
  cursor: not-allowed;
}
</code>

Hope it helps other folks.
Cheers !

**Comment by user378230** [comment]
Closing as resolved.
