### ISSUE TITLE
Choices only working as curly braces, not as child elements

### ISSUE THREAD

**Issue by gausie** [angular-ui/ui-select#383]
In the following example, the div gets appended to the ui-select element rather than appearing in the list. The effect is that I a bunch of blank lines in the select box.

```html
<ui-select ng-model="user.selected">
    <ui-select-match placeholder="existing user">{{$select.selected.name}}</ui-select-match>
    <ui-select-choices repeat="user in users track by $index" refresh="refreshUsers($select.search)" refresh-delay="0">
        <div ng-bind-html="''+user.name | highlight: $select.search"></div>
    </ui-select-choices>
</ui-select>
```

Whereas here, it works fine

```html
<ui-select ng-model="user.selected">
    <ui-select-match placeholder="existing user">{{$select.selected.name}}</ui-select-match>
    <ui-select-choices repeat="user in users track by $index" refresh="refreshUsers($select.search)" refresh-delay="0">
        {{ user.name }}
    </ui-select-choices>
</ui-select>
```

Does anyone know why this might be happening?

**Comment by abobwhite** [comment]
I am seeing this problem in some cases as well. Curly brace works. I thinking there is some issue with ```ng-bind-html``` and how the data is loaded on initialization. When I ```ng-bind-html```, the select choices are all there, but have nothing to display but their padding. The selection displays the name correctly.

Which angular version did you upgrade to get the better error message? I am on 1.2.18.

**Comment by user378230** [comment]
Closing this issue as over a year old and doesn't have a repro sample. 

If you believe its still relevant please update with a plunkr (or similar) against the latest version of ui-select (currently v0.15.0)
