### ISSUE TITLE
Externalise JSON data from demo.js

### ISSUE THREAD

**Issue by getkub** [angular-ui/ui-select#385]
folks, any chance to externalise json data from demo.js?
Especially the Country:CountryCode json into something like countries.json?
Advantages are
- Size of demo.js is reduced.
- Can show another example of http calling external file.

Thanks in advance.

**Comment by wesleycho** [comment]
Is there a real benefit to reducing the size of demo.js?

**Comment by getkub** [comment]
quite long before I posted, so actually forgot if its still relevant now  :) 
But the advantages were, quite obvious because lot of times, the data was available externally. So great to have an example out-of-box with .json file external

**Comment by Jefiozie** [comment]
Hi, 

I see the point what you are meaning but I think this is not common practice where people use this.
Maybe you can make a example share it here so that people can have a example?
For now I'm closing this issue feel free to comment.
