### ISSUE TITLE
multiselect with bootstrap unnecessarily increases height when decreasing width

### ISSUE THREAD

**Issue by Tim-Erwin** [angular-ui/ui-select#394]
When creating a multi-select box with flexible width, the height of the widget gets increased. The "cursor" seems to jump into the next line although there is plenty of space to the right. See this plunker: http://plnkr.co/edit/Gacq9NlQVMYetyaYeAnS?p=preview
Just drag the vertical splitter line to the right a tad and you will see the height being doubled.

**Comment by tuanht** [comment]
in v0.10.0, I noticed the comment: `//Give tags time to render correctly`

```
    var calculate = function(){
      var newWidth = container.clientWidth - input.offsetLeft - 10;
      if(newWidth < 50) newWidth = container.clientWidth;
      _searchInput.css('width',newWidth+'px');
    };
    $timeout(function(){ //Give tags time to render correctly
      if (container.clientWidth === 0 && !containerSizeWatch){
        containerSizeWatch = $scope.$watch(function(){ return container.clientWidth;}, function(newValue){
          if (newValue !== 0){
            calculate();
            containerSizeWatch();
            containerSizeWatch = null;
          }
        });
      }else if (!containerSizeWatch) {
        calculate();
      }
    }, 0, false);
```
So I increase timeout from 0 to 50 to fix it.

**Comment by wesleycho** [comment]
Looking at the current code in `master`, this looks like it should be fixed - feel free to open a new issue with details if it is not.
