### ISSUE TITLE
IE9 + Placeholder blows up

### ISSUE THREAD

**Issue by amcdnl** [angular-ui/ui-select#396]
When using the placeholder control with IE9, I get the following error:

```
 Error: [$compile:ctreq] Controller 'ngModel', required by directive 'placeholder', can't be found!
```

and also

```
TypeError: Unable to get property 'source' of undefined or null reference undefined
```

tracing the error up the call stack, we can see there is a undefined exception in the `ngModel.$formatters` function.  http://www.screencast.com/t/Q3UGvMYQp

My control setup looks like:

```
<ui-select ng-model="$parent.saveAsId" name="report" style="width:100%;">
    <ui-select-match>{{$select.selected.name}}</ui-select-match>
    <ui-select-choices group-by="reportType" repeat="report.id as report in availableReports | filter: $select.search">
        <div ng-bind-html="report.name | highlight: $select.search"></div>
    </ui-select-choices>
</ui-select>
```

I'm using Angular 1.3.1

**Comment by MWalid** [comment]
Same problem here.. 

Any help will be appreciated.

**Comment by MWalid** [comment]
That was my fault :), I'm using jade for html templating, one tab missed before `ui-select-match` blowed everything up!!!

Old code:

    ui-select(
      ng-model="journal.from.id",
      theme="bootstrap",
      style="width: 400px"
      )
    ui-select-match(placeholder="من المدين") {{$select.selected.name}}
    ui-select-choices(
        repeat="account in accounts track by $index"
        )

Updated code:

    ui-select(
      ng-model="journal.from.id",
      theme="bootstrap",
      style="width: 400px"
      )
      ui-select-match(placeholder="من المدين") {{$select.selected.name}}
      ui-select-choices(
        repeat="account in accounts track by $index"
        )
You may notice additional one tab in the updated code.

**Comment by stl-winniechan** [comment]
I'm still seeing the same problem on Chrome. I'm using angular#1.3.15, angular-ui-select#0.11.2. 
My html setup looks like:
{code}
            <ui-select ng-model="data.selectedSet"
                        style="min-width: 100px;"
                        title="Choose a person">
                <ui-select-match placeholder="Select a set in the list">
                    {{$select.selected.set_name}}
                </ui-select-match>
                <ui-select-choices repeat="set in pzSets | filter: {name: $select.search}">
                    <div ng-bind-html="set.set_name | highlight: $select.search"></div>
                </ui-select-choices>
            </ui-select>
{code}

Any help will be appreciated.
