### ISSUE TITLE
No available option(s) text

### ISSUE THREAD

**Issue by amcdnl** [angular-ui/ui-select#400]
When you have no available selections such as I've already selected all my options in a multi-select or you have conditional population that results in zero options you need the ability to show some type of text instead of just a empty padding area.

Example: http://www.screencast.com/t/l2WV1GWBPE

Maybe its empty by default but allow a global config option to set it to like 'No available selection(s)' or something.  Thoughts?

**Comment by piernik** [comment]
+1

**Comment by user378230** [comment]
Closing as covered by `ui-select-no-choice` directive.
