### ISSUE TITLE
Possibility to pass the name attribue as the placeholder is passed

### ISSUE THREAD

**Issue by stunaz** [angular-ui/ui-select#403]
Hello, 
Will be great to have the ability to passe the ‘name’ attribute to the generated input element, just as the ‘placeholder’ is passed through the ‘ui-select-match’ element.

In fact i think i would be nice to allow to pass other native standard html element as name, id ....

**Comment by trickpattyFH20** [comment]
+1

**Comment by noullet** [comment]
+1

**Comment by realavaloro** [comment]
Yes, it would be great to have some guidance on how to validate select (and for that a `name `attribute would be likely required).
However, `ui-select` does not generate an input element, it generates a `div `element and `div ` elements don't have a name attribute.
Is there any example for client-side validation on `ui-select` using some other approach?

**Comment by jigarakatidus** [comment]
@realavaloro i just tried giving name attribute to `ui-select`, it works. i think we can treat `ui-select` as `input` tag.
```
<div ng-messages="<form>.<name>.$error" ng-if="<form>.<name>.$touched">
    <div ng-message="required">Please enter this field</div>
</div>
```
*Note* Make sure `required` attributed is added in `ui-select`.

**Comment by iberodev** [comment]
@jigarakatidus thank you. Yes, passing a `name` attribute to the `ui-select` seems to work fine.

**Comment by stunaz** [comment]
closing
