### ISSUE TITLE
Append the list to body

### ISSUE THREAD

**Issue by jimmywarting** [angular-ui/ui-select#41]
I have a select in a div with overflow hidden/auto
In every (most?) usecase it's desirable to let the select go outside of the overflow element, like the native select and [select2][1] dose)

Its true for all kind of typeahead, custom `<datalist>` polyfill things

  [1]: http://ivaynberg.github.io/select2/

**Comment by lebster** [comment]
@jimmywarting @pabuisson hmm looks like i am  having the same problems with scrolling when using position: fixed. Did you guys come with any alternative solutions? I think I am going to have to go back to the normal select. All other solutions out there seem to have issues too.

**Comment by jpdesigndev** [comment]
There seems to be little to no movement on this. I'm thinking the best (perhaps only) way to fix the issues around dropdowns and overflow content is to append the dropdown to the body element, and position it absolutely. My team and I are racing toward a deadline, and the UI relies on `ui-select` elements frequently. That being said, I will be working on this solution at some point in the future (date unknown).

Does anyone have any recommendations/requirements, assuming `<body>` append and `position: absolute` that I should keep in mind?

**Comment by drewbeck** [comment]
@jpdesigndev Why do you consider hiding dropdown on body scroll a requirement? This is not standard behavior for regular select dropdowns and I'm not sure why it should be implemented here.

**Comment by jpdesigndev** [comment]
@drewbeck Well, that's what I've seen.

Here's a quick breakdown (All latest browsers)

* OS X
  * Chrome
    * Disallow body scroll
  * Safari
    * Disallow body scroll

* Windows 7
  * Chrome
    * Allow scroll, but hide select dropdown immediately 
  * IE
    * Disallow body scroll

*** 

Given this small dataset, perhaps looking into disabling scrolling for everything other than the dropdown list is desirable. That could prove rather complex, I imagine. Thoughts?

**Comment by drewbeck** [comment]
Thanks for that breakdown! I didn't know Windows Chrome was different. I wonder why that is?

I think disallowing body scroll makes more sense, given these options. With 2-finger scroll it's easy to accidentally have your cursor in the wrong box — having the dropdown disappear in that case I think would be very frustrating. 

My ideal from a UX perspective would be that the dropdown scrolls with the browser. This isn't standard but I've seen it and I like it quite a bit more than the no-scroll case (see dropdowns on seamless.com for an example). It would be amazing to have this as an option. But disabling body scroll entirely would be consistent with most browsers and most users' experiences I believe.

**Comment by jpdesigndev** [comment]
@drewbeck 

Disallow body scroll is going to be complex. Here's why:

It's not always body that might be scrolling. Think about apps with many sections with `overflow: scroll`. Perhaps, this can easily be addressed. I'm not sure if `scroll` events are bubbled up.

I'll keep thinking about it, and put something together soon. We'll see how it goes.

**Comment by drewbeck** [comment]
Yeah I hear you. The app I'm working on is exactly what you say: lots of scrolling sections.

Select2 manages it by adding a "select2-drop-mask" div that spans the entire browser window and catches all scroll and click events. The dropdown div is on top of that. A possible solution here?

**Comment by cmlenz** [comment]
I made PR #718 which just adds an `append-to-body` attribute to the `<ui-select-choices>` element, causing it to be moved to end of the document body.

I would appreciate testing, feedback, fixes, and so on. Specifically I have only been able to test the change with the Bootstrap theme on Angular 1.3.x with the latest version of Chrome, Firefox, Safari, and IE.

It would be nice to get this feature into UI Select.

**Comment by lebster** [comment]
https://github.com/angular-ui/ui-select/pull/491

**Comment by lebster** [comment]
Here is another PR that seems to solve this issue. https://github.com/angular-ui/ui-select/pull/491

**Comment by cmlenz** [comment]
@lebster Right, but unfortunately the diff on #491 is unusable AFAICT. Maybe formatting changes?

**Comment by brianfeister** [comment]
My hope is to see this fixed via #718.

**Comment by wesleycho** [comment]
Closing as already implemented in the library, as documented [here](https://github.com/angular-ui/ui-select/wiki/ui-select)

**Comment by viccowang** [comment]
ha~ I fixed my bug. Thanks!
