### ISSUE TITLE
ui-select doesn't work with angular 1.2.18 and next versions

### ISSUE THREAD

**Issue by antogarcia72** [angular-ui/ui-select#416]
Hi,

I'm testing ui-select to be used in my app, but when i try to use with angular 1.2.18 or next, ui-select doesn't show correctly the options.

Using this punker:
http://plnkr.co/edit/Hijaxg?p=preview 

and changing these imports : 

<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.3.3/angular.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.3.3/angular-sanitize.js"></script>
  
happend this:

![screenshot - 191114 - 12 36 50](https://cloud.githubusercontent.com/assets/8242767/5105051/c8307562-6fe8-11e4-8fdb-d85495fe30f5.png)

Thank you in advance.

**Comment by user378230** [comment]
Closing this issue as over a year old and may have been resolved in more recent versions. 

If you believe its still relevant please reopen with a plunkr (or similar) against the latest version of ui-select (currently v0.15.0)
