### ISSUE TITLE
ui-select boxes with ancestor fieldsets that have disabled set are not being disabled.

### ISSUE THREAD

**Issue by hmbl9r** [angular-ui/ui-select#417]
I made a pull request, but I guess it's not passing the build test (not sure why).

here's the link to it https://github.com/angular-ui/ui-select/pull/415

**Comment by luzrafaelf** [comment]
+1

**Comment by Jefiozie** [comment]
Closing this one down as the pr is closed als. If I misunderstand please let me know then I will reopen it.
