### ISSUE TITLE
ng-required gives parse: true validation error in angular 1.3.3

### ISSUE THREAD

**Issue by crob** [angular-ui/ui-select#421]
ui-select ng-required="true" ng-model="myModel" name="myModel" always causes a validation parse error

**Comment by user378230** [comment]
Closing this issue as over a year old and doesn't have a repro sample. 

If you believe its still relevant please reopen with a plunkr (or similar) against the latest version of ui-select (currently v0.15.0)

**Comment by deeg** [comment]
@user378230, want to shoot me an email? Wasn't sure how else to contact you with minimal fallout.

**Comment by user378230** [comment]
@deeg is there a problem? I'm just trying to tidy up a little, hoping I've not made a faux pas!

**Comment by deeg** [comment]
@user378230, no wanted to invite you to a dev chat room where we can all talk. What you are doing is great!
