### ISSUE TITLE
ui-select should set css class ng-touched after the user touched the select

### ISSUE THREAD

**Issue by wald-tq** [angular-ui/ui-select#423]
I am using the combination `.ng-invalid.ng-touched` to show only validation errors after the user touched the form field.

The ui-select field should follow angular core and add this css class.

If I have time I can look into that and supply a pull request. It shouldn't be a big issue. But I would like to get feedback on the issue first.

**Comment by graup** [comment]
+1

**Comment by Purpwood** [comment]
+1

**Comment by leandro-freitas-softdevelop** [comment]
+1

**Comment by brunobastosg** [comment]
+1

**Comment by wald-tq** [comment]
is already fixed in version 0.12
