### ISSUE TITLE
Question: Clearing a selection.

### ISSUE THREAD

**Issue by RobiFerentz** [angular-ui/ui-select#425]
After an item has been selected, I move it into a certain list and remove it from the list provided in the repeat attribute. I would also like to clear the selected item from 'active' view the ui-select. Is there a way to do that?

**Comment by abobwhite** [comment]
I agree. Select2 has an option to ```allowClear``` that you can see on this page: https://select2.github.io/examples.html under the Placeholders example. This is a really crucial option that I expected to be supported already.

I don't have time for a pull request myself but I'd like to see this happen.

**Comment by atentis** [comment]
Has anyone made any progress with this? Is there no way to clear the input still?

**Comment by abobwhite** [comment]
This works now, however, there are styling issues with bootstrap. See #578. I still believe that the allow-clear attribute is undocumented which is probably why you thought it wasn't implemented.

**Comment by dimirc** [comment]
I just merged PR https://github.com/angular-ui/ui-select/pull/667 and now select2 and bootstrap should work ok with `allow-clear`
