### ISSUE TITLE
Action on paste, add ng-paste?

### ISSUE THREAD

**Issue by Jacq** [angular-ui/ui-select#429]
Is there any way to populate an ui-select using a pasted text into the input element?
I'm thinking on paste for example 1,2,3,4 so the 1 2 3 4 items are added to the ui-select.
I've tried with ng-paste but without modifying the ui-select src I think I cannot attach it to the inner input element which is the one that gets the paste event.
thanks!
Jacq.

**Comment by tjsail33** [comment]
Bump. Would also like to see the parsing of pasted text for delimiters.
