### ISSUE TITLE
uiSelect should expose OPEN and other events

### ISSUE THREAD

**Issue by ttonyh** [angular-ui/ui-select#432]
uiSelect should expose **open** and other events that select2 has: **opening**, **change**, **close**, **highlight**, **selecting**, **removing**, **removed**, **loaded**, **focus**, and **blur**. I understand several are already available but it would be nice to have them all accessible through a single format, e.g. broadcast/on or via attr/observe.

**Comment by cvharris** [comment]
I think the workaround with decorators is too much for the simplicity of a few new attributes. Instead, why not add an `on-close` callback attribute. I've modified my select.js to accept this.

In the `ui-select` `link` function, parse the attribute:
```javascript
$select.onCloseCallback = $parse(attrs.onClose);
```
then inside the controller's `close` method call
```javascript
ctrl.onCloseCallback($scope, {
    $model: ctrl.parserResult.modelMapper($scope, {})
});
```
Works as expected and is the right fix for the app my team is working on.

**Comment by vdzundza** [comment]
Workaround https://github.com/angular-ui/ui-select/issues/432#issuecomment-65490071 doesn't work

**Comment by csizzle** [comment]
Anyone have any luck getting the blur event (and all the others) to work on the active text field?  I'm thinking of using jQuery to bind it after it's live, and take control from there.

The snippet from Tony H worked for me, except that the events are called at points during selection that would not normally be interpreted as a .blur or .focus on a normal select.

What I'm after is using the text the user has entered as a newly created value which gets selected and blurs if the user clicks away from the active ui-select element.  The select/dropdown currently remains in an active state until a selection is made.  Also, I want that when the tab key gets pressed during selection, it tabs to the next element.  It currently selects the first item in the list, and leaves that item focused.

Are any of these things possible out-of-the-box?

**Comment by csizzle** [comment]
So, I bound .blur to the ".ui-select-search" input box, and selected the first item in the list of options each time that this blurred.  The only problem came when I arrowed down to make a selection, then pressed the tab key, it still selected the first option.  Any ideas?

**Comment by cssensei** [comment]
This is still an issue. One solution it's to use the decorators or add some additional attribute to the directive and then do some work in the `link` function, but really best would be to have these events in the open API layer.

**Comment by rochesterdesigns** [comment]
What I've elected to do is handle validation of the ui-select on form submit, which is less than ideal.  Leveraging the jQuery Select2 plugin, and moving away from Angular in this specific case seems like a viable option as well.

**Comment by yvesmh** [comment]
@ttonyh 's workaround wasn't working for me on angular 1.3.15 and ui-select 0.12.0, so I had to tweak it a little bit:

```javascript
  .config(function ($provide) {
    $provide.decorator('uiSelectDirective', function ($delegate) {

      var directive = $delegate[0];
      var directiveCompile = directive.compile;

      directive.compile = function (tElement, tAttrs) {
        var link = directiveCompile.apply(this, arguments);
        return function(scope, elem, attrs) {
          link.apply(this, arguments);
          scope.$watch('$select.open', function(val) {
            scope.$parent.$broadcast('uiSelect:open', val);
          });
        };
      };

      return $delegate;

    });
  });
```

If you want to know when blur occurs on your controller: (note this event will also fire if user selected something)

```javascript
    $scope.$on('uiSelect:open', function(evt, opened) {
      if(!opened) {
        console.log('user selected something or blur ocurred');
      }
    });
```

**Comment by ttonyh** [comment]
Since my last update, there's been some changes to the way ui-select sets up the directive. They now use the compile function, which is why my above code won't work. Here's an update that I just tried, and it seems to work, if you guys want to give it a shot and let me know your results:

```
module.config( function( $provide ) {
    $provide.decorator( "uiSelectDirective", function( $delegate ) {
        var directive = $delegate[ 0 ],
            compile = directive.compile;

        directive.compile = function compile( tElement, tAttrs ) {
            var link = compile.apply( this, arguments );
        
            return function( scope, element, attrs, controller ) {
                link.apply( this, arguments );

                var $select = controller[ 0 ];

                scope.$watchGroup( [ "$select.open", "$select.focus" ], function( val ) {
                    scope.$parent.$broadcast( "uiSelect:events", val );
                });
            };
        };

        return $delegate;
    });
});
```

This basically extends their compile function instead of the code I posted above, which overrides it.

**Comment by RavenHursT** [comment]
Well.. a lot of talk about workarounds w/ decorators.  Which is what we ended up doing to achieve onOpen and onClose API functionality.  If anyone's interested, here's what we did:

```
    $provide.decorator('uiSelectDirective', function( $delegate, $parse ) {
            var directive = $delegate[ 0],
                preCompile = directive.compile;
        
            directive.compile = function compile() {
                var link = preCompile.apply( this, arguments );
        
                return function( scope, element, attrs, controller ) {
                    link.apply( this, arguments );
        
                    var $select = controller[ 0 ];
        
                    if(attrs.uiSelectOnOpen || attrs.uiSelectOnClose) {
                        $select.onOpenCallback = $parse(attrs.uiSelectOnOpen);
                        $select.onCloseCallback = $parse(attrs.uiSelectOnClose);
                        scope.$watch('$select.open', function(newV){
                            if(newV) {
                                $select.onOpenCallback(scope, {
                                    $model: $select.parserResult.modelMapper(scope, {})
                                });
                            } else {
                                $select.onCloseCallback(scope, {
                                    $model: $select.parserResult.modelMapper(scope, {})
                                });
                            }
                        });
                    }
                };
            };
        
            return $delegate;
        });
```

Once we had that, I figured why not just make a PR to add it to UI-Select?  So here's my PR: https://github.com/angular-ui/ui-select/pull/1153

Hopefully if can make it into a 12.x release at some point @dimirc ?

**Comment by kunal999** [comment]
I am trying to make this work for handling the `focus` event, however it does not work as expected. The `$select.focus` property is set and reset multiple times when making a selection. Hence, it triggers the focus event multiple times when making a selection in the list of items. I would expect `focus` property to be set and true until I either tab out of the control or click somewhere else in the document.
Note: I am using `single select` with `bootstrap` theme.

**Comment by mtucciar** [comment]
@RavenHursT Thank you so ****ing much for this. I've spent two days trying to get the damn blur event to be available from my calling controller and FINALLY your solution works for me. Gonna +1 your PR

**Comment by pehrlich** [comment]
For any hapless googler.  This feature is merged and works.  You  need 0.19 or greater.  The documentation is here: https://github.com/angular-ui/ui-select/wiki/uis-open-close
