### ISSUE TITLE
Preformance

### ISSUE THREAD

**Issue by jacobharasimo** [angular-ui/ui-select#436]
Just wanted to let you know that this control is very expressive to use.

when looking at a page I made with multiple instance of this control i'm finding 69.93ms of delay for it

here is the json from the chrome angular performance output:

[{"name":"push","time":0.07799995364621275,"percent":"0.0534","$$hashKey":"EC58"},{"name":"$locationWatch","time":0.2139999996870758,"percent":"0.147","$$hashKey":"EC4S"},{"name":"autoScrollWatch","time":0.02999999560415749,"percent":"0.0206","$$hashKey":"EC66"},{"name":"ngModelWatch","time":2.736000402364877,"percent":"1.87","$$hashKey":"EC3G"},{"name":"{{$select.placeholder}}","time":2.9649988282471877,"percent":"2.03","$$hashKey":"EC3C"},{"name":"!$select.searchEnabled || ($select.selected && !$select.open)","time":1.955000800080597,"percent":"1.34","$$hashKey":"EC3O"},{"name":"$select.disabled","time":1.570999680552633,"percent":"1.08","$$hashKey":"EC3Q"},{"name":"{'focus': $select.open, 'disabled': $select.disabled, 'selectize-focus' : $select.focus}","time":3.796000732108947,"percent":"2.60","$$hashKey":"EC38"},{"name":"searchEnabled","time":0.6250001606531442,"percent":"0.428","$$hashKey":"EC4I"},{"name":"$select.selected","time":0.4409995162859557,"percent":"0.302","$$hashKey":"EC4M"},{"name":"{{$select.selected.formatted_address}}","time":0.11400011135265235,"percent":"0.0781","$$hashKey":"EC50"},{"name":"$select.searchEnabled && ($select.open || $select.isEmpty())","time":2.670000598300247,"percent":"1.83","$$hashKey":"EC3E"},{"name":"{{$group.name}}","time":2.973000053316352,"percent":"2.04","$$hashKey":"EC3A"},{"name":"$select.isGrouped","time":1.9569995347410458,"percent":"1.34","$$hashKey":"EC3K"},{"name":"{active: $select.isActive(this), disabled: $select.isDisabled(this)}","time":69.93400049395854,"percent":"47.9","$$hashKey":"EC34"},{"name":"$select.open","time":1.4579996350221345,"percent":"0.999","$$hashKey":"EC3S"},{"name":"regularInterceptedExpression","time":33.89999771025034,"percent":"23.2","$$hashKey":"EC36"},{"name":"$select.search","time":0.4369998350739482,"percent":"0.299","$$hashKey":"EC4Q"},{"name":"disabled","time":0.05099980626255268,"percent":"0.0349","$$hashKey":"EC5Y"},{"name":"{{nav.state}}","time":0.6840002606622877,"percent":"0.469","$$hashKey":"EC4G"},{"name":"{{nav.name}}","time":0.5220003658905623,"percent":"0.358","$$hashKey":"EC4K"},{"name":"{active:nav.active}","time":0.7489998824894426,"percent":"0.513","$$hashKey":"EC4E"},{"name":"business.categories[0]","time":0.1060001086443662,"percent":"0.0726","$$hashKey":"EC4W"},{"name":"business.country","time":0.050000089686363866,"percent":"0.0343","$$hashKey":"EC5S"},{"name":"function () {\n                        return element[0].getAttribute('width');\n                    }","time":0.1289999927394092,"percent":"0.0884","$$hashKey":"EC4U"},{"name":"function () {\n                        return element[0].getAttribute('height');\n                    }","time":0.04499993519857522,"percent":"0.0308","$$hashKey":"EC60"},{"name":"tiles","time":0.05799997597932815,"percent":"0.0397","$$hashKey":"EC5U"},{"name":"layers.baselayers","time":0.0639997888356447,"percent":"0.0439","$$hashKey":"EC5O"},{"name":"layers.overlays","time":0.053000112529843976,"percent":"0.0363","$$hashKey":"EC5W"},{"name":"center","time":0.0349997426383198,"percent":"0.0240","$$hashKey":"EC68"},{"name":"markers","time":0.04300003638491038,"percent":"0.0295","$$hashKey":"EC62"},{"name":"{{$select.selected.name}}","time":0.997999508399517,"percent":"0.684","$$hashKey":"EC44"},{"name":"countries.isLoading","time":0.06399984704330575,"percent":"0.0439","$$hashKey":"EC5Q"},{"name":"states.isLoading","time":0.05000026430934673,"percent":"0.0343","$$hashKey":"EC64"},{"name":"!business.categories[0]","time":0.07899990305304525,"percent":"0.0541","$$hashKey":"EC5C"},{"name":"!business.categories[1]","time":0.06499991286545984,"percent":"0.0445","$$hashKey":"EC5I"},{"name":"!business.categories[2]","time":0.06300001405179505,"percent":"0.0432","$$hashKey":"EC5G"},{"name":"{{$select.selected}}","time":0.9780000546015809,"percent":"0.670","$$hashKey":"EC48"},{"name":"paymentType.accepted","time":0.39199995808303323,"percent":"0.269","$$hashKey":"EC4O"},{"name":"/images/icons/payment_types/{{paymentType.slug}}.png","time":0.9240005747415125,"percent":"0.633","$$hashKey":"EC4A"},{"name":"{{paymentType.name}}","time":1.2609992991201568,"percent":"0.864","$$hashKey":"EC3Y"},{"name":"{{socialNetwork.name|uppercase}}","time":1.354000938590617,"percent":"0.928","$$hashKey":"EC3W"},{"name":"{{socialNetwork.name}}","time":0.8939997642301023,"percent":"0.613","$$hashKey":"EC4C"},{"name":"/images/icons/social_network/{{socialNetwork.slug}}.png","time":1.2090001255273821,"percent":"0.828","$$hashKey":"EC3U"},{"name":"{noMarginBottom:$index>=8}","time":1.5050004003569497,"percent":"1.03","$$hashKey":"EC3M"},{"name":"markers[\"newLocation\"]","time":0.09599979966878888,"percent":"0.0658","$$hashKey":"EC4Y"},{"name":"/images/icons/pins/{{category.slug}}.png","time":1.1099997791461649,"percent":"0.761","$$hashKey":"EC42"},{"name":"{{category.name}}","time":1.893999287858601,"percent":"1.30","$$hashKey":"EC3I"},{"name":"{{category.slug}}","time":0.9029997163452212,"percent":"0.619","$$hashKey":"EC40"},{"name":"services","time":0.08100009290501473,"percent":"0.0555","$$hashKey":"EC5A"},{"name":"{active:category==selected}","time":1.1160001740790908,"percent":"0.765","$$hashKey":"EC46"},{"name":"shopping-retail","time":0.09500002488493921,"percent":"0.0651","$$hashKey":"EC54"},{"name":"hotels-travel","time":0.07299991557374602,"percent":"0.0500","$$hashKey":"EC5E"},{"name":"financial-services","time":0.06599992047995328,"percent":"0.0452","$$hashKey":"EC5K"},{"name":"beauty-spas","time":0.08200004231184715,"percent":"0.0562","$$hashKey":"EC56"},{"name":"restaurants","time":0.06099988240748644,"percent":"0.0418","$$hashKey":"EC5M"},{"name":"entertainment-activities","time":0.08600007276982073,"percent":"0.0589","$$hashKey":"EC52"}]

**Comment by wesleycho** [comment]
Closing as too full of noise and not enough useful/granular information.
