### ISSUE TITLE
old version angular js not working on select2 and selectize example

### ISSUE THREAD

**Issue by zzyclark** [angular-ui/ui-select#440]
I try to load select2-bootstrap3 and selectize-bootstrap3 example on my browser, both chrome and firefox. The user list is blank, name on the list can't be displayed. 

I thought the problem is angular js version. I change the version from 1.2.15 to 1.2.19. Then these two examples can work normally.

**Comment by user378230** [comment]
Closing this issue as over a year old and doesn't have a repro sample. 

If you believe its still relevant please update with a plunkr (or similar) against the latest version of ui-select (currently v0.15.0)
