### ISSUE TITLE
highlight filter throws undefined error when using $sce.trustAsHtml

### ISSUE THREAD

**Issue by mohan-evolent** [angular-ui/ui-select#442]
highlight filter throws undefined error when the data is parsed with $sce.trustAsHtml

example given below.  start typing test in the dropdown and the error can be seen on the console window.
http://plnkr.co/edit/xkvMmGUkTNkfjsPrviIU?p=preview

**Comment by wesleycho** [comment]
Closing as fixed in the latest release: http://plnkr.co/edit/n4LsGeoCoFBA3GZvWyBd?p=preview
