### ISSUE TITLE
query functions

### ISSUE THREAD

**Issue by vovka-s** [angular-ui/ui-select#448]
It'll be usefull to add query function like in original select2 to search results in remote dataset by every term.
Or callback for loading remote data

**Comment by XciD** [comment]
+1

**Comment by zoyaH** [comment]
+1

**Comment by Nekle** [comment]
+1

**Comment by wesleycho** [comment]
This is better implemented on the user side - this is because this is a type of pet feature that ends up adding bloat to the library, which is not useful for users who do not want such a feature.

Closing as something not desired.
