### ISSUE TITLE
Is it possible to reference my own html partials?

### ISSUE THREAD

**Issue by robson-gilli** [angular-ui/ui-select#450]
Hi.

I have a situation where I need to have three ui.selects on the same page, all using bootstrap. The issue is that the layout of those components are completely different from each other.

Is it possible to have external partials and reference them directly through a 'templateUrl' attribute on the directive, or something similar?

**Comment by user378230** [comment]
For future reference this can be done specifying a custom value for the theme attribute and using it to prefix templates that are store in the `$templateCache`

A relevant line: https://github.com/angular-ui/ui-select/blob/161cff56c0ba9d4a86ae213056dd78ba18296036/src/uiSelectDirective.js#L8
