### ISSUE TITLE
onEnable / onDisable Callbacks

### ISSUE THREAD

**Issue by AdamAxtmann** [angular-ui/ui-select#451]
I am populating a ui-select with remote data, but I don't want to fetch the data if the ui-select is disabled. It would be nice to have an onEnable event to allow a function call when the select becomes enabled.

**Comment by rwlogel** [comment]
+1

**Comment by user378230** [comment]
Closing as legacy issue. 

I this case I imagine the value passed to the `search-enabled` attribute could just be `$watch`ed
