### ISSUE TITLE
Binded model is not available inside on-select's handler

### ISSUE THREAD

**Issue by germanger** [angular-ui/ui-select#455]
This is my view:

    <ui-select ng-model="selectedExporter.selected" ng-disabled="fetchingExporters || working" on-select="onExporterSelected()">
        <ui-select-match placeholder="">{{$select.selected.name}}</ui-select-match>
        <ui-select-choices repeat="exporter in exporters | filterBy: ['name', 'code']: $select.search"> 
            <div ng-bind-html="exporter.name | highlight: $select.search"></div>
        </ui-select-choices>
    </ui-select>

This is my code:

    $scope.selectedExporter = {};
    $scope.exporters = []; 

    $scope.onExporterSelected = function () {
        console.log($scope.selectedExporter);  // Prints "{}"
    };

As you can see, the model is not available inside that handler...
I'm using the last version (0.8.3)

Although I'm using angular 1.2.26 (and last is 1.3.4)

**Comment by user378230** [comment]
Closing as legacy issue and resolved.
