### ISSUE TITLE
Allow adding items on the fly "tagging" on regular mode as well.

### ISSUE THREAD

**Issue by gotenxds** [angular-ui/ui-select#456]
I want to be able to add new items just like tagging on multiple mode only not in multiple mode but on 'regular' select mode.

**Comment by Aklakan** [comment]
+1

**Comment by cannelony** [comment]
+1

**Comment by RobiFerentz** [comment]
Anything done with this one yet? I think there's a pull request to add this somewhere.

**Comment by Pavek** [comment]
+1

**Comment by brianfeister** [comment]
Available in v0.9.8
