### ISSUE TITLE
Looses field focus after selecting an entry

### ISSUE THREAD

**Issue by mattiash** [angular-ui/ui-select#46]
ui-select with the bootstrap theme does not handle focus() properly. After the user selects an entry from the dropdown by pressing Enter, keyboard focus is lost (I think that focus is moved to the <body> element). The problem can be seen in the following plunkr:

http://plnkr.co/edit/FZ6xHJHLhmyIxLKS4mAK?p=preview

**Comment by realavaloro** [comment]
This issue seems to be back when using `"angular-ui-select": "0.14.9"` and Angular 1.5.0
Anyone can confirm whether the problem remains?

**Comment by realavaloro** [comment]
I am experiencing the same issue with angular 1.5.0 and angular-ui-select 0.14.9 although I cannot reproduce it in a basic example
http://plnkr.co/edit/Qt1KJflr9Eh9wMBVfpGT?p=preview
so it must have some conflict with some of my other libraries but I still haven't found which one!

Any clue by any chance on which one might be likely to conflict as per past experience?
```
    "angular": "1.5.0",
    "bootstrap-sass-official": "3.3.6",
    "angular-bootstrap": "1.2.1",
    "angular-mocks": "1.5.0",
    "angular-route": "1.5.0",
    "angular-sanitize": "1.5.0",
    "angular-animate": "1.5.0",
    "angular-messages": "1.5.0",
    "angular-ui-router": "0.2.18",
    "angular-ui-select": "0.14.9",
    "angular-toastr": "1.7.0",
    "font-awesome": "~4.5.0",
    "Hover": "~2.0.2",
    "oidc-token-manager": "^1.0.1",
    "restangular": "1.5.1",
    "lodash": "1.3.0",
    "ag-grid": "3.2.0"
```
