### ISSUE TITLE
ng-repeat fired on hover

### ISSUE THREAD

**Issue by gaui** [angular-ui/ui-select#460]
Is this normal behavior? Can this be avoided?

https://s3.amazonaws.com/uploads.hipchat.com/136601/989834/HHK0VvyS3TIArW4/select2-loop.gif

Plunker:
http://plnkr.co/edit/CvHxWZzv6V7XK368cZF3?p=preview

**Comment by dimirc** [comment]
Related to https://github.com/angular-ui/ui-select/pull/1211
