### ISSUE TITLE
uiSelectChoices directive incorrect work with angular 1.2.6 - 1.2.9

### ISSUE THREAD

**Issue by D2Phoenix** [angular-ui/ui-select#461]
Content not transclude to choices list.

![problem_ui_select](https://cloud.githubusercontent.com/assets/6198982/5256669/0d145768-79dd-11e4-9525-7b91149db573.png)

After some investigation, I found next solution(change passing transcludeFn directly to groups and choices):
```javascript
	if(groupByExp) {
	  $compile(groups, transcludeFn)(scope);
	}
    $compile(choices, transcludeFn)(scope); 
```

**Comment by user378230** [comment]
Closing as only v1.2.18+ is supported as per README.
