### ISSUE TITLE
Dropdown selection problem with Angular v1.3.1+

### ISSUE THREAD

**Issue by Dev63** [angular-ui/ui-select#482]
Beginning with AngularJS v1.3.1 (and still true through v1.3.5), the ui-select dropdown does not highlight the initial programmatic selection, but instead highlights the first entry in the list.  Once you select an entry manually, subsequent clicks to drop down the list will correctly highlight the current choice.

You can see this working incorrectly in [this plunker](http://plnkr.co/edit/GiwazfTn6uuwa8W5qnK2?p=preview), where I have taken the demo plunker and updated the links to angular v1.3.5 and set the initial person to Amalie.  But when you click the drop down, it highlights Adam, not Amalie.

**Comment by equilerex** [comment]
No updates to this issue? definitely still valid!

**Comment by brianfeister** [comment]
PR's welcome!

**Comment by kasperlewau** [comment]
Testing the above plunker with some different versions of ui-select. 

The 0.10.0 release appears to have taken care of the problem on my end, left the rest of the code untouched. 

[plunk](http://plnkr.co/edit/rWfkqEkeEMFh1W0x9OTV?p=preview)

**Comment by Jefiozie** [comment]
@kasperlewau , if I understand you correct this issue is resolved from 0.10 and up?
Thanks.

**Comment by kasperlewau** [comment]
As far as I could tell, yeah. 0.10.0 appeared to solve the issue(s) on my end.

**Comment by Jefiozie** [comment]
Thanks, closing it down. 

ps.  If someone feels the need or have the same problem please open a new issue.
