### ISSUE TITLE
"Force scope model value and ngModel value to be out of sync to re-run formatters"

### ISSUE THREAD

**Issue by davisford** [angular-ui/ui-select#495]
This line is in the source [line 293 in master right now](https://github.com/angular-ui/ui-select/blob/master/src/select.js#L293)

```javascript
ctrl.ngModel.$modelValue = null; //Force scope model value and ngModel value to be out of sync to re-run formatters
```

This totally breaks ui-select for me, and seems un-necessary.  It took me a while to track this down, unfortunately.  The end result is if you have the following kind of scenario:

1. Blank form, user fills out, and chooses multi-select values from `ui-select`, click save
2. You persist values
3. Later user goes to same form to edit value you just fetched form persistence...and you repopulate the scope bindings hoping their previous choices will show up in the form, but they do not.   The form remains blank.  New choices show in the view, but do not bind to the scope property.

This is hard to explain -- would create a plnkr.co if I could but it is down right now.  In short, trying to rebind to previously selected choices from `ui-select` is broken b/c this line seems to wreck the ngModel binding.

Removing this line resolves the issue for me.

Here's an example of my markup:

```html
<ui-select name='locations' multiple='true' ng-model='alert.locations' theme='bootstrap' ng-required='true'>
  <ui-select-match placeholder='Select or search for a location'>{{$item.name}}</ui-select-match>
  <ui-select-choices repeat='l in locations track by l.location_key | orderBy:"name">
    <div ng-bind-html='l.name | highlight: $select.search'></div>
  </ui-select-choices>
</ui-select>
```

```javascript

angular.module('foo').controller('FooCtrl', ['$scope', function ($scope) {
  
   $scope.alert = { /* an object */
     locations: [ ],
     etc: { }
   };
   // go fetch alert for editing

   $scope.locations = [];
   // fetch locations
}])
```

**Comment by wesleycho** [comment]
Is this still currently an issue? Can you reproduce this with the latest release of UI Select?

**Comment by davisford** [comment]
No idea, that was two years ago..which is like two lifetimes in software years.  It's safe to say I found a workaround.
