### ISSUE TITLE
ng-required does not set ui-select as $invalid in multi-select mode

### ISSUE THREAD

**Issue by jdmcnair** [angular-ui/ui-select#500]
The `ui-select` element is still showing valid when no items are selected in multi-select mode and the ng-required directive is applied. It appears to invalidate correctly in single-select mode.

**Comment by abobwhite** [comment]
+1 Looking for a workaround myself.

**Comment by wald-tq** [comment]
+1 got the same issue. Have you found a solution yet?

**Comment by wald-tq** [comment]
Duplicate of #258
