### ISSUE TITLE
reset-search-input=true resets input box but not button every second call

### ISSUE THREAD

**Issue by deitch** [angular-ui/ui-select#502]
The `ui-select` is bound to a scope var with `ng-model`. I reset it so that when the input text box blurs, and it switches back to a `button`, it always shows the placeholder text of "Search..."

Yet, each second call it ignores the reset.

1. Create a `ui-select` with `reset-search-input=true`. 
2. Click the select, it becomes an `<input>`
3. Type into the `input`
4. Select an item
5. The `ui-select` changes from `input` back to `button`, and is cleared
6. Repeat steps 2-5. This time, the `button` does not reset to the placeholder text.

I modified the original sample plunkr to show it, here: http://plnkr.co/edit/16DRYH8MbPJOy0GpogZz?p=preview

I have it call `on-select` to trigger the desired action and reset the `ng-model`, so it is cleared.

For some reason, resetting the scope variable tied to the model only clears it every second time. Is this a timing issue? If so, why would it consistently be every second time?

**Comment by deitch** [comment]
Any updates?

**Comment by deitch** [comment]
If it helps... it appears to have something to do with the order of calling in `ngModelWatch` in angular. When it fails, it calls it for the `ctrl` for the `input` and then for the `ngModel`; when it succeeds, the other way around.

**Comment by deitch** [comment]
Brutally painful, but I did figure it out. It has to do with when the various ng-model calls are made by watches.

I worked around it using a separate directive `reset-search-model` and then using `on-select` to capture the information. I can submit it, if anyone wants.

**Comment by sonicd300** [comment]
i'd like to see your code, im having the same problem, it will help me a lot.

**Comment by deitch** [comment]
Hey @sonicd300 , I didn't want to hack the original ui-select code, and risk making it incompatible with upgrades. So I wrote my own little directive to clear it appropriately. After enough headache, it turned out to be very simple to clear. But isn't that always the case? The biggest problem has the simplest solution... once you figure it out. :-) 

Here is the gist https://gist.github.com/deitch/e4abbaeeaca7b0d66fcf

I also modified the plunkr to show it working. 
http://plnkr.co/edit/58OgDXOaW12D38U2m381?p=preview

Personally, I think this should be added to the core as an option. But I might be biased...

Enjoy!

**Comment by sonicd300** [comment]
Thanks for the gist, i've modified a little bit, let me know what you think.

Basically removed the if so you just set reset-search-model, it's presence will be enough to make the directive work, no need to set the attribute to true/false

https://gist.github.com/sonicd300/3bf44e56a4bdb3eb8a0d

**Comment by deitch** [comment]
Like. Very much. Now.... can we get the angular-ui team to make this a standard part of ui-select?

**Comment by sonicd300** [comment]
Hope they include this or something to solve this bug, i've spent a lot of time trying to figure it out on my own (not as much as you) then decided to check the bug report and found you, many thanks bro.

**Comment by deitch** [comment]
I hope so too. But I am glad my hard work paid off for more than just me!

If you message with any of them, or can bump it, please do.

**Comment by ulilicht** [comment]
@sonicd300 
if you're still searching for a solution, workarounds can be found here: http://stackoverflow.com/a/28318018/2938151

**Comment by sonicd300** [comment]
Hi @ulilicht thanks for the link, your time is much appreciated.

In my case I prefer the directive instead of having patch logic in a controller, so when library updates I can easily remove the directive and go back to normal with less effort.

**Comment by eugenekgn** [comment]
Is there an answer for this one?

**Comment by dimirc** [comment]
I updated the original plunker with last version of library and I don't see the problem anymore. Can you reconfirm this?

Updated [plunker](http://plnkr.co/edit/lpSO9CxjU3sVbWp0Cayi?p=preview)

**Comment by deitch** [comment]
@dimirc yes, it looks like this latest plunkr does not have the problem. 

It looks like you are using 0.9.8 in this plunkr. Can you share the change, or point to a commit so we can see the diff?

**Comment by deitch** [comment]
Hmm, I am still seeing it when I remove my added directive. I am exploring further...

**Comment by deitch** [comment]
Yes, and definitely using 0.9.9, but I cannot yet reproduce it in the plunkr. Trying.

**Comment by deitch** [comment]
OK, I see it. You are using the `on-select` callback to reset the model. I guess that would work, but would you not just want to use the extended directive option `reset-search-model` that automatically does it? Isn't that both cleaner and more in line with the angular directive style?
