### ISSUE TITLE
on close callback

### ISSUE THREAD

**Issue by eromanowski** [angular-ui/ui-select#507]
I need a way to wire up to the on close event. Once the ui-select closes I need to set focus on a text input. I'm not seeing any event in the documentation to wire up to. What would be the best way to do this? 

I noticed there is a $select.open boolean flag in select.js, could I put a watch on this boolean flag to determine if the ui-select dropdown has been closed?

I tried setting focus in the on-select callback, but there seems to be other things still happening that causes my text input to lose focus.

**Comment by Zax** [comment]
+1

**Comment by crazytanvi** [comment]
+1

**Comment by user378230** [comment]
You should now be able to use the `uisOpenCloseCallback` to watch for the close event.
