### ISSUE TITLE
enableCellEditOnFocus causes cellEditableCondition to be called twice

### ISSUE THREAD

**Issue by Dev63** [angular-ui/ui-select#508]
Setting `enableCellEditOnFocus=true` causes `cellEditableCondition` to be called twice.

I have an alert in my cellEditableCondition function to tell the user why he is not being allowed to edit the cell, and the alert gets called twice.  

[Plunker](http://plnkr.co/edit/Jjsk19dbuImEA3AfuwYg?p=preview) based on [Tutorial 201](http://ui-grid.info/docs/#/tutorial/301_editableOnFocus).  Click on a 'Name' cell and see alert called twice. Even worse, after doing so, go to another browser tab, and then return, and see two more messages as focus returns.

Is this a bug; is there a simple workaround?

**Comment by wesleycho** [comment]
Closing as this is a [UI Grid](https://github.com/angular-ui/ui-grid) issue, not a UI Select issue.
