### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by Hesesses** [angular-ui/ui-select#511]
bower install angular-ui-select --save

bower cached        git://github.com/angular-ui/ui-select.git#0.9.5
bower validate      0.9.5 against git://github.com/angular-ui/ui-select.git#*
bower extra-resolution      Unnecessary resolution: modernizr#2.8.x

And nothing gets installed

Any ideas whats wrong?

**Comment by user378230** [comment]
Closing as legacy issue, doesn't appear to be a problem with the library.
