### ISSUE TITLE
Nuget support

### ISSUE THREAD

**Issue by siulung4073** [angular-ui/ui-select#513]
Hi. sorry if this is not the place for this, but it would be great to have the library in nuget!

thanks!

**Comment by rogier21** [comment]
Since VS2015 is not being released anytime soon, could we have a nuget package?

**Comment by Incognito-Nemo** [comment]
+1

**Comment by amanmahajan7** [comment]
+1

**Comment by wesleycho** [comment]
Microsoft is moving towards npm support, so closing this as something that isn't to be supported - frontend is also consolidating around npm, so it is highly recommended to use npm for client-side dependencies.
