### ISSUE TITLE
Cannot assign to read only property 'uiSelectChoiceLocked' of

### ISSUE THREAD

**Issue by jziggas** [angular-ui/ui-select#514]
Getting an error in the console when trying to use ui-lock-choice:

    Cannot assign to read only property 'uiSelectChoiceLocked' of ADMIN at ctrl.isLocked (https://localhost:8443/.../bower_components/angular-ui-select/dist/select.js:479:39)

In my template I am using:

    <ui-select-match ui-lock-choice="$item === 'ADMIN'">...</ui-select-match>

Has anyone else come across this? I'm using ````~0.9.4```` according to ````bower.json````.

**Comment by piaggi** [comment]
I have the same problem. 
It was identified only on Chrome browser and when items are string values.

**Comment by sboichon** [comment]
I'm having the same error. Anyone found a fix ?

**Comment by JonathanRamier** [comment]
try to upgrade to ver ~0.10.0

**Comment by jtrussell** [comment]
Any work being done on this - or would a PR be welcome? Seems to happen when items are strings rather than objects.

**Comment by Grant-Lay** [comment]
Any known workarounds for this?

**Comment by wesleycho** [comment]
Can someone post a reproduction based on the latest release on Plunker?

**Comment by wholypantalones** [comment]
There you go. https://plnkr.co/edit/Oi43dM?p=preview

**Comment by user378230** [comment]
Closed by c01d363 (#1712)
