### ISSUE TITLE
"Error: c.push is not a function"

### ISSUE THREAD

**Issue by Arkh1** [angular-ui/ui-select#517]
"Error: c.push is not a function"

Just curious if anybody else is getting this error when trying to use ui-select.  Each instance of ui-select is generating two of these errors for me.  When I start filtering the select it generates a lot more of them.

Running the following frameworks: 
Angular 1.3.5
Bootstrap 3.3.1
Angular-UI 0.12.0
jQuery 2.1.1

Here is a sample instance of ui-select in the application that I am working on.
```html
<ui-select ng-model="selectedPhoneNumber" theme="select2" style="min-width: 300px;" class="setting-controls did-select-dropdown form-control">
    <ui-select-match>
        {{$select.selected.fullName + ' - ' + ($select.selected.primaryPhone.number | tel)}}
    </ui-select-match>
    <ui-select-choices repeat="entry.primaryPhone.number as entry in companyDirectoryEntries | filter: $select.search | orderBy:'firstName'">
        <span ng-bind-html="entry.fullName | highlight: $select.search"></span> - 
        <span ng-bind-html="entry.primaryPhone.number | tel | highlight: $select.search"></span>
    </ui-select-choices>
</ui-select>
```

**Comment by user378230** [comment]
Closing this issue as over a year old and doesn't have a repro. 

If you believe its still relevant please reopen with a plunkr (or similar) against the latest version of ui-select (currently v0.15.0)
