### ISSUE TITLE
Null tag added to list (race condition)

### ISSUE THREAD

**Issue by aeharding** [angular-ui/ui-select#520]
Hi guys,

I'm happy that tagging is being added to ui-select, however, it's still pretty rough around the edges. 0.9.5 fixed a lot of the things that made it unusable (couldn't select first thing, other breaking stuff), but I've encountered another smaller issue with 0.9.5.

http://plnkr.co/edit/Yx4I7EEM7jn7XVdKqsbL?p=preview
![image](https://cloud.githubusercontent.com/assets/2166114/5458339/fc009596-8516-11e4-8e99-b2b1f7ccc1ea.png)

Click inside the input area, and then type a comma and then hit enter very quickly (it doesn't occur when you press comma and then spacebar, for some reason). A null item will be added to the array of items, which is annoying since it causes many errors in the console, and cannot be removed by clicking the 'x' or using the delete button.

Also, why does the dropdown flicker when tagging is enabled? It's kinda annoying, and it'd be nice if that could be fixed.

I appreciate the work done here guys!

**Comment by NJAldwin** [comment]
I'm seeing this as well, though it's not a race condition in this case.  Pressing the down arrow (to open the dropdown), then pressing the up arrow (to deselect anything), then pressing enter causes a null element to be added.  The null element does not appear in the list, so it probably shouldn't be able to be selected.

![dropdown with nothing selected](https://cloud.githubusercontent.com/assets/145036/5694748/4154e1c2-9946-11e4-8c07-76002975c3ff.png)

![dropdown with a null element](https://cloud.githubusercontent.com/assets/145036/5694746/117dbbd6-9946-11e4-9b3a-d4c0dc8d52f9.png)

Furthermore, this null element does not seem to be removable, instead throwing this:

```
TypeError: Cannot read property '_uiSelectChoiceLocked' of undefined
    at ctrl.removeChoice (http://run.plnkr.co/Agl9e65wEUyqtG1P/select.js:497:23)
    at getNewActiveMatchIndex (http://run.plnkr.co/Agl9e65wEUyqtG1P/select.js:609:20)
    at _handleMatchSelection (http://run.plnkr.co/Agl9e65wEUyqtG1P/select.js:625:18)
    at http://run.plnkr.co/Agl9e65wEUyqtG1P/select.js:648:23
    at Scope.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.js:12556:28)
    at Scope.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.js:12654:23)
    at HTMLInputElement.<anonymous> (http://run.plnkr.co/Agl9e65wEUyqtG1P/select.js:643:14)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.js:2816:10
    at Array.forEach (native)
    at forEach (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.js:320:11)
```

Similar behavior occurs in object-based tagging.  [Plunker demo](http://plnkr.co/edit/szYtoGgyFZVXAx12Y13c?p=preview)

**Comment by jtomek** [comment]
I am having the same problem.

**Comment by brianfeister** [comment]
I didn't look closely at this the first time I commented on it.  It's a valid bug.  It's related to the internal `ctrl.activeIndex` property's tracking as it relates to the `tagging` feature.  Can't promise to fix this immediately, but I'll add it to my to-do list.

**Comment by wesleycho** [comment]
Closing as this looks like it has since been fixed. Feel free to open a new issue if it is still a problem in the latest release.
