### ISSUE TITLE
When window is resized input inside does not update

### ISSUE THREAD

**Issue by acondiff** [angular-ui/ui-select#522]
![screen shot 2014-12-16 at 10 43 43 am](https://cloud.githubusercontent.com/assets/806104/5458687/97e083fa-8511-11e4-959b-c39a53770252.png)
In multi select inputs that are styled to be 100% width, when the window is resized, the input inside .ui-multiselect-container does not update causing big layout issues. To resolve this, the input's width needs to be updated on window resize.

**Comment by karanba** [comment]
Having same issue with  0.13.2
