### ISSUE TITLE
Model Does Not Bind

### ISSUE THREAD

**Issue by roadsunknown** [angular-ui/ui-select#531]
Data model does not bind unless the repeat source object and the ng-model source object are retrieved from the same original data model. #405 fixes the issue, but needs to be merged. #410 is related/same and #420 could also be considered related.

**Comment by b3n0n** [comment]
hello @brianfeister [this plunkr](http://plnkr.co/edit/qFa5PaohYFk1loKKrumK?p=preview) seems to fix the issue, and doesnt break any tests, change is in select.js line 944

**Comment by brianfeister** [comment]
Thanks @b3n0n!  Will ship v.0.9.8 including this fix in a few minutes.
