### ISSUE TITLE
ng-repeat fired on mouse enter event

### ISSUE THREAD

**Issue by gaui** [angular-ui/ui-select#532]
Every time when I hover over some item in the dropdown, it always fires the ng-repeat filter ($digest).
This is lagging my application because I'm working with a large dataset in the ng-repeat.

http://stackoverflow.com/questions/27234374/ng-repeat-continuously-fired-on-hover/27276849

http://i.imgur.com/cStlXzy.gif

http://plnkr.co/edit/OxiutZ8t4IX1bOxiOTgo?p=preview

**Comment by kaseOga** [comment]
+10

**Comment by pitieu** [comment]
+1

**Comment by gaui** [comment]
@pitieu Thanks, could you make a PR so it can be merged in?

I tested 0.12.0 and this still is a problem. Shame, because this library would be a replacement of chosen.

**Comment by dimirc** [comment]
Should be solved with https://github.com/angular-ui/ui-select/pull/1211
