### ISSUE TITLE
createSearchChoice: How would one achieve this Select2 feature in ui-Select?

### ISSUE THREAD

**Issue by kimardenmiller** [angular-ui/ui-select#534]
Is there an equivalent way to achieve what Select2 does in createSearchChoice?

**Comment by kimardenmiller** [comment]
Does ```tagging``` require ```multiple```?

All the examples I'm finding uses it. What if we only need single-select?

**Comment by idreeshaddad** [comment]
@kimardenmiller For what it's worth: No it does not. Try pressing ( , comma) after tagging.

@brianfeister Why does (Enter) work as a tagging token by default on multiple, and it does not work on single; even if defined in tagging-tokens?
