### ISSUE TITLE
ui-select modifying ng-model object

### ISSUE THREAD

**Issue by ilanbiala** [angular-ui/ui-select#540]
With this snippet:
```
<div class="form-group">
			<label for="users" class="col-sm-3 control-label">Users</label>
			<div class="col-sm-8">
				<ui-select multiple search-enabled ng-model="editingDesk.users" on-remove="editingDesk.removedUsers.has($item) ? editingDesk.removedUsers.delete($item) : editingDesk.removedUsers.add($item)" on-select="editingDesk.newUsers.has($item) ? editingDesk.newUsers.delete($item) : editingDesk.newUsers.add($item)">
					<ui-select-match placeholder="Select users...">{{$item.userName}}</ui-select-match>
					<ui-select-choices repeat="user in users | filter: $select.search">
						{{user.userName}}
					</ui-select-choices>
				</ui-select>
			</div>
		</div>
```

When the controller instantiates, `editingDesk.users` is properly populated. Once the controller finishes instantiating, `editingDesk.users.length` is 0. If I comment out the HTML above, then I don't have this issue.

**Comment by ilanbiala** [comment]
@brianfeister I switched to an array, and I still have this issue. Can you take a look to see what the issue is, because now I'm just using regular javascript.

**Comment by Asimov4** [comment]
There are cases where it does make sense to check the values in the ng-model against the ui-select-choices.
In the case of tagging, any value is potentially valid and should not be discarded.

**Comment by b3n0n** [comment]
so it could be a toggle for this verification? @brianfeister @Asimov4 ?

**Comment by ilanbiala** [comment]
@brianfeister this seems like it could be prevented by what @Asimov4 is saying. Any thoughts?

**Comment by Asimov4** [comment]
I suggested a pull request to not check values if the tagging mode is enabled.
According to the doc: https://github.com/angular-ui/ui-select/wiki/ui-select
"Enable tagging mode (add new items on the fly)." means that new items can be added to the list of choices. We should not check the model against the initial list of choices when trying to go from model to view.

**Comment by Asimov4** [comment]
I submitted this new pull request with a test: https://github.com/angular-ui/ui-select/pull/683
Thanks for the feedback @dimirc and sorry for the messy attempts.

**Comment by dimirc** [comment]
@ilanbiala are you still having issues with this? I'm putting together some changes at https://github.com/angular-ui/ui-select/pull/748 that might be related

**Comment by ilanbiala** [comment]
I reworked my implementation to hack around it after having some issues.

**Comment by wesleycho** [comment]
Is this still currently an issue? Can someone post a reproduction in Plunker based off of the latest release?
