### ISSUE TITLE
Feature request: Multiple select with ctrl-click without closing the dropdown

### ISSUE THREAD

**Issue by amergin** [angular-ui/ui-select#542]
Currently, each selection click closes the dropdown which is frustrating when you want to make multiple selections fast on a long dropdown list. 

In optimal case, a user could make several selections holding down the ``ctrl`` key, and the dropdown would be kept open. Furthermore, the current position of the dropdown scroll would be kept. For a demo, see the [Chosen demo page](https://harvesthq.github.io/chosen/) (multiple select dropdown).

**Comment by EliSnow** [comment]
Might I also add, it would be nice if Ctrl-A or some other mechanism selected all of the currently displayed options.

**Comment by user378230** [comment]
A `close-on-select` attribute can be set to `false` on newer versions of ui-select to achieve something similar to the desired result here. 

Closing as there doesn't appear to be much demand for this feature.
