### ISSUE TITLE
Is infinite scroll with remote data possible with ui-select?

### ISSUE THREAD

**Issue by BjoernKW** [angular-ui/ui-select#550]
Is infinite scroll with remote data possible as described on http://ivaynberg.github.io/select2/ with ui-select?

For instance:

$("#e7").select2({
    placeholder: "Search for a repository",
    minimumInputLength: 3,
    ajax: {
        url: "https://api.github.com/search/repositories",
        dataType: 'json',
        quietMillis: 250,
        data: function (term, page) {
            return {
                q: term, //search term
                page: page // page number
            };
        },
        results: function (data, page) {
            var more = (page * 30) < data.total_count;
            return { results: data.items, more: more };
        }
    }
});

**Comment by PowerKiKi** [comment]
Dupe of #221

**Comment by amcdnl** [comment]
Probably related to #620 too.
