### ISSUE TITLE
group-by attributes causes - Error: [$sce:unsafe] http://errors.angularjs.org/1.2.18/$sce/unsafe

### ISSUE THREAD

**Issue by idanb11** [angular-ui/ui-select#551]
Hi all,
I'm using the latest version of ui-select and when i use the following group-by value, i get the $sce:unsafe error:
`group-by="'string'"`
If I totally remove the group-by attribute, the error stops showing and everything is good - so this is not related to the $sce error that is shown in the FAQ section of the Wiki page.

Please help.

Idanb11

**Comment by brutto** [comment]
+1 (angular 1.3.8+)

PS: trying use $sce for return strings (via someGroupFn(item)) -- group appear above each select item =\

**Comment by brutto** [comment]
@idanb11 i found workaround -- just add ngSanitize module as required.

**Comment by idanb11** [comment]
@brutto great thanks.
