### ISSUE TITLE
Style: Bootstrap. Missing type="button" for template bootstrap/match.tpl.html

### ISSUE THREAD

**Issue by patricklehmann** [angular-ui/ui-select#561]
This causes in an error, where the form is submitted when hitting this button

**Comment by realityking** [comment]
Also #536

**Comment by wtilton** [comment]
Just got this as well.

**Comment by realityking** [comment]
Fixed with 1e25650d78242abfe54bfd1c50d4997485729b8c

**Comment by wesleycho** [comment]
Closing as fixed.
