### ISSUE TITLE
bootstrap styles

### ISSUE THREAD

**Issue by zawiasam** [angular-ui/ui-select#563]
Control layout is broken when you apply a theme for bootstrap template and when screen is in size "-md-" (for "-sm-" is ok) 
![image](https://cloud.githubusercontent.com/assets/7436990/5609946/d00c2a5e-94ac-11e4-808c-45f2614221ff.png)
![image](https://cloud.githubusercontent.com/assets/7436990/5609947/e1330c58-94ac-11e4-85f3-50b1adc7d7d8.png) 

after:
Commit: 9e635c12463861a0d0124306190f18a668d85f2f

**Comment by leonardoporro** [comment]
I've written this template, without using columns. It seems to work.
    (match.tpl.html)

<div class="input-group">
        <div class="form-control" tabindex="-1" ng-click="$select.activate()">
            <span ng-show="$select.isEmpty()" class="text-muted pull-left">{{$select.placeholder}}</span>
            <span ng-hide="$select.isEmpty()" class="pull-left" ng-transclude=""></span>
        </div>
        <div class="input-group-btn">
            <button type="button" class="btn btn-default" ng-if="$select.allowClear && !$select.isEmpty()" ng-click="$select.select(undefined)">
                <span class="glyphicon glyphicon-remove ui-select-toggle"></span>
            </button>
            <button type="button" class="btn btn-default" ng-click="$select.activate()">
                <span class="caret ui-select-toggle" ng-click="$select.toggle($event)"></span>
            </button>
        </div>
    </div>

**Comment by aeisenberg** [comment]
Thanks for raising this issue. We are hitting it too. It looks like if we stick to v0.9.3 or earlier, we can avoid this problem.

**Comment by brianfeister** [comment]
Fix released in  v0.9.6
