### ISSUE TITLE
Tagging - change default order

### ISSUE THREAD

**Issue by NJAldwin** [angular-ui/ui-select#574]
By default, enabling tagging mode seems to always add the possible tag to the *top* of the dropdown.  Is there / is there planned to be a way to change where in the list a new tag appears?  To facilitate quick data entry, I'd like actual matches (if any) to be the first choice during typing.

For example:
![multiple choice dropdown with text 'ma' typed, showing "ma (new)" listed before "Magenta" and "Maroon"](https://cloud.githubusercontent.com/assets/145036/5694712/076ba2c2-9944-11e4-859f-55996d1c3a47.png)
([Plunker based on the demo](http://plnkr.co/edit/szYtoGgyFZVXAx12Y13c?p=preview))

I'd expect typing `ma` to default to selecting `Magenta` (alphabetically first), providing `ma (new)` as a last-resort option.  Basically, I expect it to work as if tagging was not enabled, unless I type something that does not match anything or I explicitly scroll the highlight down to the new tag entry.

**Comment by NJAldwin** [comment]
Possibly related (should I create a separate issue?): pressing the down arrow (to open the dropdown), then pressing the up arrow (to deselect anything), then pressing enter causes a null element to be added.  The null element does not appear in the list, so it probably shouldn't be able to be selected.

![dropdown with nothing selected](https://cloud.githubusercontent.com/assets/145036/5694748/4154e1c2-9946-11e4-8c07-76002975c3ff.png)

![dropdown with a null element](https://cloud.githubusercontent.com/assets/145036/5694746/117dbbd6-9946-11e4-9b3a-d4c0dc8d52f9.png)

Furthermore, this null element does not seem to be removable, instead throwing this:

```
TypeError: Cannot read property '_uiSelectChoiceLocked' of undefined
    at ctrl.removeChoice (http://run.plnkr.co/Agl9e65wEUyqtG1P/select.js:497:23)
    at getNewActiveMatchIndex (http://run.plnkr.co/Agl9e65wEUyqtG1P/select.js:609:20)
    at _handleMatchSelection (http://run.plnkr.co/Agl9e65wEUyqtG1P/select.js:625:18)
    at http://run.plnkr.co/Agl9e65wEUyqtG1P/select.js:648:23
    at Scope.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.js:12556:28)
    at Scope.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.js:12654:23)
    at HTMLInputElement.<anonymous> (http://run.plnkr.co/Agl9e65wEUyqtG1P/select.js:643:14)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.js:2816:10
    at Array.forEach (native)
    at forEach (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.js:320:11)
```

Similar behavior occurs in object-based tagging.  [Plunker demo](http://plnkr.co/edit/szYtoGgyFZVXAx12Y13c?p=preview)

**Comment by brianfeister** [comment]
If I understand your request correctly, from [the wiki](https://github.com/angular-ui/ui-select/wiki/ui-select) check out the `tagging-label` property.  From https://github.com/angular-ui/ui-select/blob/master/examples/demo-tagging.html, there is an option which omits the `{search term} (new)` bit via `tagging-label="false"`.  I would recommend going that route for your use case.  I would consider it unlikely to add more complexity in this area should this be insufficient.

An example with that property:

```
  <h3>Simple String Tags </h3>
  <h4>(Predictive Search Model / No Labels)</h4>
  <ui-select multiple tagging tagging-label="false" ng-model="multipleDemo.colors2" theme="bootstrap" ng-disabled="disabled" style="width: 300px;">
    <ui-select-match placeholder="Select colors...">{{$item}}</ui-select-match>
    <ui-select-choices repeat="color in availableColors | filter:$select.search">
      {{color}}
    </ui-select-choices>
  </ui-select>
  <p>Selected: {{multipleDemo.colors2}}</p>
```

**Comment by NJAldwin** [comment]
I see that setting `tagging-label` to `false` makes the entry disappear, and thus only have any affect when nothing else is present.  I still think it would be useful to have the entry appear in the drop-down, but have it appear at the end, rather than at the beginning.  Does that not make sense?  I still think that even if it's appearing in the dropdown, it should yield to existing entries.

**Comment by brianfeister** [comment]
With respect, I feel that is a bad UX pattern and for that reason don't have any intention of going that direction.

**Comment by ronythomas** [comment]
I see that setting tagging-lablel to false does not work when you get the model through refresh

**Comment by parliament718** [comment]
The problem with this is that even when there is an exact match in the existing list, that options still appears second, after the (new) for the same term. I can imagine a user will simply see the "correct" entry highlighted (the new options) and hit enter, unknowingly adding a new item, instead of selecting the keyword other users have already established. 

How can I at least remove the (new) item when there is an exact match?

**Comment by qraynaud** [comment]
I also would prefer the new option at the end. I find at usage (in my app) that 99% of new entries are reusing previous tags, thus you always use keybord to select the tag while a simple enter would have worked. It is uselessly painful. Why not adding an option for this?
