### ISSUE TITLE
Does ui-select dislike ngResource?

### ISSUE THREAD

**Issue by kimardenmiller** [angular-ui/ui-select#575]
Any use of ```ngResource``` to generate ```ui-select-choices``` seems to generate strange results, very slow, refresh not working correctly, choices not clearing.

Is ```ngResource``` to be avoided in accessing RESTful data?

**Comment by user378230** [comment]
There shouldn't be any issues though you may need to provide some kind custom `refresh` function if using an async data source. https://github.com/angular-ui/ui-select/wiki/ui-select-choices
