### ISSUE TITLE
Tagging label problem with group-by option

### ISSUE THREAD

**Issue by idanb11** [angular-ui/ui-select#577]
Hi @dimirc ,
Great work...

Please have a look at the [demo](http://plnkr.co/edit/letVEHZG80WjIvDtoWP9?p=preview)

If you try to use ui-select with combination of tagging and group-by 
when you start to add a new custom tag the drop-down open with empty content and no tagging label are shown.
Everything else works fine besides that.

Idanb11

**Comment by noam3127** [comment]
I've been experiencing the same issue. Any help would be appreciated.

**Comment by angusoid** [comment]
Has anyone found any fixes for this issue?
