### ISSUE TITLE
How to handle Virtual Directories

### ISSUE THREAD

**Issue by greengumby** [angular-ui/ui-select#581]
Hi,

Currently with the code below there is always a 404 when requesting the templates. This is due to the fact the site is prefixed by a virtual directory.

How do you configure a virtual directory?

Cheers

 templateUrl: function (tElement) {
                // Gets theme attribute from parent (ui-select)
                var theme = tElement.parent().attr('theme') || uiSelectConfig.theme;
                var multi = tElement.parent().attr('multiple');
                return theme + (multi ? '/match-multiple.tpl.html' : '/match.tpl.html');
            },

**Comment by user378230** [comment]
Templates can be manually added to angular's `$templateCache` in an `angular.run(...)` block.

Closing this issue as its over a year old.
