### ISSUE TITLE
isArray vs isArrayLike

### ISSUE THREAD

**Issue by lifehackett** [angular-ui/ui-select#584]
ng-repeat uses an `isArrayLike` function and I am wondering if you would be amenable to doing the same.

https://github.com/angular/angular.js/blob/v1.3.8/src/ng/directive/ngRepeat.js#L333
https://github.com/angular/angular.js/blob/v1.3.8/src/Angular.js#L194

The use case is that in my project we have created an array like model class and I would like to be able to pass that in to the repeat function of ui-select without having to convert it to a true array which I am currently able to do for ng-repeat.

If you would prefer, I can submit a PR for this request.  The one downside that I can't see avoiding since angular does not appear to expose isArrayLike is that ui-select will have to maintain its own version of the function.

**Comment by user378230** [comment]
Closing as `ui-select` supports objects as data sources.
