### ISSUE TITLE
Prevent .select2-dropdown-open class from being added when select list is empty

### ISSUE THREAD

**Issue by pruchai** [angular-ui/ui-select#585]
I have a drop down with 4 options. When all 4 options are added to `multiple` element and the menu is empty, clicking inside the element still adds `select2-dropdown-open open` class to the container causing it to expand vertically.

Full menu:
![screenshot 2015-01-14 10 15 55](https://cloud.githubusercontent.com/assets/2467628/5744550/93ee51ce-9bd6-11e4-8cf5-543d3527774c.png)

All 4 options added to the container:
![screenshot 2015-01-14 10 16 09](https://cloud.githubusercontent.com/assets/2467628/5744565/b359cd40-9bd6-11e4-8fd4-fea52fa09b6c.png)

Clicking inside the container causes it to expand vertically:
![screenshot 2015-01-14 10 16 18](https://cloud.githubusercontent.com/assets/2467628/5744568/be663bf6-9bd6-11e4-913d-b44e2e6465e3.png)

**Another ~~(unrelated)~~ issue:**

**EDIT**: Actually, it is a related issue. Blank row that is being added at the bottom is `.select2-search-field`, which should not be there since there is nothing else to search for. The dropdown is now empty.

Sometimes an extra blank row is added to the bottom of the container. If you look at the screenshots attached above, length of options in the first row is approximately equal to the length of the second row, so no empty row is added. 

On the screenshot below, second row is longer than the first row, causing addition of the empty row at the bottom

![screenshot 2015-01-14 10 25 38](https://cloud.githubusercontent.com/assets/2467628/5744705/e5335952-9bd7-11e4-9039-2d788e26f9c9.png)

Another example
![screenshot 2015-01-14 10 35 15](https://cloud.githubusercontent.com/assets/2467628/5744849/1132ef6c-9bd9-11e4-868f-02a1096aed68.png)

![screenshot 2015-01-14 10 38 16](https://cloud.githubusercontent.com/assets/2467628/5744895/7b3c85f8-9bd9-11e4-812a-0860878a0148.png)

I am not sure if this is angular-ui-select related, but I have not seen this issue in any of the demos.

**Comment by wesleycho** [comment]
Going to close due to lack of reproduction in Plunker - feel free to open a new issue if this is still a problem with reproduction based on the latest release.
