### ISSUE TITLE
arrow key navigation is not working if search-enabled="false"

### ISSUE THREAD

**Issue by burib** [angular-ui/ui-select#589]
if search is enabled then you can navigate with arrow keys between the select-items, if search is disabled then arrow key navigation is not working.

**Comment by bettercallsteve** [comment]
+1

Looks like keyboard shortcuts (specifically handleDropDownSelection) is being bound to _searchInput.on 'keydown', and disabling the input prevents it from working.

**Comment by davideanderson** [comment]
+1

**Comment by seinavco** [comment]
+1

Please fix this issue..

**Comment by foxx9** [comment]
+1

**Comment by piebe** [comment]
Problem is not (only) the event listener but the input focus. The input focus is set to searchInput even if search is disabled. Since the input element is not available the focus goes to the body instead and shortcuts and tab order are broken. 

So the input focus should be set to another element, but which one...

**Comment by ethagnawl** [comment]
+1. Just spent 20 minutes head-desking over this.

**Comment by E-Fil** [comment]
+1

**Comment by brycereynolds** [comment]
+1

**Comment by kwantum0** [comment]
+1

**Comment by mharmuth** [comment]
+1

**Comment by danarmstrong** [comment]
+1

**Comment by eXaminator** [comment]
+1

**Comment by unlight** [comment]
+1

**Comment by timvandijck** [comment]
This is because the input is hided with ngHide. This is not the proper solution but a dirty fix that breaks the keyboard acces to the component.

A better solution for the Select2 theme could be to use the "minimumResultsForSearch" option that Select2 provides.

**Comment by brentmiller** [comment]
+1 to fixing this bug.
