### ISSUE TITLE
Create a select states

### ISSUE THREAD

**Issue by brayann** [angular-ui/ui-select#592]
Hi guys, I'm sorry for the noob question, but I can't figure out how to make this using this package:

![screen shot 2015-01-19 at 02 10 39](https://cloud.githubusercontent.com/assets/253673/5795832/6ac11cf2-9f80-11e4-8fef-d430a064b9cf.png)

Given that I have this set of data to do it:

![screen shot 2015-01-19 at 02 08 46](https://cloud.githubusercontent.com/assets/253673/5795834/7584f208-9f80-11e4-8a4b-8f4cc8e0d3c3.png)

Of course the groups can't be selected. Any ideas on how to do it? Thanks,

**Comment by AntiFreez** [comment]
As I know you can't do this natively. But you can configure your templates for choices any way you want.

**Comment by user378230** [comment]
You'd probably need to transform the items array then use group by. See example in [demo-groupby.html](https://github.com/angular-ui/ui-select/blob/161cff56c0ba9d4a86ae213056dd78ba18296036/examples/demo-groupby.html).

ui-select does not support nested items input.
