### ISSUE TITLE
how can i $watch when a user makes a selection i.e $scope.country.selected.name  ?

### ISSUE THREAD

**Issue by jpca999** [angular-ui/ui-select#593]
how can i $watch when a user makes a selection i.e $scope.country.selected.name  ?

or when the $scope.country.selected.name value is changed ?

**Comment by Raytray** [comment]
Is this what you were looking for? https://github.com/angular-ui/ui-select/blob/master/examples/demo-event-on-select.html

**Comment by user378230** [comment]
See `on-select` in wiki https://github.com/angular-ui/ui-select/wiki/ui-select
