### ISSUE TITLE
"tagging" with default select box

### ISSUE THREAD

**Issue by trickpattyFH20** [angular-ui/ui-select#597]
Such a great project. Thanks for the work!

I'm having some problems though, the "tagging" function does not work for any of the select boxes other than multi-select. Having this feature on the default single select box is pretty important to my use and I'm guessing it's pretty important to most people's use of the plugin. 

Does anyone have plans to implement the "tagging" feature for the default select box?

**Comment by ArdentZeal** [comment]
+1

**Comment by trickpattyFH20** [comment]
@brianfeister started a thread discussing tagging features for multiple select boxes.
If nobody from that thread ends up handling tagging for single select boxes I will write a workaround or maybe even something worthy of a pull request if I have time, since this feature is vital to the project I'm working on. I'll let you know @ArdentZeal .

**Comment by brianfeister** [comment]
Would love to see a PR for this @trickpattyFH20 ... I just haven't had time to do it.  There was another open issue for this feature, but I can't find it right now.  Perhaps it was a comment on the original PR...

**Comment by catchshyam** [comment]
@brianfeister I have raised a PR (https://github.com/angular-ui/ui-select/pull/657)

Please review and let me know if this can be merged.

Thanks,

**Comment by brianfeister** [comment]
Thanks @catchshyam - I will try to look at it this weekend, apologies for the delay and thanks for your help!
