### ISSUE TITLE
A blank select choices

### ISSUE THREAD

**Issue by TAMMENY** [angular-ui/ui-select#601]
I am using ui-select with its angular interface for a select form like
![_003](https://cloud.githubusercontent.com/assets/5690568/5851582/8b97741e-a244-11e4-9538-aeac5aa0094a.png)

but i got a blank select choices：
![_001](https://cloud.githubusercontent.com/assets/5690568/5851457/9a0dcc8e-a242-11e4-804b-fe6c6fad96ce.png)

and the chrome console：
![_002](https://cloud.githubusercontent.com/assets/5690568/5851491/0d218a8a-a243-11e4-9f01-fee0a914aa43.png)

If you know how to fix this, please let me know, Thanks.

**Comment by macksfield** [comment]
I have the same issue at the moment. Using angular-ui-select 0.9.6 and angularjs 1.2.26

**Comment by hatpick** [comment]
@TAMMENY Can you create a plunker (or at least tell us where do you have fieldList, etc.)

**Comment by TAMMENY** [comment]
@hatpick 
fieldList=[{id:1, value:'one'}, {id:2, value:'two'}, {id:3, value:'three'}];
In this project, this bug is possible in any type of page. However,  in another project, i used the same method and same code, the bug that i mentioned above does not exist.
thx.

**Comment by TAMMENY** [comment]
@macksfield If U fix the bug, please let me know, thx.

**Comment by macksfield** [comment]
@TAMMENY I was able to fix the bug. I was incorrect about the version of AngularJS I was using. The error exists for me using 1.3.0b5 angularJS and 0.9.6 angular-ui-select. When I updated to angular 1.3.11, the error was no longer being thrown.

**Comment by TAMMENY** [comment]
@macksfield  When I updated angular from 1.2.16 to 1.2.26, the error was no longer being thrown. 
Thank U so much.

**Comment by jaredly** [comment]
can we fix this? 1.2.16 super broken http://plnkr.co/edit/7LbsdsWx1d6Nkuu3EKOf?p=preview

**Comment by uiktiomasfeliz** [comment]
Same issue here using latest angularjs stable version and latest version of pluggin!

![1111](https://cloud.githubusercontent.com/assets/5663564/12672760/d866e85c-c678-11e5-8f51-345d7be1d4b7.PNG)


If i hit F5, then it fill's with values

**Comment by user378230** [comment]
Minimum angularjs supported is v1.2.18
