### ISSUE TITLE
ui-select broken with angularjs 1.3.10

### ISSUE THREAD

**Issue by ekarlso** [angular-ui/ui-select#605]
http://plnkr.co/edit/V0Pdyy?p=preview enter anything and hit enter into the select box and it will be left as text as well as the entry.

**Comment by jrsprice** [comment]
I've ran into the same issue. Trying to code dive and fix the issue on my end.

**Comment by ekarlso** [comment]
jrsprice you managed to come up with anything useful on this ?

**Comment by umidbekkarimov** [comment]
I put `ctrl.search = '';` to 457 line, and that helped me, but i don't think that this is correct solution

```javascript
          if (!ctrl.multiple || ctrl.closeOnSelect) {
            ctrl.close(skipFocusser);
          }
          if ($event && $event.type === 'click') {
            ctrl.clickTriggeredSelect = true;
          }

          ctrl.search = '';
        }
      }
    };
```

**Comment by ekarlso** [comment]
Is there any fix to this?

**Comment by skosno** [comment]
Use reset-search-input="true" on ui-select:
http://plnkr.co/edit/SVZ3FhnjijTOwf2m6FzO?p=preview

**Comment by jeffreynolte** [comment]
@skosno - I had the same issue.  Thanks for the solution :+1:

**Comment by zhenyi2697** [comment]
Ran into the same issue with the official examples.
Thanks for the solution of @asosno 

Waiting for a fix.

**Comment by dimirc** [comment]
I tested it with last release ([v0.11.2](https://github.com/angular-ui/ui-select/releases/tag/v0.11.2)) and its working. Feel free to reopen if issue persists
