### ISSUE TITLE
Adding item to uiSelect.items from other directive

### ISSUE THREAD

**Issue by hinok** [angular-ui/ui-select#607]
Hey,
I have to inject dynamically an option to ui-select. I decided to use directive in my case.
It's quite simple and basically it looks like this:

```html
<ui-select ui-select-append-all-items="All items" ng-model="option.selected" ...>
```

```javascript
.directive('uiSelectAppendAllItems', function($timeout) {
  
  function link($scope, $el, $attrs, controllers) {
    var uiSelectController = controllers[0];
    var label = $scope.uiSelectAppendAllItems || 'All';

    var all = {
      id: '$uiSelectInitFirstItem',
      name: label
    };

    $timeout(function() {
      uiSelectController.items.unshift(all);
    });
  }

  return {
    restrict: 'A',
    require: ['^uiSelect'],
    link: link,
    scope: {
      uiSelectAppendAllItems: '@'
    }
  };
  
});
```

It almost works. *All items* option is added to the list, I can select it etc.
The problem is with searching and filtering options in ui-select.
If I search option which is not in the list, *All items* option magically disappears.

Plunker: http://plnkr.co/edit/cTKNkaLFvEpuYRE9z7Ec?p=preview

**Comment by wesleycho** [comment]
Can you update the Plunker to the latest release?

**Comment by user378230** [comment]
Probably resolved by doing a `$watchCollection` on `items` and adding the new items again. `$select.items` is fetched from source frequently.
