### ISSUE TITLE
on-select on-remove $item is the same as $model

### ISSUE THREAD

**Issue by ilanbiala** [angular-ui/ui-select#608]
In the on-select and on-remove callbacks, `$item === $model` in v0.9.6. Has something changed?

**Comment by ilanbiala** [comment]
@amcdnl any ideas?

**Comment by amcdnl** [comment]
Can you give a more detailed example?

**Comment by ilanbiala** [comment]
`on-select="handleSelect($item, $model)`

```
$scope.handleSelect = function(item, model) {
  item === model; // -> true
};
```

**Comment by martinczerwi** [comment]
+1 on this issue.

Consider a multi-select field, in the callback $item should be the singular item removed or added, and $model should be the collection.

A simple workaround could be to return `$select.selected` for `$model` [here](https://github.com/angular-ui/ui-select/blob/1e1d9088271a52d8882ec5b6ebd83090b048b3bc/src/uiSelectController.js#L295) and [here](https://github.com/angular-ui/ui-select/blob/master/src/uiSelectMultipleDirective.js#L49)

**Comment by user378230** [comment]
`$item` and `$model` refer to the selected value, one is the item as it appears in the source list the other is the item that gets passed/assigned to the `ngModel`
