### ISSUE TITLE
Clicking dropdown option doesn't select element

### ISSUE THREAD

**Issue by jordanthornquest** [angular-ui/ui-select#612]
Hey, folks! I am running Angular 1.3.0, and I cannot seem to get the ui-select to function correctly when it comes to clicking on options. I copied the `demo.js` & the `bootstrap.html` demo files, and clicking on options does not add the options to a select, whether it is a single select or a multi-select.

**Comment by jordanthornquest** [comment]
Hey, so here's some further diagnosis: this only happens when Batarang for AngularJS 0.7.4 is enabled. Seriously, it slows everything way, way down for ui-select, and makes it impossible to click on choices in order to select them.

**Comment by robshep** [comment]
confirmed for me too.  Thanks for pointing out the chrome plugin workaround.  Strange!

**Comment by dparish** [comment]
I'm seeing a similar problem but the examples work for me it's just my simple implementation that doesn't. I'm not sure batarang is the actual problem.

**Comment by uhomira** [comment]
I had a similar problem that was solved by removing creepy Batarang.

**Comment by nickradford** [comment]
That's bizarre about Batarang. Good find :smiley:

**Comment by toboid** [comment]
Had the same problem, disabling Batarang fixed it. Thanks very much

**Comment by adamcmoore** [comment]
Gah, I just spent an hour and half fighting this. Thank you Jordan!

**Comment by migajek** [comment]
@jordanthornquest  THANK YOU. Just spent an hour trying to figure what is wrong. Batarang was disabled, had to enable & disable it.

**Comment by Dr4K4n** [comment]
@jordanthornquest Thank you very much! Wasted at least an hour trying to find the cause. After disabling batarang everything works again -.- (Using Angular 1.3.15)

**Comment by mraible** [comment]
@jordanthornquest Thanks for this solution. Ran into this today and fought it for a good hour. Using Angular 1.3.2 and disabling Batarang solved the problem. First google result - nice work!

**Comment by irizvi** [comment]
+1 Thanks for the Batarang fix.

**Comment by xolraid** [comment]
+1 Thanks for the Batarang fix.Thanks.

**Comment by wesleycho** [comment]
Closing as a batarang issue (and duplicate of another closed issue).
