### ISSUE TITLE
manipulate selected item before adding to ng-model

### ISSUE THREAD

**Issue by Ir1sh** [angular-ui/ui-select#618]
I have read the docs and this dosn't appear to be possible, but please correct me if I am wrong.

I have a form field that allows you to add guests to a reservation.  it fetches the list guests from the server and each person object is fairly complicated with a number of fields like name, building, floor etc.  I need this info so that it can be displayed in options dropdown.  This all works fine.

However the array of selected guests has a different format namely [{user: {id: 1, name: ''}}]

Is there a way for me to take the selected person object, use it to create the new much more straightforward object and return that so it is added to the ng-model and dispalyed in the ui-select-match.

If this is not currently possible is it a feature you would accept a pull request for as it could probably be implemented fairly easily in a similar manner to tagging="function"

**Comment by swalters** [comment]
What I do is create a wrapper directive with an ng-model.  Then I add formatter and parser in my directive to manipulate the ngModelController model value.  Works great for me.  You need one the later releases where uiSelect can use the parent ngMododel controller

**Comment by wesleycho** [comment]
The suggested solution is the best approach to modifying the model.

Closing this as a support issue.
