### ISSUE TITLE
Associative array is not supported?

### ISSUE THREAD

**Issue by burzum** [angular-ui/ui-select#627]
I'm trying to use an array like this with ui-select.

```js
[1: 'Swiss', 2: 'Germany']
```

But *all* of the examples show only an array of objects. How can I make ui-select to work with these associative arrays?

**Comment by kooliokey** [comment]
I have used it just fine with an array like that, example:
```
$scope.static.brands = ['Apple', 'Microsoft', 'Sony', 'Panasonic',...];
```
```
<ui-select ng-model="dataItem.brand" reset-search-input="false">
	<ui-select-match placeholder="Brand">{{dataItem.brand}}</ui-select-match>
	<ui-select-choices repeat="value in static.brands | filter: $select.search">
		<div ng-bind-html="value | highlight: $select.search"></div>
	</ui-select-choices>
</ui-select>
```
The important part is the `ui-select-choices` directive and the repeat you do controls what is displayed.

Hope that helps a little!

**Comment by dimirc** [comment]
Can you setup a plunker?

**Comment by Shiti** [comment]
I was also struggling with the same issue 
http://plnkr.co/edit/fCdtL4?p=preview

**Comment by dimirc** [comment]
@Shiti I see that your example is working, or what's wrong on it?

**Comment by Shiti** [comment]
The selected value is not reflected in the model. In the plunker there is line 

```
<p>Selected: {{brand}}</p>
```

in the view but it never displays the value of brand selected (the model bound to ui-select)

**Comment by kooliokey** [comment]
@Shiti It's an AngularJS gotcha. You have to use a ngModel that is a key on an object. That's why in my code I always use an object on the scope called `dataItem` to store the model data.

**Comment by kooliokey** [comment]
@Shiti See this version of your Plunker with the model bound to dataItem.brand: http://plnkr.co/edit/j7u9WmNDEb8wAQZRNltg?p=preview

**Comment by Shiti** [comment]
It's not uncommon to use strings or numbers for models in AngularJs code (also, they are all objects in javascript). 
It would be nice if the documentation explicitly states this restriction and the cause if possible.

**Comment by kooliokey** [comment]
Hmmm. I've always just avoided using anything directly on the scope because I've run into many issues such as the on demoed in the plunker. From what I've seen it's custom directives that suffer from the issue, but I don't know the exact reasons. I was under the impression it was just a catch with Angular, so I guess it would be nice for the documentation to point it out if that is not the case.

**Comment by dimirc** [comment]
@kooliokey @Shiti take a lot at the [FAQ](https://github.com/angular-ui/ui-select/wiki/FAQs#ng-model-not-working-with-a-simple-variable-on-scope) that I think its related to what you are referring to.

@burzum reopen this issue when you setup a plunker reproducing to problem to better help you

**Comment by burzum** [comment]
@dimirc OK, the example Shiti has set up is not exactly what I meant. I'll set it up when I find the time today. Thank you.
