### ISSUE TITLE
Can not set placeholder when selection is active

### ISSUE THREAD

**Issue by marianafranco** [angular-ui/ui-select#629]
Hey guys,
It's possible to include a new option in the ui-select-match to set the placeholder when there is some selected elements? Today the placeholder is set only when no element was selected. This way I can show some message to indicate to the user that he needs to click in the select to be able to add new elements.

Here is one example of what I'm looking for:

![placeholder](https://cloud.githubusercontent.com/assets/120240/6028238/193605c2-abcf-11e4-8832-a0df9ef7b2eb.png)

I made this change in my fork (https://github.com/marianafranco/ui-select) where I created a new option "placeholder-active" for this, but it'll be nice to have this in the official repo.

**Comment by sime** [comment]
Might be worth submitting a PR so the code can be reviewed more easily.

I'm interested in something like this.

**Comment by marianafranco** [comment]
OK, will prepare a PR. First I want to try to make select2 and selectize themes works with this new "placeholder-active" option ;)

**Comment by marianafranco** [comment]
Here are the PR: https://github.com/angular-ui/ui-select/pull/774

**Comment by Jefiozie** [comment]
Hi, I think this issue can be closed as the PR is closed. If needed people can have a look at the PR you made to make a custom version of it. 

Thanks.
