### ISSUE TITLE
Scrolling doesn't work in mobile devices!

### ISSUE THREAD

**Issue by ghominejad** [angular-ui/ui-select#630]
Scrolling the list doesn't work!
I've tested it on many android devices

**Comment by kooliokey** [comment]
Scrolling on iOS devices works fine. I don't have an android device to test with though, so I can't double check that. I tested on iOS8, iPhone 6 and iPad Air 2 both in Safari and Chrome.

**Comment by ghominejad** [comment]
Phonegap and cordova use android default browser. kindly test it with android browser.

Thank you

**Comment by ronaldjeremy** [comment]
i cannot get it to scroll the list on chrome for android either...

**Comment by tallsam** [comment]
try installing ng-touch and it should work.

**Comment by wesleycho** [comment]
Going to close this as a user issue - custom CSS should be enough to address issues here.

**Comment by zorang** [comment]
This is disaster that this is not fixed till today for mobile devices!!!
