### ISSUE TITLE
Ability to specify maximum number of tags allowed

### ISSUE THREAD

**Issue by sanketsaurav** [angular-ui/ui-select#631]
I don't know if this feature already exists, because I couldn't find it in the docs. An attribute like `max-tags` would be pretty useful.

**Comment by evillemez** [comment]
@sanketsaurav It isn't an included feature, but easy to add.  See this comment:

https://github.com/angular-ui/ui-select/pull/348#issuecomment-63736469

**Comment by sanketsaurav** [comment]
@evillemez Thanks for pointing out. I got around this by writing a custom validator on the model's size. This should be a feature, don't you think?

**Comment by cdjackson** [comment]
#1110

**Comment by dimirc** [comment]
Should be solved with https://github.com/angular-ui/ui-select/pull/1110
