### ISSUE TITLE
Select nested in a control with isolate scope loses bindings to scope when selecting a value

### ISSUE THREAD

**Issue by Charleh** [angular-ui/ui-select#633]
See this plunk:

http://plnkr.co/edit/hxKZI07DVPa5PhcCKLQ9?p=preview

Basically, I've nested the ui-select directive in another directives template and tried to pass ng-model to it using an isolate scope binding. This works fine as long as you don't try and choose a value (e.g. updates to the value on the scope correctly update the select box)

If you select a value on the nested ui-select, it breaks the binding to scope. Any changes to the selected value from then on seem to hit the wrong scope (a child scope I believe)

In the above plunk, if you leave the top dropdown box as-is and mess with the other ones which are all bound to the same property on the scope everything works fine. 

If you then select a value from the top dropdown, no values are updated on the page, and subsequent updates to the value from other controls on the page don't hit the broken dropdown any more.

**Comment by Charleh** [comment]
After some more digging, looks like it might actually be an angular issue - not sure if I'm misunderstanding prototypal inheritance but it appears that the scope that it's writing against is a child scope which is inheriting the parent.

The disconnect happens during $$writeModelToScope in ng-model controller in angular

It looks like the method looks at the property name and tries to index it on the scope, but instead of setting the inherited property value, it writes a new property value with the same name on the child, hiding the parent value.

`key = ensureSafeMemberName(element.shift(), fullExp);
  ensureSafeObject(obj[key], fullExp);
  obj[key] = setValue;
  return setValue;`

It appears on the `ensureSafeObject` line, `obj[key]` points to the parent property, but on the `obj[key] = setValue` line a new property is created on the child instead of what I would expect which is that the inherited parent value is modified. 

Am I just misunderstanding how the inheritance should work or does this look like a bug?

**Comment by Charleh** [comment]
Ok looks like it's more of a misunderstanding - I'll have to manually push the value onto the parent scope as writes in javascript don't look up the prototype chain (makes sense!). Going to try watching the value on scope and pushing it to the parent to see if that works

**Comment by Charleh** [comment]
Ok my bad - turns out if you are wrapping a directive you need to prefix the templates ng-model bindings with $parent so that when it's being written back to it updates the correct object! My confusion was from the fact that the reads were working, so it looked like it was becoming unbound, but in fact it was just reading the child-most written value from the chain!

**Comment by CharlJKruger** [comment]
Had the exact same issue, so if the scope is nested e.g. `$scope.main.list` you need to have `..as-sortable="sortableOptions" ng-model="$parent.main.list"`
