### ISSUE TITLE
Internet Explorer, multiple select, Remove item click not working

### ISSUE THREAD

**Issue by ztaff** [angular-ui/ui-select#637]
Hi
We are using a select box, multiple choices, in a modal dialog (ui.bootstrap.modal).
In IE (ver 9,10,11 ) after choosing an item it cannot be removed.
It seems that when the click handler is triggered by a span inside a button tag, IE will not trigger the remove click, but only the click on the button. Hence only the select handler will be triggered.

A solution I've found is to change the template "bootstrap/match-multiple.tpl.html" into replace the BUTTON with a span.
The resulting HTML will be as below

Cheers, Staffan

```html
<span style="margin-right: 3px;" class="ui-select-match-item btn btn-default btn-xs" tabindex="-1" ng-disabled="$select.disabled" ng-click="$select.activeMatchIndex = $index;" ng-class="{'btn-primary':$select.activeMatchIndex === $index}">
    <span class="close ui-select-match-close" ng-hide="$select.disabled" ng-click="$select.removeChoice($index)">&nbsp;×</span> <span uis-transclude-append="">
        <span ng-bind="$item.FullName" title="expert@ln.se" class="ng-binding ng-scope">N N</span>
    </span>
</span>
```

**Comment by wesleycho** [comment]
Going to close due to lack of reproduction - feel free to open a new issue with detailed reproduction in Plunker based on the latest release.
