### ISSUE TITLE
Error thrown with latest dist using example code

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [angular-ui/ui-select#64]
[UPDATE: MY OWN FAULT, SEE BELOW]
I've run into the name collision issue here and have tried to fix it myself but then discovered there is a new dist from my last one so I just confirmed it has the new prefix ui-select on match and choices so I thought I was home free but...nope.

It appears to work as it's supposed to at a rough first trial with it, however:

This error is thrown with the latest select.js and select.css downloaded from /dist about 10 minutes ago:

```
Error: [ui.select:transcluded] http://errors.angularjs.org/1.2.14/ui.select/transcluded?p0=Expected%201%20.ui-select-match%20but%20got%20'%7B0%7D'.&p1=0
```

I just copied the exact example from /examples/bootstrap.html pasted here for convenience:

```
 <div class="form-group">
    <label class="col-sm-3 control-label">Default</label>
    <div class="col-sm-6">

      <ui-select ng-model="person.selected" theme="bootstrap">
        <ui-select-match placeholder="Select or search a person in the list...">{{$select.selected.name}}</ui-select-match>
        <ui-select-choices repeat="item in people | filter: $select.search">
          <div ng-bind-html="item.name | highlight: $select.search"></div>
          <small ng-bind-html="item.email | highlight: $select.search"></small>
        </ui-select-choices>
      </ui-select>

    </div>
  </div>
```

And this is the area of code throwing the error:

```
 var transcludedMatch = transcluded.querySelectorAll('.ui-select-match');
    if (transcludedMatch.length !== 1) {
      throw uiSelectMinErr('transcluded', "Expected 1 .ui-select-match but got '{0}'.", transcludedMatch.length);
    }
    element.querySelectorAll('.ui-select-match').replaceWith(transcludedMatch);
```

Clearly there _is_ a ui-select-match so...?  (I'm using jquery-2.0.3  if that has any bearing on this)

**Comment by Dealize** [comment]
昨天刚碰到同样的问题，然后也是第二天无意间解决了。
在使用ui-select时候，在ui-select-choices中的peopel  先要在后台初始化
people=[];（试过赋值为“”、{}都会报错）
