### ISSUE TITLE
An exact dropdown match while "free tagging" (no labels) doesn't auto-select.

### ISSUE THREAD

**Issue by JeromeLam** [angular-ui/ui-select#640]
Here's a screenshot of what I mean:
![image](https://cloud.githubusercontent.com/assets/1011816/6092773/41a4134c-aebc-11e4-9507-5ddc02a9960e.png)
**Setup**:  *multiple tagging tagging-label="false"*

To reproduce, just open the [tagging demo](https://github.com/angular-ui/ui-select/blob/master/examples/demo-tagging.html), focus on the input under *Simple String Tags
(Predictive Search Model / No Labels)*, type "Green" and press Enter.  When I press Enter, I assume the "Green" option would be selected since it's an exact match, although it's not highlighted.  The behavior is that what I typed would get cleared and nothing gets selected.  I validated this against master.

In an unlikely edge case, a duplicate would get created, but since that's not what's happening, I figure the exact match should get auto-selected.  If not, it would mean that a user free typing an exact match can only tag that match while using the mouse or the arrow keys to select it from the dropdown.  Is this the desired user behavior?

**Comment by user378230** [comment]
Closing as I believe this is resolved in more recent versions of `ui-select`. 

If you believe its still relevant please update with a plunkr (or similar) against the latest version of ui-select (currently v0.15.0)

Thanks!
