### ISSUE TITLE
Can't select normal input after opening ui-select

### ISSUE THREAD

**Issue by bettercallsteve** [angular-ui/ui-select#646]
I have a form made up of normal inputs and ui-selects.

If a user clicks on a ui-select to open and does not select anything, and then they click on a normal input to focus it, the input is highlighted and then immediately unselected.

Example: Click on a select and then click on the input at the top.
http://plnkr.co/edit/0FfN8es9ssJkd17elBxJ?p=preview

![ui-select-bug](https://cloud.githubusercontent.com/assets/10201088/6130128/2ca28198-b111-11e4-8e52-a2b1228f3bc0.gif)

**Comment by dimirc** [comment]
Seams related to https://github.com/angular-ui/ui-select/issues/283

**Comment by dimirc** [comment]
This PR should fix it https://github.com/angular-ui/ui-select/pull/668
