### ISSUE TITLE
Can ui-select replicate the same select2 "multiple" behavior ?

### ISSUE THREAD

**Issue by ubirajaralucena** [angular-ui/ui-select#650]
Hi all,

FOA, congratulations for the great work you have donne =)

Could you please help me to configure the right options to achieve the same select2 behavior when using the "multiple" attribute ? [ui-select] removes the selected items from the list while [select2] keep them and adds a "aria-selected=true" attribute to the selected items. As in https://select2.github.io/examples.html (Multiple select boxes).

Thanks again

**Comment by uoyknaht** [comment]
+1 for this issue. I also need that selected options would still be visible in options list. Currently this code removes them:

      if (ctrl.multiple){
        //Remove already selected items
        $scope.$watchCollection('$select.selected', function(selectedItems){
          var data = ctrl.parserResult.source($scope);
          if (!selectedItems.length) {
            setItemsFn(data);
          }else{
            if ( data !== undefined ) {
              var filteredItems = data.filter(function(i) {return selectedItems.indexOf(i) < 0;});
              setItemsFn(filteredItems);
            }
          }
          ctrl.sizeSearchInput();
        });
      }

**Comment by Luddinus** [comment]
+1

**Comment by cobrelli** [comment]
+1 for the issue. It would be nice to have this as an option.

**Comment by ejbaker** [comment]
+1

**Comment by user378230** [comment]
Related #1567

**Comment by user378230** [comment]
Closed with #1622 now released

**Comment by wellaya** [comment]
+ better to have select unselect feature same as select2 in multiple select mode
