### ISSUE TITLE
0.9.6 + angular 1.3.11 error

### ISSUE THREAD

**Issue by btm1** [angular-ui/ui-select#652]
Your examples use 1.3.0 of angularjs but as soon as you update the version to 1.3.11 and you look at the tagging example there is an issue.  the tagging seems to sort of work:

The key bindings for tagging tokens don't work anymore so you type ',' or ENTER and it doesn't auto tag.
Also even if you hit return and select the tag it keeps the written text in the input field afterwards at the end of the tags.

**Comment by btm1** [comment]
any movement on this? If i knew the library better i'd just crawl in there and fix it myself.

**Comment by octavioamu** [comment]
Do you refer to this? I'm having that problem with 1.3.1 
http://ajax.googleapis.com/ajax/libs/angularjs/1.3.1/angular.js
![screenshot at 17-29-15](https://cloud.githubusercontent.com/assets/1358093/6307807/190806d6-b926-11e4-9a50-39ae40a2885a.png)

http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.js
![screenshot at 17-29-34](https://cloud.githubusercontent.com/assets/1358093/6307809/20800742-b926-11e4-9ca1-f438ceeb6457.png)

**Comment by octavioamu** [comment]
@btm1 try to write 'reset-search-input'  without quotes in the directive

**Comment by btm1** [comment]
reset-search-input works but i'm guess that's just a temporary fix until that bug is resolved?

**Comment by octavioamu** [comment]
I don't thinks is a fix because is working with angular 1.3.0 Is a bug introduced with angular 1.3.1 and in the code the option 'reset-search-input' is undefined. Have not ideia why and how in 1.3.0 is true.

**Comment by btm1** [comment]
yeah i'm not sure all i know is this fixes my issue for now though. But I'm guessing that there needs to be revisited.

**Comment by dimirc** [comment]
Should be fix now with https://github.com/angular-ui/ui-select/pull/703
