### ISSUE TITLE
 ui-select dropdown on-select function call issue

### ISSUE THREAD

**Issue by madasuk** [angular-ui/ui-select#653]
I am trying to migrate my select dropdown to ui-select. The ng-change function call which is working perfectly with normal dropdown is not working with on-select  in ui-select.  Please find my plunker at
http://plnkr.co/edit/Ufhb0IfzrTlG3XLY2ahh?p=preview. Is there any bug with ui-select or am I doing any mistake in using ui-select.

**Comment by user378230** [comment]
Use `$item` and `$model` as parameters in `on-select` not `on-select="getDataBasedonCustomer(uiSelectedCustomer)" `

See example in wiki https://github.com/angular-ui/ui-select/wiki
