### ISSUE TITLE
Hightlights 1. element since Angular 1.3.1

### ISSUE THREAD

**Issue by mihaxx** [angular-ui/ui-select#655]
Since Angular version 1.3.1 the first element will be highlighted and not the element which is defined in the js. After clicking on an element, it highlights correctly.

See: http://plnkr.co/edit/Sza2ZshnNlU4jdjSOFaP?p=preview

It was not a problem in version 1.3.0 and before

**Comment by dimirc** [comment]
I updated your plunker with last library version and looks like its working correctly now.

Updated [plunker](http://plnkr.co/edit/QKeaJE7NnKyGYdOCLfPk?p=preview)

**Comment by mihaxx** [comment]
Great thanks for a fast fix!
