### ISSUE TITLE
ui-disable-choice modifies choice objects

### ISSUE THREAD

**Issue by dcopp** [angular-ui/ui-select#656]
When using a list of objects, the property _uiSelectChoiceDisabled is added to each item.

Plunker: http://plnkr.co/edit/uijTx559uQyRtVuBscj5?p=preview

Click the select control to see the effect in the json dump below it.

 Either this side-effect should be documented (if by design ui-select "owns" the list given) or ui-select should not pollute the list elements with its own data.

**Comment by dcopp** [comment]
Duh...incorrect repeat syntax.

Wrong: repeat="choice in choices"
Correct: repeat="choice as choice for choice in choices"

**Comment by pakdev** [comment]
This can be an issue when multiple selects want different items disabled from the same list. It appears that ui-select prevents an option from being selected if this property exists.

**Comment by wesleycho** [comment]
Going to close this as a duplicate of #1200, as that issue seems a little more detailed.
