### ISSUE TITLE
Infinite loop when using data-ui-select-choices attributes instead of element

### ISSUE THREAD

**Issue by cjanz** [angular-ui/ui-select#660]
The steps to reproduce are the same as in #104 except that data-* attributes should be used, e.g. `<div data-ui-select-choices>...`.

Therefore the fix in #109 (commit 09d3172) could be extended like this to fix this issue as well:

```javascript
          transcludedChoices.removeAttr('data-ui-select-choices'); //To avoid loop in case directive as attr
```

BTW: Thank you for providing this great library :-)

**Comment by dimirc** [comment]
Can you confirm if https://github.com/angular-ui/ui-select/pull/579 is solving it?

**Comment by cjanz** [comment]
Thanks for the fast feedback. I can confirm that #579 solves the problem :-)
