### ISSUE TITLE
Attempt to pre-populate selected items with directive wrapped ui-select not working...

### ISSUE THREAD

**Issue by cleon26** [angular-ui/ui-select#661]
Please see this plunkr:
http://plnkr.co/edit/ucQ98a4zB7oeBQhfHWTR

I'm trying to create a directive/controller that wraps the ui-select.  The directive will be responsible for retrieving the list of possible selections (for now it's hardcoded, but could be on the fly later) while the consumer of the directive will just be passing in a set of id's that might have been previously selected.
(My actual scenario for this is...  users can create notes in my system with tags.  They can also come back later and modify the tags so I need to have them selected)

For some reason, it doesn't seem to sync my selected items properly.  I'm new enough in angular that I'm unsure as to whether or not I've done something wrong with the directive, or the ui-select is misbehaving or this is just something that won't work.  Can anybody tell me what's going wrong?

Thanks in advance,
Rob

**Comment by wesleycho** [comment]
Closing this as a support issue.
