### ISSUE TITLE
Can't not select with mouse when hostname is "localhost"

### ISSUE THREAD

**Issue by eddie11n** [angular-ui/ui-select#666]
Can't not select item with mouse when hostname is "localhost", but  work with "127.0.0.1"

**Comment by dimirc** [comment]
Can you explain better your situation?

**Comment by eddie11n** [comment]
I test my app with Chrome on my mac.

When URL in address bar is "http://127.0.0.1:9000/#/ports/4", everything work well

but visit with URL "http://localhost:9000/#/ports/4",  then dropdown menu can display, but I can't select item from it.

![admin](https://cloud.githubusercontent.com/assets/1493845/6206442/be8a2bf8-b5c4-11e4-99f4-b851fce684bf.jpg)

**Comment by lianyi** [comment]
That's a known CORS issue from Chrome. https://code.google.com/p/chromium/issues/detail?id=67743

**Comment by eddie11n** [comment]
I can load the remote resource and select item with keyboard.

It seems to have nothing to do with CORS

**Comment by dimirc** [comment]
Any errors at console?

**Comment by eddie11n** [comment]
nothing at console

**Comment by dimirc** [comment]
What version of Angular and uiSelect?

**Comment by evuolas** [comment]
I had the same issue with Angular 1.4 (angular#1.4.0-build.3832+sha.bd6c04a) and ui-select 0.9.3. Updated ui-select to the latest release 0.9.7 and it now works fine.

**Comment by anik786** [comment]
I still have the same problem. please see https://github.com/angular-ui/ui-select/issues/714
