### ISSUE TITLE
Version: 0.9.8 allow-clear bootstrap theme problem

### ISSUE THREAD

**Issue by Panchitoboy** [angular-ui/ui-select#674]
Hi,

I want to know if i'm doing somenthing wrong, but when i use allow-clear using bootstrap-theme the remove icon goes to the next line.

i prepared this plnk to show the error: http://plnkr.co/edit/P2ylwfEIXFX8gPxt282c?p=preview

**Comment by JeromeLam** [comment]
@Panchitoboy This issue will be fixed by PR #667 in version 0.9.9.

**Comment by Panchitoboy** [comment]
Thank you @JeromeLam
