### ISSUE TITLE
Selection issue

### ISSUE THREAD

**Issue by Bana0615** [angular-ui/ui-select#675]
when you choose an option from the dropdown and then you click the dropdown again you should be able to delete your old selection otherwise it makes it annoying to clear the model becasue you will have to create an extra button to do it.

**Comment by dimirc** [comment]
Did you try `allow-clear`?

**Comment by Bana0615** [comment]
do you just add that as an attribute? and if so where do you add the attribute?

**Comment by dimirc** [comment]
If I remember correctly, right now only bootstrap and select2 themes work with `allow-clear`

**Comment by Bana0615** [comment]
it works thank you! but if you use the current version of the js file it breaks the aloow clear. But it works with an old js file marked

/*!
 * ui-select
 * http://github.com/angular-ui/ui-select
 * Version: 0.9.8-develop - 2015-02-16T06:10:43.771Z
 * License: MIT
 */

Image of problem with news js file:
![untitled](https://cloud.githubusercontent.com/assets/1860512/6233279/be8c7594-b69f-11e4-886c-cd4742e93630.png)

**Comment by dimirc** [comment]
Check https://github.com/angular-ui/ui-select/pull/667

**Comment by Bana0615** [comment]
thanks for all the help
