### ISSUE TITLE
Clear entire selection?

### ISSUE THREAD

**Issue by atentis** [angular-ui/ui-select#676]
I have a traditional select that is the parent to the ui-select. When the user makes a change on the parent select that does not have a value I would like to clear the selections in ui-select control entirely. I have tried making the array that populates the ui-select null or empty with no luck.

How do I simply just clear out the ui-select selections via a function?

Thanks!

**Comment by dimirc** [comment]
Can you create a plunker with what you are trying to do?

**Comment by atentis** [comment]
Will have one for you very soon

**Comment by atentis** [comment]
http://plnkr.co/edit/HEMNlJQGxJ2cEoZATnw8?p=preview

Work in progess... Having issues getting the multi-select to work in the plunker but this should give you an idea of what I want to do. When you change the select back to -- Select -- I want to clear out the selections made in the multiselect on the ui

Thanks

**Comment by dimirc** [comment]
The example isn't clear but I did some changes to do what you needed on a button

PD: use the last version of the library

Updated [plunker](http://plnkr.co/edit/VTJLytxDwjQjnf3XzZCr?p=preview)

Reopen the issue if you need any help

**Comment by atentis** [comment]
Once I upgraded the library it fixed the issue. Thanks for your help
