### ISSUE TITLE
how to refresh ui-select-match

### ISSUE THREAD

**Issue by zengchuan** [angular-ui/ui-select#677]
Here the example:
http://plnkr.co/edit/xGrIa9R8uQDx8Qmx2dbd?p=preview

when on-select changed to 'Adam', ui-select-match show 'adam@email.com', not 'adam2@email.com'

**Comment by pabuisson** [comment]
Having quite the same question here. I'm currently editing an item from a modale window, update the item itself (the ngModel remains the same, only displayed text is updated), but I can't find any way to update the ui-select-match value that's now out of sync. If anyone ( @zengchuan ?) has any solution or workaround ? I couldn't find anything so far.

**Comment by wesleycho** [comment]
Demonstration using the `refresh` attribute: http://plnkr.co/edit/YCdcjzYGeHC1g5vGF9QX?p=preview

Closing as a support issue.
