### ISSUE TITLE
Format "group-by DIV" like "templateResult" from select2

### ISSUE THREAD

**Issue by ollivierv** [angular-ui/ui-select#679]
Hi,
In **Select2**, the callback **formatResultat** (now **templateResult** in *v4.0.0*), can be use to format _ALL_ the list elements, even the "group-by" ones if an array with **children** is provided. 

This kind of code works well to put a **flag** just before the "group-by" text :

```javascript
formatResult : function (e)
{
	if( e.children != undefined )
		return "<img class='flag' src='http://something.net/" + e.img + ".png'/>" + e.text;
	else
		return e.text;
},
```

How can do this with ui-select ? I can't find a way. 
Thank you.

**Comment by faisalferoz** [comment]
+1

**Comment by wesleycho** [comment]
This seems like a nice to have, which is generally not a great idea in a library. The reason is because a lot of users won't want such a feature, which then results in feature bloat in a library, and more code that each consumer has to load.

Closing this as a won't implement.
