### ISSUE TITLE
setting chosen property of selected object as ngModel instead of the whole object

### ISSUE THREAD

**Issue by jrencz** [angular-ui/ui-select#68]
I'd like to ask if the module already is capable of the following and I just haven't found how or is it not yet possible:

Referring to the [demo](http://plnkr.co/edit/GtOOWE?p=preview): I'd like for the module to be able to set only the email of the selected person as ngModel value, not the whole object (email, name, age) as it does now.

As I inspected the code it seems to be impossible looking at the line 62:

``` javascript
    var match = expression.match(/^\s*([\s\S]+?)\s+in\s+([\s\S]+?)(?:\s+track\s+by\s+([\s\S]+?))?\s*$/);
```

and the way [`ctrl.select`](https://github.com/angular-ui/ui-select/blob/master/src/select.js#L194) is used for both [keyboard](https://github.com/angular-ui/ui-select/blob/master/src/select.js#L227) and [pointer](https://github.com/angular-ui/ui-select/blob/master/src/select.js#L403)

What I'd like to propose is something closer to the ngOptions `select as label for value in array` syntax in the native [angular select](https://docs.angularjs.org/api/ng/directive/select) but `label` is not used in this case anyway since it's displayed using the template that is transcluded - so let's name it `property as value in array`. Example:

``` html
<ui-select ng-model="person.selected" theme="select2">
  <ui-match placeholder="Select a person in the list or search his name/age...">{{$select.selected.name}}</match>
  <ui-choices repeat="email as person in people | propsFilter: {name: $select.search, age: $select.search}">
    <div ng-bind-html="person.name | highlight: $select.search"></div>
    <small>
      email: {{person.email}}
      age: <span ng-bind-html="''+person.age | highlight: $select.search"></span>
    </small>
  </ui-choices>
</ui-select>
<p> Selected: {{ person.selected }} </p> <!-- I expect "Selected: foo@bar.com" instead of what it displays now: the whole object -->
```

**Comment by mkamayd** [comment]
I find this feature very cool. I think should be well documented.
