### ISSUE TITLE
Selection should clear input text

### ISSUE THREAD

**Issue by RuZman** [angular-ui/ui-select#680]
Since AngularJS 1.3.0 the "multi selection" doesn't clear the input text if an item is selected.

"multi selection" is working with AngularJS 1.3.0:
http://plnkr.co/edit/8SmB9sy1stlTn8wh6STp?p=preview

"multi selection" is not working with Angularjs 1.3.1 anymore:
http://plnkr.co/edit/Wgl0Y2S0RpVCZTtHqkE4?p=preview

The example https://github.com/angular-ui/ui-select/blob/master/examples/demo-multi-select.html with the AngularJS version 1.3.0-beta.17 is also effected.

**Comment by maku** [comment]
I think this is also true for single selection. (also when no value is selected the input value should be cleared)

Right?

**Comment by LeleDev** [comment]
@maku Think so

**Comment by btm1** [comment]
bump. I'm also having this issue

**Comment by dimirc** [comment]
Should be solved with https://github.com/angular-ui/ui-select/pull/703

Check updated [Plunker](http://plnkr.co/edit/aPyJb6mYwSc3AEYL6XMy?p=preview)
