### ISSUE TITLE
specifying allow-clear value on a select-base

### ISSUE THREAD

**Issue by starf** [angular-ui/ui-select#681]
When using allow-clear, it changes the value to "undefined" which is not always the wanted behaviour.
Could it be possible to add something like: allow-clear-value="0" (and obviously show placeholder or nothing when model is that value)

Would it be more "correct" to refactor my code to work with undefined?
Greetings.

**Comment by dimirc** [comment]
What other case other than `allow-clear-value="0"` are you having? I dont see enough use cases to justify make this changes yet

**Comment by starf** [comment]
or an empty string. no biggie actually. thanks for considering.

**Comment by starf** [comment]
scrap that, this is a duplicate of #302 

Explanation: in 0.9.9, choosing allow-clear removes the model from the array it is in which creates all kind of issues, we need to specify whether it will be 0 or an empty string or undefined or whatever. 

Been dabbling inside the code but it's a level above my head.

Thanks

**Comment by starf** [comment]
The plunkr, in the hopes this could get resolved soon :)
http://plnkr.co/edit/G3f7ox2suhUNM8e86jOb?p=preview

**Comment by starf** [comment]
Ok, all i want to know, is the behaviour in the plunkr normal?

**Comment by user378230** [comment]
Closing this as I believe this can be resolved by creating a custom directive to add a formatter for the ng-model which can be used to interpret the undefined value as the user sees fit.
