### ISSUE TITLE
New version is broken (0.9.9)

### ISSUE THREAD

**Issue by martybalandis** [angular-ui/ui-select#685]
Error: c.generateId is not a function
and when I try to click I get:
Error: f.focusser is undefined

Using Angular 1.3.13

What has changed since?, because all of the sudden is not working..

**Comment by dimirc** [comment]
Can you setup a plunker for this?

**Comment by dimirc** [comment]
I setup a [plunker](http://plnkr.co/edit/Cne9OB37Kht31bXsokSf?p=preview) with angular 1.3.13 and I don't see any problem. Reopen the issue if you find a way to reproduce it pls
