### ISSUE TITLE
service naming clash with angular-ui/ui-utils highlight

### ISSUE THREAD

**Issue by jrencz** [angular-ui/ui-select#69]
ui-select reimplements the functionality of already existing module [ui.highlight](https://github.com/angular-ui/ui-utils/blob/master/modules/highlight/highlight.js) in the angular-ui/ui-utils package.

For the sake of consistence across the angular-ui it should be used as a dependency IMHO.
For what it's worth it also overwrites the existing instance of `highlight` service since it's not namespaced and angular won't deal with it automatically.

**Comment by wesleycho** [comment]
Closing, as it looks like ui-utils no longer has a highlight filter.
