### ISSUE TITLE
search-enabled="false" hides the input box with associated placeholder

### ISSUE THREAD

**Issue by mjhamm75** [angular-ui/ui-select#691]
When I set search-enabled="false", my input box and associated placeholder disappear.  This also affects CSS that may be attached to the input box as well.  My suggested fix is to move the !$select.searchEnabled logic from the ng-hide to the ng-disabled for that input box (see below):

$templateCache.put("selectize/select.tpl.html","<div class=\"ui-select-container selectize-control single\" ng-class=\"{\'open\': $select.open}\"><div class=\"selectize-input\" ng-class=\"{\'focus\': $select.open, \'disabled\': $select.disabled, \'selectize-focus\' : $select.focus}\" ng-click=\"$select.activate()\"><div class=\"ui-select-match\"></div><input type=\"text\" autocomplete=\"off\" tabindex=\"-1\" class=\"ui-select-search ui-select-toggle\" ng-click=\"$select.toggle($event)\" placeholder=\"{{$select.placeholder}}\" ng-model=\"$select.search\" ng-hide=\"($select.selected && !$select.open)\" ng-disabled=\"$select.disabled || !$select.searchEnabled\" aria-label=\"{{ $select.baseTitle }}\"></div><div class=\"ui-select-choices\"></div></div>");}]);

**Comment by michaelmalone** [comment]
I am experiencing the same issue.

**Comment by Patrik-Lundqvist** [comment]
This seems related to #453, where a pull request is waiting

**Comment by rolivares** [comment]
Same here ... waiting for commit :(
