### ISSUE TITLE
Add new value

### ISSUE THREAD

**Issue by crash21** [angular-ui/ui-select#697]
Hello,

Is it possible to add new value if it's not found in the auto-suggest?

Thanks a lot.

**Comment by awerlang** [comment]
You could always push the search string onto the options array. But it is a lot of work to style and handle it appropriately.

AFAIK there's no native support for that, +1 to it.

**Comment by danielabar** [comment]
Does anyone know if this has been implemented?

**Comment by danielabar** [comment]
Actually, just found [this demo](http://plnkr.co/edit/m1SQXUxftBLQtitng1f0?p=preview) where adding a new option is supported in tagging mode, exactly what I need.

**Comment by gitnik** [comment]
Another +1 for this

**Comment by user378230** [comment]
This is the purpose of the tagging functionality in the recent versions of the library. 

Closing as resolved.
