### ISSUE TITLE
Support for "searchField" not working or not implemented?

### ISSUE THREAD

**Issue by gshergill** [angular-ui/ui-select#700]
Hi,

Unsure if this is supported or not, but looking at the wiki I thought it might have been via one of the "tagging" options, but wasn't able to get it working, not by editing the "fitler: $select.search".

Is this not working? Not documented? Not implemented? Or am I totally missing it?

Thanks.

Kind Regards,

Gary

**Comment by dimirc** [comment]
Can you explain more about what you mean with `searchField`?

**Comment by gshergill** [comment]
Hi,

From the selectize usage doc:
searchField	An array of property names to analyze when filtering options.	array	['text']

So in selectize I can pass in parameters to define which fields I am filtering on for search, for example:
```html
<selectize ... config="configOne" ...>
```

```javascript
$scope.configOne = {
...
  searchField: [$scope.searchfieldOne, $scope.searchfieldTwo], // e.g. ['name', 'age']
...
}
```

**Comment by dimirc** [comment]
You could just create a filter:

Like in the [demo](https://github.com/angular-ui/ui-select/blob/master/examples/demo.html#L85)
```
<ui-select-choices repeat="person in people | propsFilter: {name: $select.search, age: $select.search}">
```
Filter defined at [controller](https://github.com/angular-ui/ui-select/blob/master/examples/demo.js#L11)
