### ISSUE TITLE
auto select when typing "<<" or last "<" character end string" at tagging mode

### ISSUE THREAD

**Issue by huyd** [angular-ui/ui-select#702]
Hi team, 
my html: <ui-select multiple tagging tagging-label="" ...
the ui-select auto select when I type double "<<" or the string has "<" at end string. is it error ?

**Comment by user378230** [comment]
Closing this issue as it is over a year old and doesn't have a repro sample. 

If you believe its still relevant please update with a plunkr (or similar) against the latest version of ui-select (currently v0.15.0)
