### ISSUE TITLE
Is there a changelog?

### ISSUE THREAD

**Issue by starf** [angular-ui/ui-select#705]
What are the (breaking) changes between 0.9.9 and 0.10.0 ?

**Comment by dimirc** [comment]
There shouldbn't be any, you could check the changes at [commits history](https://github.com/angular-ui/ui-select/commits/master) for now. A new feature will the that matches are sortable, other than there is just a few bug fixes a refactor splitting source code to multiple files but final dist files is the same.  

Unfortunately we don't have s standard way to define a changelog yet but suggestions are welcome

**Comment by JobaDiniz** [comment]
+1
Without release notes we can't safely upgrade to the version. This should be one of the top priorities for this repo.

**Comment by starf** [comment]
through trial and error, i'm afraid.

**Comment by onemenny** [comment]
+1

**Comment by starf** [comment]
0.13.0 CHANGELOG.md file created
Thanks for this.
