### ISSUE TITLE
Using the "active" class to identify the currently selected item, not to highlight options on hover

### ISSUE THREAD

**Issue by ubirajaralucena** [angular-ui/ui-select#706]
Currently, ui-select adds an "active" class to the selected option, BUT as soon as we hover over the other options, those options get this "active" class. – IMO the "active" class shouldn't be used for highlighting.
For my needs I added an extra "selected" class to identify the currently selected item, letting the "active" class for highlighting only. Here is a small plunker http://plnkr.co/edit/oRAsSYcYDxuJcOtM09tb where the "fixSelectedItem" directive does the job.

**Comment by Akaryatrh** [comment]
Same here, the active class would be more useful for selected item.
Thx for the workaround @ubirajaralucena :+1:

**Comment by dimirc** [comment]
Can you setup a PR?

**Comment by rzschech** [comment]
+1

**Comment by rzschech** [comment]
I added a check mark by comparing the model value to the choice:

```
<ui-select ng-model="selected">
    <ui-select-match>{{$select.selected.label}}</ui-select-match>
    </ui-select-match>
    <ui-select-choices repeat="choice in choices">
        <span class="fa" ng-class="selected.id === choice.id && 'fa-check'" style="margin-left: -17px"></span>
        <span>{{choice.label}}</span>
    </ui-select-choices>
</ui-select>
```

**Comment by dimirc** [comment]
Please check https://github.com/angular-ui/ui-select/pull/1211 and let me know your opinion
