### ISSUE TITLE
Track by with single property binding fails

### ISSUE THREAD

**Issue by AntiFreez** [angular-ui/ui-select#709]
http://plnkr.co/edit/kp1QFUFCCgdvoVfrLxVv?p=preview

**Comment by kether667** [comment]
+1 it seems this was introduced in 0.10.0 or 0.9.9

**Comment by adematte** [comment]
It works fine in the version I am using: 0.9.0.

**Comment by abobwhite** [comment]
This did work but seems to not work anymore - I am using 0.9.9. This is a big issue.

**Comment by chrislovecnm** [comment]
:+1:  One this. I have been fighting this and already selected values in the select boxes ... Time to roll back to previous version.  This is broken in the latest version :frowning:

**Comment by bbreuil-harris** [comment]
+1

**Comment by adematte** [comment]
This is still broken in 0.13.1. Any updates on a fix/workaround?

**Comment by wesleycho** [comment]
Closing this as a duplicate of a couple of issues.
