### ISSUE TITLE
ui-select in an ng-repeat (or custom directive) has all items active

### ISSUE THREAD

**Issue by matt-king** [angular-ui/ui-select#715]
Placing a ui-select in an ng-repeat will sometimes cause all items to be active, or what looks like to be sometimes undefined. 

See this modified version of the demo:

http://plnkr.co/edit/Za8Po67Kcf0bhdXxoXuy?p=preview

**Comment by awerlang** [comment]
Did you notice `person` is using to refer to 2 different variables?

Rename one of them like this:

```html
  <div ng-repeat="person2 in people">
  <h3>Select2 theme</h3>
  <p>Selected: {{person2.selected}}</p>
  <ui-select ng-model="person2.selected" theme="select2" ng-disabled="disabled" style="min-width: 300px;">
```
