### ISSUE TITLE
ui-select dropdown issue when we use inside <div class="input-group"> and <ui-select class="form-control">

### ISSUE THREAD

**Issue by jsandeepm** [angular-ui/ui-select#717]
Please find the attached screenshot. This issue happens when we use <ui-select> element inside <div class="input-group"> and <ui-select class="form-control">. 

code attached: 
<div role="form">
	<div class="form-group">
		<label class="control-label">Pipeline Target</label>

		<div class="input-group">
			<ui-select multiple ng-model="pipeLineTargets.selectedPipelineTargets"
					   theme="select2"
					   class="form-control">
				<ui-select-match placeholder="Select a Pipeline Target">{{$item.pipelineTarget}}
				</ui-select-match>
				<ui-select-choices
						repeat="pipeLines.pipelineTarget as pipeLines in pendingPipeLines | filter:$select.search">
					<div ng-bind-html="pipeLines.pipelineTarget | highlight: $select.search"></div>
				</ui-select-choices>
			</ui-select>

			<span class="input-group-addon clickable"
				  ng-click="pipeLineTargets.selectedPipelineTargets = undefined">
				Clear
			</span>
		</div>
	</div>
</div>

Please let us know the fix.

Thanks,
Sandeep M

![image 2](https://cloud.githubusercontent.com/assets/9821180/6479716/f6bb2a92-c26f-11e4-8c5e-7507dbb5a6c4.jpg)

**Comment by user378230** [comment]
Closing this issue as it is over a year old and doesn't have a repro sample. 

If you believe its still relevant please update with a plunkr (or similar) against the latest version of ui-select (currently v0.16.0)
