### ISSUE TITLE
Render dropdown above the input if there is not room below

### ISSUE THREAD

**Issue by JoaoMosmann** [angular-ui/ui-select#719]
Dropdown should be rendered above the input whether there're no space below it.

Example: 

Scroll down to the Select2
http://plnkr.co/edit/uvXvxEeuOHgvimHH6U6z?p=preview

It works in the Select2 examples https://select2.github.io/examples.html

**Comment by cmlenz** [comment]
Duplicate of #148

**Comment by wesleycho** [comment]
Closing as already addressed in the library by #1212
