### ISSUE TITLE
ui-select search result overlaps inside accordion

### ISSUE THREAD

**Issue by RohitSonawane** [angular-ui/ui-select#72]
I am trying to implement ui-select inside of accordion but since the accordion height is small it overlaps the ui-select search result. It seems to be problem of css. But i can't seems to figure it out. I am using 'select2' theme. Is there any fix?
Plunkr : http://plnkr.co/edit/17ime385yybvlCXWBsTX?p=preview
- Rohit

**Comment by wesleycho** [comment]
This sounds like the classic limitation with the CSS box model - the only solution for something like this is to support an `appendTo` type feature where the user can append the ui select elements to a custom element. Currently, there is the [append-to-body](https://github.com/angular-ui/ui-select/wiki/ui-select) option that would let you work around this, but supporting appending to a custom element of the user's choice would also be useful.

**Comment by Jefiozie** [comment]
@RohitSonawane , could you verify if this is still a valid issue? If so please provide a new plunker so that somebody can make a PR for it. Thanks.

**Comment by Jefiozie** [comment]
Closing it down as it is a very old issue. Please create new issue if this is still a bug/ problem.

Thanks.
