### ISSUE TITLE
pressing 'enter' key on a ui.select with a selected item causes the highlight to fall of the first element

### ISSUE THREAD

**Issue by 0xF013** [angular-ui/ui-select#722]
if the select has a selected value and is not collapse, pressing the enter key will cause it to collapse and highlight the first option (pressing the 'down' arrow works fine).

I suppose it is caused by https://github.com/angular-ui/ui-select/blob/master/src/uiSelectController.js#L561 but I might be wrong (that line of code was the source of the problem when ui.select was one big file).

**Comment by wesleycho** [comment]
Can you reproduce this in a Plunker based on the latest release?

**Comment by Jefiozie** [comment]
Closing the issue down, due not been commented over a year if needed it can be reopened.
