### ISSUE TITLE
Keyboard actions do not close the choices list

### ISSUE THREAD

**Issue by lee-elenbaas** [angular-ui/ui-select#73]
If i open the select using the keyboard or mouse
and then use keyboard to navigate and manipulate some other UI element - the select does not close the choice list (unlike what it does with the mouse)

**Comment by paci1234** [comment]
Hello, have you found a solution on this?
I need the UI-Select dropdown to be closed automatically when I scroll down the page. And if I find a way how to force close it, I can manage to do it but do you guys have an idea about this?
