### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by piernik** [angular-ui/ui-select#733]
Could You give us changelog file?
What was changed in 0.11?

**Comment by dimirc** [comment]
You could check commits at https://github.com/angular-ui/ui-select/commits/master
But basically are some bug fixes and the new feature (to allow set focus to component https://github.com/angular-ui/ui-select/pull/728)
There shouldn't be breaking changes

**Comment by piernik** [comment]
setFocus is good option - thanks
