### ISSUE TITLE
Inconsistency when binding larger arrays

### ISSUE THREAD

**Issue by pgrm** [angular-ui/ui-select#734]
Hi, not sure if this issue has been reported this way already and if it's a problem on AngularJS or ui-select but here is my experience with ui-select with ~60 items

ui-select:

    <ui-select multiple ng-model="config.SelectedIDs" theme="bootstrap" ng-disabled="DisplayState == 'View'" sortable="false" close-on-select="false">
        <ui-select-match placeholder="Select values">{{$item.Name}}</ui-select-match>
        <ui-select-choices group-by="'GroupName'" repeat="value.Id as value in MetaData.Values | filter: $select.search">
            <div ng-bind-html="value.Name | highlight: $select.search"></div>
        </ui-select-choices>
    </ui-select>

`MetaData.Values` has over 60 items and when I first set on my scope `MetaData` and only afterwards `config` sometimes my `config.SelectedIDs` become a list of `undefined` values (the number of items stays the same). After I switched the order and first assigned `$scope.config` and only afterwards `$scope.MetaData` it seems to work now.

The error also didn't occur during debugging or with other instances with less items to choose from (~10 or less).

**Comment by user378230** [comment]
Closing this issue as it is over a year old and doesn't have a repro sample. 

If you believe its still relevant please update with a plunkr (or similar) against the latest version of ui-select (currently v0.16.0)
