### ISSUE TITLE
null values in ng-model after changing ng-model programmatically on multiselect

### ISSUE THREAD

**Issue by KKrisu** [angular-ui/ui-select#739]
**version** 0.11.1

**Demo** http://plnkr.co/edit/kLsFtY?p=preview

**settings** multiselect, complex ui-select-choices objects

**Issue**
When ng-model is empty and I'm programmatically changing ng-model values, it changes ng-model to null. When ng-model is not empty and I'm changing values programmatically it works fine. That's why when you click on the button on my demo second time (or you choose any value manually using UI), the values are set correctly.

**FIX**
PR: https://github.com/angular-ui/ui-select/pull/740

**Comment by renanlecaro** [comment]
I got into some trouble when modifying the model outside of ui-select too 
http://plnkr.co/edit/Wboo1fiePaLHKX0eHjxI?p=preview
It looks like it's more of a one way binding than a 2 ways : adding / removing elements with ui-select works well, but the digest cycle of the directive is not always triggered.

**Comment by z3ws** [comment]
I have the same proble than Kris Kesy

**Comment by nascosto** [comment]
+1 We are having the same problem. Spent quite a bit of time tracking this down.

**Comment by clydetacoma** [comment]
+1

**Comment by lianyi** [comment]
+1

**Comment by VoltiSubito** [comment]
+1

**Comment by olso** [comment]
+1

**Comment by lisaq-leafnode** [comment]
We are also having the same issue. When is this pull request likely to be merged in?

**Comment by dimirc** [comment]
Should be fixed with #748
