### ISSUE TITLE
Fix ng-model binding when focus is lost

### ISSUE THREAD

**Issue by mike9182** [angular-ui/ui-select#752]
Entered values are not written back to the model when another form element is clicked.

Steps To Reproduce:
1. Enter search term that has a matching element.
2. Click a button on the form.

Result: The value in the model IS NOT updated with the entered value.
Expected Result: The value in the model IS updated with the entered value.

**Comment by user378230** [comment]
Closing this issue as it is over a year old and doesn't have a repro sample. 

If you believe its still relevant please update with a plunkr (or similar) against the latest version of ui-select (currently v0.16.0)
