### ISSUE TITLE
sortable not working in IE11

### ISSUE THREAD

**Issue by pgrm** [angular-ui/ui-select#753]
In IE11 you can't change the order of items with drag&drop when you activate `sortable`. The cursor changes properly and everything looks good but releasing the cursor doesn't actually change anything. That is IE11 on Windows 8.1 - on Windows 10 it works.

This is the IE version from Windows 8.1 which isn't working:

![ie_version_not_working](https://cloud.githubusercontent.com/assets/713456/6629113/bae59aaa-c90b-11e4-8157-19e1deee7649.png)

and this is the IE version from Windows 10, were drag & drop and reordering works properly:

![ie_version_works](https://cloud.githubusercontent.com/assets/713456/6629139/e16172e4-c90b-11e4-88a9-1621ea90b0bd.png)

**Comment by homerjam** [comment]
I don't have a way to test this - is there anything in the console that might help us diagnose this?

**Comment by szsolt** [comment]
The problem was related to setData throwing an exception at the dragstart event.

Should be fixed in the pull request.

**Comment by pgrm** [comment]
Thx :+1:

**Comment by wesleycho** [comment]
Closing as likely in the wrong repository - UI Select has no sortable support.

**Comment by homerjam** [comment]
@wesleycho I think this refers to this directive https://github.com/angular-ui/ui-select/blob/master/src/uiSelectSortDirective.js

**Comment by szsolt** [comment]
Removed changes to dist and done a rebase to the current upstream master

**Comment by user378230** [comment]
Closing as Resolved, by #1503 (merged).
