### ISSUE TITLE
Decline tag creation throws error

### ISSUE THREAD

**Issue by Patrik-Lundqvist** [angular-ui/ui-select#755]
If the tagging function returns null in order to decline a new tag I get the following error:
```javascript
Uncaught TypeError: Cannot set property 'isTag' of null
```
[Here is a plunker](http://plnkr.co/edit/WyIC087njDHLmIVGTAj7?p=preview)

**Comment by LeleDev** [comment]
Some other issues / pull requests related to this topic:
https://github.com/angular-ui/ui-select/pull/683
https://github.com/angular-ui/ui-select/issues/520
https://github.com/angular-ui/ui-select/pull/678
https://github.com/angular-ui/ui-select/pull/663

Hope it gets fixed soon

**Comment by sandcastle** [comment]
:+1:

**Comment by wesleycho** [comment]
Closing this as a duplicate.
