### ISSUE TITLE
support perfect-scrollbar

### ISSUE THREAD

**Issue by parliament718** [angular-ui/ui-select#758]
I use perfect-scrollbar for all my scrollbars. http://noraesae.github.io/perfect-scrollbar/
It's a very popular library, and works very well in my experience (works with touch too).

Would be nice to get support for this:

```
 <ui-select>
    <ui-select-match></ui-select-match>
    <perfect-scrollbar> <!--nice and clean-->
      <ui-select-choices repeat="item in items | propsFilter: { label: $select.search }">
        <span ng-bind-html="item.label | highlight: $select.search"></span>
      </ui-select-choices>
    </perfect-scrollbar>
  </ui-select>
```

**Comment by user378230** [comment]
Closing as we shouldn't really have dependency on anything other than angular & theme css. 

feel free to update this issue if you make any progress with your own implementation.
