### ISSUE TITLE
cancel selection

### ISSUE THREAD

**Issue by parliament718** [angular-ui/ui-select#760]
How can I cancel item selection?

I have some items in my dropdown that I need to respond to, however I don't want them to change the currently selected value. 

Probably the best way would be to cancel selection when on-select callback returns false, would this be easy to add?

**Comment by parliament718** [comment]
merge please.

**Comment by samuelcastro** [comment]
How can I cancel selection like in multiple mode?
Currently I'm not able to remove a item selected, there is no "x" icon to remove that selection.

Some tip?

**Comment by wesleycho** [comment]
Closing as a usage issue - one can always have a model separation layer that abstracts out desired behavior and intermediary model management.
