### ISSUE TITLE
Passing options as Object

### ISSUE THREAD

**Issue by andyfensham** [angular-ui/ui-select#763]
Hi, In previous version of angular ui-select at https://github.com/angular-ui/ui-select2, you could pass the options as an object like below : 

$scope.select2Options = {
        'multiple': true,
        'simple_tags': true,
        'tags': ['tag1', 'tag2', 'tag3', 'tag4']  // Can be empty list.
    };

How would I do this in the new version of ui-select.

Thanks

Andy

**Comment by user378230** [comment]
This can't be done, please refer to wiki on how to use attributes to configure `ui-select`
