### ISSUE TITLE
Can't add more than 10 pixels of padding to ul.select2-choices without breaking it

### ISSUE THREAD

**Issue by martynchamberlin** [angular-ui/ui-select#766]
First off, love what you guys are doing with this. It's hands-down the best thing out there right now for what it does.  

So with the jQuery version of UISelect at https://select2.github.io/examples.html#tags, you can do the following:

1. Add 11 pixels (or more) of padding to the span.select2-selection div (its unique identifier on that page is `#tags span.select2-selection` if you want to pull it up in Chrome's Inspect Element tool). 
2. Add one item to the collection.
3. Focus the cursor inside the select menu and (and this is the user experience we're craving here) the cursor remains on the first line instead of the second line. Yay! 

With the Angular UI version of this plugin, anything more than 10 pixels breaks it after adding 1 item. In other words, the second item goes onto a new line. 

To replicate this, change line 137 (https://github.com/angular-ui/ui-select/blob/master/dist/select.css#L137) to `padding: 11px` and then experiment with the select menus at 
https://github.com/angular-ui/ui-select/blob/master/examples/demo-tagging.html

It's a bummer that 10 pixels is the magical cut-off for the Angular version (as opposed to the jQuery version that seems to work perfectly for me at any range of padding) because we're trying to build a very large search box on a site whose primary function is search. We really need to be able to have some pretty padding *and* be able to show more than one per line inside the select menu. 

Is this something you can fix please? 

Thanks!!

**Comment by dimirc** [comment]
Try to create a plunker or updates sone printscreens to illustrate all this better

**Comment by martynchamberlin** [comment]
Thanks. For now, I’ve found any easy solution by just changing the padding on its parent element. That fixes the problem for me. If the problem persists for others I’ll let them take a crack at it. 


Martyn Chamberlin 
Perfection Coding, LLC 

Mobile: (918) 978-9113 www.PerfectionCoding.com

**Comment by wesleycho** [comment]
Closing as per comments.
