### ISSUE TITLE
I can´t set a default value if the data comes from an $resource

### ISSUE THREAD

**Issue by reds071286** [angular-ui/ui-select#771]
First, apologize for my bad English, I want to load a list of  states and set selected one of this by default in my ui-select element. I dont have any problem if i do something like this.

 $scope.constants = {
            states: [
              {
                 codeId: "SIN",
                  codeDescription: "SINALOA"
              },
              {
                  codeId: "MICH",
                  codeDescription: "MICHOACAN"
              },
              {
                  codeId: "COL",
                  codeDescription: "COLIMA"
              },
            ]
        };

 $scope.constants.selected = "COL";

But the problem is that my list of states comes from an API call with $resource method and i cannot set a default value in the same way, Any ideas why? o what i have to do?

**Comment by dimirc** [comment]
Setup a

**Comment by dimirc** [comment]
Setup a plunker to be able to help faster
