### ISSUE TITLE
Add new tag on the fly based on external action?

### ISSUE THREAD

**Issue by martynchamberlin** [angular-ui/ui-select#775]
I have a select menu that enables tagging, as per https://github.com/angular-ui/ui-select/wiki/ui-select. 

Here's the user experience I'd like:

1. I'm in the select menu and I type some custom text that the dropdown can't match.
2. I click an external submit button
3. This click causes that custom text to populate as a new tag in the select menu.

Right now I can easily make #3 happen by hitting the submit button (that's the `tagging-tokens` option). But I'd like to do it by clicking a submit button instead.

Any ideas how to do that? Possible? 

Thank you!

**Comment by user378230** [comment]
Closing as usage issue. Not sure it's possible.
