### ISSUE TITLE
close-on-select doesn't reset search when reset-on-search is true

### ISSUE THREAD

**Issue by yaring** [angular-ui/ui-select#777]
When close-on-select="false" and reset-on-search="true" the expected behaviour is that the options will still be open but the search term will be reset.

Example:
http://plnkr.co/edit/QtZzjWwt5Q0mF3B7d8Ng?p=preview

**Comment by flankstaek** [comment]
Ran into this issue as well.

The work-around I developed was to add `on-select="$select.search = '' "`

**Comment by user378230** [comment]
Closed by #1761
