### ISSUE TITLE
New tags added to bottom of list as a configurable option

### ISSUE THREAD

**Issue by CodyHinze** [angular-ui/ui-select#780]
For usability reasons and to allow for better reuse of existing tags, add an option to move the new tag item to the bottom of the list.  

In these use cases a user would typically select the best match as they type from the top of the list, instead of creating a new tag. To allow for this functionality a configuration option that allows the item to be pushed and removed form the last index position instead of the first would be needed.  

See the attach screen shot for the desired result.

![tagging item order](https://cloud.githubusercontent.com/assets/2073449/6736851/c7781bee-ce3d-11e4-8459-d75b352e1d97.jpg)

**Comment by renanlecaro** [comment]
I agree, this is a common use case. I solved it by generating the list and appending an item at the end programmatically in the source function, but an attribute would be cleaner.

**Comment by wesleycho** [comment]
This is best implemented on the user side using the refresh functionality.

Closing this as a usage issue.
