### ISSUE TITLE
ngRepeat:dupes error for multi select and remote data source

### ISSUE THREAD

**Issue by yannlebel** [angular-ui/ui-select#781]
Hi,

I found a race condition in the latest version v0.11.2, for multi select.

If the data source of the select is loaded after the selection the widget raise the error ngRepeat:dupes and create duplicates item in the drop down.
But if the data source is loaded before the selection everything works as expected.

Here is a plunker to demonstrate the issue [http://plnkr.co/edit/juqoNOt1z1Gb349XabQ2?p=preview]

In this plunker if the variable objectLoadTime (line 6) is lower than dataSourceLoadTime (line 5) everything works

If the variable objectLoadTime is greater than dataSourceLoadTime duplicates are created.

Thanks

**Comment by benno208** [comment]
+1

**Comment by savokiss** [comment]
+1， I cant find the demo code. But as you say, I prepare the data before ui-select render and it works!

**Comment by mauricioborges** [comment]
+1. Has anyone found a workaround?

**Comment by wesleycho** [comment]
Closing as a duplicate of several ng-repeat errors.
