### ISSUE TITLE
Error when pasting text in IE

### ISSUE THREAD

**Issue by BKlerx** [angular-ui/ui-select#789]
The code for the event handler that is called when pasting some text into the input control throws an error because 'e.originalEvent.clipboardData' is undefined in Internet Explorer.

I found a solution on http://stackoverflow.com/questions/27738155/unable-to-get-property-getdata-of-undefined-or-null-reference-in-ie-but-not

This code applies the fix and works fine for me:
  _searchInput.on('paste', function (e) {
    var data;
    if (window.clipboardData && window.clipboardData.getData) { // IE
      data = window.clipboardData.getData('Text');
    }
    else if (e.originalEvent.clipboardData && e.originalEvent.clipboardData.getData) { // other browsers
      data = e.originalEvent.clipboardData.getData('text/plain');
    }
...

I am using jQuery 2.1.3 and AngularJS 1.3.14

**Comment by rohitrpaswan** [comment]
![image](https://cloud.githubusercontent.com/assets/4832153/14165093/df6f1d56-f722-11e5-8674-8a08aa2e77a0.png)
