### ISSUE TITLE
How to handle onblur event?

### ISSUE THREAD

**Issue by vdzundza** [angular-ui/ui-select#790]
Hi guys. Is it possible to handle 'blur' event on ui-select?

**Comment by csizzle** [comment]
I am also wondering this.

**Comment by shuron** [comment]
me too!

**Comment by sandyajadhav** [comment]
I am also facing same issue

**Comment by bliitzkrieg** [comment]
Anybody figure this out?

**Comment by mariusz360** [comment]
Me too.

**Comment by trashhead** [comment]
This would be nice :)

**Comment by geninsin** [comment]
There is nobody here?

**Comment by wesleycho** [comment]
Closing as a duplicate.
