### ISSUE TITLE
z-index issue on append-to-body

### ISSUE THREAD

**Issue by piernik** [angular-ui/ui-select#791]
If I open bootstrap modal with `ui-select` - it's below modal.
Z-index for bootstrap in append-to-body should be greater that `1050`.

**Comment by cmlenz** [comment]
I'm not sure whether that's the right fix. The current value (1000) is taken from Bootstraps own `@zindex-dropdown`. How does the Bootstrap JS deal with this problem? Is the dropdown element appended to the modal or modal background instead of the body?

**Comment by Gary-Li** [comment]
same problem to me.

**Comment by blairmorris** [comment]
I'm having the same issue, it seems that when opening a bootstrap UI modal, the dropdowns are hidden from having a lower z-index than the modal and the modal's backdrop. This results in the entire field disappearing when clicked. I'm trying to figure out a workaround for myself now, but it's a definite issue if you'll be using it inside of a Bootstrap UI modal.

**Comment by danielnemetz** [comment]
Anything new here?

**Comment by aske-cph** [comment]
Still an issue..

Made a super dirty quick-fix:

body > .ui-select-container {
	z-index:99999999999;
}

**Comment by wesleycho** [comment]
Closing as a user issue - one can easily add a higher z-index to the component's via CSS.
