### ISSUE TITLE
Demo uploaded not working on chrome

### ISSUE THREAD

**Issue by hearsid** [angular-ui/ui-select#795]
The demo on plunkr 
![screenshot](https://cloud.githubusercontent.com/assets/3892451/6800975/a58e7c34-d249-11e4-98dc-27c4f44a8000.png)
is not working on my chrome , linux mint rebecca . 
Chrome version : Version 40.0.2214.111 (64-bit) .

**Comment by user378230** [comment]
The demos appear to be functioning fine now in Chrome, closing.
