### ISSUE TITLE
How to obtain current search string inside keypress listener?

### ISSUE THREAD

**Issue by dKab** [angular-ui/ui-select#800]
Say I want to achieve behavior similar to **Tagging without multiple** in [this](http://plnkr.co/edit/m1SQXUxftBLQtitng1f0?p=preview) plunker. I assume I would have to listen to keypress event and add new object to the list each time key is pressed while removing old shorter version of it, right?
But how can I get hold of current search string inside my keypress handler? Since my model isn't plain string but an object and untill any option is selected it's value remains empty.

**Comment by clydetacoma** [comment]
I am doing something similar using the select search to filter a different list of items from the text. I use data-refresh="getChoices($select.search)" on the ui-select-choices and in my getChoices method I filter my list of options and use the text to filter my secondary list. 

I imagine you could use it in a similar way to get your desired result.

**Comment by dKab** [comment]
thanks for your help, clydetacoma!
