### ISSUE TITLE
Avoid clearing search input on focus and blur?

### ISSUE THREAD

**Issue by clydetacoma** [angular-ui/ui-select#801]
Is there a reason multiple select was designed to clear the search text when clicking outside of the input field/select choices? Or a reason for clearing the search text on focus? I want to use the input field text for a search as well as letting the user select from the select options.

I want to know if I were to submit a pull request if it would need to be a bugfix or a feature. If that is the intended functionality I would create a feature to keep the search text unless a select option is chosen.

**Comment by nascosto** [comment]
:+1:

**Comment by Downchuck** [comment]
reset-search-input="false" is close.

**Comment by clydetacoma** [comment]
Almost. I want it to clear on select but not on blur and focus. reset-search-input="false" makes it so it always clears or never clears.

**Comment by Downchuck** [comment]
Here's what I wound up with:
```
reset-search-input="false" on-select="$item.search = $select.search; $select.search='';
```

**Comment by clydetacoma** [comment]
That worked for my Downchuck, thanks!
