### ISSUE TITLE
Unable to add tooltip in input box

### ISSUE THREAD

**Issue by ramprakash-ravi** [angular-ui/ui-select#802]
I tried adding tooltip to input box in ui-select but its not working.

input(type='hidden', ui-select2='userSelect2options', data-placeholder='All User',
                      ng-model='selectedUsersForFilter', style='width:100%; margin-left:5px;',ng-readonly='isUserSelectDisabled', tooltip='Please select atleast one User')

How to add tool tip for input box in ui-select2 ?

**Comment by gerardp** [comment]
+1
Any idea about this feature?

**Comment by user378230** [comment]
You will probably need to modify [select.tpl.html](https://github.com/angular-ui/ui-select/blob/master/src/bootstrap/select.tpl.html) with the tooltip attribute. 

Closing due to being an old issue, please update if you require further assistance and we can look at reopening.
