### ISSUE TITLE
Track by in multiple select

### ISSUE THREAD

**Issue by i4got10** [angular-ui/ui-select#806]
If specify __multiple__ and __track by__ simultaneously I recieve the error "Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed."

Demo. Just select 2 items in select, and you will get the error.
http://plnkr.co/edit/taoUPj40sWnjuRD5zVCh?p=preview

**Comment by chuyik** [comment]
Same here.

**Comment by chuyik** [comment]
Use the forked version and everything works great with Angular 1.3.

Try it: https://github.com/richardallen/ui-select

**Comment by joaquinrivero** [comment]
@chuyik But, won't load a selected values.

**Comment by eranimo** [comment]
Can this be fixed? Currently multiple entries are unsupported because of this.

**Comment by segalr3** [comment]
same here, using angular 1.2.25, ui-select latest version
