### ISSUE TITLE
uis:close event not subscribed to in multiple - focus lost

### ISSUE THREAD

**Issue by photostu** [angular-ui/ui-select#807]
There is no event subscriber to uis:close in the mulitple directive. Is this by design?
The reason I ask is that selecting an option in multiple does not retain focus on close.

If this is legitimate, I can submit a PR to fix. Just let me know, thanks!

**Comment by wesleycho** [comment]
Going to close this issue as a duplicate - there is an open issue about event handling for various situations, not limited to just focus/blur.
