### ISSUE TITLE
Escape and enter should not propagate outside of ui-select

### ISSUE THREAD

**Issue by mareczek** [angular-ui/ui-select#808]
At present when ui-select is focused escape and enter propagate outside of ui-select.
When escape is pressed while the list of options is opened and the ui-select is displayed in modal the modal closes
or
when enter is pressed while one of the options is highlighted the form is being submitted.

**Comment by drewfreyling** [comment]
@mareczek I don't think 85cbd70 fixes the enter key press issue FYI.

**Comment by mareczek** [comment]
@drewfreyling  85cbd70 was i mistake (isn't it obvious?), hence 6b0fd79

**Comment by drewfreyling** [comment]
@mareczek That makes a bit more sense now! My apologies.

**Comment by mareczek** [comment]
@drewfreyling no problem, do you have any knowledge if this can be merged / or when it could be merged?

**Comment by drewfreyling** [comment]
Tagging @dimirc for that info...

**Comment by kiddo13** [comment]
Got the same problem too.

**Comment by mtraynham** [comment]
+1 Pretty big issue if you ask me...

**Comment by zigzackattack** [comment]
Yeah. Doesn't this bug make it impossible to include in a form with an `ng-submit`?

**Comment by Sylox** [comment]
:+1:

**Comment by mtraynham** [comment]
@zigzackattack yeah, it does.  An `enter` key press submits the form regardless of validity.
@mareczek's solution worked for me... but it looks like this project is on halt?  Nothing committed in a month...

**Comment by just-boris** [comment]
Pull request to solve it: https://github.com/angular-ui/ui-select/pull/901

**Comment by manichandra** [comment]
Thanks @mareczek

**Comment by MikeMatusz** [comment]
#901 certainly does correct one issue, but it introduces a new one.  A control should only consume an event when it actually does something with it.  So if pressing enter causes an item to be selected, it should stop propagation, same if pressing escape closes the dropdown.  But if the user hasn't typed anything and enter/escape isn't closing the dropdown or selecting an item, it should be allowed to propagate and submit or close the modal.  Now you can't ever submit a form if focus is within this control.  I can try to get a new pull request put together that would do this.

**Comment by oslo10e** [comment]
I do agree with @MikeMatusz, enter/escape should trigger default behavior when drop down list is closed. Because it should be possible to submit a <form> that contains <ui-select> by pressing ENTER, or closing a modal window that contains <ui-select> by pressing ESC.
At least it should be an optional attribute of <ui-select >

**Comment by oslo10e** [comment]
@MikeMatusz I made a pull request, #1279, to allow submit when pressing ENTER key in ui-select element by adding in-form="true". If you appreciate it, can you vote for it ?
