### ISSUE TITLE
When no item is selected ui-select throws console errors. No null check in two places.

### ISSUE THREAD

**Issue by priyanshuch** [angular-ui/ui-select#813]
![rsz_1rsz_screenshot_from_2015-04-01_131353](https://cloud.githubusercontent.com/assets/7846288/6936620/f1230182-d871-11e4-9e6e-2c012959e25d.jpg)

**Comment by wesleycho** [comment]
Closing due to lack of reproduction - feel free to open a new issue with reproduction in Plunker based on the latest release if this is still an issue.
