### ISSUE TITLE
How to programmatically clear or modify selection when using multiple-selection mode?

### ISSUE THREAD

**Issue by erobwen** [angular-ui/ui-select#817]
I am having some issues when trying to programmatically clear the selection of an ui-select component that is using multiple selection mode. 

Modifying the model directly works when in single select mode, so I thought it would be similar in multiple select mode. However, when I try to modify the model in my surrounding controller, the ui-select widget suddenly appears broken. There are no options at all to select and the ui-select widget is just blank. (even if I can log to the console and verify that my filters are letting some items through). 

If I could just clear the selection somehow it would make it possible to do what I am trying to do.

It is worth noting that I already do some programmatic manipulation of the selection that works. I have several choices in the dropdown that are incompatible, and cannot be selected at the same time. In the ng-change callback I send the selection and manipulate it, by removing the items that are incompatible with the newly selected item (too keep track of the newly selected item I have my own list "previousSelection")

ng-change="justSelectedProductArea($select.selected)"

But maybe the situation is different when the change is initiated by the widget itself rather than other widgets? I do not know. Somehow it does not work when the events in another selector tries to clear the selection in a particular selector.

**Comment by bob-lee** [comment]
I am in the similar situation (ui-select 1.12.1, select2 theme, multi selection). Select choices of my ui-select are refreshed on selection of the other drop down list. On refreshing, I was just assigning null to  'viewmodel.choices' array, but the nasty situation came up like below:

Previous: A selected from [A, B, C]
(Other drop down list changed and choices refreshed)
Current: A select from [B, C, D] // A is illegal now

Naturally, I tried to assign null to 'viewmodel.choicesSelected' array which causes error below:

"TypeError: Cannot read property 'length' of null
    at c.directive.controller.i.getPlaceholder" // in angular.js

**Comment by bob-lee** [comment]
My bad. Assigning null to array was causing a problem. When other drop down list is changed, I was doing:

viewmodel.choicesSelected  = null;
viewmodel.choices  = null;

And if I had any selected items, it crashes. Instead after I changed as below, all works ok:

if (viewmodel.choicesSelected) viewmodel.choicesSelected.length = 0;
if (viewmodel.choices) viewmodel.choices.length = 0;

**Comment by wesleycho** [comment]
Closing as a support issue.
