### ISSUE TITLE
What is the difference between $item and $model in the event function params?

### ISSUE THREAD

**Issue by toymachiner62** [angular-ui/ui-select#827]
There are 2 params for the events https://github.com/angular-ui/ui-select/wiki/ui-select#events: $item and $model. When i log these they both contain the same object.

Are they supposed to contain different objects or what is the person of having both of them?

**Comment by toymachiner62** [comment]
Why was this closed with no answer?

**Comment by user378230** [comment]
After a year I don't think it's getting answered. It doesn't look like it's causing a bug/problem either.

Just tidying up...

**Comment by toymachiner62** [comment]
Well maybe it's pointless to have both if they are the same thing? This could be refactored to remove one and make the code simpler?

If there is a difference it'd be nice to have it documented.

**Comment by user378230** [comment]
Feel free to submit a PR :smiley:
