### ISSUE TITLE
Is there a standard approach to adding Select or Clear All options?

### ISSUE THREAD

**Issue by brycepj** [angular-ui/ui-select#828]
In the list of choices, is there a way to add an option that adds/removes all options to/from the selected group? Has anyone implemented something like this? 

I suppose I could probably hack around this with `ng-change` -- I'm just wondering if there's a better way.

**Comment by user378230** [comment]
Clear all has been implemented in more recent versions of the library. 

To simulate select all, simply add a button to add all the options to your ng-model array.
