### ISSUE TITLE
two way binding to the text input?

### ISSUE THREAD

**Issue by alexandros-s** [angular-ui/ui-select#829]
I have a question.

I'm trying to achieve this http://jsfiddle.net/mhelvens/SZ55R/1/ but unfortunately it doesn't work for me. 
I'm trying to get my head around why it is not working with this particular directive.

What I want to do is to two way bind the input box model of the directive. Usually I was doing that using an isolated scope. In your case though you have scope to true and you listen to attributes with `attrs.
$observe`

The user case is that I have a faceted search that is also accepts free text keyword and I want to pass the content of the text input as a search parameter instead when it's not matching an item from the list.

**Comment by Nadrendion** [comment]
I didnt see this issue earlier and reported something similar in #860.
This feature would be very nice.

**Comment by yaojingguo** [comment]
+1

**Comment by user378230** [comment]
From #1046:

>Fairly simple to do with a custom directive...

>```js
myModule.directive('myUiSelect', function() {
  return {
    require: 'uiSelect',
    link: function(scope, element, attrs, $select) {
      scope.$watch(function() { return $select.search; }, function(newSearchValue) {
        //...
      });
    }
  };
});
```
>You can also then programmatically set `$select.search` to a new value if you wish.
>
>(Ref: [7. Accessing `$select`](https://github.com/angular-ui/ui-select/wiki/Accessing-$select))
