### ISSUE TITLE
No Results Found Message

### ISSUE THREAD

**Issue by KatelynL** [angular-ui/ui-select#831]
Is is possible to add in a message for when no results are found in the search?  I believe the original select2 and selectize included this is as a feature.

**Comment by brightcode** [comment]
I also missed this. Select2 shows the following when no results match the search:
 
    <ul class="select2-results">
      <li class="select2-no-results">No matches found</li>
    </ul>

**Comment by amcdnl** [comment]
I was thinking we should have new 3 options:

- Search placeholder text ( different from input )
- No results text 
- Ajax searching text

@dimirc thoughts?

**Comment by jitendersandhu** [comment]
+1

**Comment by sridharthumma** [comment]
+1

**Comment by wesleycho** [comment]
Closing as a duplicate of #152
