### ISSUE TITLE
Angularjs ng-view with ui-select

### ISSUE THREAD

**Issue by miquelgatius** [angular-ui/ui-select#834]
I have tried to add another html to my index with ng-view, it's working fantastic but it's ignoring the style/angularjs code(only happens on this one). So instead of this:
https://www.drupal.org/files/project-images/select2.png
displays that:
http://i1-scripts.softpedia-static.com/screenshots/Bootstrap-Form-Helpers_1.png

**Comment by blowsie** [comment]
What is the question? You should provide some code
