### ISSUE TITLE
selected is passed by reference 

### ISSUE THREAD

**Issue by anoopsinghbayes** [angular-ui/ui-select#835]
i may not be able to explain the issue properly in words but this example can show case the issue
http://plnkr.co/edit/J02AmsvBIMyWl8fufLiR?p=preview
step to generate the issue 

1)select vanilla from ui-select in first row and set quantity in the quantity field of this row
2)click add row ,again select vanilla in this row and set quantity for this row 

now this changes the quantity for the first row

**Comment by wesleycho** [comment]
It would be best to separate out the model - the selected object passed is just the one from the choices.

Closing as a usage issue.
