### ISSUE TITLE
How to preselect a value in async ui-select

### ISSUE THREAD

**Issue by razam217** [angular-ui/ui-select#838]
Hi,
How can I select a value initially in the ui-select in which we get the results from the service asynchronously. Is there any possible easy way to pre-select? And how can we add minimum limit of input characters while searching something?

**Comment by zhenyi2697** [comment]
I need this feature too. Basically, I want to be able to set value into the search box, so that ui-select "memorize" user's last selection. This is essential because when user want to select multiple value from the search result, they will not have to re-enter the same search text.

**Comment by kshutkin** [comment]
+1
