### ISSUE TITLE
ui-select breaks with angular js v1.3.0

### ISSUE THREAD

**Issue by anoopsinghbayes** [angular-ui/ui-select#85]
![select2](https://cloud.githubusercontent.com/assets/6286517/3278694/cb1554b0-f3cd-11e3-9b45-b163f226fab1.PNG)

select breaks with angular js version 1.3

the above snapshot is for the basic example as in the demo plunkr

**Comment by btm1** [comment]
This is still happening for me and doesn't appear to be fixed in the latest release. I'm not sure why this is closed. I'm using .9.6 and angular 1.3.11.

![screen shot 2015-01-27 at 3 09 54 pm](https://cloud.githubusercontent.com/assets/4110944/5929226/9e539aba-a636-11e4-85f1-ba2757c5e235.png)
![screen shot 2015-01-27 at 3 09 23 pm](https://cloud.githubusercontent.com/assets/4110944/5929225/9e51505c-a636-11e4-82a8-31311cfe1e6a.png)

**Comment by stristr** [comment]
Agreed, not fixed.

**Comment by emretoprak** [comment]
Still have problem i'am looking for alternatives....

**Comment by yatagan** [comment]
I recommend http://brianreavis.github.io/selectize.js/

**Comment by btm1** [comment]
now i'm having all sorts of issues with this library and 1.3.11. Tagging no longer works :(

**Comment by MartinMuzatko** [comment]
We use ui-select via ajax load. UI Select works only every second ajax call.
Same issue:
```
 Error: [ui.select:transcluded] http://errors.angularjs.org/1.3.8/ui.select/transcluded?p0=Expected%201%20.ui-select-choices%20but%20got%20'%7B0%7D'.&p1=0
    at js/angular-ui-select.js:108:24
    at js/angular-ui-select.js:1252:39
    at js/angular.min.js:51:108
    at js/angular.min.js:52:497
    at l (js/angular.min.js:56:476)
    at link (js/angular-ui-select.js:1232:25)
    at $ (js/angular.min.js:70:426)
    at v (js/angular.min.js:59:401)
    at js/angular.min.js:66:472
    at js/angular.min.js:112:276 <div class="{{field.name}} ui-select-container ui-select-multiple ui-select-bootstrap dropdown form-control ng-pristine ng-untouched ng-valid ng-scope" ng-class="{open: $select.open}" ng-model="field.permissions" theme="bootstrap">
```

**Comment by yogeshnath** [comment]
If I change to below version, it does work:
<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.js"></script>

**Comment by jylinman** [comment]
Hey guys, ran into the same thing in Angular 3.1.15 but I updated angular to 3.1.17 and it is working again.

**Comment by Jonybang** [comment]
I was try 1.3.17 and it does not work for me

**Comment by harksha** [comment]
1.2.3 error: with select2 theme http://plnkr.co/edit/c5GLHaitABkw2FHUwVcX?p=preview
I realise this angular version may not be supported anymore, but then, could you upgrade the documentation?
