### ISSUE TITLE
with multiple select, an array ng-model won't get updated, while an array inside an object ng-model works

### ISSUE THREAD

**Issue by israelidanny** [angular-ui/ui-select#852]
I'm using a multiple select for a countries selector. My HTML looks like this:
```html
<ui-select multiple ng-model="selectedCountries" theme="bootstrap">
  <ui-select-match placeholder="Select country...">{{$item.text}}</ui-select-match>
  <ui-select-choices repeat="country.id as country in countries | propsFilter: {id: $select.search, text: $select.search}">
    <div ng-bind-html="country.text | highlight: $select.search"></div>
  </ui-select-choices>
</ui-select>
```

With a corresponding:
```javascript
$scope.selectedCountries = [];
```

It doesn't really work. However, if I only change the first line to:
```html
<ui-select multiple ng-model="someObject.selectedCountries" theme="bootstrap">
```

Which looks like this in the controller:
```javascript
$scope.someObject = {
   selectedCountries: []
};
```

Suddenly everything works. This doesn't make much sense. Why the weird behaviour?

**Comment by clintam** [comment]
This is a common pitfall when using writable expressions in angular: your ng-model must have a dot in it.

(http://stackoverflow.com/questions/17606936/angularjs-dot-in-ng-model)

Suggest to close this issue.

**Comment by leocaseiro** [comment]
:+1:  Thanks, that's really good info!

**Comment by wesleycho** [comment]
Closing as a support issue.

**Comment by TabrisK** [comment]
perfect ! its really help me !!!

**Comment by anika-infoobjects** [comment]
phew! Thanks perfectly worked..
