### ISSUE TITLE
Pressing enter for selection of a dropdown value directly submits form

### ISSUE THREAD

**Issue by razam217** [angular-ui/ui-select#862]
I am working with ui-select, and whenever I press enter to select some searched results, the result is selected and the form directly goes on to submit. I cant figure it out, what is the problem.

Here is the HTML I'm using

    <ui-select ng-model="$parent.selectedPatient"
										theme="select2"
										reset-search-input="true"
										title="Select Patient">
										<ui-select-match allow-clear="true"     placeholder="Select Patient">{{$select.selected['Patient.name']['HumanName.text']}}</ui-select-    match>
										<ui-select-choices repeat="patient['@id'] as patient in patients track by $index"
											refresh="refreshPatients($select.search)"
											refresh-delay="0">
											<div ng-bind-html="patient['Patient.name']['HumanName.text'] | highlight: $select.search"></div>
										</ui-select-choices>
									    </ui-select>

**Comment by knifesk** [comment]
Having the same issue.... will look into it later.

**Comment by razam217** [comment]
Hi @knifesk,
I have found a solution, I was using `<button>`, and the default type of button is submit, so I had to specify the type="button", and the issue fixed....

Reference: https://github.com/gregurco/ui-select/commit/673369ce8b906fa2da610e887a9611f90a15351e

**Comment by knifesk** [comment]
Yes I know.. but when you're pressing enter key in the search field the form should not be sent.. your solution removes the possibility of submitting the form with the enter key... even if you are in another field, because the form has no default action and can only submitted by mouse or tabbing to the button and pressing enter.

**Comment by loverajoel** [comment]
Hey guys this pr solve this issue https://github.com/angular-ui/ui-select/pull/868

**Comment by knifesk** [comment]
You're awesome! Thanks for testing it and creating the tests for it

**Comment by mtraynham** [comment]
Same bug as #808?

**Comment by knifesk** [comment]
In part.. this bug does not contemplate ESC key, only fixes the behaviour with ENTER key... @loverajoel, in the condition you can compare if the key is KEY.ESC also to fix that issue too.. 

```javascript 
if (key === KEY.ENTER || key === KEY.ESC)
```
that should do the trick

**Comment by brianfeister** [comment]
@loverajoel is @knifesk's comment about `KEY.ESC` valid in your opinion?  If you think so, can you push that change to your PR?
