### ISSUE TITLE
Clearing the selection sets model value to 'undefined'

### ISSUE THREAD

**Issue by mirow** [angular-ui/ui-select#863]
Clearing the selection in a non-multiselect which has the "allow-clear" attribute sets the model value to undefined, while the expected value would be null.

Being undefined causes Angular to ignore the change, so it won't be sent to the server.

**Comment by arathael** [comment]
+1
Doing a manual checkup before submit to correct this..

**Comment by maxavi** [comment]
+1

**Comment by igler** [comment]
+1

**Comment by user378230** [comment]
Please do not +1 it creates unnecessary noise in issues, use github reactions.

***
This looks like a small change, it could probably be fixed in a quick PR with associated unit test. Instead of +1'ing consider submitting a PR! :smiley:

**Comment by zuzusik** [comment]
BTW, the fix for this broke code for those waiting for `undefined` here. 

This was definitely a **breaking change** and should have been released in new major version...
