### ISSUE TITLE
bind value in search box to ng-model?

### ISSUE THREAD

**Issue by zedL** [angular-ui/ui-select#867]
Is it possible to bind the entered value in the search box to the model? 
So if no match could be found in ui-select-choices, than I want to bind the entered text to the ng-model... Has someone an idea?

**Comment by wcomartin** [comment]
is there any updates on this?

**Comment by user378230** [comment]
The tagging functionality in recent versions of the library should be what you are after. 

Or you can create a custom directive that taps in `$select.search` in the uiSelectController.

Closing for now as is an old issue and doesn't appear to be much demand for this feature.
