### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined each time when I select or unselect an item from multi select

### ISSUE THREAD

**Issue by elangovang** [angular-ui/ui-select#870]
I'm getting this stack trace:

TypeError: Cannot read property 'length' of null
    at uis.directive.link.ngModel.$formatters.unshift.checkFnMultiple (select.js:1128)
    at Array.<anonymous> (select.js:1143)
    at Object.<anonymous> (angular.js:23419)
    at n.$get.n.$digest (angular.js:14300)
    at n.$get.n.$apply (angular.js:14571)
    at HTMLDivElement.<anonymous> (angular.js:21571)
    at HTMLDivElement.o.event.dispatch (jquery.js:4371)
    at HTMLDivElement.o.event.add.r.handle (jquery.js:4057)

**Comment by Senadtm87** [comment]
I had same problem, multiselect works fine but in console logs error so i just added in checkFnMultiple function test for matches!=null
   if(matches!=null && matches.length>0 && result[matches[1]] == value[matches[1]]){

**Comment by juanpasolano** [comment]
This worked for me +1. Could this be merged? @Senadtm87 have you made a pull request?

**Comment by Vitall** [comment]
+1

**Comment by juanpasolano** [comment]
I see this function has actually changed in the master branch: [link](https://github.com/juanpasolano/ui-select/blob/master/src/select.js#L604-L615).
I wouldn't know if it fixes this issue.

**Comment by martinoss** [comment]
I noticed this error too after adding "tack by $index" in the repeater expression

**Comment by estvmachine** [comment]
@juanpasolano  no, it doesnt fixed with that. With the tip of @Senadtm87 , but why this error happens?.

**Comment by samuelcastro** [comment]
Thanks @martinoss, fixed just removing "track by $index" from repeat expression.

**Comment by sandcastle** [comment]
:+1:

**Comment by EllaShar** [comment]
Any news about this? Removing the "track by" does the trick but it's not a real fix...

**Comment by wesleycho** [comment]
I believe this is already fixed in `master` - feel free to open a new issue with reproduction if this is not the case.

**Comment by hybridappdev** [comment]
Thanks @martinoss it is working fine after removing "track by" from the repeat, can you please explain cause of the error.
