### ISSUE TITLE
Wrong input focus when angular DebugInfo is disabled

### ISSUE THREAD

**Issue by piebe** [angular-ui/ui-select#872]
The plunker below contains the standard ui-select example, but with angular 1.3 and DebugInfo disabled, ie

$compileProvider.debugInfoEnabled(false);

Use the mouse to select the first selectbox, then select the second selectbox and start typing. The result will appear in the first select instead of the second. 

http://plnkr.co/edit/aRORZjU8VKhKuJW1pTxx

Most likely cause line 149 in uiSelectDirective:
var targetScope = angular.element(e.target).scope(); //To check if target is other ui-select
            
.scope() is not available when DebugInfo is turned off...

**Comment by ckniffen** [comment]
+1

**Comment by awerlang** [comment]
+1
