### ISSUE TITLE
Demo doesn't block browser auto-complete

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ui-select#874]
Using Chrome 41, the browser allowed me to select one of my stored addresses, which was not an allowed option on the scope. Wrapping the ui-select in a ```<form autocomplete="off">``` tag, solves the issue.

This is a widely discussed problem of browsers selectively respecting the autocomplete attribute.

**Comment by realrunner** [comment]
What do you mean by "a tag" ?

**Comment by AgDude** [comment]
Sorry, I entered invalid markdown, the comment should make more sense now.

**Comment by jquinter** [comment]
tried this under chrome 42, osx 10.10.2, last version stable of ui-select. Didn't solve the issue.

**Comment by MikeMatusz** [comment]
Seems like in the latest versions of Chrome/FF, I have to actually modify the template to put autocomplete="false" on the input element.  "off" doesn't seem to work anymore.

**Comment by jgesser** [comment]
Hi folks, the solution made by hugobessa worked for me.
Does any one knows when it will be released and this issue closed?
thanks!

**Comment by dimirc** [comment]
Should be solved soon with https://github.com/angular-ui/ui-select/pull/1210
