### ISSUE TITLE
Bootstrap theme tagging style bug

### ISSUE THREAD

**Issue by monkeymonk** [angular-ui/ui-select#876]
The input seems to be stuck under the .btn elements.

![capture d ecran 2015-04-22 a 13 46 51](https://cloud.githubusercontent.com/assets/574338/7273654/2d6aaa16-e8f6-11e4-9128-566d0cf58d13.png)

Where it will be something like that :

![capture d ecran 2015-04-22 a 13 50 30](https://cloud.githubusercontent.com/assets/574338/7273707/9b220c70-e8f6-11e4-93de-2416d0f38f2a.png)

**Comment by user378230** [comment]
Closing this issue as it is over a year old and appears to be working fine in more recent versions of the library. 

If you believe its still relevant please update with a plunkr (or similar) against the latest version of ui-select (currently v0.15.0)
