### ISSUE TITLE
Tagging tokens not being initialized to default for AngularJS 1.3.1+

### ISSUE THREAD

**Issue by afuna** [angular-ui/ui-select#881]
This means that you can't input new / unknown values that aren't in the dropdown if you have the `tagging` attribute but don't have the `tagging-tokens` attribute.

Put up a quick demo here:

http://plnkr.co/edit/jZ3u8MTbIWGDbaApq0U0?p=preview

Start with the third from the top (the one immediately after the fork). That uses AngularJS 1.3.0. New value + enter works perfectly.

Then go to the next revision, which uses 1.3.1. Suddenly new value + enter doesn't persist the new value.

Then go to the last revision, which adds the `tagging-tokens` attribute. Now things work again.

From what I can tell, attrs.watch is now no longer being called for taggingTokens when there's no tagging-tokens attribute defined, so taggingTokens is no longer being initialized.

**Comment by selvach** [comment]
+1. 

As well as tagging-tokens not being defaulted, tagging no longer occurs onBlur. 
Just to add, this regression first appears in angular-ui-select 0.11.2.

**Comment by Pavek** [comment]
+1

Some details: I researched this issue before for a different case. Conclusion: Angualr 1.3.1 stoped triggeering attrs.$observe('attrName', ...) when attribute is missing. This is performace optimization I guess.

**Comment by 43081j** [comment]
+1

This is due to angular/angular.js@531a8de72c439d8ddd064874bf364c00cedabb11.

Maybe in the observer for `tagging`, we could default `taggingTokens` if it hasn't already been set? This way if the `taggingTokens` observer is hit, there is no change, otherwise a default is set.

**Comment by wesleycho** [comment]
I'm a bit confused, is this an issue?

**Comment by Jefiozie** [comment]
Closing it down as it is a old issue. Please create new issue if this is still a bug/ problem.
Next i'm trying to get a good overview of recent bugs.

Thanks for understanding.
