### ISSUE TITLE
Issue with focus, when clicked on $document

### ISSUE THREAD

**Issue by DSDOS** [angular-ui/ui-select#891]
Hello,

We've created form with select (using your plugin) and another input (for title). 

When we click on select (it opens options) and then click on title input, select button is still focused (and closed). We believe title input should be focused instead. 

We've also noticed all that is need to be done to fix this issue is to change line 1087 to:
$select.close( true );

Thanks.

**Comment by wesleycho** [comment]
Can you create a reproduction via Plunker?

**Comment by wesleycho** [comment]
Closing in favor of #1116
