### ISSUE TITLE
UI Select Items Not Appearing in IE 8

### ISSUE THREAD

**Issue by DeanPoulin** [angular-ui/ui-select#90]
When I view the example  [plunkr: http://run.plnkr.co/Uz2DH8wogGVCgtXZ](http://run.plnkr.co/Uz2DH8wogGVCgtXZ) noted in the README it appears as though the dropdown elements are not being bound into the DOM correctly and appear blank.
![IE 8 ui-select items missing](https://cloud.githubusercontent.com/assets/246410/3403250/7d75f6f6-fd64-11e3-9462-2e0efd0cda03.png)

You can see in the IE DOM the actual a tag is not inside of the element. I'll keep looking to see if I can track down what's causing this.

![DOM Elements Missing](https://cloud.githubusercontent.com/assets/246410/3403276/e36cf072-fd64-11e3-9d57-7aa0b73620bf.png)

**Comment by PaulAndreLOUIS** [comment]
+1

**Comment by bashanam** [comment]
+1

**Comment by wesleycho** [comment]
Closing due to age of this issue - feel free to open a new issue if this is still a problem with the current release.
