### ISSUE TITLE
Is this project deprecated?

### ISSUE THREAD

**Issue by pratik60** [angular-ui/ui-select#900]
@dimirc  @brianfeister 
Can we please assign more maintainers who can look at this project, and at least merge the good pull requests?

Following up on this thread -: https://github.com/angular-ui/ui-select/issues/884

Its completely understandable that the current maintainers are overloaded with work, but they should be definitely asking for people who can offer to maintain the code. I hate so many pull requests lying idle, and quite a few seem to be good fixes.

**Comment by simkessy** [comment]
+1

**Comment by brianfeister** [comment]
Discussed on #884
