### ISSUE TITLE
How to great a reusable auto-complete control?

### ISSUE THREAD

**Issue by salarmehr** [angular-ui/ui-select#904]
I am trying to make some directives for some my auto-complete controls (e.g. an input to select a user id). I don't know how to update the parent model after user selects an option and how to specify the property that should be set on the model. Here is my attempt (using 'ui-select plugin').  

    .directive('UserCombo', ['$http', function ($http) {
        return {
            templateUrl: '../template/userCombo.php',
            scope: {
                label: '@',
                model: '@'
            },
            link: function (scope, element, attr) {
                scope.refreshUsers = function (query) {
                    var params = {query: query};
                    return http.get(
                        '/user/combo',
                        {params: params}
                    ).then(function (response) {
                            scope.options = response.data
                        });
                };
            }
        }
    }]);

The directive's view:

    <p>
        <label for="user">{{label}}:</label>
        <ui-select theme="bootstrap" ng-model="form.user">
            <ui-select-match ng-attr-placeholder="{{label}}:">{{$select.selected.fullName}}</ui-select-match>
            <ui-select-choices repeat="item.id as item in options  | filter: $select.search"
                               refresh="refreshUsers($select.search)">
                <span ng-bind-html="item.fullName|highlight: $select.search"></span>
            </ui-select-choices>
        </ui-select>
    </p>

And it's usage:

                    <div user-combo="" model="form.manager" label="Admin"></div>

**Comment by user378230** [comment]
Closing as this is a general angular question rather than a ui-select issue. 

You might try stackoverflow for better assistance.
