### ISSUE TITLE
Clear the search text

### ISSUE THREAD

**Issue by dlidstrom** [angular-ui/ui-select#905]
Is is possible to clear the search filter? Check out the demo at http://plnkr.co/edit/a3KlK8dKH3wwiiksDSn2?p=preview. If you type something in the address dropdown, then click outside the dropdown to close it, then click the dropdown again the text you entered is still there. It would be nice to have a way to reset this text. Is there?

**Comment by Sjors** [comment]
You're using `reset-search-input="false"`. If you set that to true or leave it out, the text will be cleared when you click outside the dropdown.

**Comment by user378230** [comment]
Closing as resolved.
