### ISSUE TITLE
how can we reduce size of Datepicker Popup

### ISSUE THREAD

**Issue by nutanabhiram** [angular-ui/ui-select#908]
Is there any way to reduce size of datepicker popup in angularJS . The Popup seems a little big for my screen in the the application thus getting me scrollbar on screen.

Please look at the following plunker for datePicker reference.
http://plnkr.co/edit/fMy05fn1ri9qwL0NJFDe?p=preview

**Comment by AdamAxtmann** [comment]
Just put a css class on the surrounding div... 

http://plnkr.co/edit/uJCm3PdWd1zbjAKdO8Rs?p=preview

**Comment by nutanabhiram** [comment]
Adam
I dont want the control to be smaller. I want the Popup to be samaller in size. Is there any way to redice the calendar popup size . Currently its deafult size. 
Steps to see to understand what I am talking about. 
Go to your plunker.
Click to open Calneadtr popup top select date. 
I want this popup to be of smaller size and default size.

I hope you got my issue

**Comment by user378230** [comment]
Closing as this is the `ui-select` repo.

**Comment by kraravind167** [comment]
I'm new to web development
I've tried to reduce by css , but at some size it's forcestopping to reduce 
If any one  has solution , help me out 
Thanks
