### ISSUE TITLE
How to implement tagging without items being in dropdown?

### ISSUE THREAD

**Issue by dlwhiteman** [angular-ui/ui-select#911]
I would like to use ui-select as a tagging field, and the tags do not have to already be available in the choices list.  All of the demos I see only allow tags to be entered if they are already in the dropdown.

I would also like the entered tags to be stored in the model as a comma separated list?  Is this possible at all?

**Comment by irongomme** [comment]
Hi, you  can do that : 

```
<ui-select-choices repeat="tag in [] | filter:$select.search">{{tag}}</ui-select-choices>
```

**Comment by dlwhiteman** [comment]
Thank you! Does this also result in the data being stored in the model as a
comma separated string?

**Comment by irongomme** [comment]
No i think results are stored in the model as a javascript array

**Comment by wesleycho** [comment]
Closing as a support issue.
