### ISSUE TITLE
Change select to Multiple programmatic 

### ISSUE THREAD

**Issue by imaa** [angular-ui/ui-select#916]
Hi , 
thanks for the grate plug-in , 

i facing a challenge of how i can convert the ui-select (non multiple) to a multiple ui-select programmatic ?

**Comment by alexbowers-tecmark** [comment]
Give it the tags: option, and multiple: true in the config

**Comment by imaa** [comment]
@alexbowers-tecmark  i want to change it in the controller (Javascript ) any way i used $complie and it works out thanks for your replay
