### ISSUE TITLE
Control is not displayed properly and keyboard support is lost, when search enabled option is given false

### ISSUE THREAD

**Issue by vikramnagineni** [angular-ui/ui-select#917]
Steps to reproduce:
1. Give search enabled as false for ui-select.
2. Notice that the controls are broken.

**Comment by mattaningram** [comment]
I've noticed this as well. Keyboard controls only work properly when search is enabled.

**Comment by kunal999** [comment]
+1

**Comment by wesleycho** [comment]
Looks like this is still an issue: http://plnkr.co/edit/lB1YIIzBdBUNXl7rRB4K?p=preview
