### ISSUE TITLE
Multiselect: suggested items don't update on external change

### ISSUE THREAD

**Issue by just-boris** [angular-ui/ui-select#918]
When I try to add or remove values using internal methods (remove on "&times;" button, add by click on choice) items properly disappeared from choices. When I do the same by changing ng-model from my controller items didn't update.

Here is plunker with demo: http://plnkr.co/edit/ZT2ywjYIwmPpRmbOMr31?p=preview. Try to add value via button and look, this is still in choices list.

Based on [stackoverflow question](http://stackoverflow.com/questions/30150585/angular-ui-select-multi-select-dropdown-is-not-getting-updated-on-selecting-som/30163988)

**Comment by just-boris** [comment]
Extra: it happened because [`refreshComponent`](https://github.com/angular-ui/ui-select/blob/948d38318c/src%2FuiSelectMultipleDirective.js#L139) is called before [the actual value has been set](https://github.com/angular-ui/ui-select/blob/948d38318c/src%2FuiSelectMultipleDirective.js#L153)

**Comment by shkleinik** [comment]
+1 have the same problem

**Comment by mateusleon** [comment]
+1

I've made a paliative fix on my ctrl, deleting the collection, to force the `$watchCollection` to enter on the if below (https://github.com/angular-ui/ui-select/blob/master/dist/select.js#L397):

```javascript
    $scope.$watchCollection(ctrl.parserResult.source, function(items) {
      if (items === undefined || items === null) {
        // If the user specifies undefined or null => reset the collection
        // Special case: items can be undefined if the user did not initialized the collection on the scope
        // i.e $scope.addresses = [] is missing
        ctrl.items = [];
      }
      // ...
```

After the deletion is made, I fill up the collection updated with the actual values, and there you go... not the correct way, of course.

**Comment by carlos-** [comment]
+1

**Comment by ma-zal** [comment]
+1

**Comment by vertex** [comment]
:+1:

**Comment by sdasun** [comment]
1+

**Comment by i4got10** [comment]
:+1:

**Comment by dicbrus** [comment]
the same issue...

**Comment by dicbrus** [comment]
Interesting to note that version 0.3.8 working excellent, so strange that it is not still fixed
https://plnkr.co/edit/E1yErzVefrPlKurUsHH9?p=preview

But if you change js script to last ui-select version, the problem appears.

**Comment by dicbrus** [comment]
this solved the problem 
https://github.com/angular-ui/ui-select/pull/1019/files

**Comment by wesleycho** [comment]
Going to close in favor of #1434.
