### ISSUE TITLE
Dropdown menu is not shown on mouse click after some item is selected.

### ISSUE THREAD

**Issue by yjw9012** [angular-ui/ui-select#920]
I am trying to implement Selectize dropdown on top of AngularJS.
The problem is, without any item selected, I click on dropdown, items appear below it, select some item and the items are hidden. Now, when I mouse-click on the dropdown, items do not appear. However, they appear with up/down Arrow key or manual name typing.

I've spent some time looking into why it is happening.

My observation:
The reason why it seems that the dropdown list does not show up is that, assuming user already selected any item in the list before, when user clicks on the dropdown again, actually it shows the list and then hides the list immediately, not giving user a second chance to select items.

Any idea what might be causing this issue?

**Comment by justin-romano** [comment]
I think the issue is cos.  There is a grid-cell style that has overflow hidden but I'm sure there is more to it. I was hoping it was in the road map for the near future so I would not need to do anything immediately

**Comment by c0bra** [comment]
@yjw9012 @justin-romano  If you use UI-Select you can specify `append-to-body` to take the dropdown outside of the grid. It supports styling for Selectize as well.

I have write-up with an example on how to do this here: http://brianhann.com/ui-grid-and-dropdowns/

**Comment by yjw9012** [comment]
Actually, I figured this out a few days ago. It was my mistake. I made a custom directive and wrap it with label. I changed label to div and it works great.
