### ISSUE TITLE
Requiring Form to have a name attribute

### ISSUE THREAD

**Issue by alexbowers-tecmark** [angular-ui/ui-select#922]
Is there a way to get the select3.js file to work with a form that doesn't have a name attribute.

It isn't really an issue, but it does throw console errors and I imagine has some consequences I haven't found yet.

The error (if omitting the name attr) is this:

```
TypeError: Cannot set property '$dirty' of undefined
    at compile.setPristine (select3.js:39)
    at select3.js:158
    at angular.js:16299
    at e (angular.js:4924)
    at angular.js:5312
```

Which links through to this (after following functions)

``` javascript
var form = scope.$eval(elm.closest('form').attr('name'));
```

If it isn't possible, maybe make the error reporting more verbose.

For example, if form is undefined there, throw an error saying 'Form must have a name attribute' or something, so that the error is easier to track down for those that don't want to dive into source code of select3.js

**Comment by user378230** [comment]
This appears to concern a different library. `select3.js` doesn't exist in this repo.
