### ISSUE TITLE
Search in multiple fields

### ISSUE THREAD

**Issue by FrancescoMussi** [angular-ui/ui-select#923]
Hello.
I have an issue that once i managed to resolve. But the solution is not working anymore.
I want to filter among people according to two different criteria : name and email.
Separately.
For example if I have a person called Francesco Totti with email roma@gmail.com
i would like that will show up that person by searching 'francesco' or 'roma'

I thought i had found a solution with this code:

<ui-select-choices repeat="person in list_people | filter: {email: $select.search.email, name: $select.search.name}"> -->

but somehow is not working anymore.
I would like to ask: that is still the proper way to procede?
How exactly can i obtain to search in multiple fields with angular ui-select?

Thank you!

**Comment by user378230** [comment]
See `propsFilter` in examples: https://github.com/angular-ui/ui-select/blob/cb75ecff41be55c1a835b59156470eab737a32b4/examples/demo.js#L7
