### ISSUE TITLE
ng-if doesn't work for ui-select-choices

### ISSUE THREAD

**Issue by shkleinik** [angular-ui/ui-select#924]
I receive list of items from server and I want to filter some of them on client side:

```html
<ui-select multiple  ... >
            <ui-select-match placeholder="Select Field...">{{$item.name}}</ui-select-match>
            <ui-select-choices repeat="field in ctrl.fields" ng-if="field.flag == 1">
                {{field.fieldName}}
            </ui-select-choices>
 </ui-select>
```

I tried smth simpler:
```html
ng-if="true"
```

...and I tried to reproduce the issue with demos in plunker and it is an issue. Can you please suggest some workaround? Currently I'm filtering the collection in controller just after I receive it.

**Comment by lordnox** [comment]
ng-if is currently not allowed in ui-select-choices, I'm not sure if documented or not.

ng-if will be overridden here:
https://github.com/angular-ui/ui-select/blob/master/src/uiSelectChoicesDirective.js#L48

you should use a filter for the repeat expression:
```
<ui-select-choices repeat="field in (ctrl.fields | myFlagFilter(field.flag))">
  {{field.fieldName}}
</ui-select-choices>
```

**Comment by wesleycho** [comment]
Closing as a usage issue.
