### ISSUE TITLE
Prevent backspace key from clearing selected value

### ISSUE THREAD

**Issue by LeleDev** [angular-ui/ui-select#926]
Is there a way to prevent backspace key from clearing the selected value in ui-select?

Thank you in advance

**Comment by iamvaruns** [comment]
I am having the same issue, can someone help ?

**Comment by LeleDev** [comment]
Still nothing?

**Comment by fferraris** [comment]
+1

**Comment by pierregaste** [comment]
+1

**Comment by AndriyBilyak** [comment]
+1

**Comment by danmo** [comment]
Until it's supported by ui-select I had to create an angular directive that patches this: https://gist.github.com/danmo/020cc4ad33b87929b021e5c193a3e25c

**Comment by Wizjonero** [comment]
@pierregaste your solution works only on UI Select Single, right?

**Comment by pierregaste** [comment]
@Wizjonero Yes, that's right!

We cannot use this option with uiSelectMultipleDirective because backspace key is used for remove a selected value.

**Comment by CoconutDeveloper** [comment]
@pierregaste was this ever merge? I need this desperately, I'm asking because I don't see it in the documentation at least.

**Comment by pierregaste** [comment]
@CoconutDeveloper yes it was merged : https://github.com/angular-ui/ui-select/pull/1736

I forget to add documentation. You could create a new PR for this ;)
