### ISSUE TITLE
compatible with select2 4.0?

### ISSUE THREAD

**Issue by kukac7** [angular-ui/ui-select#928]
https://select2.github.io/announcements-4.0.html

**Comment by alejandromagnorsky** [comment]
+1. Select2 version 4.0 has been launched 3 weeks ago.

**Comment by alexbowers-tecmark** [comment]
This is the error that I get:
The select2('data') method was called on an element that is not using Select2.

**Comment by smajl** [comment]
WTF? Guys, this implementation has completely different code base than original select2, it just has a theme that looks like select2 and behaves in a similar way... How do you imagine this "compatibility"? lol
