### ISSUE TITLE
Append text to the bottom of autocomplete

### ISSUE THREAD

**Issue by junajan** [angular-ui/ui-select#936]
Hello,
is there any way, how to append text to the bottom of the autocomplete box?

Use case: We are using ui-select for user search (in messages module) where are some restrictions that user can't search throught all users - he can find there only his friends and some other connections.. And we would like to tell users that there are these restrictions and if they want to write to another person, they should do something else..

**Comment by user378230** [comment]
This can be done by updating the choices template https://github.com/angular-ui/ui-select/blob/161cff56c0ba9d4a86ae213056dd78ba18296036/src/bootstrap/choices.tpl.html
