### ISSUE TITLE
ui-select dropdown options not coming out of ng-grid

### ISSUE THREAD

**Issue by Debanjan92** [angular-ui/ui-select#937]
![ui-select](https://cloud.githubusercontent.com/assets/12497685/7682702/88a3f1a2-fd97-11e4-8ef2-31ceaad69b6c.png)

**Comment by c0bra** [comment]
@Debanjan92 Try using the `append-to-body` attribute. The grid does not allow it's contents to overflow.

**Comment by Debanjan92** [comment]
Hi, 
We are using "ui-select" within "ng-grid", which is populated dynamically using cell template.

Sample cell-template:

eval("htmlDropdown = '" +
                "<div>" +
                    "<ui-select ng-hide=moDisabled style=\"width:75%;float:left;\" ng-model=\"COL_FIELD\" theme=selectize ng-disabled=disabled>" +
                        "<ui-select-match placeholder=\"Select\">{{COL_FIELD}}</ui-select-match>" +
                        "<ui-select-choices repeat=\"it in opts" + gridId + " | filter: $select.search\">" +
                            "<span ng-bind-html=\"it | highlight: $select.search\"></span>" +
                        "</ui-select-choices>" +
                    "</ui-select>" +
                "</div>" );

Implementing this code within an ng-grid, the options stay within the grid, as shown in the image above.
Will be highly grateful if you could kindly help to sort out the problem. :)

**Comment by Debanjan92** [comment]
Hi, 
We are using "ui-select" within "ng-grid", which is populated dynamically using cell template.

Sample cell-template:

eval("htmlDropdown = '" +
                "<div>" +
                    "<ui-select ng-hide=moDisabled style=\"width:75%;float:left;\" ng-model=\"COL_FIELD\" theme=selectize ng-disabled=disabled>" +
                        "<ui-select-match placeholder=\"Select\">{{COL_FIELD}}</ui-select-match>" +
                        "<ui-select-choices repeat=\"it in opts" + gridId + " | filter: $select.search\">" +
                            "<span ng-bind-html=\"it | highlight: $select.search\"></span>" +
                        "</ui-select-choices>" +
                    "</ui-select>" +
                "</div>" );

Implementing this code within an ng-grid, the options stay within the grid, as shown in the image above.
Will be highly grateful if you could kindly help to sort out the problem. :)

**Comment by c0bra** [comment]
@Debanjan92 You can find an explanation of how to do that here: http://brianhann.com/ui-grid-and-dropdowns/

**Comment by Debanjan92** [comment]
it worked.. Thanks :)

**Comment by Debanjan92** [comment]
function setAllowClear(allow) {
        $select.allowClear = (angular.isDefined(allow)) ? (allow === '') ? true : (allow.toLowerCase() === 'true') : false;
      }

**Comment by Debanjan92** [comment]
ng-options="item.ProfileID as item.ProfileName for item in availableProfilesProductionHistory"

-------------------------------------------------------------------------------------------------

How can we represent this kind of options in ui-select repeat?

**Comment by wesleycho** [comment]
Closing as a support issue.
