### ISSUE TITLE
How do I manipulate the search results?

### ISSUE THREAD

**Issue by egervari** [angular-ui/ui-select#955]
I really like the text-based search feature... but I was curious if I could process those search results before showing them to the user? 

You know how you have a setting to make some choices not selectable? Well, I'd basically like those same options to be unsearchable as well. So if you have an option to do that, or if you let me implement a function to filter them out, that would be awesome for my use case.

Can you help? Thanks

**Comment by user378230** [comment]
You can create a custom angular filter and apply it to `items` in `ui-select-choices`

The filter can check the item and apply search if necessary. 

Closing as an old issue.
