### ISSUE TITLE
Possible error with ngModel.$render with null/undefined values

### ISSUE THREAD

**Issue by ro0sterjam** [angular-ui/ui-select#967]
I was having an issue with a multiple select item when the provided model was undefined and noticed that ngModel.$render first checks if ngModel.$viewValue is null, and if so, set  $select.selected to an empty array.

However, immediately after, $select.selected is set to ngModel.$viewValue again, causing it to become undefined again. I suppose a fix would be to set ngModel.$viewValue = [] rather than $select.selected = [].

Original Code:

      ngModel.$render = function() {
        // Make sure that model value is array
        if(!angular.isArray(ngModel.$viewValue)){
          // Have tolerance for null or undefined values
          if(angular.isUndefined(ngModel.$viewValue) || ngModel.$viewValue === null){
            $select.selected = [];
          } else {
            throw uiSelectMinErr('multiarr', "Expected model value to be array but got '{0}'", ngModel.$viewValue);
          }
        }
        $select.selected = ngModel.$viewValue;
        scope.$evalAsync(); //To force $digest
      };

Possible fix:

      ngModel.$render = function() {
        // Make sure that model value is array
        if(!angular.isArray(ngModel.$viewValue)){
          // Have tolerance for null or undefined values
          if(angular.isUndefined(ngModel.$viewValue) || ngModel.$viewValue === null){
            ngModel.$viewValue = [];
          } else {
            throw uiSelectMinErr('multiarr', "Expected model value to be array but got '{0}'", ngModel.$viewValue);
          }
        }
        $select.selected = ngModel.$viewValue;
        scope.$evalAsync(); //To force $digest
      };

**Comment by wesleycho** [comment]
Can you post a reproduction in Plunker so it is clearer what is meant?
