### ISSUE TITLE
Group-by function with parameters

### ISSUE THREAD

**Issue by eliagilad** [angular-ui/ui-select#970]
I would like to use a group by function that gets another parameters in addition to "item".

group_by_func: function (item, type){}

However, I haven't found a way to send the item object explicitly.
Is it possible?

**Comment by tarlepp** [comment]
+1 for this

**Comment by joeskeen** [comment]
@eliagilad @tarlepp I finally figured out how to do this after a bit of digging and tinkering.  It all comes down to this line: (https://github.com/angular-ui/ui-select/blob/a7dc9d0226130d288fbc97ad93930da38225234a/src/uiSelectController.js#L115)
```js
var groupName = angular.isFunction(groupFn) ? groupFn(item) : item[groupFn];
```
so, if what you pass into `group-by=` is a function (i.e. `vm.group_by_func`), it will pass the item into that function.  All you have to do to accept more parameters is make that function return a function that takes the item:
```html
  <ui-select-choices repeat="item in vm.items" group-by="vm.group_by_func(type)">
```

```js
  vm.group_by_func = function(type) {
    return function(item) {
      //you have access to both `item` and `type` here
    };
  }
```

**Comment by wesleycho** [comment]
Closing this as a support issue
