### ISSUE TITLE
UI select breaks when item select is too big

### ISSUE THREAD

**Issue by viniciusdacal** [angular-ui/ui-select#975]
![captura de tela 2015-05-31 as 20 43 45](https://cloud.githubusercontent.com/assets/2660570/7904530/ef955bf6-07d5-11e5-9975-42b739e250d2.png)

As we can see in the above image, when select an item bigger than the select-container, it breaks the interface.
Maybe we can set text-overflow: ellipsis;

**Comment by viniciusdacal** [comment]
I will try to fix it and I will send a pull request.
I think this will fix issue #933 too.

**Comment by wesleycho** [comment]
Closing as a duplicate
