### ISSUE TITLE
Opening the dropdown should scroll to the selected item.

### ISSUE THREAD

**Issue by pietschy** [angular-ui/ui-select#976]
Currently the drop down opens at the first item. It would be better if it scrolled to ensure the current selection is visible.

A second issue exists in that moving the mouse over the dropdown to scroll clobbers the original active item so you can no longer tell what the selected item was (when using the selectize theme). 

It would probably be better if the hover state was separate from the active state as mentioned in #282.

**Comment by starf** [comment]
It should indeed scroll to the selected item. +1

**Comment by Cornally** [comment]
For anyone in a pinch, the "_ensureHighlightVisible()" function is called whenever the user strikes a "vertical" key (e.g. up/down arrow).  While I haven't run the tests yet, I've seen success executing the same logic inside the "ctrl.activate()" function's $timeout where focus is also set.  Again, this is merely a bandaid.

**Comment by dimirc** [comment]
Will be solved with PR https://github.com/angular-ui/ui-select/pull/1208 
https://github.com/angular-ui/ui-select/commit/d2ce54c0cc41fbfcdf2badb5ed45b45246d12026

**Comment by DerekDomino** [comment]
When `reset-search-input` is set to `false` in `ui-select` directive, the dropdown does not highlight/select nor scroll to the previously selected item.

**Comment by mgohin** [comment]
same as @DerekDomino

**Comment by MDziwny** [comment]
The PR #1208 has broken multiple selection with `close-on-select=false`, if the user use the mouse to select an item, then it goes back to the highlighted element.

For instance, the user wants to select X, Y and Z. He selects X with the mouse and the dropdown goes back to A.

**Comment by sonphnt** [comment]
This does not work on Angular 1.5.7. I dont know if that is a problem. I am trying to debug the code, I dont understand at this line. Can you explain to me ? It always goes into 'if' condition with animate = true, so the else statement never triggered and _ensureHighlightVisible () never be called.

`if (ctrl.$animate && ctrl.$animate.on && ctrl.$animate.enabled(container[0])) {
                      var animateHandler = function (elem, phase) {
                          if (phase === 'start' && ctrl.items.length === 0) {
                              // Only focus input after the animation has finished
                              ctrl.$animate.off('removeClass', searchInput[0], animateHandler);
                              $timeout(function () {
                                  ctrl.focusSearchInput(initSearchValue);
                              });
                          } else if (phase === 'close') {
                              // Only focus input after the animation has finished
                              ctrl.$animate.off('enter', container[0], animateHandler);
                              $timeout(function () {
                                  ctrl.focusSearchInput(initSearchValue);
                              });
                          }
                      };

                      if (ctrl.items.length > 0) {
                          ctrl.$animate.on('enter', container[0], animateHandler);

                      } else {
                          ctrl.$animate.on('removeClass', searchInput[0], animateHandler);
                      }
                  } else {
                      $timeout(function () {
                          ctrl.focusSearchInput(initSearchValue);
                          if (!ctrl.tagging.isActivated && ctrl.items.length > 1) {
                              _ensureHighlightVisible();
                          }
                      });
                  }`

**Comment by karas111** [comment]
+1
Same as @sonphnt 
You can try this:
`if (ctrl.$animate && ctrl.$animate.on && ctrl.$animate.enabled(container[0])) {
                  var animateHandler = function (elem, phase) {
                      if (phase === 'start' && ctrl.items.length === 0) {
                          // Only focus input after the animation has finished
                          ctrl.$animate.off('removeClass', searchInput[0], animateHandler);
                          $timeout(function () {
                              ctrl.focusSearchInput(initSearchValue);
                          });
                      } else if (phase === 'close') {
                          // Only focus input after the animation has finished
                          ctrl.$animate.off('enter', container[0], animateHandler);
                          $timeout(function () {
                              ctrl.focusSearchInput(initSearchValue);
                          });
                      }
                  };

                  if (ctrl.items.length > 0) {
                      ctrl.$animate.on('enter', container[0], animateHandler);
                     $timeout(function () { _ensureHighlightVisible();});
                  } else {
                      ctrl.$animate.on('removeClass', searchInput[0], animateHandler);
                  }
              } else {
                  $timeout(function () {
                      ctrl.focusSearchInput(initSearchValue);
                      if (!ctrl.tagging.isActivated && ctrl.items.length > 1) {
                          _ensureHighlightVisible();
                      }
                  });
              }`

**Comment by kidroca** [comment]
Hello, 
I've tracked down 2 cases that prevent the dropdown to scroll to to the selected item on open

Here is a plunk that reproduces the issue: https://plnkr.co/edit/n9jwLCyUv87Ba3vPgOvu

#### 1. In combination with `ngAnimate` 
- Add `ngAnimate` as module dependency 
- Create an ui-select with ng-model that has initial value
- Click to toggle the dropdown open
- Not scrolled to active item

#### 2. When configured with `uiSelectConfig.resetSearchInput = false`
- Configure ui-select with `uiSelectConfig.resetSearchInput = false`  (or define on component)
- Create an ui-select with ng-model that has initial value
- Click to toggle the dropdown open
- Not scrolled to active item

**Comment by Shadokkk** [comment]
Did anyone find a solution ? I have the same problem with the same angular and ui select versions as you

**Comment by kidroca** [comment]
You can use the fork I made for the pull request until they release a new version:

In package.json replace:
`"ui-select": "^0.19.8"`
with:
`"ui-select": "git@github.com:kidroca/ui-select.git#v0.19.8-fork"`

The run an `npm-install` 

Fork: https://github.com/kidroca/ui-select/tree/v0.19.8-fork

**Comment by jpmnteiro** [comment]
@kidroca thank you, the fork works perfectly fine. Any word from the maintainers as to when we can expect this merged/solved on master?

**Comment by kidroca** [comment]
Glad you like it. We almost merged the changes last week, maybe track the pull request topic to know for sure: #2034
