### ISSUE TITLE
The list opens up, although enough space at the bottom

### ISSUE THREAD

**Issue by isimonov** [angular-ui/ui-select#977]
There is a situation when the list is up coming off, although bottom has enough space. Not logical behavior. How I was able to track the problem only occurs in Google Chrome

http://plnkr.co/edit/oZCudVaPNc42B7hLYB7j?p=preview

![opens_up](https://cloud.githubusercontent.com/assets/2580203/7908886/01182a2c-0851-11e5-81fc-28496bc2e8e6.jpg)

**Comment by equilerex** [comment]
Can confirm... maybe it depends on the form's css but for me, it jumps all over the place... not doing anything  and continuously clicking it will open it "up" about 80% of the times regardless how close you are do the bottom of the page

it is definitely related to a merge 4 days ago: https://github.com/angular-ui/ui-select/pull/836
if you want it to work, downgrade to v0.11.2 until someone can shed some light into it ;)

**Comment by dcominottim** [comment]
Is there a way to disable the "up direction" rendering at all?

**Comment by ggregoire** [comment]
@equilerex Nice catch. I downgraded and now it works as expected :)

**Comment by igorlino** [comment]
From usability perspective, its really annoying not to control the direction where things appear.

The version, as it, is unusable.

**Comment by igorlino** [comment]
The https://github.com/angular-ui/ui-select/pull/989  fixes the issue of inconsistent behaviour. Although I personally would like to have it configurable.

**Comment by isimonov** [comment]
Yes, it would be better not to do the thing than to do bad. Moreover, the need for this function in General is questionable, because it is difficult to do, hard to debug and difficult to maintain.

**Comment by LeleDev** [comment]
It's a shame that no option / way to disable these buggy  up-direction dropdowns has been provided yet

**Comment by dimirc** [comment]
Should be solved with https://github.com/angular-ui/ui-select/pull/1212

**Comment by igorlino** [comment]
That's one small step for a man, a giant leap for mankind.

**Comment by igorlino** [comment]
@isimonov  Please allow making the direction configurable (static or dynamic). If its only dynamic even if it works correctly, it does not bring a consistent user experience in some cases.
Imagine there is a critical information that should not be hidden by the dropdown going up. Or in some layouts the label is up, and you don't want to hide it.

**Comment by isimonov** [comment]
I agree, direction configurable would be best) ui-select project, unfortunately, at an impasse. I think the best solution would be to start over under the new major version. In my projects now I use now ui bootstrap Typeahead with some minimal modifications. It's easier and no bugs.

**Comment by karptonite** [comment]
In the mean time, I have my own hack that allows me to set a select to open down only, here:
https://github.com/karptonite/ui-select/commit/b3fcd9d72756ef02a0f3f844884f7dcded2fe663
No promises but you are welcome to give it a try. The template changes seem to be some sort of build artifact, btw--the only relevant changes are in uiSelectDirective.js

**Comment by dimirc** [comment]
@igorlino @isimonov @karptonite I agree with you so I just created PR https://github.com/angular-ui/ui-select/pull/1213 that will allow to configure dropdown position. Take a look and let me know your comments
