### ISSUE TITLE
Sortable CSS class remain if drag and drop fails

### ISSUE THREAD

**Issue by kkotosky** [angular-ui/ui-select#978]
To recreate: 
Open a select multiple with sortable = true;
Select many items.
Drag one items across all of the other items quickly.
Drop your item in a location such that the tag is put in its original location.
dropping, dropping-before and dropping-after classes will remain on other tags even though dropping in no longer happening

![screen shot 2015-06-01 at 2 24 55 pm](https://cloud.githubusercontent.com/assets/6353801/7919998/0453a57c-086a-11e5-972c-3f0650b9f324.png)
![screen shot 2015-06-01 at 2 26 00 pm](https://cloud.githubusercontent.com/assets/6353801/7920016/271f3d14-086a-11e5-8009-8128525c4c8d.png)

**Comment by idozorenko** [comment]
I couldn't find a reasonable solution for this bug. Also there are some major bugs with sorting, like item is not moved on drop or moved into a wrong place (IMHO implementation is very poor), so I've rewritten uiSelectSort directive completely. I can create PR if anyone is interested.

**Comment by user378230** [comment]
This should have been resolved by #902, though it is not yet released.

**Comment by user378230** [comment]
Closing #902 released.

**Comment by lavankumargudipudi** [comment]
c
