### ISSUE TITLE
When using $select.activate with a new value, new dropdown tag is not made

### ISSUE THREAD

**Issue by kkotosky** [angular-ui/ui-select#979]
This is cause because a new drop-down selector is only created upon a key-up event. 
This does not seem ideal as text inputs can have values assigned to them, or $select.search can be updated outside of a keystroke to a new value. When this happens it does not generate a new dropdown selector row for the user to select. 
(Note: tagging-label is turned on and 33 is not in the list of available items)
Current Situation:
![screen shot 2015-06-01 at 2 30 14 pm](https://cloud.githubusercontent.com/assets/6353801/7920123/d661e20e-086a-11e5-8653-c6b3899e3d7c.png)
Should be (after some key (in this case "command") is pressed):
![screen shot 2015-06-01 at 2 30 32 pm](https://cloud.githubusercontent.com/assets/6353801/7920126/de721400-086a-11e5-81cb-3041956e1564.png)

**Comment by MartinNuc** [comment]
I am also wondering how to deal with this. So far no progress :-/

**Comment by wesleycho** [comment]
Demonstrating this working [here](http://plnkr.co/edit/ymRpgdjWiVjhYoRT1Ct7?p=preview) - this appears fixed if it was an issue prior.
