### ISSUE TITLE
No content appended to `uis-transclude-append` span element

### ISSUE THREAD

**Issue by VegaFromLyra** [angular-ui/ui-select#985]
Hi folks,

There seems to be something wonky going on with one of the projects I am working on that uses ui-select so was hoping to get some help debug the problem. I am using version 0.8.3 and the `bootstrap` theme.

On my dev box, the ui-select works as expected but once I deploy the file by copying it over to our dev staging area, the control is broken and appears as follows when I select any item:

![screen shot 2015-06-02 at 4 48 32 pm](https://cloud.githubusercontent.com/assets/2251508/7946884/6208dd62-0947-11e5-935e-c7b94bdb75de.png)

I verified that the dependencies are being copied over and are present in the staging environment. After some debugging, the problem seems to be that there is no content appended to the span element tagged with `uis-transclude-append`, so this is how it looks in the broken state:

```<span uis-transclude-append>
   <span class="ng-binding ng-scope">
   </span>
</span>```

This is not the case with my dev machine so I suspect something in my build setup is causing this to happen on the staging environment.

Any pointers on why this could happen?

**Comment by VegaFromLyra** [comment]
Used the latest version of ui-select and this issue auto-magically disappeared so closing it

**Comment by AfricanStig** [comment]
Same problem in 2018, what files did you replace?
