### ISSUE TITLE
direction up of drop down seems to work incorrectly

### ISSUE THREAD

**Issue by sagivf** [angular-ui/ui-select#990]
Looks to me like this nice added functionality is in correct:
https://github.com/angular-ui/ui-select/commit/559a9fa090570c1ce5d49d48cb13a6a186ee94b8
$document[0].documentElement.scrollTop seems to always be 0.

Added pull request 
https://github.com/angular-ui/ui-select/pull/989

**Comment by dimirc** [comment]
Should be solved with https://github.com/angular-ui/ui-select/pull/1212
