### ISSUE TITLE
Latest build (12.0) not working with latest angular (1.4.0) and bootstrap (3.3.4)

### ISSUE THREAD

**Issue by shmuelbit** [angular-ui/ui-select#993]
I've linked to a Plunker to demonstrate this. It is base on the Demo. I've changed the versions of angular, bootstrap and the ui-select.

http://plnkr.co/edit/lhAdsJs93jg8A5IgQcQF?p=preview

Thanks

**Comment by MikaAK** [comment]
it works fine you cannot use github urls inside of your html...
http://plnkr.co/edit/ZVM5qIf1Do2a7SToksPD

**Comment by shmuelbit** [comment]
My bad.. Thank you for your input.

I'm still having an issue in my environment . We've upgraded from Angular 1.3.14 to 1.4.0 and the select box stop working properly. I'm using the bootstrap theme and the select box only opens after I search for something and then clear the search criteria.

Thanks

**Comment by MikaAK** [comment]
I'm having this issue as well. The search box wouldn't open for me with 1.4

**Comment by ManuelRauber** [comment]
I can confirm that behavior.

**Comment by C00per** [comment]
I have the same problem

**Comment by meditsimple** [comment]
Upgraded to angular 1.4.1, ui-select 0.12 and listing wasn't showing up randomly (and with no error) only for using directive ui-select within another directive ...

Revert to angular 1.3.16 fixed the odd behavor :/

**Comment by Charkhan** [comment]
Upgraded to angular 1.4.1, ui-select 0.12 and opening the listing were randomly not showing, but only when using the directive within another directive.

Revert to angular 1.3.16 fixed this odd behavior...

**Comment by YidingW** [comment]
Same problem.

**Comment by stanleyxu2005** [comment]
@YidingW @Charkhan @C00per @ManuelRauber Maybe you can try set a theme. In my case, it did not work until I set `<ui-select theme="select2" ...`. And also you need to include two stylesheets.
```
  <link rel="stylesheet" href="path/to/select2/3.5.2/select2.css"/>
  <link rel="stylesheet" href="path/to/select2-bootstrap-css/1.4.6/select2-bootstrap.css"/>
```

**Comment by FloGou** [comment]
It seems to come from the ng-show that hides the root ul element if $select.items is empty. It is only present on the bootstrap template, so that's why it works withe select2 or selectize themes.

**Comment by mmaday** [comment]
I tried the $scope.$watch that @FloGou mentioned to no avail.

For whatever reason, the `ng-show="$select.items.length > 0"` is not evaluating in Angular 1.4:
```
<ul class="ui-select-choices ui-select-choices-content ui-select-dropdown dropdown-menu"
    role="listbox"
    ng-show="$select.items.length > 0">
```
I'm sure there's a reason for that condition, but none of the other templates have it.  If I change that expression to `ng-show="$select.open"`, it works fine:
```
<ul class="ui-select-choices ui-select-choices-content ui-select-dropdown dropdown-menu"
    role="listbox"
    ng-show="$select.$open">
```

Also, adding an arbitrary class via ng-class using $select.items.length (e.g. `ng-classz=\"'items-' + $select.items.length\"`) also works.

**Comment by btm1** [comment]
any progress on this? I'm having the same issue.

**Comment by btm1** [comment]
so if you are using bootstrap theme and you are not using multiselect the bandaid I've found for now is to simple put an ng-if on the directive tag that watches the length of the array that populates the list i.e.

				<ui-select ng-if="select_options.length" ng-model="query.cohort" theme="bootstrap" ng-change="cohort_changed('cohort')" style="width: 150px;">
					<ui-select-match placeholder="select a starting stage...">{{$select.selected.value}}</ui-select-match>
					<ui-select-choices repeat="hort.key as hort in select_options | filter: $select.search">
						<div ng-bind-html="hort.value | highlight: $select.search"></div>
					</ui-select-choices>
				</ui-select>

The same trick does NOT work on mutliselect bootstrap theme though for some reason.

**Comment by btm1** [comment]
any progress on this?

**Comment by zaideygrek** [comment]
+1

**Comment by C00per** [comment]
any news?

**Comment by btm1** [comment]
+1

**Comment by stan-z** [comment]
+1

**Comment by C00per** [comment]
I'm affraid that I should migrate to another solution becase I can't see any progress here. ((( Can someone recommend analog for ui-select with similar functionality?

**Comment by btm1** [comment]
@C00per you should just go back to using the original ui-select and just make a quick directive to apply it... it's not that hard. Obviously it's less declarative than what's happening here but it won't has dependencies as closely tied to angular releases.

**Comment by Fost** [comment]
anyone ? :)

**Comment by YidingW** [comment]
The 0.13 update should have already fixed the compatibility problem. 

I have no problem with Angular 1.4.7, Bootstrap 3.3.5 and Select 0.13.2.

**Comment by Dimitar-Karazhov** [comment]
I have issues just after upgrade to Angular 1.4.7, Bootstrap 3.3.5 and Select 0.13.2.
Select not working...

**Comment by wesleycho** [comment]
Closing as this appears fixed.

Any unrelated issues should be opened separately and not polluting other issue threads.
